### ISSUE TITLE
Groups / Teams

### ISSUE THREAD

**Issue by jlndk** [santigarcor/laratrust#10]
Hi.

Ealier today I created [an issue on the original entrust repo](https://github.com/Zizaco/entrust/issues/615), regarding the possibility of adding groups to the package.

However i just noticed the concerns regarding the maintainer of the original repo, so I looked up forks and stumbled upon this. Even though I'm gonna make the pull request myself, I would very much prefer the code going into a maintained codebase.

(BTW I've done a lot of explanation of my problem on the original issue, so please check it out if you're unsure of what I mean by groups)

Personally I think many people would benifit for this feature, since It's very common for application to be based around groups (like slack).

**Comment by santigarcor** [comment]
@jlndk i think it would be useful so if you can make a PR it would be great.

**Comment by jacurtis** [comment]
Yes, I think this would be a great addition and would be used by many people.

**Comment by erikwestlund** [comment]
I think this would be awesome.

**Comment by santigarcor** [comment]
I'm going to start working in that during week.

**Comment by jlndk** [comment]
My team found another way around this problem, but I'm glad someone else has started working on the feature :D

**Comment by santigarcor** [comment]
@jlndk , @erikwestlund , @jacurtis I've done most of the groups implementation. Could you please try it in [this](https://github.com/santigarcor/laratrust/tree/groups-implementation) branch. In packagist it's the `dev-groups-implementation` one.

These are the things you should know:

- The `detachRoles()` when no param passed, it only removes the roles that doesn't belongs to any group.
- The attachRole, hasRole and can works like @jlndk described [here](https://github.com/Zizaco/entrust/issues/615).

I hope you can try that out, and if you find something please tell me so i can change it.

Cheers!

**Comment by santigarcor** [comment]
I just tagged a RC for the version with groups
