### ISSUE TITLE
[Lumen 5.4] no helpers for config_path()

### ISSUE THREAD

**Issue by Vuishnak** [santigarcor/laratrust#100]
Hi.
I installed clean version of Lumen (5.4), but after registering service provider I got an error:
```php
FatalThrowableError in LaratrustServiceProvider.php line 51:
Call to undefined function Laratrust\config_path()
```

As far as I know, Lumen doesn't have laravel helpers. What I need to do? Thx.

**Comment by santigarcor** [comment]
Could you please try using this package https://github.com/irazasyed/larasupport because i think i would have to make some changes in order to make it work completely with lumen.
