### ISSUE TITLE
about documentation and role owner

### ISSUE THREAD

**Issue by nermamax** [santigarcor/laratrust#103]
I am reading documentation and in there you mention owner role, which I find a strange role to define. 

in the docs:
$user->hasRole('owner');   // false
$user->ability(['admin', 'owner'], ['create-post', 'edit-user']);

When would user have owner role? When he creates a post yes he is owner of that post and if you assign role owner to him and later use this to check if he hasRole('owner') before he can edit the post this will lead to be able to edit anyones post.

So why mention the role owner in the docs, it's confusing and there should not be such a role. Or if there should be can someone explain to me why there should be?

**Comment by edgreenberg** [comment]
In my app, the owner role is like an uber-user.  His only privilege (so far) is to promote users to admins.

**Comment by santigarcor** [comment]
It is just an example, maybe in you app you don't have owner role but simple-user or anything like that.
