### ISSUE TITLE
  Getting Call to undefined method Illuminate\Database\Query\Builder::attachPermissions()

### ISSUE THREAD

**Issue by nermamax** [santigarcor/laratrust#105]
I am creating my own seeder for permissions and I get this error

this is my code:

        // attach permissions
        $admin = Role::whereName('admin');

        // $admin->detachPermissions([$crudPost, $updateOthersPost, $deleteOthersPost, $crudCategory, $crudTag, $crudUser]);
        $admin->attachPermissions([$crudPost, $updateOthersPost, $deleteOthersPost, $crudCategory, $crudTag, $crudUser]);

In documentation I noticed this line

By using the LaratrustRoleTrait we can do the following:
`$admin->attachPermission($createPost);`

But where do I use LaratrustRoleTrait, I tried placing it in User and got another error:
`Trait method cachedPermissions has not been applied, because there are collisions with other trait methods on App\Models\User`

I also tried placing it in Role.php

```
use Laratrust\LaratrustRole;
use Laratrust\Traits\LaratrustRoleTrait;

class Role extends LaratrustRole
{
    use LaratrustRoleTrait;
}
```

but I get the same error. How do I get attachPermissions() function to work?

**Comment by nermamax** [comment]
There seems to be problem with whereName function:

        // attach permissions
        $admin = Role::whereName('admin');

        echo $admin->id;

produces:

  [ErrorException]
  Undefined property: Illuminate\Database\Eloquent\Builder::$id

**Comment by KKSzymanowski** [comment]
Try
```php
$admin = Role::whereName('admin')->firstOrFail();
```
Instead of
```php
$admin = Role::whereName('admin');
```

**Comment by nermamax** [comment]
thanks that did it

**Comment by KKSzymanowski** [comment]
Just to clarify my answer, any `where`, `with`, `groupBy`, `orderBy` etc. function called on the Model creates a query builder. You have to finalize the building process by saying what you want to do with the query.
You can do for example `first`, `firstOrFail`, `find`, `findOrFail`, `get`, `paginate`, `toSql`.

This is I think the first thing that got me confused a lot in Laravel so I understand what you're struggling with.
