### ISSUE TITLE
return all permisions hold by roles that user has but no duplicates

### ISSUE THREAD

**Issue by nermamax** [santigarcor/laratrust#109]
Is there a function to return all permissions that user has by being associated with roles. For example is user has admin and author role

admin role permissions: crud-user, crud-post, crud-tag, crud-category
author role permissions: crud-user

If I assign both admin and author to the $user1 how would I get all the permissions but not duplicates back that those two roles combined give to the $user1? If laratrust does not have such function and I could not find any, how would I do it with Laravel?

**Comment by KKSzymanowski** [comment]
As far as I know there's no such function.
If you want only permission names you can do something like this:
```php
class User
{
    // ...
 
    public function getAllPermissions()
    {
        $permissions = [];
    
        foreach($this->roles as $role) {
            foreach($role->permissions as $permission) {
                $permissions[] = $permission->name;
            }
        }

        return array_unique($permissions);
    }
}
```
I haven't tested it but it should work.
You can refactor this code using Laravel Collections, specifically `merge` and `pluck` methods. You can read about them in the Laravel documentation.
