### ISSUE TITLE
LaratrustSeeder issue in inserting permission structure.

### ISSUE THREAD

**Issue by axelex** [santigarcor/laratrust#111]
if you set similar users in both roles_structure and permission_structure, and then try run LaratrustSeeder, you get the following exception: [Illuminate\Database\QueryException]                                                                                                                                                                                                   
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'superadministrator@app.com' for key 'users_email_unique']

This is of course because you try creating the users both in roles_structure handler as in permission structure handler in LaratrustSeeder class.

This is not an urgent matter, just wanted to point out the issue.

Thanks!

**Comment by KKSzymanowski** [comment]
I don't really understand why you want to create two users with the same email address. Can you elaborate on this?

**Comment by axelex** [comment]
I don't want to create two users with the same email. 
I just want to use the permission_user table, so I can directly get user permissions by user, but also need the permissions in the permission_role table so I can get permission by role. 
Just wanted to be able to get user permissions without necessarly know their roles.
Not really sure if this make sense...

**Comment by KKSzymanowski** [comment]
For getting user's permissions use `$user->permissions`, for getting permissions available through roles see [this](https://github.com/santigarcor/laratrust/issues/109) issue. I still don't understand how did you end up  violating the integrity constraint.

**Comment by santigarcor** [comment]
@KKSzymanowski maybe he put the same name inside the role_structure for the role name and the permission_structure for the user name.

**Comment by axelex** [comment]
Yes. That's what I did. I know how to get the permissions. But in order to get permission in this situation there are more joins to get them, than it it would be if there were made directly through permission user, so they would've been fetched faster. And since I saw you add the posibility, I thought I could use them like that too.
If it wasn't meant to work like that too,  not really sure why there is a permission_user table.

**Comment by santigarcor** [comment]
Because you can attach permissions directly to the user without the need of a new role, for example if you have a user that can also view the list of users but it's only that specific case, it's not worth it to create a new role only for that user, so you attach the permission and that's all.

**Comment by axelex** [comment]
Okay. Thanks!
Sorry for my late feedback.
