### ISSUE TITLE
suggestion for blade directive

### ISSUE THREAD

**Issue by nermamax** [santigarcor/laratrust#112]
I have this code:

	@canAndOwns('crud-post', $post)
		<button id="deleteBtn-{{ $post->id }}" class="btn btn-xs btn-danger" type="submit"><i class="fa fa-trash"></i> Delete</button>
	@elseif(Auth::user()->hasRole(['admin', 'editor']))
		<button id="deleteBtn-{{ $post->id }}" class="btn btn-xs btn-danger" type="submit"><i class="fa fa-trash"></i> Delete</button>
	@else
		<button id="deleteBtn-{{ $post->id }}" class="btn btn-xs btn-danger disabled" type="submit"><i class="fa fa-trash"></i> Delete</button>
	@endOwns

I need to render a delete button if user owns it OR if user is admin or editor. More elegant would be if I could do something like:

	@hasRoleOrOwns('admin,editor', $post)

	@endability

so in my case code above would end up much cleaner, I want to check if user is either admin or editor and allow them to delete the post, and if user is of type author, he can delete this post as well if it's his own post.

	@hasRoleOrOwns('admin,editor', $post)
		<button id="deleteBtn-{{ $post->id }}" class="btn btn-xs btn-danger" type="submit"><i class="fa fa-trash"></i> Delete</button>
	@else
		<button id="deleteBtn-{{ $post->id }}" class="btn btn-xs btn-danger disabled" type="submit"><i class="fa fa-trash"></i> Delete</button>
	@endOwns

but last suggestion would perhaps not be good if user that was author has been striped of his role and degraded to basic user who can not crud-post anymore, he would still be allowed to read, update, delte his own posts with hasRoleOrOwns.

perhaps **hasRoleOrPermissionAndOwns**('admin,editor', 'crud-post', $post) this way only admin, editor and user with crud-post who also owns this post can read, edit and delete the post.

What do you think about this suggestion?

**Comment by KKSzymanowski** [comment]
It's going some silly way, don't you think?
> hasRoleOrPermissionAndOwns

Why not 
`(hasRole() || can()) && owns()`

That's one thing. Second, I'd wrap the check in some method on `Post` model like `canBeDeleted` and use that in your view.

And third, I think it's unnecessary to duplicate the button markup. Isn't this cleaner?
```html
<button id="deleteBtn-{{ $post->id }}"
        class="btn btn-xs btn-danger {{ $post->canBeDeleted() ? 'disabled' : '' }}" 
        type="submit"
>
    <i class="fa fa-trash"></i> Delete
</button>
```

**Comment by nermamax** [comment]
is it possible to have (hasRole() || can()) && owns() in the blade? I do not like to create extra function under Post model to check if it can be deleted, then I would have to have 4 methods like that for each permission for each model that can be managed by users

**Comment by nermamax** [comment]
or perhaps I could create my own blade extension for this method I had in mind :)

**Comment by KKSzymanowski** [comment]
You can do
```blade
@if(($signedIn->hasRole('role') || $signedIn->can('permission')) && $signedIn->owns($post))
```

Or you can extract it to `User` model and there you can name it whatever you want:
```php
public function hasRoleOrPermissionAndOwns($role, $permission, $object)
{
    if(!$this->hasRole($role) && !$this->can($permission)) {
        return false;
    }

    return $this->owns($object);
}
```
And then in blade just 
```blade
@if($signedIn->hasRoleOrPermissionAndOwns('role', 'permission', $post))
```

You can of course create your own blade directive, but if you decide to do so, I'd suggest to keep it as simple as possible. By that I mean do all the logic in the User class and use the directive to only reference this one method. That way it's a lot easier to test and more reusable(you might need to check the same thing in eg. a controller).

**Comment by nermamax** [comment]
thanks alot for this example, I appreciate your help, I've learned alot from this discussion :)
