### ISSUE TITLE
Seeder does not have permissions with vagrant/homestead

### ISSUE THREAD

**Issue by iamface** [santigarcor/laratrust#115]
I am running into issues when trying to run the seeder. I followed the directions at http://laratrust.readthedocs.io/en/3.2/ for installation and configuration. I am using a fresh install of Laravel 5.4 and using Homestead.

Everything worked smooth until I ssh into the vagrant box and run `php artisan laratrust:seeder`. I am getting the following error `Couldn't create seeder.
Check the write permissions within the database/seeds directory.`

Below are my permissions:
`drwxr-xr-x  1 vagrant vagrant    204 Mar 17 18:04 database`
`drwxr-xr-x 1 vagrant vagrant  136 Mar 29 17:51 seeds`
`-rw-r--r-- 1 vagrant vagrant  241 Mar 29 17:51 DatabaseSeeder.php`
`-rw-r--r-- 1 vagrant vagrant 4563 Mar 29 17:27 LaratrustSeeder.php`

`vagrant@novus:/vagrant/database/seeds$ whoami`
`vagrant`

I shouldn't have to modify permissions and my user is the group and owner.

Could this be an issue with Homestead's default user permissions not able to run the seeder?

Thanks

**Comment by KKSzymanowski** [comment]
As you can see [here](https://github.com/santigarcor/laratrust/blob/5dbe574dde15c514484f9f6a6b5ec647a7dbed73/src/commands/MakeSeederCommand.php#L78), the command checks if the `database/seeds/LaratrustSeeder.php` exists and if it doesn't it tries to open it.
From the permissions you pasted I assume the file already exists. If you want to create a new one, you can try to delete this file or rename it before running the command.

**Comment by iamface** [comment]
Ah, I was trying to seed with `php artisan laratrust:seeder` instead of `php artisan db:seed` \:p.

I added `$this->call(LaratrustSeeder::class);` to my **DatabaseSeeder.php** and seeding worked as expected.

There is no issue here, this is working great.
Thanks! \:D
