### ISSUE TITLE
Previous upgrade migrations are not included in the package

### ISSUE THREAD

**Issue by SirLamer** [santigarcor/laratrust#118]
In order to upgrade from 3.0 to 3.2, one has to first retrieve 3.1 and run the upgrade command with that in place in order to get the 3.0 to 3.1 migration script. It cannot be easily just copied from Git because it is generated from the config properties. All migration steps should be included in the package to the maximum extent possible.

**Comment by santigarcor** [comment]
Well that's not necessarily true because if you want to do that you'll have to update to 3.1 first, it's just like Laravel, you can't update directly from 5.2 to 5.4.

Following your idea each new version has to have all the updates since 3.1. That could be  unmaintainable in the future, and doesn't apply to all cases.

**Comment by SirLamer** [comment]
With respect, Laravel is a bit of a different beast than its add-on packages. I don't see that this would be technically impossible.

As far as I can see from the docs, the only change needed for 3.0 to 3.1 in addition to the migration is to add one config property. It wouldn't be tough to have the upgrade command take an input like "--from 3.0" and then include the additional migration.

This is just a usability suggestion, if you don't want to do this then that's fine but it makes the maintenance cost of using your package higher. Your call.

**Comment by SirLamer** [comment]
Just to add to this, it would necessitate that the migration class name be different in each case. This is necessary anyway, even with two-step sequenced upgrades, because you are going to have a class name collisions after performing the two migrations in any case. I modified the class names to "LaratrustUpgradeTables30To31" and "LaratrustUpgradeTables31To32".

Laravel is designed for all old database changes to be persisted in future releases held as migrations. My personal project has something like 100+ migration files in it, and they are staying there.

**Comment by SirLamer** [comment]
Actually class name collisions won't matter because it is tracking migrations off of the filenames which is time-stamped. Still, a good idea for clarity reasons.

**Comment by santigarcor** [comment]
Off course there's no comparison, but it is more maintainable. Think maybe about the future updates, if you want to change there'd have to be all the possible combinations of updates paths because not everyone will be in 3.0.

Maybe the upgrade file name it's a good idea to implement.

**Comment by SirLamer** [comment]
It's not hard, you just associate each migration with a package version. In the upgrade command, you allow people to include a "from" option, the default is the previous version which required migration. You export all of the migrations for difference between the provided version and now.

But, as I said, your call.
