### ISSUE TITLE
Multi plan limit access my website 

### ISSUE THREAD

**Issue by phuongphally** [santigarcor/laratrust#121]
Can you give me idea how to create or design tables with your library support multiple plan access of users ? 

Thanks for your reply .

**Comment by KKSzymanowski** [comment]
I've never done it but I think you can treat plans as roles and specific plan features as privileges.
Take a look at [NPM pricing](https://www.npmjs.com/pricing). Column names would be your roles and row names would be your privileges eg.

Role: Developer PRO
Privileges: 
- Search and install public packages
- Publish and download open source packages
- Publish and download private packages

And the associated code:
```php
$searchPublic = Permission::create([
    'name'         => 'search_public',
    'display_name' => 'Search and install public packages'
]);

$publishPublic = Permisson::create([
    'name'         => 'publishPublic',
    'display_name' => 'Publish and download open source packages',
]);

$publishPrivate = Permisson::create([
    'name'         => 'publishPrivate',
    'display_name' => 'Publish and download private packages',
]);

$developerPro = Role::create([
    'name'         => 'developer_pro',
    'display_name' => 'Developer PRO',
])->attachPermissions([
    $searchPublic,
    $publishPublic,
    $publishPrivate,
]);
```

**Comment by phuongphally** [comment]
@KKSzymanowski Thanks for your answer, I will think base your answer . 

If you have any Idea about this kindly give me more details 

Thanks .
