### ISSUE TITLE
Question: Role Hierarchy Functionality

### ISSUE THREAD

**Issue by timramseyjr** [santigarcor/laratrust#124]
First I want to say thank you guys for all the hard work.  It was awesome to be able to drop this in as a replacement to Entrust to solve some of the issues I was having with Entrust not being updated.

I was curious if thought was ever given to implementing a role hierarchy, or if there is currently a way to the achieve hierarchy.

I would like for administrators to be able to create roles, but not a superadministrator role. Or show a multi-select box of roles with all roles removed that are < authenticated user.

My thought was to add a integer column to the role table to store some arbitrary value and make sure the column was <= the current level of the authenticated user when showing the Role List, but I didn't know if I was missing something looking through the docs and this functionality exists, or if someone has already done this and has a better idea?

**Comment by santigarcor** [comment]
I haven't done that, and currently there's no hierarchy support.

Maybe if you add a parent role Id column it'd be easier.

**Comment by yazfield** [comment]
having a parent id is one way to do it however it takes a lot of DB requests if you have deep hierarchies, your idea of giving "access levels" to roles is more efficient but needs some work.

**Comment by timramseyjr** [comment]
@santigarcor I was wondering if you would be interested in pull request for the levels method?  If so, I will go back through and do more testing, document, etc and make an official pull request, but I have the basic functionality here - https://github.com/timramseyjr/laratrust/tree/levels 

I may in the future decide the parent_id route is one that would suite my needs better and code it, but at this time access levels are all I need.

It would be helpful if I didn't have to worry about my own fork and updating/etc is why I ask

**Comment by santigarcor** [comment]
Well it could be useful, but how would it work with the current features?

And is it separate from the authorization functionality? In case someone just doesn't want to use that levels feature.

**Comment by yazfield** [comment]
You could add it as an optional feature by separating it's migrations from the base mifrations and having the actual code in an optional trait `hasHierarchy` then the user decides if he wants to use it.
It looks like it doesn't effect anything else.

**Comment by timramseyjr** [comment]
@santigarcor  It is really opt-in to use the functionality as it doesn't do anything without calling the middleware or blade directives.  There is a new 'level' column added to the roles table with a default value that is defined in the config.  I have added a 'levels_map' on the seeder that would  assign different values to superadmin, admin, and user, but they wouldn't do anything unless specifically wanted to use it.  You can look through the compare [here](https://github.com/timramseyjr/laratrust/compare/3.2...timramseyjr:levels) and see really quickly the additions.  Let me know

**Comment by santigarcor** [comment]
I like the idea of an optional trait, the name could be hasLevels o something like that.

If you can work on it and document it I would really appreciate it. I won't be able to review and merge it because I'm on a trip until first week of May.

**Comment by yazfield** [comment]
It won't change much in the submitted PR so I'll leave it to @timramseyjr

**Comment by timramseyjr** [comment]
I have been swamped, but should have some time next week to make the changes/document and put a PR together.

**Comment by timramseyjr** [comment]
I am just about done. Struggling with the formatting of the markdown a bit.  What interface are `.. NOTE::` and `.. code-block:: php` for(ie. Is this readthedocs custom markdown)?  I tried to do a search online and couldn't find any relevant information.

**Comment by timramseyjr** [comment]
Submitted PR #132 and moved the migration into it's own, so it is 100% opt in.  This was mainly for those who have already migrated, so they can add this functionality without issues - by running the new artisan command.

**Comment by envision** [comment]
Was this released as a standalone package somewhere...?
