### ISSUE TITLE
What is module in role_structure

### ISSUE THREAD

**Issue by manojsharma20** [santigarcor/laratrust#125]
Hi,

I want to do seeder for laratrust. I am able to understand the permission_map, but not able to understand the role_structure and permission_structure in the below segment:

```
return [
    'role_structure' => [
        'superadministrator' => [
            'users' => 'c,r,u,d',
            'acl' => 'c,r,u,d',
            'profile' => 'r,u'
        ],
        'administrator' => [
            'users' => 'c,r,u,d',
            'profile' => 'r,u'
        ],
        'user' => [
            'profile' => 'r,u'
        ],
    ],
    'permission_structure' => [
        'cru_user' => [
            'profile' => 'c,r,u'
        ],
    ],
    'permissions_map' => [
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete'
    ]
];
```

Could you please elaborate the module concept in role_structure like 'users', 'acl', 'profile' what they are, also elaborate 'cru_user' and its 'profile' in permission_structure.

**Comment by santigarcor** [comment]
For example the users module is the users crud, so if you have a 'create' permission inside the 'users' module it will create the permission 'create_users'. It's a easier and flexible way to seed the database.

The 'cru_user' is just a way to call the example user. It will be used for the email and name fields.

**Comment by manojsharma20** [comment]
is users is related to models which i have and performing action on the same. 

if i 'cru_user' do not specify permission_structure then what will happen. I did not understand your second paragraph.

**Comment by manojsharma20** [comment]
What if i want to create my own users, not your predefined.

**Comment by santigarcor** [comment]
you can delete cru_user if you want.

The role seeder creates users based on the rolename and also assings the permissions to the role.

for example the role superadministrator will be created and also a user with the same name. The cru_user is used to assign direct permission to the user only when you dont want to create another role for an specific user.

Have you read the docs?

**Comment by manojsharma20** [comment]
Yes, I have gone through your docs and according to that i have implemented your nice role permission plugin. I was confused about the module thing you are using. Is there any way to customized the role seeder  so that domain can be configured from .env. Like i will create USER_DOMAIN = gmail.com and then all user by default from seeder will be created under this domain.

**Comment by santigarcor** [comment]
you can do it by changing the seeder code, it's inside database/seeder directory

**Comment by envision** [comment]
I'm also having problem @santigarcor with understanding why the seeder created a  'cru_user' to database? I understand it seeds an example user for each _role_, but what is a _cru_user_ ?

**Comment by envision** [comment]
In practice if I comment out this under _permission_structure_ : 
``` 
'cru_user' => [
    'profile' => 'c,r,u'
],
```

I'm getting seeded one additional (11th) permission **Create Profile**. It's purpose remains unclear though :)

**Comment by santigarcor** [comment]
@envision it it created because you can attach direct permissions to your users without a role, so that's why that user is there, you can leave that array empty and nothing will happen.

**Comment by Sogl** [comment]
@santigarcor Really need to update documentation. I understand all parts in `laratrust_seeder.php` except `permission_structure`even after I read all the comments here. 

It need for create permissions for user without roles?
