### ISSUE TITLE
Question: correct way to apply permissions to user?

### ISSUE THREAD

**Issue by jamesgraham** [santigarcor/laratrust#127]
I assumed that having a role would mean the user inherits all permissions setup for that role.

It seems I need to do the following and assign explicitly:

```
$user->attachRole($role);
$user->savePermissions($role->permissions);
```

Is this correct?

**Comment by santigarcor** [comment]
No, you only need to assign a role to the user, and if your role has any permissions you can check for that permission from the user.

Attaching permissions to the user is optional in case you see the situation that you need to do that.

**Comment by NeutronStein** [comment]
I am also facing that issue. I have a user with admin role to which is attached all permissions. But when I check permission it always return false.

**Comment by santigarcor** [comment]
Have you tried to clear laravel cache? Remember that laratrust uses cache
by default.

I have to add a line to clear all the cache in the seeder. So the current
solution is to clear it manually.

**Comment by jamesgraham** [comment]
Is there any documentation on the cache behaviour? We are clearing redis manually but maybe there is a method call to do this

**Comment by KKSzymanowski** [comment]
@jamesgraham 
You can flush role and permission cache for one user with `$user->flushCache()`.
You can also flush permission cache for one role with `$role->flushCache()`.
You can flush all app cache with `php artisan cache:clear`.
There is however no method to clear all cache entries created by Laratrust. We could probably add a console command to do that. @santigarcor, what do you think?

**Comment by santigarcor** [comment]
It's a nice idea, it could solve a lot off problems regarding the cache
usage. But I won't be back and able to work on it until first week of May.

**Comment by KKSzymanowski** [comment]
I'll look into it and if I can come up with a decent solution I'll let you know so you can review it.

**Comment by santigarcor** [comment]
Nice, thank you again Kuba 😀

**Comment by KKSzymanowski** [comment]
File and Database cache drivers don't support sections, so we cannot rely on that.
The only solution I see is to fetch all users and roles from the database and forget the cache entry for each one. It would be quite slow probably, I will test it today and let you know how it behaves.

**Comment by jamesgraham** [comment]
@KKSzymanowski it may just be my local environment but `$user->flushCache()` and `php artisan cache:clear` do nothing to reset the permissions. Instead I need to issue `$user->attachRole(x)` in code.

**Comment by santigarcor** [comment]
@jamesgraham if you want​ to attach only one permission just use attachPermission.
