### ISSUE TITLE
Strict check of can

### ISSUE THREAD

**Issue by phpspider** [santigarcor/laratrust#130]
I wanted to add a check if any user can only x thing.

if ($user->can('edit-user')){
//some code
}else{
//some code
}
this user must have only edit-user permission nothing else then it would be executed.

**Comment by KKSzymanowski** [comment]
I don't think Laratrust provides a simple solution to your problem.
First of all, you might want to rethink your authorization architecture. It feels kinda weird to check if user has *only* that permission.
If you really want to stick with this approach, I'd do something like that(not tested):
```php
$permissions = $user->permissions->pluck('name');

if(in_array('edit-user', $permissions) && count($permissions) == 1) {
    // Authorized
} else {
    // Not authorized
}
```

**Comment by phpspider** [comment]
This can be done in this way also
if($user->can('edit-user') && count($permissions) == 1) {
    // Authorized
} else {
    // Not authorized
}
