### ISSUE TITLE
Question: support of groups in Laratrust 3.2 ?

### ISSUE THREAD

**Issue by ebarault** [santigarcor/laratrust#131]
hi @santigarcor,

I have moved from master to 3.2 to try the multi-user models feature, but i see groups are not supported in 3.2 (the migration went bad, and I had to start over for the records) What are your plans? adding group support in 3.2 and making it the new master at some point or merging additional features from 3.2 in master?

in other words: should i stick to master or is it safe to go with 3.2 ?

Thx,

**Comment by santigarcor** [comment]
Hi Eric, I recommend you to stick with 3.2. Currently I'm in a holiday
until next week, but the idea is to port the groups feature from the master
branch to the next release of Laratrust.

**Comment by ebarault** [comment]
excellent 👍  thanks for replying quickly @santigarcor

**Comment by AnvarGear** [comment]
What an excellent feature, I was thinking how to implement it in an archaic way while giving you the suggestion.

I will be attentive and enjoy the holidays :)

**Comment by santigarcor** [comment]
This is already implemented in the [master](https://github.com/santigarcor/laratrust/tree/master) branch. I'm  doing some adjustments to the docs before tagging a release.
