### ISSUE TITLE
remember_token not setting with remember me checked.

### ISSUE THREAD

**Issue by Jam0r85** [santigarcor/laratrust#135]
When using the Laratrust seeder, it automatically generates a random string for each account remember_token when inserting the records.

This (for some reason) prevents the remember_token from being updated when you login with any of the accounts created.

Changing this to null seems to solve this issue?

**Comment by santigarcor** [comment]
Well i can't find the reason why it happens, so i think the best solution is to remove the remember_token from the seeder.
