### ISSUE TITLE
Using with JWT returns unauthenticated (with fix)

### ISSUE THREAD

**Issue by ixperiencenl** [santigarcor/laratrust#138]
I'm using Laratrust together with JWT Auth and I couldn't get it working on my route middleware. It kept return unauthenticated everytime. I have now fixed this as follows:

Adding:
`$user = \JWTAuth::parseToken()->authenticate(); `
to LaratrustRole.php on line 42

It all works fine now, but I'm wondering if this is the correct implementation (I guess not since editing a core file in your package). Can anyone point out how this should be done?

**Comment by KKSzymanowski** [comment]
First of all, I have never used JWT Authentication, but I have successfully used Laravel Passport with Laratrust many times. If it's a fresh project you might want to give it a shot.

I assume you put this code before [this](https://github.com/santigarcor/laratrust/blob/3.2/src/Laratrust/Middleware/LaratrustRole.php#L43) line.
How would you authenticate users without Laratrust? Where would you put the authentication logic? If in middleware, make sure this middleware is called before any Laratrust-related middleware.

Lastly, authorisation logic should be independent of authentication, but you can copy any of Laratrust middleware classes to `app/Http/Middleware`, edit them to suit your needs, and point to the new path in `app/Http/Kernel.php` but keep in mind, if the middleware in core changes, you'd need to update your copy accordingly.

**Comment by ixperiencenl** [comment]
Your assumption is correct. 
First users login and get authenticated by Laratrust. JWT just provides the key for using afterwards. Authentication is done in routes.
I'll try integrating Passport, maybe it isn't that much work, and I'm not in a far stage of completion yet.

Yes indeed, I wasn't happy with editing the core of Laratrust. I'll go forward with Passport.

**Comment by KKSzymanowski** [comment]
Any luck with Passport? I can provide you with help or example code from one of my apps, if you're stuck on something.

**Comment by ixperiencenl** [comment]
Thnx for updating, no not yet, busy implementing other stuff as well. An example is very welcome of course!

**Comment by KKSzymanowski** [comment]
The example for password grant in Laravel documentation cannot really be tested so I modified it. I do not make a Guzzle request to the URL, instead I invoke the controller method(should be also faster, not having to boot Laravel again).
`app/Http/Controllers/SessionController.php`
```php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Session\StoreSessionRequest;
use GuzzleHttp\Psr7\ServerRequest;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Laravel\Passport\Client as OAuthClient;
use Laravel\Passport\Http\Controllers\AccessTokenController;

class SessionController extends Controller
{
    public function store(StoreSessionRequest $request, AccessTokenController $controller)
    {
        $client = OAuthClient::wherePasswordClient(true)->whereRevoked(false)->first();

        if(!$client) {
            return new Response(['error' => 'Authentication error'], 500);
        }

        $passportRequest = new ServerRequest('POST', config('app.url') . '/oauth/token');

        $passportRequest = $passportRequest->withParsedBody([
            'grant_type'    => 'password',
            'client_id'     => $client->id,
            'client_secret' => $client->secret,
            'username'      => $request->email,
            'password'      => $request->password,
            'scope'         => '*',
        ]);

        return $controller->issueToken($passportRequest);
    }

    public function destroy(Request $request)
    {
        $request->user()->token()->revoke();

        return new Response('', 204);
    }
}
```
For that to work, you need to have a password grant client. You can generate it with:
```bash
php artisan passport:client --password --name="My password grant token"
```
Passport returns several fields, the two I'm interested in are `token_type` and `access_token`.
In my JS app(VueJS + Vuex + Vue Router + axios) I make a call to the store method on `SessionController` and tell `axios` to use the token in all future requests.
My code is split up into several modules, but essentially it's doing the following:
```js
axios.post('/api/session', {email: email, password: password})
     .then(response => {
         let tokenType = response.data.token_type;
         let accessToken = response.data.access_token;
         axios.defaults.headers.Authorization = tokenType + ' ' + accessToken;
     }, error => { someErrorHandingHere(error) });
```
To logout user I make a following call:
```js
axios.delete('/api/session')
     .then(()=> {
         delete axios.defaults.headers.Authorization;
     }, error => { someErrorHandingHere(error) });
```

Then with routes defined as follows:
`routes/api.php`
```php
<?php

use Illuminate\Routing\Router;

/** @var Router $router */

$router->post('session', 'SessionController@store');

$router->group(['middleware' => 'auth:api'], function(Router $router) {
    $router->delete('session', 'SessionController@destroy');
    $router->get('currentUser', 'CurrentUserController@show');

    // Other routes
});
```
I can for example make a call to `/api/currentUser` to retrieve the signed-in user.

I think it sums up the setup.

I know it feels a bit an overkill to use Passport just to authenticate users in the JS app, but once you understand it, it becoms easier with every new project you build and if you decide to write a mobile app, you won't need to modify your Laravel codebase.

If you run into some issues with the API calls, it's sometimes useful to test them outside the app eg. using curl or [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop).

One last advice, read carefully through the Passport documentation, there are some pitfalls you can fall into.

**Comment by ixperiencenl** [comment]
Thanks for the update! I hope I can give it a try this week, otherwise it'll be next. I'll close this for now.

**Comment by ixperiencenl** [comment]
Well, installing Passport was OK, first had to remove the whole JWT thing. Now I got Passport working, but getting a check on the authenticated user doesn't go that well. The StoreSessionRequest  you are using isn't present in my project and therefore some things go wrong (like getting authenticated user info etc.). If this can be solved easily then I should be able to use Passport instead of JWT.

**Comment by santigarcor** [comment]
What i understand from the code that Kuba put there, you can replace the `StoreSessionRequest`with the simple `Request`, because it's retrieving only the data you sent through the axios request.

**Comment by KKSzymanowski** [comment]
Yes, `StoreSessionRequest` can be replaced with `Illuminate\Http\Request`. I use the former for validating the email and password and throwing an error when the client has already been authenticated. It also provides autocompletion for request values.

Here's the complete class if you're interested:
```php
<?php

namespace App\Http\Requests\Session;

use Illuminate\Contracts\Auth\Guard;
use Illuminate\Foundation\Http\FormRequest;

/**
 * @property string email
 * @property string password
 */
class StoreSessionRequest extends FormRequest
{

    public function authorize(Guard $guard)
    {
        return !$guard->check();
    }

    public function rules()
    {
        return [
            'email'    => 'required',
            'password' => 'required',
        ];
    }
}
```

**Comment by jsdecena** [comment]
You do not need to use passport to use this package with JWT. All you need to do it to login once your user once they have authenticated via the token. We just need to copy Tymon's middleware provider so we can customize it. Just copy the contents of `Tymon\JWTAuth\Middleware\GetUserFromToken` to your own provider like so

```
/**
* App\Http\Middleware\CheckUserFromTokenMiddleware
* put this file in App\Http\Kernel.php with value of 
* 'jwt.auth' => \App\Http\Middlewares\CheckUserFromTokenMiddleware::class,
*/

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, \Closure $next)
    {
        if (! $token = $this->auth->setRequest($request)->getToken()) {
            return $this->respond('tymon.jwt.absent', 'token_not_provided', 400);
        }

        $id = $this->auth->getPayload()->get('sub');

        try {
            $user = User::findOrFail($id);
            Auth::onceUsingId($user->id);
        } catch (\Exception $e) {
            throw new UserNotFoundException($e->getMessage());
        }

        try {
            $user = $this->transformToJson($fetchedUser);
        } catch (TokenExpiredException $e) {
            return $this->respond('tymon.jwt.expired', 'token_expired', $e->getStatusCode(), [$e]);
        } catch (JWTException $e) {
            return $this->respond('tymon.jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
        }

        if (! $user) {
            return $this->respond('tymon.jwt.user_not_found', 'user_not_found', 404);
        }

        $this->events->fire('tymon.jwt.valid', $user);

        return $next($request);
    }
```

We need to logged in the user in the application since the role package is checking it via the laravel's `$this->auth` which is session based.

Then if you are changing the role of the user directly in the **DATABASE**, you need to do 

`php artisan cache:clear`. [Reference](http://laratrust.readthedocs.io/en/4.0/troubleshooting.html?highlight=cache)

This is because the roles are cached by the package. I have a few hours having trouble with it. Hope someone saved their time! 😆

**Comment by ixperiencenl** [comment]
Thanks jsdecena, this solution is very time-saving and no need to install passport indeed!

**Comment by jsdecena** [comment]
Glad you liked it! 🎉  Cheers!

**Comment by Jatapiaro** [comment]
The code using Passport will be useful for me!

**Comment by anthony952** [comment]
Too late but if someone get this error, first check that you are not using the middleware at the api routes and controller construct, then if you still getting the error, make sure you are sending a payload to the backend, i mean, since the default route is POST, you must put the "uri", "payload", "token", if you put only the uri and the token, the token will be detected as the post payload and the middleware will reject your request. Cheers!
