### ISSUE TITLE
Route filters not working

### ISSUE THREAD

**Issue by AnvarGear** [santigarcor/laratrust#140]
I have one problem with the filter in the routes.
Call to undefined method Laratrust\Laratrust::routeNeedsRole()

Laratrust\Laratrust::routeNeedsRole('admin/advanced*', 'god', Redirect::to('/home'));

**Comment by santigarcor** [comment]
What laravel and laratrust versions are you using?

**Comment by AnvarGear** [comment]
Of course, the versions I'm using are:

Laravel 5.4.24
Laratrust 3.2

**Comment by santigarcor** [comment]
So you can't use the route filter methods because they're not supported. You can only use them if you were using a Laravel version < 5.1.

If you want to "filter" a route, you should use the middlewares that Laratrust comes with.

**Comment by KKSzymanowski** [comment]
Yup, you cannot use filters but you have a couple of options:
In routes:
```php
Route::get('admin/advanced/', 'FooController@foo')->middleware('role:god');
```
or
```php
Route::group(['middleware' => 'role:god'], function() {
    Route::get('admin/advanced/', 'FooController@foo');
});
```
In the controller:
```php
public function __construct()
{
    $this->middleware('role:god');
}
```
In the Form Request:
```php
public function authorize()
{
    return $this->user()->hasRole('god');
}
```

Method you choose really depends on your use case.

**Comment by mr-masoud-momeni** [comment]
i want use middleware. But I get the following error 

 **HttpException**

i use laratrust: 5.2 and laravel:5.4 

according to document: The middleware are registered automatically as role, permission and ability

But in my code not exist folder of middleware in route!

i found folders in vendor>santigarcor>laratrust>src>middleware

please help me

**Comment by santigarcor** [comment]
@mr-masoud-momeni have you tried the way @KKSzymanowski posted above?
