### ISSUE TITLE
Get roles' permissions

### ISSUE THREAD

**Issue by ronrun** [santigarcor/laratrust#142]
Hi, I thought, a user has roles, a role has permissions. user get permissions by role.

I have wrote codes with user <-> role <-> permission,
Then I want to get user's permission, I use $user->permissions(), no error, but empty.
I just find out that there is a table named permission_role and another table named permission_user.
Which means, if I want to use $user->permissions(), I have to write to permission_user, change my codes.

Then I tried to use $role->permissions(), but no such method ??
```
$user = Auth::user();
$user_roles = $user->roles()
$user_permissions = $user_roles->permissions();
```

Error:
Call to undefined method Illuminate\Database\Query\Builder::permissions()

How to get roles permissions
.

**Comment by ronrun** [comment]
Do I have to create relation in Role model? But there isn't such relation in User model.
Why $user->permission() is ok, $role->permission() not ok?

**Comment by KKSzymanowski** [comment]
It depends on what you wanna do with these permissions. If you just checking for existence, use `$user->can('doSomethingDirty')`.

**Comment by santigarcor** [comment]
This feature will be available in the next Laratrust release

**Comment by molerat619** [comment]
How can it be done now? (I am assuming the next release has happened since June 2017.)

**Comment by santigarcor** [comment]
Check the [docs](http://laratrust.readthedocs.io/en/5.0/usage/concepts.html#retrieving-relationships)

**Comment by molerat619** [comment]
That's great, thank you!

**Comment by suleodu** [comment]
Hello i will like to know how to retreive all permission assign to a role and all role that has a perticular permission

**Comment by mowbr002** [comment]
Hi there,

It would be really convenient if there were a relationship that allowed me to

**Comment by codermjb** [comment]
This is a very incredible library. But, how come I can't get a list of the roles that a user is assigned to? I am trying to build a CMS to assign and update roles, but all you have is can and not a way to get the roles for the user.
