### ISSUE TITLE
Suddenly all the permissions return false

### ISSUE THREAD

**Issue by carlost89** [santigarcor/laratrust#145]
Hi, I'm working on a project that is using your package. I check the permissions in the construct of every controller using middlewares and everything works perfectly when I sign in using a user with all the permissions.

But after a while using the app I suddenly got denied access from everywhere because the app says I dont have permission to be there, and every middleware and check for permission is returning false.

As I said, the user i'm using has all the permissions and can access everywhere, so I don't understand why after a while I got blocked and at the beginning I was able and suposed to access.

Thanks.

**Comment by KKSzymanowski** [comment]
- Which version are you using?
- Are you sure the permissions/roles are properly set-up in the database?
- How do you check permissions for existance?

**Comment by carlost89** [comment]
**Which version are you using?**

Laratrust Version: "santigarcor/laratrust": "3.2.*"
Laravel Version: 5.4.25
PHP Version: 7.0.15

**Are you sure the permissions/roles are properly set-up in the database?**

Yes, the permissions are added by  Laratrust Seeder with the command **php artisan migrate --seed**. The user I am using is called **Admin** and it has the **Admin Role** which has all the permissions for all the tables. I set the permissions in every Controller using middlewares in the construct method and everything works perfectly. But after some minutes using the app I got rejected from everywhere and all the permissions checks returns **false**, in spite of having the same permissions as the beginning in my database.

**How do you check permissions for existance?**

I check them these ways:

1. Using blade `@permissions('permission_name') @endpermission` Nothing inside this is shown after losing access

2. Using the php method `$user->can('permission_name')` This returns false after losing access.

3. Manually checking in every table in my database that the user has the correct role and the role has all the permissions.

**Comment by KKSzymanowski** [comment]
Can you try:
```bash
php artisan cache:clear
php artisan tinker
> App\User::find('your-user-id')->permissions;
```

**Comment by carlost89** [comment]
Sorry for the delay.

I haven't been able to do the tests because the error hasn't repeated again. When this happens again I'll do what you said and send feedback to you.

Thanks.
