### ISSUE TITLE
Inherit roles

### ISSUE THREAD

**Issue by mhellmeier** [santigarcor/laratrust#148]
Hey!
I would like to see a function to inherit roles. In my system, there are the following roles: `owner`, `admin`, `user`. The `admin` should inherit permissions from the `user`. So the `admin` has all permissions from the `user` plus his own permissions. The `owner` should inherit permissions from `admin`.

I know that I could copy the `user` part from my `user` array in `laratrust_seeder.php` into the `admin` and `owner` array and the `admin` part into the `owner` array, but this is very annoying if you often change your permissions or if you have got more than these 3 roles.

**Comment by KKSzymanowski** [comment]
I'm not saying this wouldn't be useful but there are two things to consider
1. You can just do
```php
$permission1 = Permission::create(['name' => '1', 'display_name' => 1]);
$permission2 = Permission::create(['name' => '2', 'display_name' => 2]);
$permission3 = Permission::create(['name' => '3', 'display_name' => 3]);

$user  = Role::create(['name' => 'user',  'display_name' => 'user']);
$admin = Role::create(['name' => 'admin', 'display_name' => 'admin']);
$owner = Role::create(['name' => 'owner', 'display_name' => 'owner']);

$userPermissions = [$permission1];
$adminPermissions = array_merge($userPermissions, [$permission2]);
$ownerPermissions = array_merge($adminPermissions, [$permission3]);

$user->attachPermissions($userPermissions);
$admin->attachPermissions($adminPermissions);
$owner->attachPermissions($ownerPermissions);
```
That way, when the user permissions change, you don't need to modify any other roles.
You could probably simplify the above code with collections.

2. I like to design my roles to have disjoint sets of permissions.
For example `user` can create posts, `admin` can manage users and `owner` can generate reports.
I will just attach the `user` role to normal users, `user` and `admin` to admins and `user`, `admin`, `owner` to the owner.
Think of this as the actual user role in the system. An owner isn't just an owner in your application, but also is an admin and a normal user. If you give him all three roles, it's immediately clear what he can do.

**Comment by mhellmeier** [comment]
Thanks for your fast reply, @KKSzymanowski .
Your first point looks really interesting. I am actually defining my roles in `laratrust_seeder.php`. Where would be a good place to put your code in?

Your second point would also be a good solution, but my system isn't designed for disjoint sets of permissions.

**Comment by KKSzymanowski** [comment]
I always create a `LaratrustSeeder.php` in `database/seeders`. Custom seeder gives more flexibility in such cases as yours.
```
php artisan make:seeder LaratrustSeeder
```
Then in `database/seeders/DatabaseSeeder.php` add
```php
$this->call(LaratrustSeeder::class);
```

You can read more about Laravel seeders in the docs:
https://laravel.com/docs/5.4/seeding

**Comment by KKSzymanowski** [comment]
To simplify the seeder you can utilize Laravel Collections:
```
$createPosts = Permission::create(['name' => 'createPosts', 'display_name' => 'Create posts']);
$manageUsers = Permission::create(['name' => 'manageUsers', 'display_name' => 'Manage users']);
$generateReports = Permission::create(['name' => 'generateReports', 'display_name' => 'Generate reports']);

$user = Role::create(['name' => 'user', 'display_name' => 'User']);
$admin = Role::create(['name' => 'admin', 'display_name' => 'Administrator']);
$owner = Role::create(['name' => 'owner', 'display_name' => "Owner"]);

$user->attachPermissions([$createPosts]);
$admin->attachPermissions($user->permissions->merge([$manageUsers]));
$owner->attachPermissions($admin->permissions->merge([$generateReports]));
```
