### ISSUE TITLE
Changing id in role table by role_id

### ISSUE THREAD

**Issue by leonfather** [santigarcor/laratrust#149]
Hello, when i change the field id in table roles by role_id i get this error :
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'permission_role_table.role_role_id' in 'field list'. Can you help me to resolve this issue?

**Comment by KKSzymanowski** [comment]
Did you reflect the changed field name in the model configuration and in relationship definitions? If so, how?

**Comment by leonfather** [comment]
Yes in model i set the primaryKey to role_id

**Comment by santigarcor** [comment]
Did you changed the migration?

**Comment by KKSzymanowski** [comment]
From what I understand, your code is failing on something like:
```php
$role->permissions()->get();
```
because it cannot find the `role_role_id` field in the `belongsToMany` relationship intermediate table.
If you want to change the primary key name you shoud:
1. Reflect this change in the migrations(also for the previously mentioned intermediate table)
2. Overwrite the relationship definition to tell Laravel what are the new key names.

You can find detailed information in the Laravel relationship documentation.

**Comment by leonfather** [comment]
i'm not using migrations i just import my sql to my database, I think it's the problem of belongsToMany. So what i must do exactly to resolve this issue?

**Comment by santigarcor** [comment]
But how is your sql to create the permission_role and role_user table? Because you also have to change the names there.

The belongsToMany relationship doesn't use the primary key, it gets all the values from the configuration file:

```php
return $this->belongsToMany(
        Config::get('laratrust.permission'),
        Config::get('laratrust.permission_role_table'),
        Config::get('laratrust.role_foreign_key'),
        Config::get('laratrust.permission_foreign_key')
    );
```

**Comment by leonfather** [comment]
I m using the same structure of sql but inside id i'm using role_id for roles table, and inside id in permissions table i'm using permission_id

**Comment by santigarcor** [comment]
And in the permission_role table?

**Comment by leonfather** [comment]
role_id and permission_id

**Comment by leonfather** [comment]
What do you think?

**Comment by santigarcor** [comment]
I wasn't able to replicate the problem, i changed everything in the migration and the `$primaryKey` in both models and everything worked. No need to change belongsToMany().

From what i see your problem is in the sql, because you said that you already changed the `$primaryKey` in both models.

**Comment by leonfather** [comment]
This is my sql :
```
CREATE TABLE `permissions` (
  `permission_id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `display_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `idx_name` (`name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `roles` (
  `role_id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `removable` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE KEY `unq_name` (`name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `roles_permissions` (
  `role_id` tinyint(3) unsigned NOT NULL,
  `permission_id` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`permission_id`,`role_id`),
  KEY `idx_role_id` (`role_id`) USING BTREE,
  FOREIGN KEY (`permission_id`) REFERENCES `_permissions` (`permission_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`role_id`) REFERENCES `_roles` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

```

**Comment by santigarcor** [comment]
Did you changed this in your laratrust.php:

`'permission_role_table' => 'permission_role',`

to 

`'permission_role_table' => 'roles_permissions',`

Have you modified the relationship? Because it's weird it's looking for `permission_role_table` when that's the name of the config key.

**Comment by leonfather** [comment]
yes i change everything in the config file

**Comment by leonfather** [comment]
The problem id that belongsToMany generate role_role_id which is model_primarykey, model= role and primary_key = role_id. Do have an idea how can i resole this?

**Comment by santigarcor** [comment]
But unless you overwrote the relationship, that problem is not supposed to happen, because as i said, laratrust defines everything in the LaratrustRoleTrait.

You can check [here](https://laravel.com/docs/5.4/eloquent-relationships#many-to-many) how to define all the arguments in the relationship.

**Comment by leonfather** [comment]
I change belongsToMany in role model but nothing work: 
```
    public function permissions(){
		return 	$this->belongsToMany(Permission::class, 'roles_permissions', 'ffff','ddddd');
	}
```

**Comment by santigarcor** [comment]
What version of laravel and laratrust are you using?
