### ISSUE TITLE
Question: Support spanish

### ISSUE THREAD

**Issue by AnvarGear** [santigarcor/laratrust#150]
Hola @santigarcor ,

Tiene soporte en español, es que tengo unas dudas para usar los permisos dentro del controlador.

Quiero listar una tabla de **solicitudes**, y solo lo puede ver el creador de dicha solicitud y un rol en especifico quiero que pueda ver todas las solicitudes de todos los usuarios.

**Comment by santigarcor** [comment]
Hola @AnvarGear, para filtrar por un rol y dueño puedes usar el [hasRoleAndOwns](http://laratrust.readthedocs.io/en/3.2/usage/concepts.html#objects-s-ownership) y para lo otro simplemente un hasRole.

Para la próxima trata de hacer las preguntas en ingles, ya que sirve para evitar duplicados de las preguntas.

**Comment by AnvarGear** [comment]
Hola Santiago,

gracias por a intentar probar, ya que no me funciono. 

Y seguire la sugerencia de publicar en Ingles.
