### ISSUE TITLE
Feature request or question: role/permission change event for audit tracking

### ISSUE THREAD

**Issue by sublime392** [santigarcor/laratrust#151]
I need to track changes to some key data fields in my application. Roles and permissions fall into that category. For normal models I have a trait that taps into the model events. I don't see any way I can really do this with your package. Any ideas on what I can do?

**Comment by KKSzymanowski** [comment]
You can listen for Eloquent events on your Role and Permission models the same way you do on your other ones. However you probably mean logging of detaching and attaching roles/permissions and it's not that simple IIRC. Laravel doesn't fire any events on `belongsToMany` relationship changes.

Tracking these operations is not a bad idea, we could probably fire some events on:
- `LaratrustUserTrait::syncRoles` - `laratrust.user.role.sync`
- `LaratrustUserTrait::attachRoles` - `laratrust.user.role.attach`
- `LaratrustUserTrait::detachRoles` - `laratrust.user.role.detach`
- `LaratrustUserTrait::syncPermissions` - `laratrust.user.permission.sync`
- `LaratrustUserTrait::attachPermission` - `laratrust.user.permission.attach`
- `LaratrustUserTrait::detachPermission` - `laratrust.user.permission.detach`
- `LaratrustRoleTrait::syncPermissions` - `laratrust.role.permission.sync`
- `LaratrustRoleTrait::attachPermission` - `laratrust.role.permission.attach`
- `LaratrustRoleTrait::detachPermission` - `laratrust.role.permission.detach`

@santigarcor, what do you think?

**Comment by santigarcor** [comment]
I think it's a nice idea because Laravel doesn't have a native solution to that problem.

This would go to the `master` branch, not the `3.2`.

**Comment by KKSzymanowski** [comment]
@sublime392 How do you imagine this functionality? Specifically, what data would you want to receive in the event listener?

**Comment by sublime392** [comment]
@KKSzymanowski I need to keep an audit trail for when a role or permission is added or removed from a user. So user_id,user_type, and role_id (or permission_id). I grab other surrounding details as I can but that would be unrelated to role/permission events. e.g. If it was a system or user initiated event, IP address if applicable, etc.  

I suppose I also need to keep track of permission adds/removes on a role, since that is an indirect way of changing a users permissions.

What I actually record in the end is a polymorphic audit item:
  `auditable_id` 
  `auditable_type` This would be 'User' if changing user's roles and 'Role' if changing permissions on a role
  `audit_field_name` One record for each field that is changed in a model
  `change_source` either 'system' or a user_id if a user initiated the change
  `user_id` This is used if the auditable item is a model that belongs to a user
  `ip_address` If applicable
  `original_value` A role_id/permission_id would be here if detaching a role
  `new_value` A role_id/permission_id would be here if attaching a role

**Comment by sublime392** [comment]
I would also like to make use of Laravel's notifications on some role events. e.g. Adding a 'online-bill' role to a user could trigger a notification to welcome them to paperless billing.

**Comment by KKSzymanowski** [comment]
So something like this would be ok?

```php
class User extends Authenticatable
{
    use LaratrustUserTrait, Notifiable;

    public static function boot()
    {
        parent::boot();

        static::attachedRole(function(User $user, $roleId) {
            Audit::log('role_attached', $user, $roleId);
            
            $user->notify(new RoleAttached($roleId));
        });
    }
}
```

**Comment by sublime392** [comment]
Yeah. I think that would be awesome!

**Comment by KKSzymanowski** [comment]
And how would you imagine the event for syncing roles/permissions?
Would it be
```php
static::rolesSynced(function(User $user, Collection $rolesAfter) {});
// or
static::rolesSynced(function(User $user, Collection $rolesBefore, Collection $rolesAfter) {});
```
or somehow else?

**Comment by sublime392** [comment]
For my purposes I would need the before and after collections. Ultimately, I will need to derive from that a set of audit records; one for each add or delete. So for my selfish purposes it would be best if the individual attach/detach events fired as appropriate even when syncing. But that does not seem generally appropriate since a sync event might carry a different context than an attach/delete event for  some use cases.  I would be excited if the rolesSynced event provided the before and after collections.

**Comment by KKSzymanowski** [comment]
Firing individual attaching/detaching events when synching cannot be done because Laravel performs it as a batch operation, not individually. I think we can provide the `before` and `after` role IDs.

**Comment by santigarcor** [comment]
Or we can pass the data that the sync method returns.
