### ISSUE TITLE
Get List of Users with a specific Permission?

### ISSUE THREAD

**Issue by thc1967** [santigarcor/laratrust#152]
Aside from running the raw database queries myself, is there a way to get the list of all users with a specific permission?

I was thinking something like the following would be useful:

```$usersWithPerm = Permission('permission.id')->getAuthorizedUsers();```

**Comment by KKSzymanowski** [comment]
If you do not have a lot of users you can do
```php
User::with('permissions')
      ->get()
      ->filter(function($user) { return $user->can('doSomething') });
```
If you care about performance and scalability you'll gonna have to create a custom query.

**Comment by thc1967** [comment]
I went about it the opposite way because I only allow my permissions to be associated with roles.

```$permission = Permission::with('roles.users')->where('name', '=', 'my.permission')->firstOrFail();```

The gross part there is I could get repeats on the users within ```$permission->role->users``` so I need to work some magic to spin it down to a single list formatted the way I want.

**Comment by santigarcor** [comment]
Why don't you use:
```php
 $users = User::whereHas('roles.permissions', function ($query) use ($permissionName) {
        $query->where('name', $permissionName);
    })->get();
```

**Comment by thc1967** [comment]
Yeah, about 10 minutes after I posted, I thought of that. I'm having a rough day today, probably shouldn't be coding. I'll give that a shot when I get a chance.

Thanks!

**Comment by santigarcor** [comment]
You're welcome, but i'm going to add a query scope to the LaratrustUserTrait just like the `scopeWhereRoleIs` to fetch users by permissions.

**Comment by thc1967** [comment]
That's awesome... but I haven't a clue how to use it?

**Comment by santigarcor** [comment]
Well i added it for the next version of Laratrust. In the mean time you can use the solution i gave you previously.

**Comment by KieronWiltshire** [comment]
was this ever added?

**Comment by santigarcor** [comment]
@KieronWiltshire yes it's in the docs https://laratrust.santigarcor.me/docs/5.2/usage/concepts.html#retrieving-relationships

**Comment by KieronWiltshire** [comment]
@santigarcor ah my bad, I did try looking for it! cheers!

**Comment by santigarcor** [comment]
I think is better if you use 
```php
$users = User::wherePermissionIs('my-permission')->get();
```
