### ISSUE TITLE
How to get assigned role of the user?

### ISSUE THREAD

**Issue by Seroja1010** [santigarcor/laratrust#154]
when I try to get user's role using $user->roles(), it returns empty.
How to get assigned role?

**Comment by santigarcor** [comment]
If you call `$user-roles()` you are going to get a query builder instance. You have to call `$user->roles()->get()` or `$user->roles`.

I case you did that, and you really got a empty array, please clear your application cache, maybe you made a change directly in the DB and Laratrust uses cache so it doesn't get reflected immediately.

**Comment by Seroja1010** [comment]
yes working properly. Thanks
