### ISSUE TITLE
Laravel Eloquent Observer events do not fire, possible overlapped with boot function

### ISSUE THREAD

**Issue by ericlie** [santigarcor/laratrust#157]
Hi!

```
Laravel Version: 5.4.27
using : "santigarcor/laratrust": "4.0.*"
```

In my current project, I have an observer for my user class
in my **AppServiceProvider@boot**
```php
User::observe(UserObserver::class);
```
I have a **deleting** method inside my **UserObserver** and previously it ran without any issue
and after using **LaratrustUserTrait**, it does not fire my deleting event inside **UserObserver**

I believe it probably cause by the **return true** inside **LaratrustUserTrait@bootLaratrustUserTrait**
```php
        static::deleting(function ($user) {
            if (method_exists($user, 'bootSoftDeletes') && !$user->forceDeleting) {
                return true;
            }

            $user->roles()->sync([]);
            $user->permissions()->sync([]);

            return true;
        });
```
It seems like the returning value prevent event from bubbling to observer. When i comment the returning value, everything works.

Current work around is to put my deleting logic from **UserObserver@deleting** into **User@delete**

```php
    public function delete()
    {
        $this->posts()->delete();
        return parent::delete();
    }
```
I wonder if there is another elegant workaround with regards to this issue.

Thanks

**Comment by santigarcor** [comment]
I think the best solution for this is to remove the `return true;` from the model events in the `LaratrustUserTrait`
