### ISSUE TITLE
Permissions are all false for a user with a role

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [santigarcor/laratrust#158]
I've set up Laratrust in my project. I created two roles with some permissions. However, when I run `Auth::user()->can('create-extensions')` this returns nothing. When I run `Auth::user()->hasRole('god')`, it returns 1, as it should do. Any ideas as to what could be causing this?

**Comment by santigarcor** [comment]
Please read [this](http://laratrust.readthedocs.io/en/4.0/troubleshooting.html), it could be the cache, clear your app cache.

**Comment by Fox4Iit** [comment]
Sorry, the problem is with my cache file, laravel logs, that cache has been cleared but it's not, it's ownership for files problem on my server.
