### ISSUE TITLE
Middleware return abort 403

### ISSUE THREAD

**Issue by krodo93** [santigarcor/laratrust#159]
$user =User::find(1);
        dd($user->hasRole('superadministrator')); // return true;

But,
Route::group(['prefix' => 'superadministrator', 'middleware' => ['role:superadministrator']], function() {
    Route::get('/', 'AdminController@welcome');
}); // return abort and 403

why??

**Comment by santigarcor** [comment]
What laravel and laratrust version do you have?

Is your user logged in?

**Comment by krodo93** [comment]
Laraver Version 5.4

Laratrust Version 4.0

Yes user logged..

**Comment by santigarcor** [comment]
I wan't able to reproduce the problem. I did:
```php
Auth::onceUsingId(1);

Route::group(['prefix' => 'superadministrator', 'middleware' => ['role:superadministrator']], function() {
    Route::get('/', function () {
        dump("Passed");
    });
}); 
```
And it worked without any problem.

By any chance did you attached the role directly in your DB? Please try cleaning your app cache.

**Comment by krodo93** [comment]
I use php artisan cache:clear

It's work
