### ISSUE TITLE
Setting up Multi User Model

### ISSUE THREAD

**Issue by markjordanco** [santigarcor/laratrust#161]
Hi @santigarcor 

Your package is awesome!

How do we go about using the multi user model support? Besides the user model I have an employee user model (needed to separate them because they have different profile details and managed differently). The automatic setup for Laratrust doesn't include the other user model except for adding user traits to the model file. How can we assign roles to the other user model?

Thanks!

**Comment by santigarcor** [comment]
First you have to configure your laratrust file as it's explained [here](http://laratrust.readthedocs.io/en/4.0/configuration/after_installation.html#multiple-user-models) and then you only have to use the `LaratrustUserTrait` in your models or run `php artisan laratrust:add-trait`.
