### ISSUE TITLE
Trait method cachedPermissions has not been applied, because there are collisions with other trait methods

### ISSUE THREAD

**Issue by the7th** [santigarcor/laratrust#166]
Hi guys, I wonder why when I use these two:

use Laratrust\Traits\LaratrustRoleTrait;
use Laratrust\Traits\LaratrustUserTrait;

use LaratrustRoleTrait;
use LaratrustUserTrait;

This error will occur: 
 
FatalErrorException
Trait method cachedPermissions has not been applied, because there are collisions with other trait methods on

I tried aliasing both LaratrustUserTrait as SomethingElse1 and LaratrustRoleTrait as SomethingElse2 but it still happened. I don't know where I messed up...

<img width="847" alt="screen shot 2017-07-17 at 4 40 11 pm" src="https://user-images.githubusercontent.com/2613772/28260709-e80641f4-6b0e-11e7-8f31-56fad81a7e0e.png">

**Comment by KKSzymanowski** [comment]
Are you using both traits in one class?

**Comment by the7th** [comment]
Well right now I'm just horsing around trying to figure out what both traits are doing. So those two shouldn't be in one class eh?

**Comment by KKSzymanowski** [comment]
No, the usual setup is you add the `LaratrustUserTrait` to your User model, extend LaratrustRole in your Role model, and extend LaratrustPermission in your Permission model. In some rare cases, when you need to eg. extend some other class in your Role model, you can use the `LaratrustRoleTrait`.

Take a look at what `php artisan laratrust:setup` does to see what's the preferred initial setup.

**Comment by the7th** [comment]
I see, that makes sense. I'll look into what `php artisan laratrust:setup` does. By the way, since I am extending Authenticatable by using `Illuminate\Foundation\Auth\User as Authenticatable`, how do I follow closely to the guide which extends the `Model`? I am trying to follow http://laratrust.readthedocs.io/en/4.0/configuration/models/user.html to the tee...

**Comment by KKSzymanowski** [comment]
The `laratrust:setup` command will add the trait automatically, but if you want to do this manually, you can still extend `Authenticatable`. If you want to extend `Model`, you'll need to implement interfaces and use traits applied in `Illuminate\Foundation\Auth\User`.
```php
<?php

namespace Illuminate\Foundation\Auth;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
}
```

**Comment by the7th** [comment]
I see... I think I see it a little bit more clearly now. Thanks!
