### ISSUE TITLE
Laratrust 4.0 with Laravel 5.1?

### ISSUE THREAD

**Issue by jonathanwkelly** [santigarcor/laratrust#167]
- Laravel Version: 5.1 
- Laratrust Version: 3.2

### Description:
In attempting to upgrade to get the Teams feature, I see that Laravel 5.2 is now required. What is provided with Laravel 5.2 that is required for this plugin?

**Comment by santigarcor** [comment]
If i'm not wrong some methods in the Str class. They exists in the latest versions of 5.1, but i was having problems with the composer requirements. I put something like `^5.1.40` but it didn't work, so the only way i found was to drop 5.1 and with 5.5 LTS coming it didn't seem that bad.

**Comment by KKSzymanowski** [comment]
Have you tried for example ">=5.1.10"? It should catch all next versions.

**Comment by santigarcor** [comment]
@jonathanwkelly Can you please test it with the `4.0.x-dev`? After that i will tag it.

**Comment by jonathanwkelly** [comment]
@santigarcor that does it, thank you
