### ISSUE TITLE
Documentation is quite vague

### ISSUE THREAD

**Issue by AJMaxwell** [santigarcor/laratrust#168]
- Laravel Version: 5.4.28
- Laratrust Version: 4.0.1

I'm fairly new to Laravel (coming from CodeIgniter), so this may be a noob question. I have installed Laratrust correctly, but when reading the usage documentations it all gets very vague after installation & configuration. Example: http://laratrust.readthedocs.io/en/4.0/configuration/models/role.html

The above page gives me code to set up new a Role, and the example it shows is the code that is already inside `app/Role.php`. When I look at Usage > Concepts > [Set things up](http://laratrust.readthedocs.io/en/4.0/usage/concepts.html#set-things-up), do I drop that code into the `Role` Class outside a function? Inside a function? What is the function name if it needs to be in a function? Do I run the code in `php artisan tinker`? How to do go about migrating any Tinker changes to the production server without having to repeat the whole process?

Laravel is powerful, but everything surrounding it is just seems really vague. It's like there is an expectation of some level of knowledge that I am lacking and nothing tells me what it is or how to find it. Am I missing something? Did I miss a section in the Laratrust/Laravel docs about how to do this? Or am I simply just dense?

**Comment by santigarcor** [comment]
The idea is to put that code in a [seeder](https://laravel.com/docs/5.4/seeding#writing-seeders). For the roles/permissions attachment and check you can use tinker or [controllers](https://laravel.com/docs/5.4/controllers#basic-controllers).

For example if you are building a roles crud you can do something like:

routes/web.php:
```php
Route::resource('roles', 'RolesController');
```

RolesController.php:

```php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\Permission;
use Illuminate\Http\Request;

class RolesController extends Controller
{

    public function index()
    {
        return view('roles.index', ['roles' => Role::all()]);
    }

    public function create()
    {
        return view('roles.create', ['permissions' => Permission::all()]);
    }

    public function store(Request $request)
    {
        $role = Role::create($request->only(['name', 'display_name'])); // Assuming you have those fields in the fillable list in the role model.

        $role->attachPermissions($request->permissions);

        return redirect()->route('roles.index');
    }

    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->route('roles.index');
    }
```

So, where to put the code depends on your needs.

I recommend you to check this video [series](https://laracasts.com/series/laravel-from-scratch-2017), it's a crash course in laravel and it's free.
