### ISSUE TITLE
Optional users creation

### ISSUE THREAD

**Issue by UAVova** [santigarcor/laratrust#171]
Recently, i was trying to use default laratrust seeder with custom ```users``` table structure (```username``` instead of ```name```, ```sha256``` instead of ```bcrypt```) and i've received an error, because default seeder uses hardcoded template for creating users. 

Also, received an error:
```1701 Cannot truncate a table referenced in a foreign key constraint (`auth`.`rbac_account_permissions
  `, CONSTRAINT `fk__rbac_account_permissions__account` FOREIGN KEY (`accountId`) REFERENCES `auth`.`account` (`id`))```

```rbac_account_permissions``` is custom table which is not related with ```laratrust``` in any way.

I want to suggest to add option to the config file, which will allow to specify if user want to create new user with generated role or not. 

Thank you for a great package)

**Comment by KKSzymanowski** [comment]
I don't seem to understand the issue you're facing.

> I've received an error, because default seeder uses hardcoded template for creating users.

What was the error?
If you change the structure of any table used by Laratrust, chances are you're gonna have to overwrite some of Laratrust functionality or manually seed the database.

> Also, received an error:
> ```
> 1701 Cannot truncate a table referenced in a foreign key constraint (`auth`.`rbac_account_permissions `, CONSTRAINT `fk__rbac_account_permissions__account` FOREIGN KEY (`accountId`) REFERENCES `auth`.`account` (`id`))
> ```

What's the call stack of this error? You can find it either by calling the command which generates it with 
```
-vvv
``` 
option(superverbose) or look in the Laravel logs in `storage/logs`.

**Comment by UAVova** [comment]
@KKSzymanowski Thank you fore the answer.
I mean the whole mechanism works great, but user creation for every roll is not something you would normally do when using default seeder. So, making it as an option would let other users (like me) use default seeder without changing even 1 line of it' code.

But this is only suggestion from my perspective. I may be wrong..
