### ISSUE TITLE
5.5 Update to Commands

### ISSUE THREAD

**Issue by JayteeNZ** [santigarcor/laratrust#172]
Hey Santi,

One of the latest commits to Laravel (I believe just 5.5: see [pull request)](https://github.com/laravel/framework/commit/ac9f29da4785c8b942ced8c4ab308214d618a22b) has a change to how commands are fired.

Commands must now have a ``handle`` method instead of both ``handle`` or ``fire``. I've tested this and of course, the commands fail and the migrations cannot be installed.

There are two solutions to this, unfortunately i'm not that great with Git so i'd prefer not to push a commit and potentially break something haha:

**Option 1:**
Have your commands extends a base command class which has a handle method. Then check if a method exists as fire or handle and call it

**Option 2:**
Go to Line 180 of Illuminate\Console\Command and copy the execute method, change it to allow both methods to be called.

Regards, Jack

**Comment by santigarcor** [comment]
Thanks for informing about that change, i'll change the method names to handle, and in that way it will keep the compatibility with Laravel <= 5.4.

**Comment by santigarcor** [comment]
@JayteeNZ please test it with the `4.0.x-dev` branch so then i can tag it.

**Comment by nathan6137** [comment]
Just wanted to let you know that switching to `4.0.x-dev`,  indeed fixed issue #175 
thanks!

**Comment by JayteeNZ** [comment]
I meant to update my comment and say changing the method to handle work would, but i forgot lol. Joys of being awake for over 24 hours.

Will switch to 4.0.x-dev soon, but i'm sure it will resolve it like Nathan has confirmed.

**Comment by santigarcor** [comment]
I'm tagging it right now
