### ISSUE TITLE
Default user role

### ISSUE THREAD

**Issue by UAVova** [santigarcor/laratrust#173]
What is the best way to assign role to user on creation? I can't see any method that implements such functionality, so i wanted to ask if my way of doing that is correct.

So, to assign default role to user, i'm listening ```Registered``` event and when it's triggered, i'm reading default role name from config file and using ```attachRole``` method.

What do you guys think of it?

**Comment by santigarcor** [comment]
Why don't you use the created user model event? and there you can attach any role you want.

**Comment by UAVova** [comment]
@santigarcor Please, can you provide any info about that event? can't find anything related to that in laratrust docs. Thank you.

**Comment by santigarcor** [comment]
It's not a Laratrust event. It is a eloquent model event https://laravel.com/docs/5.4/eloquent#events.

For simplicity you can make something like this:
```php
public static function boot ()
{
    parent::boot();
    static::created(function ($user) {
        $user->attachRole(config('your-default-role'));  
    }); 

}
```

But remember that will be applied to every user model after being created. If you only want to attach the default role when a user is created via a register form just stick to your Registered event.
