### ISSUE TITLE
Method Laratrust\SetupCommand::handle() does not exist

### ISSUE THREAD

**Issue by nathan6137** [santigarcor/laratrust#175]
- Laravel Version: 5.5-dev
- Laratrust Version: 4.0.2 

### Description:
when attempting to run : `php artisan laratrust:setup`
I get the following error:

> [ReflectionException]
  Method Laratrust\SetupCommand::handle() does not exist

### Steps To Reproduce:

- `composer require "santigarcor/laratrust:4.0.*"` since its laravel 5.5 i skipped over the steps 2 & 3 as per instalation guide 
- `php artisan vendor:publish --tag="laratrust"`
- add  to `routeMiddleware` array:
```'role' => \Laratrust\Middleware\LaratrustRole::class,
'permission' => \Laratrust\Middleware\LaratrustPermission::class,
'ability' => \Laratrust\Middleware\LaratrustAbility::class,
```
- run `php artisan config:clear`
- run `php artisan laratrust:setup` 
- getting the error

P.S. i tried running `composer dump-autoload`,  that didn't help

**Comment by santigarcor** [comment]
Check this https://github.com/santigarcor/laratrust/issues/172
