### ISSUE TITLE
New Feature: [Too long to post in title]

### ISSUE THREAD

**Issue by JayteeNZ** [santigarcor/laratrust#176]
New Feature:

Allow a user to be granted access if they have a certain permission registered to them OR any roles that they have assigned have the permission.

For example, here's a long blade directive name just so you can understand.

``@hasPermissionOrRoleHasPermission('access-dashboard')``

**Comment by santigarcor** [comment]
What is the difference with the ability method?

**Comment by JayteeNZ** [comment]
Doesn't the ability method check if the user has the role AND the permission?

This feature request would mean for example:

I have two roles: Admin and Super Admin
One of these roles have the permission ``access-dashboard``

Perhaps I wanted to grant access if either of these roles have the permission, or if the permission is directly assigned to me.

This would save us having to do things like ``@role('admin, owner')`` etc if we have a lot of roles on  our site.

**Comment by santigarcor** [comment]
The ability method can make both checks, by default it's an 'or' check.

Check the [docs](http://laratrust.readthedocs.io/en/4.0/usage/concepts.html#user-ability) to see the full usage of the ablity method.

Also you [can](http://laratrust.readthedocs.io/en/4.0/usage/concepts.html#checking-for-roles-permissions) simply use the can method it also makes an 'or' check by default.

**Comment by JayteeNZ** [comment]
Hmm interesting, I didn't actually see the ``$options`` array you can pass.

Well, I guess this issue can be closed :)

Thanks very much (still running on no sleep)
