### ISSUE TITLE
syncRoles() method with team argument also syncs teams.

### ISSUE THREAD

**Issue by geracam** [santigarcor/laratrust#177]
- Laravel Version: 5.1 
- Laratrust Version: 4.0 

### Description:
At this moment I am unsure if this is an oversight on Laratrust's "Teams" implementation or just a new feature that is yet to be implemented.

The behavior I'm experiencing exists when calling the `syncRoles()` method on an User instance for a specific team.

 At this time, we are seeing Laratrust update both the `role_id` and `team_id` columns in the `role_user` polymorphic table for that `user_id`. 

**However, we'd like to have the ability to sync a role for a specific team, without impacting the roles that an user might have for another team.**

At this time I couldn't find any documentation on how to sync an user's role within a team. I was able to independently write this functionality in like so:

I've noticed that in the `LaratrustUserTrait`, the `syncRoles()` method is calling the `syncModels` method, which in turn calls Eloquent's `sync()` method.

The `sync()` method actually accepts a secondary optional boolean parameter, which dictates whether the sync should detach existing records. This allows us to have a sync with the condition "attach if not already attached" see below:

[https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L70](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php#L70)

With newer versions of Laravel, it comes with a `syncWithoutDetaching()` method, which is just a simple wrapper for `sync()` with that second parameter set to `false`.

_I was able to leverage that optional second parameter to sync without detaching. It seems that Laratrust has no implementation of such a method._ 

I then also wrote a `teams()` function, similar to Laratrust's `roles()` method that retrieves the `morphToMany()` polymorphic relationship between an user and their teams, with the `role_id` pivot.

With this, I am able to leverage some existing Laratrust functions/implementations and do something along the lines of:

``` 
$modelTableValues[$teamId] = [config('laratrust.foreign_keys.role') => $this->getIdFor($role, 'role')];
$this->teams()->sync($modelTableValues, false);
$this->flushCache();
```
You'll find that this is similar to what is being done in `syncModels()` in the `LaratrustUserTrait`.

I'm opening up an issue because after extensive review of Laratrust I did not find any way to achieve what I have described above.

If it is an issue/new feature that you think would be helpful, I can make a PR to add this implementation to the actual Laratrust package. I believe it would be useful to have the ability to sync roles within a team scope, without impacting roles in other teams. I'd be happy to contribute!

### Steps To Reproduce:

Call this on an user instance:

```
$user->syncRoles([$role], $team);
```
It will attach the given role to the user for that team.

Now call the same method, but with another role and another team.

You will notice it updates both the `role_id` and `team_id` for that user. However, it makes sense for an user to be able to update (sync) a role for one specific team without impacting their role in another team.

**Comment by santigarcor** [comment]
I think this is some kind of new feature, to sync without detaching. I didn't have that in mind when i implemented the teams.

If you want you can make a PR that adds a new method called syncRolesWithoutDetaching and if you can also implement the same method but for permissions.

**Comment by geracam** [comment]
Sweet, thanks for the fast response! Just wanted to make sure we weren't missing anything.

I'll get something together and open up a PR.

**Comment by santigarcor** [comment]
BTW please use the 4.0 branch

**Comment by chicag0** [comment]
@geracam can you share your teams() relationship?
