### ISSUE TITLE
Couldn't create seeder. Check the write permissions within the database/seeds directory.

### ISSUE THREAD

**Issue by Leif0** [santigarcor/laratrust#179]
- Laravel Version: 5.4.*
- Laratrust Version: 4.0.*

### Description:

When running the command to generate the seeders (php artisan laratrust:seeder), I get this error :

"Couldn't create seeder.
Check the write permissions within the database/seeds directory."

I have full permissions on the directories as you can see here(leif is in the www-data group)

![screenshot from 2017-08-05 14-47-40](https://user-images.githubusercontent.com/8561135/28995603-641bec5c-79ed-11e7-8d7f-5574a912aeda.png)

**Comment by santigarcor** [comment]
What user runs your php-cli?

**Comment by bibou1** [comment]
Hello, 
I am in the same situation as leif0, same problem and the same permissions, what is the solution please?

**Comment by KKSzymanowski** [comment]
Maybe the `LaratrustSeeder.php` file already exists. It seems the command doesn't differentiate these cases.

**Comment by bibou1** [comment]
Thanks for your feedback
there is a laratrust_seeder.php file in the config folder. What should be done to remove it?

**Comment by KKSzymanowski** [comment]
The `config/laratrust_seeder.php` file is just a configuration for how the seeder should be set up and it was created there with `php artisan vendor:publish` command. It doesn't affect the `database/seeds/LaratrustSeeder.php` file generation.
I was asking if there is a `database/seeds/LaratrustSeeder.php` file.

**Comment by bibou1** [comment]
Sorry,

yes, there is a LaratrustSeeder.php file

**Comment by KKSzymanowski** [comment]
@bibou1 Delete it if it's incorrect. If it's what you wanted just leave it there and use it.

@santigarcor Maybe we should differentiate these cases and display a different error message when the file already exists and when the script doesn't have write permission in the directory.

**Comment by bibou1** [comment]
thank you for your answer, it works

**Comment by santigarcor** [comment]
I'll make that change
