### ISSUE TITLE
[Proposal] Optimize seeder insertion

### ISSUE THREAD

**Issue by gabriel-caruso** [santigarcor/laratrust#180]
Hi there. With this proposal, I want to discuss a possible optimization in [Laratrust's seeder](https://github.com/santigarcor/laratrust/blob/master/src/views/generators/seeder.blade.php).

Besides to [check if a role has permission](https://github.com/santigarcor/laratrust/blob/master/src/views/generators/seeder.blade.php#L48-L50), and then attach it; [check if the user has permission](https://github.com/santigarcor/laratrust/blob/master/src/views/generators/seeder.blade.php#L89-L91), and also attach it, why don't loop through permissions, `firstOrCreate` each one (as it is), grab the `id` and **then** use Laravel's [`sync`](https://laravel.com/docs/5.4/eloquent-relationships) function?

**Comment by santigarcor** [comment]
I don't fully understand how would it work, please give a more detailed description of it.

**Comment by gabriel-caruso** [comment]
Hey @santigarcor 

Let's take a part of the code inside the seeder ([from line 33 to 54](https://github.com/santigarcor/laratrust/blob/master/src/views/generators/seeder.blade.php#L33-L54)):
```php
 // Reading role permission modules
 foreach ($modules as $module => $value) {
    $permissions = explode(',', $value);

    foreach ($permissions as $p => $perm) {
        $permissionValue = $mapPermission->get($perm);
        $permission = \{{ $permission }}::firstOrCreate([
           'name' => $permissionValue . '-' . $module,
           'display_name' => ucfirst($permissionValue) . ' ' . ucfirst($module),
           'description' => ucfirst($permissionValue) . ' ' . ucfirst($module),
        ]);

        $this->command->info('Creating Permission to '.$permissionValue.' for '. $module);
                    
        if (!$role->hasPermission($permission->name)) {
            $role->attachPermission($permission);
         } else {
             $this->command->info($key . ': ' . $p . ' ' . $permissionValue . ' already exist');
        }
    }
}
```

My idea is kill this conditional and attachment in every single loop, and use `sync()` once outside the loop, and let Laravel take care if the permission exists or not. e.g.:
```php
 // Reading role permission modules
$permissions_to_sync = null;
 foreach ($modules as $module => $value) {
    $permissions = explode(',', $value);

    foreach ($permissions as $p => $perm) {
        $permissionValue = $mapPermission->get($perm);
        $permissions_to_sync[] = $permission = \{{ $permission }}::firstOrCreate([
           'name' => $permissionValue . '-' . $module,
           'display_name' => ucfirst($permissionValue) . ' ' . ucfirst($module),
           'description' => ucfirst($permissionValue) . ' ' . ucfirst($module),
        ]);

        $this->command->info('Creating Permission to '.$permissionValue.' for '. $module);                    
    }
}

$role->syncWithoutDetaching($permissions_to_sync);
```

All the docs for `sync` and its variants can be found in Laravel's documentation, [inside the Many To Many Relationships section](https://laravel.com/docs/5.4/eloquent-relationships#updating-many-to-many-relationships).

If I didn't make myself clear, I can propose a PR, so you can see the differences, and test it :+1:

**Comment by santigarcor** [comment]
Yes please make the PR so i can test that.
