### ISSUE TITLE
can't use attachRole() method

### ISSUE THREAD

**Issue by ThamrinPH** [santigarcor/laratrust#181]
i tried to seed some role and user

        ```
        $sadminRole = new Role();
        $sadminRole->name = "Super admin";
        $sadminRole->display_name = "Super Admin";
        $sadminRole->description = "working as super Admin";
        $sadminRole->save();

        $sadmin = new User();
        $sadmin->name = "Developer";
        $sadmin->email = "dveloper@dev.op";
        $sadmin->password = bcrypt('dveloper@dev.op');
        $sadmin->save();
        $sadmin =attachRole($sadminRole);
```

then i tried to run the php artisan db:seed 

this error appear
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined function attachRole()

the role and the user is a succeed i checked the db and they were added.

**Comment by roelgonzalez94** [comment]
Try $sadmin->attachRole ($sadminRole );
I also suggest you read the documentation thoroughly.

**Comment by santigarcor** [comment]
Did you follow the installations steps showed in the docs? Did you add the LaratrustUserTrait to your User model? As @roelgonzalez94 said, i recommend you to read the [docs](http://laratrust.readthedocs.io/en/4.0/installation.html).

**Comment by ThamrinPH** [comment]
@roelgonzalez94 @santigarcor  first, thank you for the responses 
i tried to follow the documentation until seeder part and tried to make new role and user for some testing
and tried to follow my friend that recommend laratrust and his code are working
 it's so embarrassing for me that i'm not reading the documentation thorooughly 
and paying attention to the symbol that used .

thank you, Thank you for the respond and the code is working, 

maaan it's so embarrassinig
