### ISSUE TITLE
API Role and Permission 

### ISSUE THREAD

**Issue by khmeropenidea** [santigarcor/laratrust#183]
#Thanks for best package . 

I am new to laravel. So what is key to implement your package role and permission as token and session sample .

Thanks for your kindly .

**Comment by santigarcor** [comment]
@khmeropenidea can you explain me what do you mean by 'token and session sample' ?

**Comment by khmeropenidea** [comment]
using token like laravel passport ?

**Comment by santigarcor** [comment]
Check https://github.com/santigarcor/laratrust/issues/138

**Comment by santigarcor** [comment]
I believe 717cdfceca50bd7db4a301ece68da9d629701644 fixes this. It will be available in the next version.
