### ISSUE TITLE
Nested Role Permission and  Teams 

### ISSUE THREAD

**Issue by khmeropenidea** [santigarcor/laratrust#184]
How to create nested Nested Role and Permission  like below 

	#Admin
		##TeamAdministrator:  Controll full application 
		 
	#Owner : Project  Owner   
		##TeamOwner1
			 
		##TeamOwner2
			 
	#User  : Call center , update news , send email user
		##TeamUser 
	
	#shopper : Can create muliti shops, multi brands, 
		@TeamShopOwner Can create See report all shops, all brands, manager users , roles
		
		@TeamManager : approval purchaser Order at one or two shops 
		@TeamPurchaser : Create Purchaser Order at two or ten shops 
			Some users can approval and create same 
	
	#supplier : Can get message from client shopper 
		
	@TeamOwner : Create musliti users , Multi team
	
	@TeamDelivery : ............
	
	@TeamSaler : ............
		
		

Thanks for replay .

**Comment by santigarcor** [comment]
Juts create the roles and attach to them each permission that you want the roles to have, if you are using the seeder you can achieve that very easily check [here](http://laratrust.readthedocs.io/en/4.0/configuration/seeder.html). The things you should keep in mind are:

- You can't do role inheritance.
- You can't use teams in the seeder, you would have to attach those roles by doing another seeder or directly in you app.
- You have to specify to each role which exact permissions it has.

Just as an example:

```php
return [
    'role_structure' => [
        'owner' => [
            'teams' => 'c,r,u,d',
        ],
        'user' => [
            'news' => 'u',
            'teams' => 'r'
        ],
    ],
    ...
];
```

**Comment by khmeropenidea** [comment]
Sorry for my english is not good .

But what I want is create web application Allow Role 

#Admin 
#Owner 

#Shopper 
#Supplier 


#Admin And Owner is working on backend and controll #Shopper and #Supplier 


#Shopper has Many Roles 
##Shopper Admin 
##Shopper Users 
##Shopper manager .. 
Base on #Shopper owner Assign and create them by themselves


#Supplier Also has Many Roles 
#Owner , #Manager #Users ..... 
Base on #Supplier owner assign them. 


@santigarcor  Please kindly. 
Thanks .

**Comment by santigarcor** [comment]
I don't understand what you really want.

In any case, if you want a role to 'have' or 'inherit' multiple roles, you can't do that so check [here](https://github.com/santigarcor/laratrust/issues/148) for alternative solutions.

**Comment by khmeropenidea** [comment]
want users to be able to have companies, with roles within that company.
@santigarcor

**Comment by khmeropenidea** [comment]
Want have three 7  Roles is base  
owner of application company have three roles like below 
##Admin 

##Owner 

##Users 

-------------------------------------------------------------

Client Role has 4 roles role 

##Shopper 
##Shopper users (Manager , Purchaser )
For shopper users  roles and permission manage by Shopper 


##Supplier 
##Supplier User(Delivery, Sale) 
For supplier user roles and permission manage by Supplier

@santigarcor 

Thanks

**Comment by santigarcor** [comment]
Check http://laratrust.readthedocs.io/en/4.0/usage/concepts.html#teams

**Comment by khmeropenidea** [comment]
A company can have many users. 
A user can belong to many companies. 
A user can have many roles A user can have different roles in different companies.
 

` How to use team feature in this package ? `

**Comment by Kristories** [comment]
@khmeropenidea

`user`
- Joko => 
  - `role` : owner in Company A
- Widodo
  - `role` : developer in Company A
  - `role` : owner in Company B

---

`team` : 
- Company A
- Company B

`role` : 
- owner
- developer

---

```php
// JOKO
$user = User::where('name', 'Joko')->first();
$team = Team::where('name', 'company-a')->first();
$role_owner = Role::where('name', 'owner')->first();
$user->attachRole($role_owner, $team); // Joko as owner in Company A

// WIDODO
$user = User::where('name', 'Widodo')->first();
$team = Team::where('name', 'company-a')->first();
$role_developer = Role::where('name', 'developer')->first();
$user->attachRole($role_developer, $team); // Widodo as developer in Company A

$user = User::where('name', 'Widodo')->first();
$team = Team::where('name', 'company-b')->first();
$role_owner = Role::where('name', 'owner')->first();
$user->attachRole($role_owner, $team); // Widodo as owner in Company B
```
