### ISSUE TITLE
Crud Permissions

### ISSUE THREAD

**Issue by phuongphally** [santigarcor/laratrust#185]
How to manage permissions  or change permissions follow as 

```
#There are 4 record
create-post
edit-post 
update-post
delete-post 
``` 

`````````
#To  one record .
manage-post (create,edit,delete,update)
````````````

Thanks ,

**Comment by phuongphally** [comment]
I want to store permission likes 
` tables permissions_role (permission_id,roles_id,create,update,delete,approval)`



##Role Manager 
###-purchaser-order (create=1,update=1,delete=1,approval=1) 

##Role Purchaser 
###-purchaser-order(create=1,update=1,delete=0,approval=0)

Thanks

**Comment by santigarcor** [comment]
You can't 'group' permissions like that now, but it'll be a feature as discussed [here](https://github.com/santigarcor/laratrust/issues/170)
