### ISSUE TITLE
Multiple User Models Middleware

### ISSUE THREAD

**Issue by jago86** [santigarcor/laratrust#186]
Is possible to use the role or permission middleware using a second model Post if I'm using multiple user models? In my case I'm using both User and Post, but middleware seems to work only with User.

**Comment by santigarcor** [comment]
I belive there are two main problems with the middlewares and the multi-user:

1. As you can see [here](https://github.com/santigarcor/laratrust/blob/4.0/src/Laratrust/Middleware/LaratrustRole.php#L49) it's using `$request->user()
