### ISSUE TITLE
facing issue while installing on linux - commands issue

### ISSUE THREAD

**Issue by yasirrose** [santigarcor/laratrust#19]
Hi,

I am facing issue on linux while installing this package. After installation, it is giving me 
`Class name must be a valid object or a string` error

I am not able to run the laratrust commands from console. Did i have to do some thing special on linux.

**Comment by KKSzymanowski** [comment]
Could you provide your `config/auth.php` file?

**Comment by yasirrose** [comment]
Here it is: 

`return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class, 
            'table' => 'users', 
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | Here you may set the options for resetting passwords including the view
    | that is your password reset e-mail. You may also set the name of the
    | table that maintains all of the reset tokens for your application.
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'email' => 'auth.emails.password',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],


];`

**Comment by KKSzymanowski** [comment]
Ok, I thought it was an issue with `auth.providers.users.model` class not defined correctly. Could you locate this exception in `storage/logs/` and paste the stack trace here?

**Comment by yasirrose** [comment]
Here is the stack trace related to class name must be valid object error:
```
[2016-08-25 14:12:43] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class name must be a valid object or a string' in /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:956
Stack trace:
#0 {main
```

Here is the stack trace about commands: 

```
[2016-08-25 12:14:46] local.ERROR: exception 'Symfony\Component\Console\Exception\CommandNotFoundException' with message 'There are no commands defined in the "laratrust" namespace.' in /vendor/symfony/console/Application.php:469
Stack trace:
#0 /vendor/symfony/console/Application.php(501): Symfony\Component\Console\Application->findNamespace('laratrust')
#1 /vendor/symfony/console/Application.php(183): Symfony\Component\Console\Application->find('laratrust:setup')
#2 /vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}
```

**Comment by KKSzymanowski** [comment]
Second error exception was thrown because you didn't register a ServiceProvider but I assume you fixed that already.

Doesn't first exception have any stack trace?
Assuming you use Laravel 5.2, this is the line that caused this exception: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L956
I would check for any relationships you defined. Maybe you misspelled something.

**Comment by KKSzymanowski** [comment]
Also, you can clear the logs and run the command againt to be sure you're looking at the correct exception report.

**Comment by yasirrose** [comment]
Yes, i have already added it in providers. 

> Also, you can clear the logs and run the command againt to be sure you're looking at the correct exception report.
> Doesn't first exception have any stack trace?

> I have cleared the logs and check that again. it doesn't have any stack trace. 
> Assuming you use Laravel 5.2, this is the line that caused this exception: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L956
> I would check for any relationships you defined. Maybe you misspelled something.

Yes i am using using laravel 5.2. It is working on my local. But when i pushed my code to linux server. It has that issue.

**Comment by KKSzymanowski** [comment]
I'm not sure I can be of much help if I can't recreate this error nor see the stack trace.
Why do you need to run any laratrust commands on production server? The generated classes and migrations are already there.

**Comment by yasirrose** [comment]
Yes, it is already there. I am checking the commands because i think it is not installing properly on live server. 

There is one more issue which i am facing. The syntax in blade for permissions is not working. it is showing as output on page as text. 

@role('Admin') @endrole

**Comment by KKSzymanowski** [comment]
Why do you say something is not installed properly? What are the symptoms?

I don't know much about these blade directives, but if it's just showing plain text it seems that they're not registered. Create a separate issue, maybe @santigarcor can help you with that.

**Comment by yasirrose** [comment]
ok. thanks. i have generated a new one.

**Comment by santigarcor** [comment]
@yasirrose i'm sorry i couldn't answer earlier but i didn't had my PC near me.

But i'm glad you solved it.
