### ISSUE TITLE
Error in migration , laravel 5.5.3

### ISSUE THREAD

**Issue by hamrahpay** [santigarcor/laratrust#193]
Hello dear , I got an error after excute  `php artistan migrate`

```
php artisan migrate
Migration table created successfully.


  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `roles` add unique `roles_name_unique`(`name`)
  )



  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

```

**Comment by KKSzymanowski** [comment]
This may be related to https://github.com/laravel/framework/issues/20627.

BTW, you can use tripple back-ticks to indicate a multiline code block.
Refer to the [Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) for more information.
