### ISSUE TITLE
Login expiry date

### ISSUE THREAD

**Issue by mhellmeier** [santigarcor/laratrust#194]
Hey,

I added an _expireDate_ column to the _users_ table.
If a user tries to log in, it should check if the current date is greater than the expire date from the database. It should login the user after this or showing them an error message, that the login has expired.

My question:
Where do I have to put the if-case in the code, to check if the login has expired? It should be after the "Login" button is pressed but before the cookie is set. Where is the correct place?

Perhaps it also would be a nice feature to implement and active optionally.

**Comment by santigarcor** [comment]
I'm sorry but this question and suggestion are not related at all to this package, the idea of Laratrust is to handle authorization, not authentication.

BTW check the `lifetime` property in your `config/session.php` it could help you.

**Comment by KKSzymanowski** [comment]
Laratrust doesn't handle user authentication, only authorization.

Nevertheless, there are countless ways to handle this depending on your business logic and personal tase.
1. You can try retrieving the user by the credentials provided in the request and checking if the account hasn't expired before you call `Auth::attempt()`.
2. You can also create your own user provider eg. by extending `EloquentUserProvider` and put the expiry checking logic in the `validateCredentials` method.
3. If you want to allow users to login but don't want to allow them to make any requests you can create a middleware which checks for account expiry and wrap some routes with it.

**Comment by mhellmeier** [comment]
Thank you, @KKSzymanowski . Overriting the `validateCredentials` method in `EloquentUserProvider` made the trick for me.

Sorry for the invalid issue.
