### ISSUE TITLE
Does middleware works?

### ISSUE THREAD

**Issue by msieprawski** [santigarcor/laratrust#198]
- Laravel Version: 5.5
- Laratrust Version: 4.0.0.

### Description / Steps to reproduce:
Fresh laratrust installation. I've added following code into web.php routes file:
```
<?php

Route::group(['middleware' => 'role:administrator'], function () {

    Route::get('admin/project/index', [
        'as' => 'admin.project.index',
        'uses' => 'Admin\ProjectsController@index',
    ]);

});
```
What I get is ReflectionException: Class role does not exist

I can see in the package's code that middleware are not registered anywhere. So how come it can work by using just an alias role:... described under http://laratrust.readthedocs.io/en/4.0/usage/middleware.html

**Comment by msieprawski** [comment]
What I did that worked for me:
Register laratrust's middleware in app/Http/Kernel.php under $routeMiddleware array as follows:
```
'role' => \Laratrust\Middleware\LaratrustRole::class,
```

I couldn't find that information in docs. Maybe it would be worth to update it? Thanks!

**Comment by msieprawski** [comment]
What I did that worked for me:
Register laratrust's middleware in app/Http/Kernel.php under $routeMiddleware array as follows:
```
'role' => \Laratrust\Middleware\LaratrustRole::class,
```

I couldn't find that information in docs. Maybe it would be worth to update it? Thanks!

**Comment by santigarcor** [comment]
@msieprawski  I'm sorry but there's information about that in the installation guide, take a look [here](http://laratrust.readthedocs.io/en/4.0/installation.html).

**Comment by msieprawski** [comment]
@santigarcor shame on me! I didn't notice that! Thank you!
