### ISSUE TITLE
Error in middleware when protect a route 

### ISSUE THREAD

**Issue by knuks** [santigarcor/laratrust#199]
- Laravel Version: 5.4.* 
- Laratrust Version: 4.0.* 

when i protecting route with permission middleware it works fine. but when i type route in address bar with permission user does not then it wil give HttpException my code as follow

Route::get('user-create',['uses'=>'UserController@create','as'=>'user.create'])->middleware('permission:create-user');

it is not handle exception when user does not have permissions

**Comment by santigarcor** [comment]
It's handling the permissions, as the docs say, by default it calls `abort(403)` that's why you're getting that HttpException.
