### ISSUE TITLE
blade directive not working

### ISSUE THREAD

**Issue by yasirrose** [santigarcor/laratrust#20]
@santigarcor 

The blade directive is showing as plain text and it is not working. I am facing this issue on product server, not at my local. 

Can you please help me to register it.

**Comment by yasirrose** [comment]
working now. Provider was not loading properly on production. There was another service provider which is causing issue. Very Happy..........

**Comment by santigarcor** [comment]
@yasirrose i'm sorry i couldn't answer earlier but i didn't had my PC near me
