### ISSUE TITLE
Have some error when using composer remove the package, Help appreciated!

### ISSUE THREAD

**Issue by kingofswing** [santigarcor/laratrust#200]
- Laravel Version: 5.4.21
- Laratrust Version: 3.2.x 

### Description:
I want to remove the package to test if composer can do it successfully. but there are several errors ,see the following section pls. so ask if anyone can give some tips , am I missing some important steps ? 

### Steps To Reproduce:
$ composer remove santigarcor/laratrust
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Dependency "laravel/framework" is also a root requirement, but is not explicitly whitelisted. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing santigarcor/laratrust (3.2.0)
  - Removing kkszymanowski/traitor (0.2.3)
  - Removing nikic/php-parser (v3.0.5)
  - Installing nikic/php-parser (v3.1.1)
    Downloading: 100%         

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Laratrust\LaratrustServiceProvider' not found     
                                                           

Script php artisan optimize handling the post-update-cmd event returned with error code 1

Removal failed, reverting ./composer.json to its original content.

**Comment by KKSzymanowski** [comment]
Here's my theory:
1. In `config/app.php` you have `LaratrustServiceProvider` listed in the providers list
2. Composer removes Laratrust
3. Laravel tries to optimise providers
4. Laravel cannot find the Laratrust provider because it was just remove by Composer
5. Laravel optimize command therefore exists with a non-zero code
6. Composer sees that something went wrong and reverts the package list to the state from before removal.

Possible fix:
First remove `LaratrustServiceProvider` from `config/app.php`, **then** remove Laratrust from composer dependencies.

**Comment by kingofswing** [comment]
@KKSzymanowski   

Just as what you said，I tested ok in another project （the previous one I had upgrade it to 4.0）， thank you Mr. KKSzymanowski  .

**Comment by kingofswing** [comment]
But there are still more steps to clear the removal of the package , first I found I had to manually to remove or delete the relevant table in mysql db, because they are useless if I want to install another package or if I wanna to keep the db clean after compose remove .. I can't use migration rollback now. second , the User.php need to be modified to 'roll back' to its original status.  Is there any other steps or places I need to modify @KKSzymanowski  ?

**Comment by santigarcor** [comment]
Man obviously if you want to completely remove the package you have to delete de migrations, delete de databases, delete the config files, remove the models, delete the User trait, and remove everything in your code related to the package. There's no way composer will automatically do this for you.

**Comment by Vincent11110** [comment]
@KKSzymanowski you are my hero! spent hours searching for a solution nothing worked. your solution did! thanks.
