### ISSUE TITLE
Can Laratrust be used with Laravel Gates and Policies?

### ISSUE THREAD

**Issue by edamov** [santigarcor/laratrust#202]
Hi, 
I want to implement some custom logic for laratrust permissions.

For, example, lets take permission `create-post`.
If I say that only admins can `create-post` there are no problems: `$admin->attachPermission($createPost)`.

But if I say, for example, that admins can `create-post` only if they are older than 30 years and today is not Sunday. I can easy add such logic in [Policy](https://laravel.com/docs/5.5/authorization#policy-methods), but as I understand I can't use Laravel `can()` method because Laratrust implement it.

So the question is what is the best way to create custom logic for permissions if I can't use Policy?

**Comment by santigarcor** [comment]
@edamov of course you can use it alongside Laravel can method, you just simply have to put in your User:

```php

use Authorizable {
    Authorizable::can insteadof LaratrustUserTrait;
    LaratrustUserTrait::can as laratrustCan;
}
```

The can method in Laratrust is just calling hasPermission behind scenes. So after doing that, you have three options to check permissions in your policies:

- $user->isAbleTo();
- $user->hasPermission();
- $user->laratrustCan();

**Comment by ChrisThompsonTLDR** [comment]
You'll need to include

    use Illuminate\Foundation\Auth\Access\Authorizable;

if you are using >= Laravel 5.5

**Comment by santigarcor** [comment]
Since version 6.0 Laratrust supports gates and policies out of the box.
