### ISSUE TITLE
Non-static method Laratrust\Laratrust::can() should not be called statically

### ISSUE THREAD

**Issue by GitzJoey** [santigarcor/laratrust#203]
- Laravel Version: 5.5.13 
- Laratrust Version: 4.0.4 

### Description:
I'm upgrading from 5.4 to 5.5, and also upgrading Laratrust from 3.2.* to 4.0.4
I've following the step to upgrade from 3.x to 4.x in the docs
but this error show up

Non-static method Laratrust\Laratrust::can() should not be called statically

when calling laratrust in view/blade
command : if(Laratrust::can('menu-purchaseorder_create').........

it seem something to do with the auto-discover that L5.5 introduced but I don't know
the best way to handling it. please help tq

**Comment by santigarcor** [comment]
I'll try to replicate it, but why don't you use the `@permission` blade directive?

**Comment by santigarcor** [comment]
The problem is the auto discover, i put:
```json
"aliases": {
    "Laratrust": "Laratrust\\Laratrust"
}
```
instead of:

```json
"aliases": {
    "Laratrust": "Laratrust\\LaratrustFacade"
}
```

**Comment by GitzJoey** [comment]
previously i use entrust that's explain why i still use Laratrust::can()
anyway thanks for very fast response, really appreciate it
