### ISSUE TITLE
Middleware Route Resouce

### ISSUE THREAD

**Issue by aiqbalsyah** [santigarcor/laratrust#204]
Hello, 
Im using laravel 5.5 so i want to handle middleware by Route::resource;

`Route::resource('/', 'HomeController',[
	'names' => [
		'index' => 'index-admins'
	],
	'middlewareGroups' => [
		'index-admins' => 'permission:index-admins'
	]
]);`

But when the permission check is fail it won't redirect to params fail..
Something wrong with my code?

**Comment by KKSzymanowski** [comment]
I have not heard of `middlewareGroups` route parameter. Where is it documented?

Does the following work?
```php
Route::resource('/', 'HomeController')
     ->names(['index' => 'index-admins'])
     ->middleware(['permission:index-admins']);
```

**Comment by aiqbalsyah** [comment]
Thanks it work..
