### ISSUE TITLE
Is there blade directive to retrieve all permissions from a user and his roles ? 

### ISSUE THREAD

**Issue by kingofswing** [santigarcor/laratrust#206]
- Laravel Version: 5.4
- Laratrust Version: 4.0 just upgraded from 3.x.x

### Description:

First of all, Thanks for the great job from @santigarcor and other guys,  I got confused when using Laratrust in Blade , because of the direct permissions assigned to the Authed user, we can use @permission(...) to test if someone has the permissions to do sth, but what if the user has a role which has the same permission ?  so is there a directive in blade view that CAN retrieve and judge if a user has the permission directly from the user and through some role he owns ? 

Another point is when to use Role-Permission and when to use User-Permission in controller and view , is there a good practice on how to plan this ,  sorry for asking such a question here, I'm new to laravel and still making the first project with role and permission added in it with this package.

**Comment by santigarcor** [comment]
@kingofswing you don't need to use any special directive, if you use the ``@permission`` directive it checks if the user has the permission directly or through a role.

The idea of direct permissions is to assign special or individual permissions without the need to create a new role only for that user.

**Comment by kingofswing** [comment]
okay , thank U for your quick response !  But to my surprise , after I deleted the same permission from permission_role table and permission_user table , now it's confirm we don't assign the proper permisstion neither to the user or to the role which the user owns, but  the @permission('some-permission') still get displayed in the blade view. I had run the  `php artisan view:clear` to clean the view cache , is there any need to do more than this ?

**Comment by santigarcor** [comment]
If you removed it directly from the database you should run `php artisan cache:clear` because Laratrust uses cache.

**Comment by kingofswing** [comment]
Yeah, it's ok! really appreciated of your help !

**Comment by dendihandian** [comment]
Is there any directive if a user has any of the given permissions?
