### ISSUE TITLE
Ability not working correctly

### ISSUE THREAD

**Issue by Akhanto** [santigarcor/laratrust#207]
- Laravel Version: 5.4 
- Laratrust Version: 5.0 

### Description:
Using ability() with only one role or only one permission ends up in an `Invalid argument supplied for foreach()` exception. 

### Steps To Reproduce:
use `@ability(anyRole, anyPermission)`    
`@endability`   
in a blade template. It will throw an error. 

Try the same with `@ability(anyRole|, anyPermission|` and it will work.

**Comment by santigarcor** [comment]
I think you are passing the the parameters wrong. You can use the ability method like this:

```php
ability(['admin', 'owner'], ['create-post', 'edit-user']);

// or

ability('admin|owner', 'create-post|edit-user');
```

**Comment by Akhanto** [comment]
Thank you for the answer. The problem was that I hadn't got multiple needed 
roles so I didn't use brackets. I thought it would work that way with only 
one role/permission.


Am 6. Oktober 2017 7:14:14 nachm. schrieb Santiago García 
<notifications@github.com>:

**Comment by santigarcor** [comment]
Well you can pass one role and one permission like this:

```php
ability(['admin'], ['edit-user']);

// or

ability('admin', 'create-post');

```
