### ISSUE TITLE
Class App\User does not exist

### ISSUE THREAD

**Issue by ThamrinPH** [santigarcor/laratrust#209]
- Laravel Version: 5.4.# 
- Laratrust Version: 5.0.# 

### Description:

The User model is where it's supposed to be inside App folder, and yet when i tried to run 
php artisan laratrust:setup

when the command going to add LaratrustUserTrait it return 'Class App\User does not exist'
what should i do?

**Comment by KKSzymanowski** [comment]
Does the class exist?
Run:
```
php artisan tinker
```
and in the tinker
```
class_exists('App\User');
```

**Comment by ThamrinPH** [comment]
@KKSzymanowski yes it return true, what's next?

**Comment by KKSzymanowski** [comment]
Sorry for the late reply, I haven't got an email.

I cannot reproduce this. Have you tried running `composer dump-autoload`?

**Comment by ThamrinPH** [comment]
@KKSzymanowski i already solved it, i have a tried to put User.php in App\ but the laratrust won't recognize it, so i put it back to where it belong inside App\Models , and change the laratrust inside config model and it works,

thank you for the reply, can i ask other question before closing this,

what if it return false, what should i do, where should i tweak? for future references if i have met the class not found problem

**Comment by KKSzymanowski** [comment]
Assuming you use PSR-4 autoloading, you should check if the file's path(relative to the autoloading root) is the same as the namespace. If you move classes around the project(and do not update namespaces) you can end up with a following situation:
`app/Models/Foo.php`
```php
<?php

namespace App;

class Foo {}
```
This class will not be autoloaded and therefore you'll end up with this `Class does not exist` error.

**Comment by aleksandar-radev** [comment]
> 

That solved my issue
