### ISSUE TITLE
Undefined index: pivot in Helper.php (line 174)

### ISSUE THREAD

**Issue by frozonfreak** [santigarcor/laratrust#211]
- Laravel Version: 5.4.36
- Laratrust Version: 5.0.1

### Description:
Checking user permission crashes with Undefined index, in Helper.php
`$user->can('create-item', 'team-name')`

Dont see any pivot data being passed into hidrateModel method in Helper.php. How to get pivot data into model?

### Steps To Reproduce:
1. Create Role, Permission and attach permission to role
2. Create Team
3. Set `use_cache` to true. happens only when use cache is true. 
4. Create user and attach role to user with team. 
5. Check if user has role in given team.

**Comment by santigarcor** [comment]
Which cache driver are you using?

**Comment by santigarcor** [comment]
I did what you said, but i wasn't able to replicate the issue. Could you try cleaning your app cache (`php artisan cache:clear`)?

**Comment by frozonfreak** [comment]
Currently using file as cache_driver. 
yes tried cache , still getting the error. 

Setting use_cache to false as workaround. So got the code working for now.

**Comment by lmarcelocc** [comment]
Clear the cache worked for me. Thanks!

**Comment by jety91** [comment]
Same here. The cache clear not solved my problem.

Laravel Version: 5.5.19
Laratrust Version: 5.0.2
Description:

Same like frozonfreak, when I call the $user->can('permission') no pivot data passed to the hidrateModel.

And the use_cache => false solved my problem too.

**Comment by santigarcor** [comment]
Can you please give me a detailed description of what are you doing so I try to replicate the issue?

**Comment by jety91** [comment]
Ok, i figured it out the issue.
In my custom Role and Permission models I set the following:
`protected $hidden = ['pivot'];`
Which is cause this issue in the 5.0.* version.

Sorry santigarcor for the inconvenience!

**Comment by santigarcor** [comment]
Hmm that's a problem, but how bad is for you to not hide the pivot?
