### ISSUE TITLE
update permissions map and enable publish function like wordpress

### ISSUE THREAD

**Issue by knour89** [santigarcor/laratrust#216]
hello team,
the existing permissions are (creat,read,update,delete) can i add new one and call it P for publish, this will enable **publish** button in my website, so some people will have the ability to publish post and somebody no, just like wordpress.

**Comment by santigarcor** [comment]
Of course, you can add as many permissions as you want to the `permissions_map`. In your case you will have:

```php
'permissions_map' => [
    'c' => 'create',
    'r' => 'read',
    'u' => 'update',
    'd' => 'delete',
    'p' => 'publish'
]
```

And when you assign the permissions you will have something like this:

```php
'role_structure' => [
    'superadministrator' => [
        'users' => 'c,d,p',
    ],
]
```
