### ISSUE TITLE
saving additional column to pivot table (role_user) while attaching 

### ISSUE THREAD

**Issue by sudanese** [santigarcor/laratrust#217]
Hi ,
I'm very new to laravel and first time using laratrust ,  I'm using laratrust with teams and I've added an additional relationship ('organization' column) in all the tables . for creating roles i can just add it like 

` $Role->organisation = $user->organisation;
        $Role->save();
`

but I'm not sure about pivot tables with the command like attach role 
` $User->attachRole($validatedData['role'], $validatedData['team']);`
how to save the organisation to the user_role pivot table while attaching the role.

**Comment by santigarcor** [comment]
If you already have the organization id in the role and the user, why would you like to have the organization id in the `user_role` pivot table? Can you please explain your use case?

**Comment by sudanese** [comment]
Ahaaaa, got your point , I think I was focusing more on how to save it more than why I needed it , I was worried in cases of removing the role, and removing the entry from the pivot table , but now I can see that this case will never happen as no role id or user id will be the same in different organisation
