### ISSUE TITLE
user_type doesn't have a default value

### ISSUE THREAD

**Issue by Akhanto** [santigarcor/laratrust#218]
- Laravel Version: 5.4.# 
- Laratrust Version: 5.0.2 

### Description:
Attaching a Role to a user doesn't work but throws the error "

Field 'user_type' doesn't have a default value (SQL: insert into `role_user` (`role_id`, `team_id`, `user_id`) values (4, , 85))

This is my laratrust config file: https://pastebin.com/PLeCdHqC

This is my database structure: 
![image](https://user-images.githubusercontent.com/11016854/32888279-13b57208-cac7-11e7-8a33-29bc1e617af0.png)

Previously I used Laratrust 4 and that feature worked. I did all steps in the upgrade guide. 

### Steps To Reproduce:

Try to attach a role by using USER->attachRole(ROLE_OBJECT)

**Comment by santigarcor** [comment]
By any chance did you create a custom roles relationship inside the user model?

**Comment by Akhanto** [comment]
The problem is solved. I don't know what happened but doing an update, clearing cache und dump-autoload helped. 
Thanks!
