### ISSUE TITLE
Team 'name' is not column name

### ISSUE THREAD

**Issue by ufeg02** [santigarcor/laratrust#219]
In my installation I use a custom table for teams. In that table there is no column name, can I somewhere change the code where Laratrust is looking for that column?

**Comment by fabiolrs** [comment]
Not sure because I haven't tested on Laratrust, but can't you make something like an assessor?

```
public function getNameAttribute() {
   return $this->whateverYouUseForName;
}
```

Check here: https://laravel.com/docs/5.5/eloquent-mutators#defining-an-accessor

**Comment by santigarcor** [comment]
@ufeg02 check if fabiolrs solution works, but i'm not 100% sure if you can do that.

You could have a name column and simply assign the value when the team is saving. Could you please show us the team table structure?

**Comment by jbgassen** [comment]
Changing Helper.php > fetchTeam function doesn't do the trick?

$team = call_user_func_array(
         [Config::get('laratrust.models.team'), 'where'],
         ['your_column_name', $team]
)->first();
