### ISSUE TITLE
Guidelines for moving from zizaco/entrust

### ISSUE THREAD

**Issue by unitedworx** [santigarcor/laratrust#22]
Hi there just found this fork of zizaco/entrust and really really happy about it since entrust is kind of dead atm.

Any guidelines of moving from entrust to laratrast? Or I should simply swap packages along with namespaces and get going? I am using "zizaco/entrust": "master@dev"

**Comment by Naoray** [comment]
I switched a few days ago. Just remove every reference to zizaco/entrust, run
```bash
composer remove zizaco/entrust
```
and go on installing santigarcor/laratrust as suggested in the [docs](https://santigarcor.gitbooks.io/laratrust-docs/content/installation.html).

**Comment by santigarcor** [comment]
@unitedworx do as @Naoray said

**Comment by unitedworx** [comment]
Thanks for the replies, was simply wondering if this is a drop-in replacement for entrust or a complete rewrite where I would need to refactor alot of my code. will give it a go in a few days and see how it goes

**Comment by Naoray** [comment]
You don't have to throw out every line of code where you use the *zizaco/entrust*. Like when you create a role/permission or query for them, cause they are used the same way in *santigarcor/laratrust*. Just delete the ServiceProvider/alias Reference in the *config/app.php* file, that's all you've to remove.

**Comment by stevevg** [comment]
Remeber to call `php artisan view:clear` to delete all compiled views after you switch to Laratrust. 
It took me 20 minutes to figure that out (my views kept looking for the "Entrust" class, obviously not finding it).
