### ISSUE TITLE
how to flash message if role middlware failed with redirect?

### ISSUE THREAD

**Issue by tjnapster555** [santigarcor/laratrust#220]
how to flash the message when redirect the user to login screen

**Comment by santigarcor** [comment]
Please give a more detailed description, i don't understand what you want to do.

**Comment by tjnapster555** [comment]
i want to check inside the middleware that what role of user is using this middleware and if he is not super-admin then i redirect him to login screen with the message that you are not super-admin 
in this package we have two options one is abort and the other is redirect i want to use redirect with flash message

**Comment by KKSzymanowski** [comment]
I believe you can extend the needed middleware and override the `unauthorized` method if you only want to flash some data in the response or override the `handle` method if you want full control over the process.

**Comment by tjnapster555** [comment]
can you give me the example please full code , i am noob so please help me

**Comment by putheakhem** [comment]
@tjnapster555  which version of laravel that you use?

**Comment by tjnapster555** [comment]
@putheakhem  laravel 5.5

**Comment by chrisrollins65** [comment]
@tjnapster555 I just did it. Wasn't exactly a walk in the park though... 

First I created my own middleware like this (atm I'm only using the "Role" middleware in my app. You'd have to create similar middleware files for "Permission" and "Ability" if you use them):

    namespace App\Http\Middleware;
    
    use Illuminate\Support\Facades\Config;
    use Illuminate\Support\Facades\Redirect;
    use Laratrust\Middleware\LaratrustRole;
    
    class LaratrustRoleCustom extends LaratrustRole
    {
        protected function unauthorized()
        {
            $parameter = Config::get('laratrust.middleware.params');
    
            return Redirect::to($parameter)->with('error', 'my flashed message');
        }
    }

Then I had to disable Laratrust's default middleware from loading in `config/laratrust.php`:

    'middleware' => [
        'register' => false,

Then I had to add my custom middleware in the `$routeMiddleware` array in `Kernel.php`:

    'role' => LaratrustRoleCustom::class,

You'd do the same for `permission` and `ability` if you need them.
