### ISSUE TITLE
Dynamic team feature in middleware routes

### ISSUE THREAD

**Issue by mdanro** [santigarcor/laratrust#222]
- Laravel Version: 5.5.x
- Laratrust Version: 5.0.# 

### Description:
   Need help for best approach regarding team/organisation route check.
Before using the team feature , based only on roles and permissions i could easily have something like:

````php
Route::group(['prefix' => 'trust','middleware' => ['permission:view-trust']], function() {
    Route::group(['middleware' =>['permission:delete-trust']], function() {
         Route::DELETE('role/{Role}', 'Trust\RoleController@destroy')->name('role.destroy');
     })
});
````

This was great and powerful and the ability to nest permissions was used. Now i want to use the same method but with teams added to the mix, however each user can define its own team name and assign user rights to that particular team role. I have the user team at login so it should be available as a user attribute or cookie, session whatever.

How can i do that using laratrust? I am thinking in overriding the constructor of the controller as a basic mechanism or even worst checking in each action if the user in the specified team has the required role and permission within the current team. Is it possible to keep the above middleware approach and dynamically add team name in web.php? Is there a more simpler method?

Thank you
Dan

**Comment by santigarcor** [comment]
I'm not sure if you can add the team name dinamically in the routes or in the controller constructor. I think the only solution you have is to use the Laravel [gates and policies](https://laravel.com/docs/5.5/authorization#introduction).

**Comment by mdanro** [comment]
So the only option remains to insert the middle-ware check for team inside each action in the body of the function and redirect if not authorized, i was trying to avoid this rework as it is very time consuming, and honestly still searching for a more elegant method.

Maybe insert the team as a route prefix and check for the team parameter inside function?
Any outside of the box ideea could be useful...

**Comment by santigarcor** [comment]
The route parameter or prefix is not a bad idea, but you will have to override the Laratrust middleware or write a custom middleware(with the same API, so you don't have to make big changes) if you want to achieve that kind of functionality. But now i can't think of an easy out of the box solution to that problem.

**Comment by mdanro** [comment]
Thank you for your fast feedback and valuable input, i am brainstorming a lazy solution and this came to my mind, make a second user "model" like a login with team and user id, and use that user id from there after authentication. In this way whenever the company changes, the "virtual" login changes and points to another "userid" and use the old permission and roles based on this new usermodel that allready encapsulates the "Team" attribute.

Should this be enough?

Kind Regards
Dan

**Comment by andersson83** [comment]
@mdanro Did u find any solution for this?
