### ISSUE TITLE
[5.0] Role::syncPermissions() is not working for other values than id's

### ISSUE THREAD

**Issue by kaphert** [santigarcor/laratrust#225]
Laravel: 5.5
Laratrust: 5.0.2

The method `syncPermissions()` on the `LaratrustRoleTrait` is not doing what it should do I think. If you call `$role->syncPermissions(['do-this','do-that'])` it should sync those permissions with the role, right? That is not working at the moment it throws an exception because the string 'do-this' and 'do-that' are passed as second argument for the `Helper::getIdFor($object, $type)` method. 

https://github.com/santigarcor/laratrust/blob/e5f5c5da56d52813460f8ef444c15c43c94605f8/src/Traits/LaratrustRoleTrait.php#L155-L168

The permissions are being mapped in that piece of code, but nothing is done with it. If you change the function to the following it does work. If I look at the `LaratrustUserTrait` there are some extra methods made like `syncModels()` maybe the same logic could be used for the `LaratrustRoleTrait`? 

```
public function syncPermissions($permissions)
    {
        $mappedPermissions = [];

        foreach ($permissions as $permission) {
            $mappedPermissions[] = Helper::getIdFor($permission, 'permission');
        }

        $changes = $this->permissions()->sync($mappedPermissions);
        $this->flushCache();
        $this->fireLaratrustEvent("permission.synced", [$this, $changes]);

        return $this;
    }
```

**Comment by santigarcor** [comment]
You are right, it should have the same functionality. If you want, make a PR with those changes.
