### ISSUE TITLE
Class 'Laratrust\LaratrustServiceProvider' not found

### ISSUE THREAD

**Issue by 13enCoin** [santigarcor/laratrust#227]
- Laravel Version: 5.0.* ->latest
- Laratrust Version: 5.0.* ->latest

### Description:

Working with a new laravel/laratrust install follow the install guides, copied to github, pulled from github to production server and it brings up class errors, tried manually adding the classes too same error. 

### Steps To Reproduce:
Install new Laravel, install laratrust and follow instructions, pull from github to vps, 
    /**
     * Create a new provider instance.
     *
     * @param  string  $provider
     * @return \Illuminate\Support\ServiceProvider
     */
    public function createProvider($provider)
    {
        return new $provider($this->app);
    }
}

**Comment by santigarcor** [comment]
It's not going to work, because you are using Laravel 5.0.* and Laratrust 5.0 requires Laravel >= 5.2.32. Also why aren't you using composer to install it? And finally, please give the errors you are getting, because i don't understand those lines you put there.
