### ISSUE TITLE
Get all teams for a user

### ISSUE THREAD

**Issue by ralbear** [santigarcor/laratrust#228]
Hi

Is there any function to get all the teams for a specific user, i currently use `Auth::user()->roles()->get()` to get the roles but i need something similar to get the teams

Thanks!

**Comment by santigarcor** [comment]
You can create a relationship similar to the roles, but pointing to the teams. Here you have the roles relationship so you can use it as guide:

```php
/**
     * Many-to-Many relations with Role.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function roles()
    {
        $roles = $this->morphToMany(
            Config::get('laratrust.models.role'),
            'user',
            Config::get('laratrust.tables.role_user'),
            Config::get('laratrust.foreign_keys.user'),
            Config::get('laratrust.foreign_keys.role')
        );
        if (Config::get('laratrust.use_teams')) {
            $roles->withPivot(Config::get('laratrust.foreign_keys.team'));
        }
        return $roles;
    }
```

You just need to change the values for the teams and that should be all.

**Comment by ralbear** [comment]
Thanks, that is what i do but i post the question because maybe the package have something similar already.

#229 maybe you find interesting to add this functionality.
