### ISSUE TITLE
Strange behaviour of permission

### ISSUE THREAD

**Issue by cerkauskas** [santigarcor/laratrust#23]
Hello.
I am really loving this package! I've been using this successfully for a while now. However, today I got a problem. I set up "admin" role with permission "manage-roles".
But `$user->can('manage-roles') == false`.
Moreover, `$user->hasRole('admin') == true`.
So I set up a little testing:
`$role = \App\Role::where('name', 'admin')->first();`
Finds my role - cool.
`dump($role->permissions);`
Through relations property I can see that "manage-roles" entry of Role model - cool again.
`dump($role->hasPermission('manage-roles'));`
I get false. I can't understand why. Any ideas?
Thank you!

**Comment by cerkauskas** [comment]
Woops, cache. :)

**Comment by jpmurray** [comment]
Hey, thanks for having gone through that, I didn't figure myself that I had a cache refreshing need! :)
