### ISSUE TITLE
Call to a member function setRelation() on null

### ISSUE THREAD

**Issue by kikky7** [santigarcor/laratrust#231]
- Laravel Version: 5.5.25
- Laratrust Version: 5.0.3

### Description:
I upgraded from v4 to v5 and did all the steps in docs. I am getting this error:
`Call to a member function setRelation() on null`
when calling this line of code:
`return $this->hasRole('bidder');`
where $this is App\User object

The error is thrown inside Laratrust\Helper@hidrateModel where $model is null.

### Steps To Reproduce:
dumps inside the hidrateModel method:

```
dump(\App\Role::where('name', 'bidder')->get()->toArray());
array:1 [
  0 => array:6 [
    "id" => 6
    "name" => "bidder"
    "display_name" => "Bidder"
    "description" => "Bidder"
    "created_at" => "2017-12-18 10:31:41"
    "updated_at" => "2017-12-18 10:31:41"
  ]
]
```
`dump($class);`
`"App\Role"`
```
dump($data);
array:7 [
  "id" => 6
  "name" => "bidder"
  "display_name" => "Bidder"
  "description" => "Bidder"
  "created_at" => "2017-12-18 10:31:41"
  "updated_at" => "2017-12-18 10:31:41"
  "pivot" => array:2 [
    "user_id" => "3"
    "role_id" => "6"
  ]
]
```
`dd($model);`
`null`

### Edit:
If it helps: it fails inside phpunit test where I check if User has certain role (didn't test it in real app, yet), and when I set use_cache to false, the test passes.

**Comment by santigarcor** [comment]
By any chance do you have something in the `$hidden` attribute in your role model? Also, try cleaning your app cache.

**Comment by kikky7** [comment]
I have this method in Role model:
```
public function setNameAttribute($value)
{
    $this->attributes['name'] = strtolower(str_slug($value));
}
```
and after debugging, I found out that this method is causing the error when caching is enabled.

**Comment by santigarcor** [comment]
I was able to reproduce it and i found that you can solve the problem by adding `return $this;` at the end of the `setNameAttribute` because in the `setAttribute` method if they find that the attribute has a mutator, they return the value that your mutator returns, and in this case it's returning null.
