### ISSUE TITLE
Too many cicles

### ISSUE THREAD

**Issue by deveres** [santigarcor/laratrust#233]
- Laravel Version: 5.5.26 
- Laratrust Version: 5.0.4 

### Description:
I have:
3 roles
112 permissions

\Laratrust\Traits\LaratrustRoleTrait::hasPermission  -> lines 138, 139

>> foreach ($this->cachedPermissions() as $perm) {
>>            $perm = Helper::hidrateModel(Config::get('laratrust.models.permission'), $perm);
Hidrate creating in cycle objects every time ->hasPermission()  is used.  For my permissions it use ~ 5Mb of memory by run.

You can just take $perm->name from cache ($perm['name']) without hidrateModel.

Memory usage with  hidrateModel - 20.57MB
Run time with  hidrateModel - 1.23s

Memory usage without  hidrateModel - 16.33MB
Run time without  hidrateModel - 852.33ms

**Comment by santigarcor** [comment]
Fixed with #235

**Comment by mailnike** [comment]
Hi, i would like to know how this will behave if I have more than 200 permissions, more than 100+ roles i.e. 100*200 = role permissions assignment (SaaS product). I am facing some memory issues with Spatie, but it seems like this package can also cause same issue, could you please share your experience or an opinion.
