### ISSUE TITLE
give super admin all permissions

### ISSUE THREAD

**Issue by chicag0** [santigarcor/laratrust#236]
Is there a way to automatically give a superadmin type Role all permissions?  Or, everytime I create a new permission to I have to go back and assign it to the SuperAdmin?

I know I can check if a user " is SuperAdmin or ->can('doSomething') " but I thought it would be easier to skip the first half of the check.  For example, it would be great if $superAdminUser->can('doSomethign') always returned true regardless of weather I already added that permission

**Comment by santigarcor** [comment]
You can add a logic to your permissions' creation, so when you create a new permission, it's automatically assigned to the role you want.

**Comment by chicag0** [comment]
Thank you, that's a good idea -- I guess I could create a PermissionObserver and attach the permission to the Admin Role.  

Also, second question (not sure I need to create another issue) -- I was thinking that the permission_role table also had a team_id.  I'd like to assign different permissions per role, per team.  

Here is what I imagine, I have two roles, called 'Team Leader' and 'Team Member' and I have a few teams like 'Support', 'Marketing', 'Sales'.  I want the 'Team Leader' role on 'Support team to have different permissions than the 'Team Leader' role on the 'Sales' team.  I want to use the same Permission, like 'read-posts' but assign it differently.

Is there a suggested way to go about this without needing to create more permissions, like 'read-posts-sales' and 'read-posts-marketing'.

**Comment by santigarcor** [comment]
Actually I can't think of the best way to solve that issue. But one way would be to create more roles so you don't have to create multiple permissions

**Comment by mhelaiwa** [comment]
Why there is no way like spatie permissions to do that?

```
Gate::before(function ($user, $ability) {
    return $user->hasRole('Super Admin');
});
```
