### ISSUE TITLE
Two sites same server

### ISSUE THREAD

**Issue by pedrorodriguesrp** [santigarcor/laratrust#238]
- Laravel Version: 5.5 
- Laratrust Version: 4.0

### Description:
When i have two sites on same server, and i login in these sites with same user e have a conflict permissions.

**Comment by santigarcor** [comment]
Please give a more detailed description of the problem.

**Comment by pedrorodriguesrp** [comment]
The problem occurs on the server or when I run both sites locally on the ampps. I have site A and site B. In both sites I have the same user with the same password, and when I log in to site A and B, the permissions of one one overlaps on the other.

The sites have separate BD, I've changed the cookie => 'SITEA' and 'cookie' => 'SITEB' and use SESSION_DRIVER = file.

Supposedly the sites are totally separate, but the permissions conflict. If for example site A is reading the permissions of site B, just go to my page to assign permissions of site A and change a permission, and the permissions of site A become over the permissions of site B.

**Comment by santigarcor** [comment]
Are you using cache? And which type of cache are you using.

Try disabling the cache, maybe that could be the problem.

**Comment by pedrorodriguesrp** [comment]
Using REDIS, change 'database' => , in database.php to diferent values in two sites and resolve the problem. Thank you
