### ISSUE TITLE
Redirect users to certain page based on roles during login.

### ISSUE THREAD

**Issue by ianaisa25** [santigarcor/laratrust#239]
Hi, I'm just a newbie. How can I use laratrust roles to redirect users to certain page when they logon. Example, admin will go to admin dashboard and users to homepage using same login.

**Comment by santigarcor** [comment]
In your LoginController you can override the `protected function authenticated(Request $request, $user)` method and there you can put the logic you need for the redirection.

**Comment by ianaisa25** [comment]
Thanks for the tip. Great help! Btw, your package is super cool.

**Comment by ianaisa25** [comment]
Finally make it to work. :)  Thank you!

**Comment by ianaisa25** [comment]
code used to redirect to admin page..

protected function authenticated (Request $request, $user) { 
if ($user-> hasRole('superadministrator')) 
{return redirect()-> route('admin.dashboard'); }
}

**Comment by davidkhierl** [comment]
@ianaisa25 Hi, Can you also help me with this

`protected function redirectTo(Request $request, $user)`
` {`
` if ($user-> hasRole('superadministrator')) {`
` return redirect()-> route('admin.dashboard');`
` }`
` }`

I have this code in my LoginController.php but i'm having an error

"Type error: Too few arguments to function App\Http\Controllers\Auth\LoginController::redirectTo(), 0 passed in C:\..\vendor\laravel\framework\src"

do i have to use any class?

**Comment by azlaan4** [comment]
@davidkhierl 
use 
return view('admin/dashboard');
instead of 
return redirect()-> route('admin.dashboard');

**Comment by azlaan4** [comment]
@davidkhierl 

have you call "Request" above like so:

use Illuminate\Http\Request;
or
use Request;

**Comment by YosefOberlander** [comment]
Hi,

Please make sure you have the ```use use Illuminate\Http\Request; ``` at the top of the file like this.

```
<?php

namespace App\Http\Controllers\Auth;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
```
