### ISSUE TITLE
How would you get the role within a team?

### ISSUE THREAD

**Issue by DPerkunas** [santigarcor/laratrust#240]
I'm wondering if I'm trying to create something that's already built in. I can't seem to find this in the documentation.

Is there a way to get the user's role within a specified team? I'm working on a company platform. Users are assigned to multiple companies, and within each company they have a role. I'm using teams as the company ID's. So how would I get the Role of the specified user based on the team?

For validating whether or not they can perform actions I do 
`$user->isAbleTo('do-something',$company_id); `

**Comment by KKSzymanowski** [comment]
`User::hasRole()` accepts a team as the [second parameter](https://github.com/santigarcor/laratrust/blob/5.0/src/Traits/LaratrustUserTrait.php#L146). Does this fit your use case?

**Comment by DPerkunas** [comment]
It does not, the goal is to list the name of the role within the given team. Not to check if they are part of the role.

Simplified Ideal Scenario : 
```
$roleNames = $user->roles()->where('team_id','=','124')->get();
var_dump($roleNames); 
```

```
[
  0 => [role_id => 1, team_id => 124, 'name' => 'Manager'], 
  1 => [role_id => 2', 'team_id' => 124, 'name' => 'Intern']
]
```

Hope that makes sense.

**Comment by KKSzymanowski** [comment]
Sorry, I misunderstood your question.
I don't think there's a built-in functionality, but if you don't want to repeat the team where clause all over the codebase you can move it to a dedicated method on the User model.
```php
public function rolesInTeam($team)
{
    return $this->roles()->where('team_id', $team)->get();
}
```
Is there more to it?
What do you mean by `Simplified Ideal Scenario`? What's the real-life scenario?

**Comment by DPerkunas** [comment]
Actually, that was it! It was that simple, thank you.
