### ISSUE TITLE
Attaching permission to roles.

### ISSUE THREAD

**Issue by ianaisa25** [santigarcor/laratrust#242]
Basically, I'm trying to make an interface to attach a permission to a role using checkbox.  

In my edit view page.

//hidden input
<input class="form-check-input"  type="hidden" name="permissions">

       
          <div class="form-group">
          // Checkbox is checked if role has permission and show all available permissions 
            @foreach($permissions as $permission)
            <div class="form-check pt-1">
              <h5 class="form-check-label" >
                <input class="form-check-input" type="checkbox" name="permissions" value="{{$permission->id}}"
                @if ($role->permissions->contains($permission->id)) checked='checked' @endif>
                {{$permission->display_name}} <small><em>({{$permission->description}})</em></small>
              </h5>
            </div>
            @endforeach

and update function in my roleController

public function update(Request $request, $id)
    {
        $this->validate($request, [
          'display_name' => 'required|max:225',
          'description' => 'required|max:225'
      ]);

        $role = Role::findOrFail($id);
        $role->display_name = $request->display_name;
        $role->description = $request->description;
        $role->save();

        if ($request->permissions) {
          $role->syncPermissions(explode(',', $request->permissions));
        }

        return redirect()->route('roles.show', $id);
    }

I was able to retrieve current permissions attached to a role and is mark  checked. MY PROBLEM is every time I tried to edit the permission for a role only one permission will be saved in the database. Example, I have 10 permissions in a checkbox, if a click 3,4,5 permission 5 will only be saved. I read many blogs including the hidden trick in input but no luck. Somebody can help me. It would be a great help. Thanks in advance!

**Comment by sharik709** [comment]
that is because you are using 
```
name="permissions"
```
try
```
name="permissions[]"
```
you'll get an array [3,4,5]. loop through it save it. It should work fine.

**Comment by ianaisa25** [comment]
I use explode in my update function...

**Comment by ianaisa25** [comment]
If I'm going to use permissions[], what would be my update function looks like? Sorry I'm just new in laravel. I tried trial and error but still no luck. I've been following devmaketer video on advance  blog but I prefer not to use vue and bootstrap as my framework.

**Comment by santigarcor** [comment]
If you use permissions[], you only have to call request->permissions and it will return an array.

**Comment by ianaisa25** [comment]
My next problem is how to sync selected permissions to a role in update function.

**Comment by santigarcor** [comment]
If the $request->permissions returns the array with the IDs, you only have to pass it to the syncRoles function and that's all.

**Comment by ianaisa25** [comment]
Thanks! :)

**Comment by turashrocks** [comment]
Thanks @santigarcor

**Comment by abenooo** [comment]
what is the syntax for the @can(permission name) in laratrust Laravel 8 to grant permission and to user permission instead of role?
