### ISSUE TITLE
User Role pivot get delete on soft deleting role/team

### ISSUE THREAD

**Issue by mohsinadeel** [santigarcor/laratrust#244]
- Laravel Version: 5.4 
- Laratrust Version: 5.0.* 

### Description:
When I soft delete role or team, the pivot table role_user entry get removed.  All other config options are intact except 'use_team' is changed to true.

**My Role Model:**
class Role extends LaratrustRole {
	use SoftDeletes;
	protected $dates = [ 'deleted_at' ];
}
**My Team Model:**
class Team extends LaratrustTeam {
	use SoftDeletes;
	protected $dates = [ 'deleted_at' ];
}
### Steps To Reproduce:

I have applied role and team to a user, but when I remove a role or team using Soft Delete the corresponding entry get delete from the pivot table.

**Comment by santigarcor** [comment]
It's a bug as you can see in the [LaratrustUserTrait](https://github.com/santigarcor/laratrust/blob/5.0/src/Traits/LaratrustUserTrait.php#L45)  vs the [LaratrustRoleTrait](https://github.com/santigarcor/laratrust/blob/5.0/src/Traits/LaratrustRoleTrait.php#L44). The if condition is not right in the LaratrustRoleTrait, LaratrustTeamTrait and LaratrustPermissionTrait.

**Comment by mohsinadeel** [comment]
Thanks for the response. I have resolved it by method overriding in my classes the if conditions. Thanks.
