### ISSUE TITLE
Using Multiple Auth Middleware Checking Gaurd

### ISSUE THREAD

**Issue by zymawy** [santigarcor/laratrust#246]
**Hay! **
I Sow This [Issue ](https://github.com/santigarcor/laratrust/issues/186)And It Seems It's Nearly My Problem  And [Fix](https://github.com/santigarcor/laratrust/commit/717cdfceca50bd7db4a301ece68da9d629701644)
I Couldn't Find Any Guidance On Setting Up Multi Auth 

I Have **User** , **Admin** Multi Auth 
I Sutep Everything But Still, The Middleware Checking The Auth User Gaurd 
I Want To Let It Work In Admin Gaurd.

**Comment by santigarcor** [comment]
With all respect, could you please try explaining yourself better? I didn't understand anything.

**Comment by zymawy** [comment]
Okay With All Respect I Will Explain Myself , 

First Of All, I Have Two Models With **User* * Model , **Admin** Model. 

User Model Has It's Own Guard _Web Guard_ 
As Well As Admin Model Has It's Own Guard _Admin Guard_

I Want Able Roles And Permissions To Admin Model Only. 

Alright My Issue Is 

How To Setup This Beautiful Package 📦 With Mu Admin Model Not User Model 

Hopefully We Are In The Same Line Till Now

**Comment by JohnmarkWB** [comment]
Hey, I think I may have a similar question. The issue I have found is that when I generate a seeder it only creates users for the users table while like in @zymawy's case they are necessary in the Admin table. Is there a way around that?

**Comment by santigarcor** [comment]
@zymawy if you differentiate your users from your admins by the model, why would you need to use the package? Anyway, remove the Trait from the User model, next remove the user model from the user_models array and finally in your middlewares set the admin guard as the [docs](http://laratrust.readthedocs.io/en/5.0/usage/middleware.html#concepts) say.

@JohnmarkWB as you can se here in the [docs](http://laratrust.readthedocs.io/en/5.0/configuration/seeder.html) the seeder picks the first item in the user_models array.

**Comment by zymawy** [comment]
@santigarcor The Project  Already Running And It Was Created From Other Developers The Manager Required !! Thx You Mr. @santigarcor For Help Out ❤️
