### ISSUE TITLE
How to detach a Role

### ISSUE THREAD

**Issue by ianaisa25** [santigarcor/laratrust#248]
Have a blessed day Santi! I'm super nood in laravel and I think I need a spoonfeed answer regarding detaching/attaching a role. I already read the docs but I don't have any clue how to pass it in my controller and view. I wanted to have a remove button where it detaches certain role to a user when  clicked and an add button where it attaches a role the same way.

**Comment by ianaisa25** [comment]
And also I tried this
$user = User::whereRoleIs('journalist')->get();
$journalist = Role:: where('name', 'journalist')->first();
$user->detachRole($journalist);

Throws an error like method detachRole does not exist

**Comment by santigarcor** [comment]
Your problem is that you are using ->get() and when you do that, the query will return a collection so that's why you are getting the exception. Do it this way:

```
$user = User::whereRoleIs('journalist')->first();
$journalist = Role:: where('name', 'journalist')->first();
$user->detachRole($journalist);
```

**Comment by ianaisa25** [comment]
Big Thanks! It works but I have another problem, everytime I press the delete button      the first user whose  role is journalist will be deleted first. Let say User A, B,C. I want to delete User C but the result turns out User A  was deleted. Here's my view blade.php

<form action={{route('remove.writer')}} method="POST">
{{csrf_field()}}

@foreach ($users as $user)
<a class="panel-block">
{{$user->name}}
<button class="button is-danger>Delete</button>
</a>
@endforeach
</form>


In Controller
public function index()
{
$users = User::whereRoleIs ('journalist')->get();
return view ('pages.news.writers')->with('users', $users);
}

public function removeWriter ()
{
$user = User::whereRolesIs('journalist')->first();
$journalist = Role::where('name', 'journalist')->first();
$user->detachRole($journalist);

return redirect()->route('to my writers page');
}

**Comment by ianaisa25** [comment]
{{csrf_field()}}
@foreach ($users as $user)

{{$user->name}}
<button class="button is-danger>Delete

@endforeach

**Comment by santigarcor** [comment]
You need to fetch the user by his id not by his role, because if there are various users with that role you won't know to which user you are removing the role.

**Comment by ianaisa25** [comment]
Thanks for the tip. I figured it out. I created a hidden form with a value of the user's id. It works now. THANKS!
