### ISSUE TITLE
permission middleware crash

### ISSUE THREAD

**Issue by jonuran** [santigarcor/laratrust#250]
- Laravel Version: 5.5.28 
- Laratrust Version: 5.0 

### Description:
Hello, thanks for this package, its really good. 
When I use a permission middleware on an class construct, (or when I use hasPermission method) and the user don't have permision, I have this error 

[Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN) Maximum execution time of 30 seconds exceeded ]

 

### Steps To Reproduce:

BankController.php

public function __construct()
{
     ...
    $this->middleware('permission:bank',['only'=>['index']]);
     ...
}
//The list-bank permission register exists in the DB

routes/web.php
...
Route::resource('bank', 'BankController');
...

on config/laratrust.php

'middleware' => [
        'register' => true,
        'handling' => 'redirect',
        'params' => 'home',

    ],

Thanks for your time!

**Comment by santigarcor** [comment]
Did you tried changing the handling to abort? and the params to 403 for example?in that case is happening the same?
