### ISSUE TITLE
Admin panel for laratrust

### ISSUE THREAD

**Issue by ralbear** [santigarcor/laratrust#252]
Is there any admin panel for laratrust? I see something similar for other permission packages but nothing to this one.

Thanks!

**Comment by santigarcor** [comment]
As far as i know, i don't think there's an admin panel for Laratrust.

**Comment by scottybo** [comment]
do you know of any guides or tutorials on how to create one?

**Comment by santigarcor** [comment]
@scottybo, you can watch this [video](https://www.youtube.com/watch?v=hEjrUCEN3WY&list=PLwAKR305CRO_cukAejlt5kz3pTtDMW_Cd&index=15) series from chapter 12 to 15, This video show how @jacurtis created the users, roles and permissions' CRUD using Laratrust, and it is very well explained.

**Comment by scottybo** [comment]
awesome, thanks!

**Comment by ferdousulhaque** [comment]
You can follow the tutorial at below link:
[Laratrust Based Admin Panel Creation from the Scratch](https://medium.com/@ferdousul.haque/laratrust-based-adminpanel-creation-from-the-scratch-in-laravel-2d6b6b69fa2a)

Also full code for admin panel at github: [Laratrust Admin Panel](https://github.com/ferdousulhaque/laratrust-adminpanel)

**Comment by molerat619** [comment]
I would really like to see a support admin panel as well. I couldn't find anything good out there yet. With Laravel Voyager I thought there might be something, but even there no.

**Comment by vhalamzah** [comment]
I love how the video series is explained into detail by @jacurtis, it is very easy and straight forward but I still don't understand how  @jacurtis used  Route::middleware('role:editor|administrator'); in the routes  file and i dont know where to place the user can or user is able to method

**Comment by schmidtflo** [comment]
Now that nova is out, any chance that you (or somebody else) will make a nova package for Laratrust? Could be inspired by the nova package for spatie/permission. https://novapackages.com/packages/vyuldashev/nova-permission

**Comment by santigarcor** [comment]
@schmidtflo It would be great but I think I would need a license to develop the package and it's a little expensive for me (in my currency).

**Comment by latifasaee** [comment]
@santigarcor I'am facing another problem after updating to Laravel 5.8 from 5.7. I already changed the fire() to dispatch(). But no luck.  May you help please.
```
In LaratrustHasEvents.php line 46:
                                                                 
  Call to undefined method Illuminate\Events\Dispatcher::fire()
```

**Comment by belzaaron** [comment]
@schmidtflo @santigarcor I'm going to be attempting to create a Nova package. But, this will be my first time developing for Nova; so I can't give a date yet. I'll be updating this comment with development status. If someone has tips / requests / etc. please let me know!

Also thank you Santiago (& [contributors](https://github.com/santigarcor/laratrust/graphs/contributors)) for your hard work and diligence with this package.

**Comment by santigarcor** [comment]
@belzaaron that's great, thank you for doing that!

**Comment by tpetry** [comment]
I have not tried it yet but there is [nova-trust](https://novapackages.com/packages/zareismail/nova-trust) for laravel nova.

**Comment by jh872** [comment]
This issue is quite old, and I'm not even sure if this is what you're looking for. However, I sat down and just smashed something together to make a simple panel. It can for certain be made better, and there are most likely some mistakes here and there, but it should give an idea. 

[Panel - Git](https://github.com/jh872/Laratrust-Panel)

Thanks for the package santigarcor.

**Comment by santigarcor** [comment]
I'm working on something for the 6.0 release :fire:

**Comment by santigarcor** [comment]
Today I release version 6.0 that now includes a very simple admin panel for roles and permissions

**Comment by rmiqbalramadhan** [comment]
How to override laratrust admin panel? I want to modify it on my own.
I'm using this command 

`php artisan vendor:publish --tag=laratrust-views`

but the result was unable to locate publishable resource
is there any reference i can read? Thank you.

(if the suggestion is to make my own view instead publishing, then ignore this)

**Comment by santigarcor** [comment]
@rmiqbalramadhan the current admin panel is not publishable.

**Comment by drishyajose** [comment]
This might help someone..
i tried the url  mentioned in the laratrust docs in my local server as 
"http://localhost/projectname/public/laratrust" 
but redirected to
 "http://localhost/laratrust/roles-assignment"  
So  i used this  in my project url as **"**http://localhost/projectname/public/laratrust/roles-assignment**"** .
Now I got the admin panel. Then, from  the menu you can access roles,permissions etc..
