### ISSUE TITLE
Can't use ->hasrole() (BadMethodCallException)

### ISSUE THREAD

**Issue by ufeg02** [santigarcor/laratrust#255]
I get an error when I try to use $user->hasrole('role').

BadMethodCallException
Method hasRole does not exist.

If I do dd .... this is the result:

```php
array:4 [▼
  "Laratrust\Traits\LaratrustUserTrait" => "Laratrust\Traits\LaratrustUserTrait"
  "Illuminate\Notifications\Notifiable" => "Illuminate\Notifications\Notifiable"
  "Laravel\Passport\HasApiTokens" => "Laravel\Passport\HasApiTokens"
  "Lexx\ChatMessenger\Traits\Messagable" => "Lexx\ChatMessenger\Traits\Messagable"
]
array:153 [▼
  0 => "capture"
  1 => "instance"
  2 => "method"
  3 => "root"
  4 => "url"
  5 => "fullUrl"
  6 => "fullUrlWithQuery"
  7 => "path"
  8 => "decodedPath"
  9 => "segment"
  10 => "segments"
  11 => "is"
  12 => "routeIs"
  13 => "fullUrlIs"
  14 => "ajax"
  15 => "pjax"
  16 => "secure"
  17 => "ip"
  18 => "ips"
  19 => "userAgent"
  20 => "merge"
  21 => "replace"
  22 => "json"
  23 => "createFromBase"
  24 => "duplicate"
  25 => "session"
  26 => "setLaravelSession"
  27 => "user"
  28 => "route"
  29 => "fingerprint"
  30 => "setJson"
  31 => "getUserResolver"
  32 => "setUserResolver"
  33 => "getRouteResolver"
  34 => "setRouteResolver"
  35 => "toArray"
  36 => "offsetExists"
  37 => "offsetGet"
  38 => "offsetSet"
  39 => "offsetUnset"
  40 => "__isset"
  41 => "__get"
  42 => "__construct"
  43 => "initialize"
  44 => "createFromGlobals"
  45 => "create"
  46 => "setFactory"
  47 => "__clone"
  48 => "__toString"
  49 => "overrideGlobals"
  50 => "setTrustedProxies"
  51 => "getTrustedProxies"
  52 => "getTrustedHeaderSet"
  53 => "setTrustedHosts"
  54 => "getTrustedHosts"
  55 => "setTrustedHeaderName"
  56 => "getTrustedHeaderName"
  57 => "normalizeQueryString"
  58 => "enableHttpMethodParameterOverride"
  59 => "getHttpMethodParameterOverride"
  60 => "get"
  61 => "getSession"
  62 => "hasPreviousSession"
  63 => "hasSession"
  64 => "setSession"
  65 => "getClientIps"
  66 => "getClientIp"
  67 => "getScriptName"
  68 => "getPathInfo"
  69 => "getBasePath"
  70 => "getBaseUrl"
  71 => "getScheme"
  72 => "getPort"
  73 => "getUser"
  74 => "getPassword"
  75 => "getUserInfo"
  76 => "getHttpHost"
  77 => "getRequestUri"
  78 => "getSchemeAndHttpHost"
  79 => "getUri"
  80 => "getUriForPath"
  81 => "getRelativeUriForPath"
  82 => "getQueryString"
  83 => "isSecure"
  84 => "getHost"
  85 => "setMethod"
  86 => "getMethod"
  87 => "getRealMethod"
  88 => "getMimeType"
  89 => "getMimeTypes"
  90 => "getFormat"
  91 => "setFormat"
  92 => "getRequestFormat"
  93 => "setRequestFormat"
  94 => "getContentType"
  95 => "setDefaultLocale"
  96 => "getDefaultLocale"
  97 => "setLocale"
  98 => "getLocale"
  99 => "isMethod"
  100 => "isMethodSafe"
  101 => "isMethodIdempotent"
  102 => "isMethodCacheable"
  103 => "getProtocolVersion"
  104 => "getContent"
  105 => "getETags"
  106 => "isNoCache"
  107 => "getPreferredLanguage"
  108 => "getLanguages"
  109 => "getCharsets"
  110 => "getEncodings"
  111 => "getAcceptableContentTypes"
  112 => "isXmlHttpRequest"
  113 => "isFromTrustedProxy"
  114 => "matchesType"
  115 => "isJson"
  116 => "expectsJson"
  117 => "wantsJson"
  118 => "accepts"
  119 => "prefers"
  120 => "acceptsJson"
  121 => "acceptsHtml"
  122 => "format"
  123 => "old"
  124 => "flash"
  125 => "flashOnly"
  126 => "flashExcept"
  127 => "flush"
  128 => "server"
  129 => "hasHeader"
  130 => "header"
  131 => "bearerToken"
  132 => "exists"
  133 => "has"
  134 => "hasAny"
  135 => "filled"
  136 => "keys"
  137 => "all"
  138 => "input"
  139 => "only"
  140 => "except"
  141 => "query"
  142 => "post"
  143 => "hasCookie"
  144 => "cookie"
  145 => "allFiles"
  146 => "hasFile"
  147 => "file"
  148 => "macro"
  149 => "mixin"
  150 => "hasMacro"
  151 => "__callStatic"
  152 => "__call"
]
```

**Comment by ufeg02** [comment]
This is how my User model looks

'''php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;
use Laratrust\Traits\LaratrustUserTrait;
use Laravel\Passport\HasApiTokens;
use Lexx\ChatMessenger\Traits\Messagable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;
    use HasApiTokens;
    use Messagable;

    protected $table = 'users';
    protected $fillable = ['name', 'email', 'password'];

    //protected $primaryKey = 'userid';

    public function user_detail()
    {
        return $this->hasOne('\App\User_Detail');
    }


}
'''

**Comment by santigarcor** [comment]
Are you trying to use the method `hasrole` or `hasRole`?

**Comment by ufeg02** [comment]
hasRole

**Comment by santigarcor** [comment]
can you please give the full stack-trace of the error?

**Comment by ufeg02** [comment]
You mean this?

BadMethodCallException 
…\vendor\laravel\framework\src\Illuminate\Support\Traits\Macroable.php96
56
Illuminate\Http\Request __call
…\app\Http\Controllers\Auth\LoginController.php45
55
App\Http\Controllers\Auth\LoginController authenticated
…\vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php104
54
App\Http\Controllers\Auth\LoginController sendLoginResponse
…\vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php43
53
App\Http\Controllers\Auth\LoginController login
…\vendor\laravel\framework\src\Illuminate\Routing\Controller.php54
52
 call_user_func_array
…\vendor\laravel\framework\src\Illuminate\Routing\Controller.php54
51
Illuminate\Routing\Controller callAction
…\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php45
50
Illuminate\Routing\ControllerDispatcher dispatch
…\vendor\laravel\framework\src\Illuminate\Routing\Route.php212
49
Illuminate\Routing\Route runController
…\vendor\laravel\framework\src\Illuminate\Routing\Route.php169
48
Illuminate\Routing\Route run
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php658
47
Illuminate\Routing\Router Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php30
46
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\RedirectIfAuthenticated.php24
45
App\Http\Middleware\RedirectIfAuthenticated handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
44
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
43
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\Vestiging.php56
42
App\Http\Middleware\Vestiging handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
41
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
40
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php41
39
Illuminate\Routing\Middleware\SubstituteBindings handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
38
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
37
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php67
36
Illuminate\Foundation\Http\Middleware\VerifyCsrfToken handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
35
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
34
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php49
33
Illuminate\View\Middleware\ShareErrorsFromSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
32
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
31
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php63
30
Illuminate\Session\Middleware\StartSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
29
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
28
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php37
27
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
26
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
25
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php59
24
Illuminate\Cookie\Middleware\EncryptCookies handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
23
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
22
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php102
21
Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php660
20
Illuminate\Routing\Router runRouteWithinStack
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php635
19
Illuminate\Routing\Router runRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php601
18
Illuminate\Routing\Router dispatchToRoute
…\vendor\laravel\framework\src\Illuminate\Routing\Router.php590
17
Illuminate\Routing\Router dispatch
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php176
16
Illuminate\Foundation\Http\Kernel Illuminate\Foundation\Http\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php30
15
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php30
14
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
13
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
12
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php30
11
Illuminate\Foundation\Http\Middleware\TransformsRequest handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
10
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
9
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php27
8
Illuminate\Foundation\Http\Middleware\ValidatePostSize handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
7
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
6
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php46
5
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
4
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
3
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php102
2
Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php151
1
Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php116
0
Illuminate\Foundation\Http\Kernel handle
…\public\index.php53

**Comment by santigarcor** [comment]
can you please give also the lines of the controller where the code fails?

**Comment by ufeg02** [comment]
```
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }
 
    protected function authenticated( $user)
    {
 
        if($user->hasRole('tabletgebruiker')) {
            return redirect('/tablet');
        }
 
        return redirect('my-account');
    }
}``
```

**Comment by santigarcor** [comment]
Which laravel version are you using?

I think your problem is the signature of the authenticated method. It should be:

```php
protected function authenticated(Request $request, $user)
{
    //
}
```

**Comment by ufeg02** [comment]
I'm running version 5.5

If I change it the way you said I get the following error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Type error: Argument 1 passed to App\Http\Controllers\Auth\LoginController::authenticated() must be an instance of App\Http\Controllers\Auth\Request, instance of Illuminate\Http\Request given, called in C:\laragon\www\SF\vendor\laravel\framework\src\Illuminate\Foundation\Auth\AuthenticatesUsers.php on line 104

**Comment by ufeg02** [comment]
Fixed! What you said was right. I had to use protected function authenticated(Request $request, $user)
with $request. The error was because I did not 'use Illuminate\Http\Request;'

Thanks!
