### ISSUE TITLE
Suggestion: move config and views out of src

### ISSUE THREAD

**Issue by judgej** [santigarcor/laratrust#258]
The `src` directory is the root for autoloading the `\Laratrust` namespace.

Neither the config files nor the views have namespaces, so I would suggest they do not belong under `src`. They could be placed at the same level as `src`. I can see the logic that says, "these are source files of a sort, so belong in the source directory". But equally, composer is saying, "any source files in this namespace should be placed here for autoloading".

Anyway, it's not important or functional, just something that could neaten the code up a little.

**Comment by santigarcor** [comment]
I thought about that before, it is doable.
