### ISSUE TITLE
Laravel Spark 

### ISSUE THREAD

**Issue by scottybo** [santigarcor/laratrust#259]
does this play nicely with Laravel Spark User roles within teams?

**Comment by santigarcor** [comment]
I don't know how it works, i have never used Spark, so i don't have any reference to guide you through it.

**Comment by scottybo** [comment]
Would it be possible to leave this issue open in case someone else might have some insight?

**Comment by obaid** [comment]
@scottybo did you ever figure this out?

**Comment by scottybo** [comment]
I ended up using Laravel Bouncer - but you'll have to do a lot of leg work no matter which package you end up using

**Comment by obaid** [comment]
Thanks. I was looking at Laravel Bouncer as well and agree that there is a lot of UI and other things that I would need to do. Any tips or pitfalls that I should keep an eye on when integrating laravel bouncer?

**Comment by scottybo** [comment]
Bouncer is great - the tricky part is getting things working on the front-end with Vuejs. I ended up parsing an array of all the permissions for the user to the Spark js variable and then referencing those in Vue

**Comment by obaid** [comment]
Nice. Thanks for the details. :)
