### ISSUE TITLE
is any question for role_user table ? there have no user_type column

### ISSUE THREAD

**Issue by hhniao** [santigarcor/laratrust#261]
Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_type' in 'where clause' (SQL: select `user_id` from `role_user` where `role_id` = 3 and `user_type` = App\Model\Admins)

i got a exception when i delete a role from role list.
i think it is lost to update new migration file, is it?

**Comment by santigarcor** [comment]
What version of Laratrust do you have? it seems like you did an upgrade but you didn't run the upgrade migration

**Comment by hhniao** [comment]
thanks for you answer. 
i have solved it.
i checked the migration file and it no any problem, the column user_type is exist. 
`// Create table for associating permissions to users (Many To Many Polymorphic)
        Schema::create('permission_user', function (Blueprint $table) {
            $table->unsignedInteger('permission_id');
            $table->unsignedInteger('user_id');
            $table->string('user_type');

            $table->foreign('permission_id')->references('id')->on('permissions')
                ->onUpdate('cascade')->onDelete('cascade');

            $table->primary(['user_id', 'permission_id', 'user_type']);
        });`
migrate:refresh, and solved it.

**Comment by hhniao** [comment]
just strange what happen on last migration, user_type column lost.
