### ISSUE TITLE
i think it is a bit problem when check permission in middleware.

### ISSUE THREAD

**Issue by hhniao** [santigarcor/laratrust#262]
`Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@welcome');
    Route::get('/manage', ['middleware' => ['permission:manage-admins'], 'uses' => 'AdminController@manageAdmins']);
});`

if i change the name of permission on the administrate web site. so i need update the code file also?

for example, rename 'namage-admins' to 'manage-more-detail-admin', so i need to update route file??
i think it is not a good idea.

how do you think about follow code?
no permission name passed.
check permission by current route.
`Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@welcome');
    Route::get('/manage', ['middleware' => ['permission'], 'uses' => 'AdminController@manageAdmins']);
});`

`Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function() {
    Route::get('/', 'AdminController@welcome');
    Route::get('/manage', ['middleware' => ['permission:/manage'], 'uses' => 'AdminController@manageAdmins']);
});`

**Comment by santigarcor** [comment]
You should check to the permission level, also it's supposed that your roles and permission names never change, only the display names are the ones that should change.

**Comment by hhniao** [comment]
ok, thanks for your reply
