### ISSUE TITLE
Role $model save() returns false after attaching/detaching roles in Laravel 5.3

### ISSUE THREAD

**Issue by larsbo** [santigarcor/laratrust#27]
When I change the permissions of a role with `$role->attachPermission()` or `$role->detachPermission()`and save the role, the role is updated in db but the `save()` method returns `false`(a.k.a. no actually model db change happened).

I think the reason for this is that in Laravel 5.3 the behaviour value of the `save()` method changed:

> The Eloquent save method now returns false if the model has not been changed since the last time it was retrieved or saved.
https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0

**Comment by santigarcor** [comment]
@larsbo You're totally right. Now the save method from the Eloquent always returns null if no change was made to the model.

Check this [post](http://stackoverflow.com/questions/39281308/now-save-return-false-in-laravel-5-3) for a possible solution to check if a model was saved

**Comment by larsbo** [comment]
Thank you for the link - I already used that fix :-)

Nevertheless I think the expected result of updating a manipulated role should be `true`. Maybe It's possible to manually make the instance "dirty" when attaching/detaching permissions?
