### ISSUE TITLE
Basic GUI to manage users, roles & permissions

### ISSUE THREAD

**Issue by molerat619** [santigarcor/laratrust#271]
Hey there. Thanks for Laratrust, it's a great module. We love it!

We were wondering if there is a basic GUI out there to manage users, roles and permissions. Since it's only us admins who will use it, it does not have to be fancy or in the companies CI or anything. Has anyone built one yet?

Thanks!

**Comment by KKSzymanowski** [comment]
There's [Entrust-GUI](https://github.com/acoustep/entrust-gui) which was built for the package on which Laratrust is based. I highly doubt it will work out of the box, but you can probably copy some parts of views and logic.

**Comment by santigarcor** [comment]
Also check #252
