### ISSUE TITLE
JSON response for ajax requests on middleware protected routes

### ISSUE THREAD

**Issue by franciskisiara** [santigarcor/laratrust#272]
- Laravel Version: 5.6 
- Laratrust Version: 5.0 

### Description:
I have an API route that I have protected using middleware. My middleware is set to abort with a 403 response if access to the route is forbidden. However when I send a post request, I do not get a json response. 

A feature, if not present, that sends back a json response, on ajax requests, when authorization fails for easier management within promises would be much welcomed by many. 

### Steps To Reproduce:
1. Create api route
`Route::get('/api/users')`

2. Protect said route with middleware
`Route::get('/api/users', ['middleware' => ['permission:users-index']])`

3. Send request to endpoint (I used postman)
 This is an excerpt of the response I get:

<img width="1245" alt="screen shot 2018-04-22 at 10 49 23" src="https://user-images.githubusercontent.com/18147985/39092644-538622cc-461b-11e8-9e53-24fe0b005549.png">

I cant catch that response in my promises, it would be lovely if I could.

**Comment by franciskisiara** [comment]
Actually found out about [interceptors](https://github.com/axios/axios#interceptors) and turns out I can achieve the same with them.

**Comment by suleodu** [comment]
How can I go about that...

**Comment by KKSzymanowski** [comment]
You can start here: https://laravel.com/docs/5.6/middleware#defining-middleware
