### ISSUE TITLE
Unable to run migrations

### ISSUE THREAD

**Issue by mikt** [santigarcor/laratrust#274]
- Laravel Version: 5.6 
- Laratrust Version: 5.0 

### Description:
When running migrations I get
```
PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'core_permission_user_user_id_permission_id_user_type_team_id_unique' is too long")
```
I have upgraded to Maria DB 10.2.14, and even put the Schema::defaultStringLength(191); in my AppServiceProvider boot function.

### Steps To Reproduce:

Install a clean laravel 5.6
Follow the instructions guide to install Laratrust 5.0 including team support
Run migrations

**Comment by santigarcor** [comment]
If you want you can override that primery key by adding a second parameter in the method, check [this](https://stackoverflow.com/questions/28626906/laravel-migration-primary-or-key-identifier-name-is-too-long).

**Comment by mikt** [comment]
This is an issue with the length of the indexes, not primary key. Got any tips for that one?
