### ISSUE TITLE
Accessing team with $user->permissions

### ISSUE THREAD

**Issue by mikt** [santigarcor/laratrust#275]
- Laravel Version: 5.6
- Laratrust Version: 5.0 

### Description:
I'm working on a function that will remove a given permission, within a team, assigned to a specific user.
When trying to create a table as overview, i'm trying to access $permission->team, but this reference is not a valid one. Example:
```
<td>
                            <?php if (isset($p->team)) {
                                $team = "[".$p->team->display_name."]";
                            } else {
                                $team = "[<b>No team</b>]";
                            }
                            ?>
                            {!! $team !!}
                        </td>
```
Where $p is a permission assigned to the user.
$p->team is always null.
How should I access this field?

### Steps To Reproduce:
Create a user, create a permission, create a team.
Assign that permission, to that user, in that team.
Iterate over the person's permissions, and use the code snippet provided above.

**Comment by santigarcor** [comment]
If you check the tables structure a permission never has one team, it should be a many to many relationship. Also, that relationship doesn't exists in the trait so you would have to create it.
