### ISSUE TITLE
Attempting to get laratrust working with laravel-users

### ISSUE THREAD

**Issue by trevorclarke** [santigarcor/laratrust#276]
- Laravel Version: 5.6 
- Laratrust Version: 5.0.# 

### Description:
I'm trying to get this working on fresh laravel 5.6 install with https://github.com/jeremykenedy/laravel-users/

I posted the question there first and he suggested I ask here.

### Steps To Reproduce:

I'm trying to get this working on fresh laravel 5.6 install with laratrust and larausers

I've run:
php artisan make:auth

composer require "santigarcor/laratrust:5.0.*"

php artisan vendor:publish --tag="laratrust"

enabled teams in config = true

php artisan laratrust:setup

composer require jeremykenedy/laravel-users

php artisan vendor:publish --tag=laravelusers

Copied Directory [\vendor\jeremykenedy\laravel-users\src\resources\views] To [\resources\views\vendor\laravelusers]
Copied Directory [\vendor\jeremykenedy\laravel-users\src\resources\lang] To [\resources\lang\vendor\laravelusers]
Publishing complete.

This has resulted in files being created e.g. resources\views\vendor\laravelusers\usersmanagement

php artisan migrate

contents of routes/web.php

Route::get('/', function () {
return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

If you can point out where I've gone wrong that would be great.

No error messages

**Comment by santigarcor** [comment]
But is there any problem or error related with laratrust? Because i haven't used that package so i can not help you installing it.
