### ISSUE TITLE
Unable to run seeder

### ISSUE THREAD

**Issue by ferdikam** [santigarcor/laratrust#279]
- Laravel Version: 5.6.22
- Laratrust Version: 5.0.9

### Description:
I run 'php artisan db:seed' but i get an error into my console : 

_**Illuminate\Database\QueryException  : SQLSTATE[0A000]: Feature not supported: 7 ERROR:  cannot truncate a table referenced in a foreign key constraint**_

I use PostgreSQL database into the last version of laravel homestead

How fix this problem  ?

**Comment by santigarcor** [comment]
Weird it's like the `Schema::disableForeignKeyConstraints();` weren't working. But to fix it you have to disable the foreign key constraints before the tables are truncated and then enable it after it runs the seeder.

**Comment by santigarcor** [comment]
And it didn't work?

**Comment by ferdikam** [comment]
yes. it work. thanks
