### ISSUE TITLE
Laratrust can method returns false, when the user role has the permission.

### ISSUE THREAD

**Issue by Fox4Iit** [santigarcor/laratrust#281]
- Laravel Version: 5.6
- Laratrust Version:5

I tried config clear, cache clear, the can method sometimes returns true, and other times returns false.
The permissions are assigned to the roles, and the role are assigned to the user.
However, allPermissions();
does get all permissions on auth()->user()->allPermissions();
but auth()->can('perm_name');
sometimes returns true, and other times returns false, even after config, view, cache, cleared.

**Comment by santigarcor** [comment]
It should be `auth()->user()->can()` not `auth()->can()`.

**Comment by Fox4Iit** [comment]
@santigarcor There is a problem with cache, the changes in the permissions, doesn't take effect!!

**Comment by Fox4Iit** [comment]
Sorry, the problem is with my cache file, laravel logs that cache has been cleared but it's not, it's ownership  files problem on my server.
