### ISSUE TITLE
Dynamic Permissions On Models (Feature)

### ISSUE THREAD

**Issue by GeoSot** [santigarcor/laratrust#284]
Hello @santigarcor 

I am using your package about two years and i can tell, you have done a beautiful job.

As you know your code  better than anyone, I would like to advice me as for best practice usage.

I want to implement a dynamic authorization usage, on models, associating them to permissions.  
Example: on an article system , i would like to have article-categories, where some of them will be possible to be accessed only if the user have an associated (to category) permission.  

The only solution I have think, is to have a pivot table **_permissions_models_**  and to save on it 'permission_id' and 'morph' of model _(something like **permissions_users** table)_  , and a helper _trait_ to provide me methods  such as:
 - relation
-  modelHasAssignedPermissions 
- attaching
- syncing 
- getPermissionsOfModel (array) 

 so i will be able to use the method "**can**" like $user->can($model->getPermissionsOFModel()** )

Is the above proposition feasible? Or can you propose me a better approach?

Thanks in advance

**Comment by santigarcor** [comment]
Well I think the idea is good, If you want make a PR. The only thing is that the api for this helper trait should be the same as the user or the role, like:

- attachPermission
- attachPermissions
- detachPermission
- detachPermissions
- syncPermissions

Also, instead of calling getPermissionsOfModel, you could name it like getAccessPermissions or allPermissions (should return a collection) and for the modelHasAssignedPermissions you can leave it like hasAssignedPermissions.

**Comment by KKSzymanowski** [comment]
@GeoSot Can you please provide a basic use case? I have a hard time imagining how would I use it.

**Comment by GeoSot** [comment]
@KKSzymanowski 

In my case i wanted to give the functionality to 'lock' some articles or categories for some users. (Create restricted members area)

But the real need was to be able to do it dynamically for different models and different instances. As a result, an admin can attach a permission to a model , that has this trait.

The permission from the other side is related with userRoles. 

So after this linking, i use the method $user->can($model->getPermissionsOFModel() ) and i have a dynamic search.


This commit was a first approach to the concept and maybe lacks some features.
 
If anybody finds it interesting, I can try to help or to analyze more of my thoughts

**Comment by KKSzymanowski** [comment]
Ok, I get it now and I find it interesting.
I didn't realise you created a PR. I'll look at the implementation and let you know what I think.
