### ISSUE TITLE
how to return all users by all roles in array

### ISSUE THREAD

**Issue by YosefOberlander** [santigarcor/laratrust#290]
- Laravel Version: 5.4
- Laratrust Version: 5.0.9

### Description:
per the documentation, you can get users with `
$users = User::whereRoleIs('admin')->get();` but when i try to pass in an array to the `whereRoles` it will only return the user with the first role name in the array. How can I add roles to the `whereRoles`?

**Comment by santigarcor** [comment]
Actually you can't do that, that method accepts only a string, but for the new release the option for an array can be added.
