### ISSUE TITLE
Unable to Attach Roles or Permissions to Users across multiple Database instances

### ISSUE THREAD

**Issue by aannecchiarico** [santigarcor/laratrust#291]
- Laravel Version: 5.6.*
- Laratrust Version: 5.0.* 

### Description:
I have an instance of Laravel running on one port which is an OAuth server (passport) which stores all of my users. I have another instance of Laravel which is an API. The API has Laratrust installed as a dependency. The User model on the API project makes a connection to the **passport** database which actually stores all of the users. 

My User Model on the API Project looks like this
```
class User extends Model
{
    use LaratrustUserTrait;
    use Notifiable;
    use SoftDeletes;

    protected $connection = 'mysql2';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new ClientScope);
    }


}
```
*mysql2* is the OAuth Database in which my User table actually lives

So what I have is:
* Laravel Passport (OAuth Server) | *Laratrust **not** installed here*
     * It has its own DB
     * Stores all Users
* Laravel API | *Laratrust installed here*
    * Has its own DB
    * This DB has all of the tables for Laratrust
    * Does not have the Users table
    * User model has the LaratrustUserTrait

I have no issues creating Roles and Permissions, but I am unable to attach roles to a user. I receive the below error: 
```
Illuminate/Database/QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'passport.role_user' doesn't exist (SQL: insert into `role_user` (`role_id`, `user_id`, `user_type`) values (1, 1, App/Models/User))'
```

When calling ``` $user->attachRole($role); ``` it trys to look for the role_user table on the OAuth Database when it actually exist.

**Comment by KKSzymanowski** [comment]
Are the two databases on the same MySQL server?

**Comment by aannecchiarico** [comment]
@KKSzymanowski The two databases are on the same server.

**Comment by KKSzymanowski** [comment]
Then I think you can overwrite the table name to prepend the database name and everything should work just fine.

**Comment by aannecchiarico** [comment]
@KKSzymanowski Thanks that seemed to solve my issue.
