### ISSUE TITLE
Suggestion: for Lumen support

### ISSUE THREAD

**Issue by bdjunayed** [santigarcor/laratrust#293]
### Description:
When I tried to run php artisan laratrust:seeder it show an error. 
Class 'Config' not found

### Steps To Reproduce:

This can be fixed by using app('config')->get() instead of \Config::get()
In the laratrust/views/seeder.blade.php at line 111

Is it possible? 
(Thank you)

**Comment by santigarcor** [comment]
@bdjunayed do you know what else i have to do in order to support lumen?

**Comment by bdjunayed** [comment]
Thanks for your concern, may be I can figure this out. Primarily I can put the requirements what I have found last week in bellow.

1. This package is require:  irazasyed/larasupport:~1.0 for (vendor publish laratrust), also need to be register it.
2. Replace of pp('config')->get() instead of \Config::get() in all the files in the repo. and
3. Edit in config/laratrust.php ('register' => false,)

Hope it works, plz let us know.
