### ISSUE TITLE
How to get all permissions of user?

### ISSUE THREAD

**Issue by artem0071** [santigarcor/laratrust#294]
Why $user->permissions is not return permissions that user accept while attaching role.

F.e. Some role attach some permission. Then some user attach role.
But when I try to get users permissions it returns empty array. But when I try to get ability of user its return true.

Only way to get all permissions is $user->allPermissions(), but it is not return array (or what it should return..) and so this is not an attribute and is not visible on $user->relationLoaded('allPermissions')

Is it possible to create some method that allows to do something like this:
$user->load('allPermissions'); // At the moment it returns Error 
"Method Illuminate\Database\Eloquent\Collection::addEagerConstraints does not exist."

**Comment by artem0071** [comment]
But why it is not possible to use $user->load('allPermissions')?

**Comment by KKSzymanowski** [comment]
Because it is not a relationship. It's just a function returning all permissions either assigned directly or from roles.

**Comment by KKSzymanowski** [comment]
If you want to, for example, return all permissions to a JS client you can create an accessor and add this attribute to the `appends` list.
```php
class User
{
    // ...
    
    protected $appends = [
        'allPermissions',
    ];

    public function getAllPermissionsAttribute()
    {
        return $this->allPermissions();
    }

    // ...
}
```

It will not be very efficient though.

**Comment by artem0071** [comment]
Yes, I made it like this, but it is nog a good idea for users collection

**Comment by KKSzymanowski** [comment]
I don't think there's a way to fetch all permissions without a union in the SQL query and unions don't really work with Laravel relationships.

I think the best thing you can do is to load both the roles and permissions, send them to the JS client and process it there.
```php
public function someControllerMethod()
{
    return User::with('roles.permissions', 'permissions')->get();
}
```
```js
class User extends Model {
    allPermissions() {
        let allPermissions = {};

        for(let role of this.roles) {
            for(let permission of role.permissions) {
                allPermissions[permission.id] = permission;
            }
        }

        for(let permission of this.permissions) {
            allPermissions[permission.id] = permission;
        }

        return Object.values(allPermissions);
    }
}
```

**Comment by KKSzymanowski** [comment]
Does the method I mentioned work for you? Have you come up with something better?

**Comment by rendercoders** [comment]
Maybe you can do this
`
$allPermissions = $user->allPermissions();
$permissions = $allPermissions->filter(function ($item) use ($system_id) {
     return $item['system_id'] == $system_id;
});
`
