### ISSUE TITLE
Improve Events Documentation?

### ISSUE THREAD

**Issue by dmason30** [santigarcor/laratrust#297]
I have just migrated from Entrust and really appreciate how easy this is to use. However, going through the docs there are some bits missing here and there but the events section seems to be the main offender. 

http://laratrust.readthedocs.io/en/5.0/usage/events.html

At least it should have a section for each event method and explain the arguments. For example

    public function roleAttached(User $user, $role, $team)
    {
        //
    }

How from this example in the docs was I supposed to realise that the `$role` argument is actually the `$role->id`.  

Also you should add examples for **permissionAttached, permissionDetached, roleSynced, permissionSynced.**

Especially the `*Synced` methods and explain what `$changes` contains?

I hope this doesn't come across too critical, It was just a pain for me to force all of these events in my code so that I could see what the values of the arguments were.

**Comment by KKSzymanowski** [comment]
You're right, it isn't exactly clear how these events work from the docs.
I haven't personally used them in a while. If you have a fresh experience with them, can you please create a PR to improve the documentation?

**Comment by santigarcor** [comment]
@KKSzymanowski and @dmason30 comments are more than welcome to the section i added to the docs.
