### ISSUE TITLE
I can't assign some permission of a certain role to a user

### ISSUE THREAD

**Issue by omar-sh** [santigarcor/laratrust#300]
- Laravel Version: 5.6
- Laratrust Version: 5.0

### Description:
let's say I have a user named John inside a team named Editors, I also have a role with three permissions and I want to assign only two of those permissions to that user, can I do this using Laratrust? and if I can't is there any simple way to override the methods to do my own logic. Thanks in advance.

**Comment by omar-sh** [comment]
@KKSzymanowski Thanks for your answer, I know I can do that but I have a certain logic that I want to do, and I need to assign permissions from a specific role. I have clients who have multiple roles each role has multiple permissions, my clients will assign permissions (from a specific role) to their employees, roles or packages in my case will be paid. I hope I could explain what I need with my bad English, and thanks for helping ❤️

**Comment by KKSzymanowski** [comment]
I still don't understand why attaching permissions directly to users would not work for you.
