### ISSUE TITLE
detachRoles from user

### ISSUE THREAD

**Issue by frantischek** [santigarcor/laratrust#301]
- Laravel Version: 5.6.30 
- Laratrust Version: 5.0 

### Description:
Hi, I want to detach all roles from a user before I delete the user.
I try with 
```
            $deluser = User::where('id', $id)->get();
        $roles = $deluser->roles()->get();
        $deluser->detachRoles($roles);
        $deluser->delete();
``` 
and
```
        $roles = $deluser->roles;
```
Both times I get: Method Illuminate\Database\Eloquent\Collection::roles does not exist.

What is wrong? Thanks for support and this really great package!

**Comment by KKSzymanowski** [comment]
The `get` method as in
```php
User::where('id', $id)->get();
```
fetches a collection of users with id of `$id`.
You probably want to get the single user with this id so I'd use the `first` or `find` method:
```php
User::where('id', $id)->first();
```
or
```php
User::find($id);
```

**Comment by KKSzymanowski** [comment]
Also, to detach all roles you can use:
```php
User::find($id)->syncRoles([]);
```

**Comment by frantischek** [comment]
Thanks! Works!
(fastest answer ever! 👍 )
