### ISSUE TITLE
User's own posts!

### ISSUE THREAD

**Issue by ssenol** [santigarcor/laratrust#302]
- Laravel Version: 5.6.16
- Laratrust Version: 5.0.9

I have a role in the name is 'Authors.'
After an author login, I just want to see your own posts.

How can I do that? If you can explain by example, I am very happy.
Thanks..

**Comment by KKSzymanowski** [comment]
Oh for God sake, this is basic app development, in no way related to Laratrust, Laravel or even PHP.

There may be many approaches but personally I like to add a `user_id` or `author_id` column on the `posts` table and the simplified controller would look like this:
```php
public function index(Request $request)
{
    return Post::where('user_id', $request->user()->id)->get();
}

public function store(Request $request)
{
    return Post::create(
        array_merge(
            $request->all(), 
            ['user_id' => $request->user_id]
        )
    );
}

public function update(Post $post, Request $request)
{
    if($post->user_id != $request->user()->id) {
        return new Response('Not your post', Response::FORBIDDEN);
    }

    $post->update($request->all());
    return $post;
}
```
