### ISSUE TITLE
can I has dynamic team id, in role middleware

### ISSUE THREAD

**Issue by kyawkyawsoezhu** [santigarcor/laratrust#304]
my use case is user request api with team_id, so is there a way to validate it dynamically?

e.g. this request https://example.com/api/articles?team_id=1 has team_id so can role middleware can resolve it?

```php
Route::get('/articles', function (Request $request) {
    return Team::where('team_id', $request->team_id)->first()->articles()->paginate();
})->middleware("role:administrator,{$get_team_id_from_request}");
```

**Comment by santigarcor** [comment]
This was asked before here #222, but the only solution i can think of is that you create a custom middleware based on the Laratrust middlewares so you can add your custom logic there.

**Comment by kyawkyawsoezhu** [comment]
thanks @santigarcor
