### ISSUE TITLE
Get Roles attached to a Team

### ISSUE THREAD

**Issue by Julius-Plehn** [santigarcor/laratrust#305]
- Laravel Version: 5.6.27 
- Laratrust Version: latest 

How can I get all roles that are attached to a team?
Do I have to use a morph function? Otherwise I would need to query the role_user database table.

Maybe I simply overlooked something in the documentation. 
Thank you for this great package!

**Comment by santigarcor** [comment]
Actually there's no relationship defined on the Team model, you could define it like the user [relationship](https://github.com/santigarcor/laratrust/blob/master/src/Traits/LaratrustUserTrait.php#L60) with the roles.
