### ISSUE TITLE
Error while attaching middleware to route

### ISSUE THREAD

**Issue by rubinrp** [santigarcor/laratrust#307]
Laravel Version: 5.5.40 
 Laratrust Version: 5.0

I have installed laratrust package  for  implementation of  feature of roles and permission into my application
I did all necessary configuration and upon defining middleware into route I receive an error 

Also I referred  following steps from laratrust documentation

>  If you want to change or customize them, go to your config/laratrust.php and set the middleware.register value to false and add the following to the routeMiddleware array in app/Http/Kernel.php

 

 Then into routes/web.php I have defined following route 
`
 Route::get('market_ajax_grid', ['middleware' => ['permission:read-market'], 'uses' => 'MarketController@market_ajax_grid'])->name('market_ajax_grid');`
![permission](https://user-images.githubusercontent.com/16507943/45484584-3d748000-b772-11e8-8135-b871821fa21c.png)

![error](https://user-images.githubusercontent.com/16507943/45484610-567d3100-b772-11e8-9830-8ebc309295bd.png)
`
Also I have attached screenshot of definition of  permission mentioned specified into above route contained into database

Please refer error attachment for details of error being received upon executing above route

Kindly provide me solution to resolve the error

**Comment by santigarcor** [comment]
Can i see your Http/Kernel.php and your laratrust config file please?

**Comment by rubinrp** [comment]
Thanks for your reply.

**Comment by rubinrp** [comment]
Thanks for your reply.
I have tried executing command php artisan config:clear but still same issue persists and also can it be possible to manually configure data of roles and permissions into database since I just need to restrict access to specific module so that I can just define permissions for specific route using middleware.
