### ISSUE TITLE
$user->hasRoles('superadministrator') return false

### ISSUE THREAD

**Issue by shahiran12395** [santigarcor/laratrust#308]
Hi. My application keep give me false value when i try to check user roles in controller. Any advice why this thing keep return false and how to fix it

**Comment by santigarcor** [comment]
I can not help you without a more detailed description.

**Comment by shahiran12395** [comment]
I want to do if..else statement so that each role will get different result and view. I try dd() the syntax but it keeps return false value.

**Comment by santigarcor** [comment]
I meant I cannot help you if you don't give me information about the data you have, the code you wrote or the case you are having right now.

**Comment by shahiran12395** [comment]
![image](https://user-images.githubusercontent.com/17264574/46277910-4600ef00-c597-11e8-84ad-575de0420298.png)
 
image above is my code and i login as superadministrator. is there anything wrong with my code or structure?

**Comment by santigarcor** [comment]
It looks fine, if you followed the setup guide it i think your problem could be in the database. Maybe that specific user has not attached that role.

**Comment by shahiran12395** [comment]
![image](https://user-images.githubusercontent.com/17264574/46389400-20452880-c704-11e8-95dd-ad7460c5fd96.png)
this is my user model
![image](https://user-images.githubusercontent.com/17264574/46389454-774afd80-c704-11e8-923f-d15542be980c.png)
this is my role user table. My table is seed like in your documentation but i just add several other roles. How do i know if a user doesnt attach with any role?

**Comment by santigarcor** [comment]
In the table `role_user` you can check if the user that you are checking really has the role that you are looking for.

In the user table you can grab the user ids and in the roles table you can grab the roles ids and compare them inside that table.

**Comment by shahiran12395** [comment]
![image](https://user-images.githubusercontent.com/17264574/46454619-9cf60680-c7d9-11e8-95fd-e11e72848437.png)
i do it like this to capture the role..below is the result
![image](https://user-images.githubusercontent.com/17264574/46454636-b26b3080-c7d9-11e8-8d36-fc4d2340d02c.png)

thanks
