### ISSUE TITLE
traits\LaratrustUserTrait.php 

### ISSUE THREAD

**Issue by sharjeelz** [santigarcor/laratrust#309]
- Laravel Version: 5.6
- Laratrust Version: 5.0 

I added a new field in users model. while registering using Auth. it is saving to DB perfectly. But after saving it gives me error like this in LaratrustUserTrait.php file.

"Invalid argument supplied for foreach()"
ErrorException thrown with message "Invalid argument supplied for foreach()"

Stacktrace:
#61 ErrorException in C:\xampp\htdocs\helpit\vendor\santigarcor\laratrust\src\Traits\LaratrustUserTrait.php:457
#60 Raven_Breadcrumbs_ErrorHandler:handleError in C:\xampp\htdocs\helpit\vendor\santigarcor\laratrust\src\Traits\LaratrustUserTrait.php:457
#59 App\User:syncModels in C:\xampp\htdocs\helpit\vendor\santigarcor\laratrust\src\Traits\LaratrustUserTrait.php:549
#58 App\User:syncRoles in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Auth\RegistersUsers.php:56
#57 App\Http\Controllers\Auth\RegisterController:register in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#56 call_user_func_array in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#55 Illuminate\Routing\Controller:callAction in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#54 Illuminate\Routing\ControllerDispatcher:dispatch in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
#53 Illuminate\Routing\Route:runController in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
#52 Illuminate\Routing\Route:run in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Router.php:665
#51 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#50 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\santigarcor\laratrust\src\Middleware\LaratrustPermission.php:33
#49 Laratrust\Middleware\LaratrustPermission:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#48 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\santigarcor\laratrust\src\Middleware\LaratrustRole.php:36
#46 Laratrust\Middleware\LaratrustRole:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#45 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#44 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#43 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#41 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:67
#40 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#38 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#37 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#35 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#34 Illuminate\Session\Middleware\StartSession:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#29 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:59
#28 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#26 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
#25 Illuminate\Pipeline\Pipeline:then in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Router.php:667
#24 Illuminate\Routing\Router:runRouteWithinStack in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Router.php:642
#23 Illuminate\Routing\Router:runRoute in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Router.php:608
#22 Illuminate\Routing\Router:dispatchToRoute in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Router.php:597
#21 Illuminate\Routing\Router:dispatch in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#20 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\fideloper\proxy\src\TrustProxies.php:57
#18 Fideloper\Proxy\TrustProxies:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
#15 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#13 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
#12 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#10 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#9 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#7 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:62
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#4 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
#3 Illuminate\Pipeline\Pipeline:then in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#2 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\xampp\htdocs\helpit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#1 Illuminate\Foundation\Http\Kernel:handle in C:\xampp\htdocs\helpit\public\index.php:55
#0 require_once in C:\xampp\htdocs\helpit\server.php:21

**Comment by santigarcor** [comment]
It looks like you are passing a wrong argument to the syncRoles method. Check that you are passing the right data.

**Comment by sharjeelz** [comment]
Appreciate it. I was passing wrong data.

**Comment by jaydeepindianic** [comment]
hhh
