### ISSUE TITLE
Role relationship perms changed to permissions?

### ISSUE THREAD

**Issue by fulbert81** [santigarcor/laratrust#31]
I was using Entrust previously but I was getting issues after updating to Laravel 5.2 and changing vendor files to fix the issue doesn't sit well with me. 

Anyway back to point, I am getting an error "Call to undefined method Illuminate\Database\Query\Builder::perms()'" when calling $role->perms(). Has the relationship model name been changed to permissions? In the documents for Soft-Deleting, the example code still makes a reference to $role->perms()->sync([]) though. Please advice.

**Comment by santigarcor** [comment]
Yeah, the role permission relationship was renamed to `permissions`

Thank you for pointing that, I have to change that in the docs
