### ISSUE TITLE
after register login error

### ISSUE THREAD

**Issue by shahiran12395** [santigarcor/laratrust#310]
![image](https://user-images.githubusercontent.com/17264574/46454812-bc416380-c7da-11e8-9925-c772d61da2bb.png)

hi. im trying to set default user roles to new register user. but im getting Type error: Argument 1 passed to Illuminate\Auth\SessionGuard::login() must implement interface Illuminate\Contracts\Auth\Authenticatable, null given.  below is my register controller
![image](https://user-images.githubusercontent.com/17264574/46454862-fc084b00-c7da-11e8-9ad6-5590848f2de3.png)

is there anything wrong with my controller?

**Comment by santigarcor** [comment]
Yes, you are not returning your user from that controller. It's not Laratrust related.

You should add `return $user;` after the attachRole
