### ISSUE TITLE
Change column 'user_type' name

### ISSUE THREAD

**Issue by ChacMaster** [santigarcor/laratrust#311]
- Laravel Version: 5.7.8
- Laratrust Version: 5.0.9

### Description:

There is some way to change de 'user_type' column name?
When i change only in the migration file, this results on error when seeding the database.

> "   Illuminate\Database\QueryException  : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_type' in 'field list' (SQL: insert into `seg_usuario_grupo` (`seg_grupo_id`, `seg_usuario_id`, `user_type`) values (1, 1, App\Model\SegUsuario))"

### Steps To Reproduce:

Change the name on the migration 

`
// Create table for associating permissions to users (Many To Many Polymorphic)
Schema::create('seg_usuario_permissao', function (Blueprint $table) {
  $table->unsignedInteger('seg_usuario_id');
  $table->unsignedInteger('seg_permissao_id');
  $table->string('**NewName**');

  $table->foreign('seg_usuario_id')->references('id')->on('seg_usuario')->onUpdate('cascade')->onDelete('cascade');
  $table->foreign('seg_permissao_id')->references('id')->on('seg_permissao')->onUpdate('cascade')->onDelete('cascade');
  $table->primary(['seg_usuario_id', 'seg_permissao_id', '**NewName**'])->name('idx-primaria');
});
`

**Comment by santigarcor** [comment]
It comes from the polymorphic relationships, you can't change the name of that column as far a i know.
