### ISSUE TITLE
[Improve] User::whereRoleIs With Team param

### ISSUE THREAD

**Issue by AyozeVera** [santigarcor/laratrust#312]
- Laravel Version: 5.6.*
- Laratrust Version: 5.0.*

### Description:
Hello, first of all nice Laravel package, and sorry for my english level. I am using your package in a project because I need to assign team based roles, so I need to list all the Users with any role or at least a certain role. In de documentation is the "whereRoleIs" method on the UsersTrait, the problem is that this trait returns all the Users in DB with that roles, it doesn't care it's team. 
Maybe could be possible to add an optional param to the "scopeWhereRoleIs" method on the User trait, that takes a Team instance, id or name (whatever you prefer) and adds a where clause to the query, so it get filtered by Team.
Something like this for example:
`public function scopeWhereRoleIs($query, $role = '', $team = null)
    {
        return $query->whereHas('roles', function ($roleQuery) use ($role, $team) {
            $roleQuery->where('name', $role);
            if (!is_null($team)) $roleQuery->where('team_id', $team->id);
        });
    }`
Thanks for your time!

**Comment by santigarcor** [comment]
Yeah! I think it would be nice, if you want, you can make a PR to the master branch I'll release a new version soon.
