### ISSUE TITLE
How to extend permission check for custom business logic

### ISSUE THREAD

**Issue by molerat619** [santigarcor/laratrust#313]
Hey there,

First of, thanks for the great job you have done with this package!

I have a question: We need to extend the logic of laratrust a bit by some business requirements. For example, we need to extend the the permission_user table to something like that:

![image](https://user-images.githubusercontent.com/3458576/47005701-9306c880-d134-11e8-9dcb-765768993df1.png)

The reason is that users can work for different stations (airports) and they have different permission-levels depending on the airport. So the user could for example view all employees of the stations A, B and C (permission called "view-employees"), but he is only allowed to edit the employees of station A.

...simplified the result would look like that (with IDs instead of actual values of course):

![image](https://user-images.githubusercontent.com/3458576/47005840-eb3dca80-d134-11e8-9275-966c5700d836.png)

Now we would like to adjust the way the permission check is done so it includes the check for the stations. What is the best way to do that? Do we have to write our own trait? 

Since we have never done adjustments like that to packages from GitHub, any directions would be highly appreciated. Thank you.

**Comment by santigarcor** [comment]
You could do it by creating a new trait that uses LaratrustUserTrait and inside of that trait you can simply change the names of the laratrusts methods like this:

```php
use LaratrustUserTrait{
    LaratrustUserTrait::hasPermission as laratrustHasPermission;
}
```

So inside your new trait's hasPermission method you can call the `laratrustHasPermission` if you are going to use that part of the logic.
