### ISSUE TITLE
Using Laratrust on different model than User

### ISSUE THREAD

**Issue by tsangaris** [santigarcor/laratrust#315]
- Laravel Version: 5.7.11
- Laratrust Version: 5.0.*

### Description:
I am trying to use Laratrust with my Admin model (instead of User model). To do this i go into config--> laratrust.php and i change the following:

    /*
    |--------------------------------------------------------------------------
    | Laratrust User Models
    |--------------------------------------------------------------------------
    |
    | This is the array that contains the information of the user models.
    | This information is used in the add-trait command, and for the roles and
    | permissions relationships with the possible user models.
    |
    | The key in the array is the name of the relationship inside the roles and permissions.
    |
    */
    'user_models' => [
        'admins' => 'App\Admin',
    ],

    /*
    |--------------------------------------------------------------------------
    | Laratrust Models
    |--------------------------------------------------------------------------
    |
    | These are the models used by Laratrust to define the roles, permissions and teams.
    | If you want the Laratrust models to be in a different namespace or
    | to have a different name, you can do it here.
    |
    */
    'models' => [
        /**
         * Role model
         */
        'role' => 'App\Role',

        /**
         * Permission model
         */
        'permission' => 'App\Permission',

        /**
         * Team model
         */
        'team' => 'App\Team',

    ],

    /*
    |--------------------------------------------------------------------------
    | Laratrust Tables
    |--------------------------------------------------------------------------
    |
    | These are the tables used by Laratrust to store all the authorization data.
    |
    */
    'tables' => [
        /**
         * Roles table.
         */
        'roles' => 'roles',

        /**
         * Permissions table.
         */
        'permissions' => 'permissions',

        /**
         * Teams table.
         */
        'teams' => 'teams',

        /**
         * Role - User intermediate table.
         */
        'admin_role' => 'admin_role',

        /**
         * Permission - User intermediate table.
         */
        'admin_permission' => 'admin_permission',

        /**
         * Permission - Role intermediate table.
         */
        'permission_role' => 'permission_role',

    ],

    /*
    |--------------------------------------------------------------------------
    | Laratrust Foreign Keys
    |--------------------------------------------------------------------------
    |
    | These are the foreign keys used by laratrust in the intermediate tables.
    |
    */
    'foreign_keys' => [
        /**
         * User foreign key on Laratrust's role_user and permission_user tables.
         */
        'admin' => 'admin_id',

        /**
         * Role foreign key on Laratrust's role_user and permission_role tables.
         */
        'role' => 'role_id',

        /**
         * Role foreign key on Laratrust's permission_user and permission_role tables.
         */
        'permission' => 'permission_id',

        /**
         * Role foreign key on Laratrust's role_user and permission_user tables.
         */
        'team' => 'team_id',

    ],

Then I run the command:

    php artisan laratrust:migration

This is the error i get:

    Laratrust Migration Creation.

    A migration that creates admin_permission, admin_role, permission_role, permissions, roles tables will be created in database/migrations directory

     Proceed with the migration creation? (yes/no) [yes]:
    > yes

     Creating migration

        ErrorException  : Undefined index: role_admin (View: /Applications/MAMP/htdocs/projects/sap/vendor/santigarcor/laratrust/src/views/migration.blade.php)

        at /Applications/MAMP/htdocs/projects/sap/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:45
        41|         // an exception is thrown. This prevents any partial views from leaking.
        42|         try {
        43|             include $__path;
        44|         } catch (Exception $e) {
      > 45|             $this->handleViewException($e, $obLevel);
        46|         } catch (Throwable $e) {
        47|             $this->handleViewException(new FatalThrowableError($e), $obLevel);
        48|         }
        49| 

     Exception trace:

     1   ErrorException::("Undefined index: role_admin")
  
`/Applications/MAMP/htdocs/projects/sap/storage/framework/views/45e7605f9507f243571422af9e9c3cdf36e964af.php:45`

      2   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: role_admin", "/Applications/MAMP/htdocs/projects/sap/storage/framework/views/45e7605f9507f243571422af9e9c3cdf36e964af.php")
      
 `/Applications/MAMP/htdocs/projects/sap/storage/framework/views/45e7605f9507f243571422af9e9c3cdf36e964af.php:45`

     Please use the argument -v to see more details.

The thing is the migration command understands which tables/migrations to create but when it goes to execute it shows the error above.

Shouldn't the content inside **laratrust.php** override the migration in /Applications/MAMP/htdocs/projects/sap/vendor/santigarcor/laratrust/src/views/migration.blade.php 

What is wrong? How can i achieve what i want?

Thanks in advance!

**Comment by santigarcor** [comment]
You should not change the keys of the `models`, `tables` and `foreign keys`, because the command that generated the file uses specific keys to seed the data into the migration. That's the source of your problem. Also, you should not edit the `migration.blade.php` file either.

**Comment by tsangaris** [comment]
> You should not change the keys of the `models`, `tables` and `foreign keys`, because the command that generated the file uses specific keys to seed the data into the migration. That's the source of your problem. Also, you should not edit the `migration.blade.php` file either.

OK, so the table names on the migrations will stay as is (role_user, permission_user, etc) and will not be changed into admin_role, admin_permission? It will just add the "use LaratrustUserTrait;" on the Admin model?

**Comment by santigarcor** [comment]
No, I meant you should not edit the keys in those files. You can change the value but not the key.

**Comment by UnderDogg** [comment]
@santigarcor thanks for your work on this package. I'm in the same situation as opening poster. For me it was 'employees' instead of 'admins'. Somehow it keeps looking for user_id. Maybe because i set 'use morph_map' to 'true'.
I'll keep trying, but can we come up with a test or an extende version of the gui project with 'employees' or 'admins' instead of users?

**Comment by MohamedHamdy11** [comment]
https://dev.to/uzairjan/using-laratrust-permission-and-roles-other-than-users-relation-4e98

**Comment by MohamedHamdy11** [comment]
@santigarcor  
https://dev.to/uzairjan/using-laratrust-permission-and-roles-other-than-users-relation-4e98

**Comment by Satishmrj15** [comment]
How to make relationship with permission-role migration to Permission Model ??
