### ISSUE TITLE
Call to a member function hasPermission() on null

### ISSUE THREAD

**Issue by JuanVillagran** [santigarcor/laratrust#316]
Hello, I have a problem with the package, everything was fine but I started to get that error, I don't know why It happened, can you help me please?

**Comment by JuanVillagran** [comment]
@if(Auth::user()->hasPermission('read-users'))
                <li class="{{ active_class(Active::checkUriPattern('user*')) }}">
                    <a href="{{ route('user.index') }}">
                        <i class="fa fa-circle"></i> <span>Gestión de Usuarios</span>
                    </a>
                </li>
            @endif

**Comment by JuanVillagran** [comment]
@if(Auth::user()->hasPermission('read-users'))
       ...
@endif

**Comment by KKSzymanowski** [comment]
Yeah, clearly your user is not authenticated. That's why `Auth::user()` returns null.

**Comment by KKSzymanowski** [comment]
BTW, you can use [blade directives](https://laratrust.readthedocs.io/en/4.0/usage/blade_templates.html?highlight=directive) to check the permission of a currently authenticated user:
```
@permission('manage-admins')
    Foo
@endpermission
```

**Comment by JuanVillagran** [comment]
Thx mate.
