### ISSUE TITLE
How long is the cache time? Where is the cache time set?

### ISSUE THREAD

**Issue by meicuihui** [santigarcor/laratrust#318]
- Laravel Version: 5.5
- Laratrust Version: 5.0
### Description:
Hi @santigarcor 

How long is the cache time for permission or roles? Where is the cache time set?

Can you give me a hint how to fix that?

Thanks

**Comment by santigarcor** [comment]
@meicuihui as you can se [here](https://github.com/santigarcor/laratrust/blob/5.0/src/Traits/LaratrustUserTrait.php#L68) it's set to 60 minutes and you can change it in the `cache.ttl` value (If it doesn't exist just create it inside the  `config/cache.php` file)

**Comment by KKSzymanowski** [comment]
On that note. To me the `cache.ttl` config value is ambiguous and you don't see immediately that it relates to Laratrust. I would suggest moving it to Laratrust own config and giving it the default value in the config to avoid confusion. That would probably need to go in the next major version though.

**Comment by santigarcor** [comment]
Yes you're right.
