### ISSUE TITLE
Listing User Teams with Roles and/or permissions

### ISSUE THREAD

**Issue by kaw393939** [santigarcor/laratrust#319]
Hello,

Thanks for this module, I was making something similar and then I found yours.   I love Medellin and come down there sometimes to see my friend Santiago (another developer if you know him).  Anyway, I just can't figure out a good way to do this.  

I want to list a users teams with their team roles and not have to make two queries or make a model out of user_roles.  

So I want to be able to do:

$teams = $user->teams 

and then get a collection that looks like:
Team Name: Some Team
Role: Owner

I've thought about making a model out of user_roles or I've been able to list a users teams, but it doesn't show their roles, it just has the roleID and I need the name of the role.

This is the crappy way I'm doing it now:
      $user = User::with('groups','roles')->find(1);

        $groups = $user->rolesTeams;
        $groups->each(function($group) {
            $roleID = $group->pivot->role_id;
            $role = Role::find($roleID);
            dd($role->name);
        });

Any ideas would be appreciated,

Thanks

**Comment by kaw393939** [comment]
I figured it out...

I made a custom pivot model.

namespace Kaw393939\Group\Pivot;
use Illuminate\Database\Eloquent\Relations\Pivot;
use Kaw393939\Group\Models\Role;

class RolePivot extends Pivot
{
    public function role() {
        return $this->hasOne(Role::Class,'id','role_id');
    }
}

Then I add it user model method for groups:

    public function groups()
    {
        return $this->belongsToMany(Group::class,'role_user')
            ->as('groupRole')
            ->using(\Kaw393939\Group\Pivot\RolePivot::class)
            ->withPivot('role_id');
    }
Now I can do this and access it, I need to clean up the names of my methods.  I need to figure out about eager loading this if possible.

        $user = User::find(1);
        $groups = $user->groups();
        $groups->each(function($group) {
            dd($group->groupRole->role->name);
        });

**Comment by gokulkhatiwada** [comment]
`$user->rolesTeams`

This is working for me

**Comment by raisonon** [comment]
Is this still best approach? Thanks
