### ISSUE TITLE
Permit User if he is the Owner of a Record

### ISSUE THREAD

**Issue by GeoSot** [santigarcor/laratrust#32]
Hello,
 i have searched the code, but i can't find a proper way, through it's methods,
 in order to permit a user edit a record if he owns it.

Is there any?

Thank in advance

**Comment by santigarcor** [comment]
Currently you have to make another check, but it would be nice to add that kind of method like `user->owns($post)`. I'll have that in mind.

**Comment by GeoSot** [comment]
Also you can think about implementing  a quick way of checking inside controllers.

For example...

Now we use:
` if (!Auth::user()->can('foo-permission')) {
            return redirect()->route('home');
        } 
`

And it could be
` 
Auth()::user()->ability(owner:$record->id,  foo-permission ,  pathToRedirectIfError  )`


Anyway, just thoughts.

You have done great work! :D
Thanks for the quick response

**Comment by santigarcor** [comment]
But you can use the middleware to do the redirection. Check out the docs.

**Comment by GeoSot** [comment]
But avoiding to user resource controllers in routes file , or am i wrong?

**Comment by santigarcor** [comment]
@GeoSot Sorry i thought i put how to use the redirection in the docs. I'll add it now

**Comment by santigarcor** [comment]
@GeoSot check [this](http://laratrust.readthedocs.io/en/3.0/usage/middleware.html#middleware-return)

**Comment by santigarcor** [comment]
Solved by #34
