### ISSUE TITLE
I'm not getting all permissions attached to a Role

### ISSUE THREAD

**Issue by ramonMontanhes** [santigarcor/laratrust#320]
- Laravel Version: 5.5.44
- Laratrust Version: ^5.0

Description: My users can have more than one Role, but only can use one at time. The Roles can have N permissions. I have a Role that have a little more than 60 permissions on the database. If I switch my user to this Role and try to print the permissions attached to this Role I only get 8 permissions.

I have created a current_role_id column on my users table to make it easy to switch over the Roles.

I'm using the `$user->allPermissions()` to get all the permissions. so, it's come with permissions from others roles of the user. So I use a foreach to filter the permissions from the current_role_id, after that I get only the 8 permissions not all the 60+.

```php
        $allPermissions = $user->allPermissions();
        $permsId = array();
        foreach ($allPermissions as $permission) {
            if($permission->pivot->role_id === $user->current_role_id) {
                $permsId[] = $permission->id;
            }
        }
```
How can I get all the permissions attached to a role?

**Comment by KKSzymanowski** [comment]
I think you overcomplicated this.

First of all, what is the `$user->current_role_id` field? It's not part of Laratrust. How do you set it, are you sure it's set properly?

Second, if I had to get all user's permissions derived from one of his roles I would do something like this:
```php
$permissions = $user->roles()->find($user->current_role_id)->permissions;
```
and depending on how you set the `$user->current_role_id` field you might need to make sure `$user->roles()->find($user->current_role_id)` does not return `null`.

**Comment by ramonMontanhes** [comment]
> First of all, what is the $user->current_role_id field? It's not part of Laratrust. How do you set it, are you sure it's set properly?

I created it because users need to switch between roles. They can not have more than one role at the same time.

I'm woke up some minutes ago and found the API link where I found the solution. Sorry I didn't know about the API link before, I was using only the docs.

**Comment by KKSzymanowski** [comment]
Is this solved then?

**Comment by ramonMontanhes** [comment]
Yes, it is.
