### ISSUE TITLE
@permission is always returning false 

### ISSUE THREAD

**Issue by saifabushamma** [santigarcor/laratrust#322]
- Laravel Version: 5.7
- Laratrust Version: 5.0

### Description:
My app is always returning @permission false for some reason

**Comment by santigarcor** [comment]
@saifabushamma Can you give more details?

**Comment by mendela1992** [comment]
Hey There,

I am also having the same issue.
` @permission('edit-profile')
           <div class="row">
                                        <div class="col-12">
                                            <button type="submit" class="btn btn-primary float-right">Update Profile
                                            </button>
                                        </div>
                                    </div>
                                    @endpermission`

**Comment by mendela1992** [comment]
Hi There ,

I am having the same issue. 
For more context to my issue, I am trying to give permissions to the any members that has any role with the appropriate permissions. 

`@permission('edit-profile')`
`<div class="row">`
`    <div class="col-12">`
`        <button type="submit" class="btn btn-primary float-right">Update Profile</button>`
`    </div>`
`</div>`
`@endpermission`

I have check that that user that is logging has the appropiate role and that the permissions request is been qssigned to him but the button does appear.

Also `dd(Auth::user()->hasRole('read-profile'))` return false.

What could the issue?

**Comment by santigarcor** [comment]
@mendela1992 I couldn't replicate the issue. Maybe you're typing something wrong. `dd(Auth::user()->hasRole('read-profile'))` you are asking for a role, but it seems that it should be a permission instead.

**Comment by saifabushamma** [comment]
@santigarcor I fresh installed your package like 3 times and i gave the user a role and that role has permissions when i try to check for permission its always false..but when i check for the user it returns true but i have to define the relation in the model i tried doing the same for the permission @Permission isn't working or any function that checks for the permission. 
thanks for your time :)

**Comment by mendela1992** [comment]
> dd(Auth::user()->hasRole('read-profile'))

Thanks for pointing that out @santigarcor  I meant to say 'hasPermissions'. But I am facing exactly the same situation as @saifabushamma . The user has the role and and permissions required but when it is checked using @permissions, it returns false.

**Comment by santigarcor** [comment]
@saifabushamma maybe you are having the same problem as @mendela1992. Or have you tried deleting the app cache?

**Comment by sahamnadeem** [comment]
when i write `dd(auth()->user()-role);` it gives me null every time. plus
 `Route::group(['middleware' => 'role:admin'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
});` 
is also not letting me into the home page even i have role admin saved to my user in database

**Comment by sahamnadeem** [comment]
`1565208315a:1:{i:0;a:7:{s:2:"id";i:2;s:4:"name";s:6:"client";s:12:"display_name";s:6:"client";s:11:"description";s:6:"client";s:10:"created_at";s:19:"2019-08-07 00:00:00";s:10:"updated_at";N;s:5:"pivot";a:2:{s:7:"user_id";i:1;s:7:"role_id";i:2;}}}`

this is my cache data when i remove this laratrust works fine and when i don't remove this laratrust does not work fine

**Comment by xenDE** [comment]
> when i write `dd(auth()->user()-role);` it gives me null every time. plus
then read the docu and learn "how to create a new issue instead of asking in other issues"

one tip: roles()

**Comment by sahamnadeem** [comment]
> > when i write `dd(auth()->user()-role);` it gives me null every time. plus
> 
> then read the docu and learn "how to create a new issue instead of asking in other issues"
> 
> one tip: roles()

no need to my issue is the same as this issue it.. we just need to mark `caching => true` to `false` and it will be very fuck fine in config file of laratrust `laratrust.php`

**Comment by xenDE** [comment]
this looks like multiple typos: dd(auth()->user()-role);

fixed: dd(Auth::user()->roles());

**Comment by Eyad-Mohammed-Osama** [comment]
I would like to add on @sahamnadeem comment's

As of **laratrust 6.3**, you can add the entry `LARATRUST_ENABLE_CACHE` to your `.env` file and assign it the value `false`

This effectively has the same result of modifying `laratrust.php` config file directly

**Important note:** don't forget to run `php artisan optimize:clear` after doing this
