### ISSUE TITLE
using the package via vue js

### ISSUE THREAD

**Issue by BechirAhmed** [santigarcor/laratrust#324]
- Laravel Version: 5.7.* 
- Laratrust Version: 5.0.* 

### Description:
Is it possible to get user roles and permissions from vue js or js generally?

**Comment by santigarcor** [comment]
Currently there isn't an implementation for JS, but it would be a nice addition to the package.

**Comment by nikocraft** [comment]
It is possible, make an endpoint to return current user's routes and permissions. Just create it your self and read it when application loads

**Comment by lexxyungcarter** [comment]
> It is possible, make an endpoint to return current user's routes and permissions. Just create it your self and read it when application loads

You could also save it to `localStorage` and create a mixin method to the main **Vue** instance, something like `can(permission)` which will check for the existence of a key that matches the name of the permission passed. 
*Remember to delete the permissions after a logout action*
