### ISSUE TITLE
Laravel 5.8 compatibility

### ISSUE THREAD

**Issue by Rux77** [santigarcor/laratrust#328]
Please add support for Laravel 5.8

**Comment by sumityadav** [comment]
Pull request #329 created.

**Comment by santigarcor** [comment]
I'll try to update the docs for the 5.2 version because we are dropping support for some older laravel versions and also some php versions. Meanwhile, you can use the master branch that already has all the fixes required for 5.8.

**Comment by santigarcor** [comment]
The 5.2 release fixes the support for 5.8
