### ISSUE TITLE
Docs Translation

### ISSUE THREAD

**Issue by luhansalimena** [santigarcor/laratrust#331]
I want to contribute to the project translating the docs files to Portuguese. So I created a new folder in the 'doc/5.1' named pt-br and I'm inserting the .md translated files into it. Will it work or you suggest another way?

**Comment by santigarcor** [comment]
@Luhancouto I'm not sure how it should be handled in the docs, if you want you can advance on the translations but better for version 5.2 and then i can search how to handle the translations using this versions system i did.

**Comment by AnasOmarObaid** [comment]
I want to contribute to the project.
When I Use whereRoleIs Function, This Function Not Accept more Than Role So I should use orWhereRoleIs function.
So I Go trait LaratrustHasScopes And Just write one code ,
and the function whereRoleIs becomes accept more than role and also accept one role
![scope](https://user-images.githubusercontent.com/43482636/77274660-1aa81d80-6cbf-11ea-9930-bb4d5e7c4cb3.PNG)
just small code ,
and this was so usefull for me.
and also will usefull for programers
