### ISSUE TITLE
Teambased user-model with roles and permissions

### ISSUE THREAD

**Issue by simonankele** [santigarcor/laratrust#332]
Hello,

I want to use the team functionality and additionally integrate the relationships in the model.

For the relationship between user and team I created the following relationships:

User.php

>     public function markets()
>     {
>         return $this->morphToMany(
>             Config::get('laratrust.models.team'),
>             'user',
>             Config::get('laratrust.tables.role_user'),
>             Config::get('laratrust.foreign_keys.user'),
>             Config::get('laratrust.foreign_keys.team')
>         );
>     }

Team.php

>     public function users()
>     {
>         return $this->morphByMany(
>             Config::get('laratrust.models.user'),
>             'user',
>             Config::get('laratrust.tables.role_user'),
>             Config::get('laratrust.foreign_keys.team'),
>             Config::get('laratrust.foreign_keys.user'));
>     }

This also works great.
However, if I want to display the corresponding roles within the teams, I always get all the roles assigned to the team and not the roles. The reference to the user is missing here.

I have created the following relationships between team and role:

Team.php

>     public function roles()
>     {
>         return $this->belongsToMany(Role::class, 'role_user', 'team_id', 'role_id');
>     }

Role.php

>     public function teams()
>     {
>         return $this->belongsToMany(Team::class, 'role_user', 'role_id', 'team_id');
>     }

BelongsToMany is right here, isn't it?

Does anyone have a solution?

Have a nice weekend

Simon

**Comment by santigarcor** [comment]
First of all that relationship is not a BelongsToMany, it's a polymorphic many to many. Also, laravel doesn't fully support ternaries relationships and that's what you need. Then you have to make some kind of 'trick' in order to get what you want.

**Comment by simonankele** [comment]
Hi, I've found a solution.

I also have implemented a solution that allows you to remove a permission from a user, even though his role contains this permission.

But I can post the solution only in a few the days?

**Comment by santigarcor** [comment]
But the package already provides the functionality for adding roles/permissions to a user within a given team. Could you please explain me, maybe I got you wrong.

**Comment by jihadismail8** [comment]
@simonankele  we are still waiting for you to post the solution here ))
