### ISSUE TITLE
$role->hasPermission($permission->name) not working in 5.2, but working in 5.0.

### ISSUE THREAD

**Issue by cvaize** [santigarcor/laratrust#333]
$role->hasPermission($permission->name) in 5.2 version always returns false, but it works properly on version 5.0.
![image](https://user-images.githubusercontent.com/26907947/54522959-3bdd7c00-4990-11e9-92ba-84e16fafe4fe.png)

**Comment by cvaize** [comment]
"laravel/framework": "5.8.*",

**Comment by cvaize** [comment]
And also there was an error. I understand that it is because of version "laravel/framework": "5.8.*".
Downgraded version to "laravel/framework": "5.7.*" and the error is gone. But mistake with $role->hasPermission($permission->name) on version "santigarcor/laratrust": "^5.2" not disappear.
![image](https://user-images.githubusercontent.com/26907947/54524007-a099d600-4992-11e9-91df-acdae5d767d9.png)

**Comment by santigarcor** [comment]
The `call to undefined method fire` problem is related with your upgrade, i think you did not follow the upgrade instructions, because the error log shows a version of the LaratrustHasEvents file that doesn't match with the 5.2 version. Maybe the permission's problem is also related to it.

**Comment by cvaize** [comment]
Reinstalling dependencies the problem with `fire` has been fixed. But the problem with `$role->hasPermission($permission->name)` is also relevant.
![image](https://user-images.githubusercontent.com/26907947/54664010-d959bc80-4b04-11e9-8ea0-4f17d0f03508.png)

**Comment by cvaize** [comment]
I wrote a loop that shows the role of the user and the permissions of this role, and also checks whether the user has this role and whether this role has the selected permission. And the last value should be true, but it does not happen.
![image](https://user-images.githubusercontent.com/26907947/54664521-46ba1d00-4b06-11e9-85be-76971ddd7c41.png)
![image](https://user-images.githubusercontent.com/26907947/54664536-50438500-4b06-11e9-9407-de3eec4dc832.png)

**Comment by cvaize** [comment]
Updated the example.
![image](https://user-images.githubusercontent.com/26907947/54665352-aadde080-4b08-11e9-91d5-2b826d5400b8.png)
![image](https://user-images.githubusercontent.com/26907947/54665372-bcbf8380-4b08-11e9-89a0-1a4a12f6745b.png)

**Comment by cvaize** [comment]
All false values must be true

**Comment by cvaize** [comment]
Understood, config:cache was not reset, now everything works!!!
