### ISSUE TITLE
Using multiple roles/permissions in middleware throws a database exception

### ISSUE THREAD

**Issue by mowbr002** [santigarcor/laratrust#334]
```Route::middleware(['role:superadmin|developer'])->group(function(){});```

```Illuminate \ Database \ QueryException (HY093)```
```SQLSTATE[HY093]: Invalid parameter number: parameter was not defined (SQL: select "roles".*, "role_user"."user_id" as "pivot_user_id", "role_user"."role_id" as "pivot_role_id", "role_user"."user_type" as "pivot_user_type" from "roles" inner join "role_user" on "roles"."id" = "role_user"."role_id" where "role_user"."user_id" = 1 and "role_user"."user_type" = App\Models\User and "name" = superadmin limit 1)```

**Comment by santigarcor** [comment]
What version (Laravel, Laratrust) are you using?

**Comment by mowbr002** [comment]
composer.json:
```
"require": {
        "php": ">=7.2.0",
        "doctrine/dbal": "^2.5",
        "dompdf/dompdf": "^0.8.2",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.7.*",
        "laravel/passport": "^7.0",
        "laravel/scout": "6.1.1",
        "laravel/tinker": "~1.0",
        "league/flysystem-aws-s3-v3": "~1.0",
        "maatwebsite/excel": "~3.1.0",
        "pmatseykanets/laravel-scout-postgres": "^4.0",
        "santigarcor/laratrust": "5.2.*"
    }
```
