### ISSUE TITLE
Question: HasOne Team ?

### ISSUE THREAD

**Issue by MatanYed** [santigarcor/laratrust#335]
Hi, in my project, every user has only 1 team, Laratrust support multiple teams for a user.
It's not an issue, but it's kinda not comfortable to work with it.

```php
$user->rolesTeams()->first();
```
instead of just
```php
$user->teams;
```

Any suggestion of how to implement this HasOne relation in my project?

**Comment by santigarcor** [comment]
Actually you should not use that relationship to define your user's team. I recommend you to create a real direct relationship between your user and the team.

**Comment by MatanYed** [comment]
@santigarcor You mean you are not recommending me to use Laratrust's team feature? Should I implement it by myself?

**Comment by santigarcor** [comment]
Yes you can use the laratrust teams feature, but that relationship does not define the direct relationship with the team but the roles that the user has inside some given teams. What you need is a direct relationship with the team, isn't it?
