### ISSUE TITLE
Add roles to factory user

### ISSUE THREAD

**Issue by Wendy59** [santigarcor/laratrust#336]
- Laravel Version: 5.7 
- Laratrust Version: 5.0.9 

### Description:
Hello, I want to make a routing test. 
First I make an assertForbidden() to verify that an user without roles can't have access to a specific route. But I want to test the same route with an user which had roles to the access to this route. How could I attach roles to this user into my user faker ?

### Steps To Reproduce:
UserFactory.php
```
$factory->define(App\User::class, function (Faker $faker) {
    return [
        'id' => App\User::encodeUuid(App\User::generateUuid()),
        'email' => $faker->unique()->email,
        'password' => $faker->password, // secret
        'created_at' => now(),
        'updated_at' => now()
    ];
});
```

Test.php
```
...
$response  = $this->actingAs(factory(\App\User::class)->make());
$response = $this->get("/mon_url");
$response->assertSuccessful();
```

Thanks!

**Comment by santigarcor** [comment]
I think you can use a seeder file where youy create the user and assign the roles using the `attachRole(s)` and `attachPermission(s)` methods. Then inside your test you can do `$this->seed(SeederClass::class)`.
