### ISSUE TITLE
Laratrust 5.2 is satisfied with Laravel 5.6, but shouldnt

### ISSUE THREAD

**Issue by dinamic** [santigarcor/laratrust#346]
- Laravel Version: 5.6.x 
- Laratrust Version: 5.2.1 

### Description:

We've got a dependency on Laratrust defined like `^5.0`.
Somewhere along the way, you guys added support for Laravel 5.7 and 5.8, but forgot to update composer.json. It still reads:

```
"laravel/framework": "~5.6.0|~5.7.0|~5.8.0",
```

As per the README.md we can see that Laratrust 5.2 should not be used with Laravel 5.6.
Why does composer.json allows this to happen?

### Steps To Reproduce:

1. have Laravel 5.6 setup
2. composer require Laratrust 5.2
3. Expect it to fail, but it would not.

**Comment by santigarcor** [comment]
But Laravel 5.6 works fine with laratrust 5.2. Maybe i didn't get what you mean.

**Comment by dinamic** [comment]
@santigarcor there are issues with it. One that came across recently is the `config/laratrust.php` changed. The [abort code](https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L234) is not there in the 5.1 world, while its there for 5.2.

So, this happened on our production instance.

![image](https://user-images.githubusercontent.com/11616/57521253-6a405d80-7328-11e9-85bd-0ad443afb019.png)

**Comment by santigarcor** [comment]
But it's weird because check the [config in 5.1 version](https://github.com/santigarcor/laratrust/blob/5.1/config/laratrust.php#L239), the code key exists in the file. Maybe the problem was updating from 5.0 to 5.1, because I remember that structure change in the config was made from 5.0 to 5.1. The only thing changed from 5.1 to 5.2 was the support for 5.8.

**Comment by dinamic** [comment]
You are correct. Seems like the issue was updating 5.0 to 5.1.

**Comment by latifasaee** [comment]
@santigarcor After upgrading Laratrust to 5.2, the user roles on a project are not saving in my database. May you help please.

**Comment by santigarcor** [comment]
@dinamic Could you please make a PR in order to add the default?

@latifasaee Please make a report opening another issue I don't think it could be related to this one.
