### ISSUE TITLE
How to rename laratrust model for teams

### ISSUE THREAD

**Issue by chrisk2204** [santigarcor/laratrust#347]
- Laravel Version: 5.7
- Laratrust Version: latest

### Description:
I am in the config/laratrust.php while following the installation process described in the docs.
In the laratrust.php 'models' array I renamed the team model to 'enterprise' => 'App\Enterprise'.
After that I changed the table names from 'teams' to 'enterprises' in the following tables array and did the same for the foreign keys.

Now, when I execute the 'php artisan laratrust:setup' it tells me the following in my terminal:

Laratrust Migration Creation.
You are using the teams feature.

A migration that creates enterprises, permission_role, permission_user, permissions, role_user, roles tables will be created in database/migrations directory

 Proceed with the migration creation? (yes/no) [yes]:
yes

Creating migration

   ErrorException  : Undefined index: teams (View: /Applications/MAMP/htdocs/ReportCamp/vendor/santigarcor/laratrust/views/migration.blade.php)

What are am I doing wrong? Can't I change the table and model names?

Greetings,

Chris

**Comment by santigarcor** [comment]
You can not change the `team` key, the idea is to only change the value of it, because the code uses the `team` key. If for you it's enterprise, it doesn't matter, to Laratrust it will be 'team' under the table.
