### ISSUE TITLE
Ability is always returning false with teams enabled

### ISSUE THREAD

**Issue by dragonfire1119** [santigarcor/laratrust#348]
I noticed on these lines if I add the ``$team`` to the ``currentUserHasRole`` & ``currentUserHasPermission`` the Ability starts working. I do have use_teams enabled.

https://github.com/santigarcor/laratrust/blob/600aa87574e8915c3bb6d10c25d39b985327818a/src/Checkers/User/LaratrustUserChecker.php#L46

https://github.com/santigarcor/laratrust/blob/600aa87574e8915c3bb6d10c25d39b985327818a/src/Checkers/User/LaratrustUserChecker.php#L47

**Comment by santigarcor** [comment]
You're right, there's the `$team` variable missing there. Could you please create the PR to fix it?

**Comment by dragonfire1119** [comment]
PR sent https://github.com/santigarcor/laratrust/pull/349
