### ISSUE TITLE
deleting function inside boot function isn't called when using LaratrustUserTrait

### ISSUE THREAD

**Issue by nermion** [santigarcor/laratrust#35]
Inside my User model I have this
```
public static function boot()
{
        parent::boot();
        static::deleting(function ($model) {
                echo "deleting user <br>";
        });
}
```

deleting function isn't call if I use LaratrustUserTrait, is there way to make sure it gets called as I need to do some stuff inside that function.

**Comment by santigarcor** [comment]
@nermion There's a problem, because Laratrust uses that [deleting](https://github.com/santigarcor/laratrust/blob/3.0/src/Laratrust/Traits/LaratrustUserTrait.php#L71-L74) function in the soft deleting case.

**Comment by nermion** [comment]
@santigarcor Laratrust also uses deleted function but in my user model static:deleted gets called. What is the difference?

**Comment by santigarcor** [comment]
@nermion The only difference i can spot is the `return true` in that method.

**Comment by nermion** [comment]
I could test commenting out 'return true' and see if that works. Does return true need to be there, anything that depends on it?

**Comment by santigarcor** [comment]
The `return true` is not the problem, because if you se the `$flushCache` function above also returns true

**Comment by santigarcor** [comment]
@nermion Did you test it?

**Comment by nermion** [comment]
Not yet, on my way home will test it in 5 minutes

**Comment by nermion** [comment]
commenting out 'return true' makes it work. Perhaps you can remove it from that function so that I don't have to edit it my self.

**Comment by santigarcor** [comment]
@nermion does it affects the behavior or something like that?

**Comment by nermion** [comment]
It doesn't seem to cause any problems for me.

**Comment by santigarcor** [comment]
@nermion I just tested that out, i'm making the changes now

**Comment by nermion** [comment]
great :)

**Comment by santigarcor** [comment]
57b94fb3c3b7ca206505bcfa03d41c362b01ba7d solves it.

**Comment by nermion** [comment]
Hi Santigarcor how do I get this latest update, my composer file says "santigarcor/laratrust": "3.0.*", when do you release this so that my project has the latest version?

**Comment by santigarcor** [comment]
@nermion well i tagged the version 3.0.6. So you just have to run `composer update`

**Comment by nermion** [comment]
I did run composer update but it did not download the 3.0.6 for me

**Comment by nermion** [comment]
actually it maight be my fault :) I'll sort it out

**Comment by santigarcor** [comment]
@nermion ok.
