### ISSUE TITLE
Delay on permission roles!

### ISSUE THREAD

**Issue by csb346** [santigarcor/laratrust#350]
Hi. I had a small problem yesterday after creating a new permission and attaching it to a role. It seems that it didn't take effect and started to debug my code. Suddenly everything was correct without having change anything relevant!
So I tried again with another permission, and Thought it would be easier to post the tinker result to understand the problem.
![image](https://user-images.githubusercontent.com/29427107/58473256-08f9f600-8140-11e9-8521-61fe0b146aaf.png)

Any idea, why the role returns false when it actually have the permisison?

Thanks.

**Comment by santigarcor** [comment]
It could be related with the cache, maybe disable the cache or clear the app cache

**Comment by csb346** [comment]
Already tried that. Clearing all caches.

**Comment by santigarcor** [comment]
What version of laratrust are you using? So i try to replicate the issue.

**Comment by santigarcor** [comment]
I'm closing this if you have more details or is happening again please reopen or create a new report.
