### ISSUE TITLE
Error while attaching permissions to role

### ISSUE THREAD

**Issue by tayyabrasool** [santigarcor/laratrust#352]
Call to undefined method Illuminate\Events\Dispatcher::fire()
Laravel version 5.8
Laratrust Version 5.0.*

Code Example
        $role = new Role;
        $role->name = $request->role_name;
        $role->display_name = $request->display_name;
        $role->save();
        $role->syncPermissions($request->permissions);

**Comment by santigarcor** [comment]
For laravel 5.8 you need to use laratrust 5.2
