### ISSUE TITLE
Possible to add roles/permissions without persisting?

### ISSUE THREAD

**Issue by KieronWiltshire** [santigarcor/laratrust#354]
Im not sure if it’s possible, and I’m not sure if this is the right place to ask, but I was wondering if it’s possible to add a role or permission to a user without persisting it.

My main reason for this is that I only want to assign roles to the users that have been specified by me, and if the user doesn’t have a role, they should instead be giving the “default” role, except I don’t see the point in adding every user to the “default” role, it would be good if I could just check if they have roles, if not then assign them to the “default” without persisting it, and do this each login.

Is this possible?

Cheers

**Comment by santigarcor** [comment]
Hi man, sorry for the late reply, but currently it's not possible to do it. If you use cache, maybe you can modify the cache key for that specific user and then add the values you need, but i'm not really sure it will work.
