### ISSUE TITLE
 No query results for model [App\Role].

### ISSUE THREAD

**Issue by ibrhaim13** [santigarcor/laratrust#355]
- Laravel Version: #.#.# 
- Laratrust Version: #.#.# 

### Steps To Reproduce:

D:\Projects\Learn\POS>php artisan db:seed
Seeding: UserTableSeeder

   Illuminate\Database\Eloquent\ModelNotFoundException  : No query results for model [App\Role].

  at D:\Projects\Learn\POS\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:454
    450|         if (! is_null($model = $this->first($columns))) {
    451|             return $model;
    452|         }
    453|
  > 454|         throw (new ModelNotFoundException)->setModel(get_class($this->model));
    455|     }
    456|
    457|     /**
    458|      * Execute the query and get the first result or call a callback.

  Exception trace:

  1   Illuminate\Database\Eloquent\Builder::firstOrFail()
      D:\Projects\Learn\POS\vendor\santigarcor\laratrust\src\Helper.php:32

  2   Laratrust\Helper::getIdFor("superAdmin", "role")
      D:\Projects\Learn\POS\vendor\santigarcor\laratrust\src\Traits\LaratrustUserTrait.php:252

  Please use the argument -v to see more details.

D:\Projects\Learn\POS>

**Comment by santigarcor** [comment]
I can not try anything here, please provide the laratrust_seeder config you setup.

**Comment by hatimhussein** [comment]
put this in the DatabaseSeeder.php

and note that the LaratrustSeeder is previeos the UsersTableSeeder

    $this->call([
             LaratrustSeeder::class,
             UsersTableSeeder::class,
         ]);

**Comment by skrskr** [comment]
i have the same error, i solve it by clear and cache config and autoload project
```
php artisan config:cache
composer dump-autoload
```
