### ISSUE TITLE
What Cache Driver is Required?

### ISSUE THREAD

**Issue by anthony-pinskey** [santigarcor/laratrust#36]
Since this is a fork of zizaco's entrust, do you have to set the cache driver to something besides file? I know his had to use either memcached, redis or array to avoid getting that tagging error.

thanks!

**Comment by santigarcor** [comment]
@anthony-pinskey well i removed that tagging error, so i think there's no cache requirement. It works even with file driver

**Comment by anthony-pinskey** [comment]
Oh great! I will definitely try this package out. Thanks!

**Comment by santigarcor** [comment]
You're welcome.
