### ISSUE TITLE
Support for Laravel ^6.0

### ISSUE THREAD

**Issue by WBDC** [santigarcor/laratrust#361]
Seems like the Laratrust 5.2  version doesn't support Laravel 6.0.
`Problem 1
    - santigarcor/laratrust 5.2.0 requires laravel/framework ~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - santigarcor/laratrust 5.2.0 requires laravel/framework ~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[6.0.x-dev, 5.8.x-dev].
    - Can only install one of: laravel/framework[6.0.x-dev, 5.6.x-dev].
    - Can only install one of: laravel/framework[6.0.x-dev, 5.7.x-dev].
    - Installation request for laravel/framework ^6.0 -> satisfiable by laravel/framework[6.0.x-dev].
    - Installation request for santigarcor/laratrust 5.2 -> satisfiable by santigarcor/laratrust[5.2.0].`

**Comment by santigarcor** [comment]
@WBDC It should be fine with the 5.2.3 version
