### ISSUE TITLE
Middlewares are not registered automatically with Laravel 6

### ISSUE THREAD

**Issue by rakk7** [santigarcor/laratrust#363]
The middlewares automatic registering option doesn't as expected with Laravel 6, I had to manually add them to register them.

https://laratrust.santigarcor.me/docs/5.2/usage/middleware.html#configuration

**Comment by santigarcor** [comment]
@rakk7 Do you know if have been any changes in the middleware registration methods in 6.0?

**Comment by santigarcor** [comment]
I'm closing this for now, if you experience it again, feel free to reopen this issue or create a new one
