### ISSUE TITLE
Support multiple role and permission tables?

### ISSUE THREAD

**Issue by xlkit456852** [santigarcor/laratrust#364]
- Laravel Version: 5.5.* 
- Laratrust Version: 5.0.* 

### Description:

Our project has two different user type (platform/brand) and they have their own role table and permission table , like this:

user tables:
administrator_platforms、administrator_brands

role tables:
role_platforms、role_brands

permission tables:
permission_platforms、permission_brands

permission_role tables:
role_permission_platforms、role_permission_brands

Is there a way to handle roles and permission in different user type independently ?

**Comment by santigarcor** [comment]
It can not be easily done with the implementation we have right now. I think the only way to make it work with the code we have, is to dynamically change the configuration values for the model's tables and classes but it wouldn't be a clean approach.
