### ISSUE TITLE
Can i use it in a UUID environment ?

### ISSUE THREAD

**Issue by M-Abdullahi** [santigarcor/laratrust#366]
- Laravel Version: 5.8.0 
- Laratrust Version: 5.2.0 

### Description:
Hi. Thank you for making this package. 
I am tasked with a project where the user records are identified by a UUID. 
Is it possible for the package to handle UUID? 
I have gone through the migration setup and modified the user_id columns but not sure if it's the right way to do it.

**Comment by santigarcor** [comment]
I think it will work, as long as your roles and permissions use regular ids it should work fine.

**Comment by M-Abdullahi** [comment]
thank you, for the feedback  :+1:
