### ISSUE TITLE
Call to undefined function str_random()

### ISSUE THREAD

**Issue by simeonbugarija** [santigarcor/laratrust#367]
First of all thank you very much for your awesome package, I'm using it in every project. Recently I upgraded my CMS to version 6 of Laravel framewok and found a small problem so just wanted to report it so others know why it is happening and how to solve it.

- Laravel Version: 6.0
- Laratrust Version: 5.2

### Steps To Reproduce:
- install latest version of Laravel framework (6.0)
- install latest version of Laratrust package (5.2)
- generate Laratrust seeder and include in DatabaseSeeder.php
- fill permission structure in laratrust_seeder.php, for example:
`'permission_structure' => [
        'test-user' => [
            'test-module' => 'c,r,u,d'
        ],
    ]`
- execute php artisan config:cache
- execute php artisan migrate:fresh --seed
- the execution breaks in LaratrustSeeder.php on line 79 with following exception:
Call to undefined function str_random()

**Comment by engjames** [comment]
try to install composer require laravel/helpers because upgrading from laravel 5.6 -6.0 phased out some functions

**Comment by mrbudbud** [comment]
thx, composer require laravel/helpers works in my code
