### ISSUE TITLE
List all team members

### ISSUE THREAD

**Issue by CThomas87** [santigarcor/laratrust#372]
- Laravel Version: 6.0
- Laratrust Version: 5.2

### Description:
Hi, 
This is less of an issue and more of a question; is there any efficient way to list the members of all teams that the current auth user has the role "manager" in.

Ie. user_id 1 is assigned to "Team 1", "Team 2" and "Team 3" as Team Leader (with the permission "list_users" but only assigned as User in "Team 4" and not assigned at all to the rest of the teams so he will see all users that have any role within Team 1/2/3 but noone from Team 4/5/6 etc.

I can do it with raw SQL but i'm new to Laravel and unsure how to do it with eloquent and which would be most efficient.

Thanks

**Comment by robotdoug** [comment]
Add a method to your `Teams` model that returns your `Users`, for example:

```
public function users()
{
    return $this->belongsToMany(User::class)->withTimestamps();
}
```
Then access it on your `Team` object to return all the users associated with your `Team`:

```
$team->users;
```

**Comment by raisonon** [comment]
For me this worked:

`    public function users()
    {
        return $this->belongsToMany(User::class, 'role_user');
    }`

**Comment by santigarcor** [comment]
I'm closing this for now.
