### ISSUE TITLE
Method to get (cached) roles of user

### ISSUE THREAD

**Issue by gdebrauwer** [santigarcor/laratrust#375]
Currently there isn't a method present that allows you to fetch the roles of a user, using the laratrust cache. It would be nice if there was a method `getRoles()` that returns an array of strings with all the roles of the user. At the moment I have to load the roles of user from database, while that information is probably most of the time present in the laratrust cache.

I saw there's already a `userCachedRoles()` method present in the `LaratrustUserChecker` class, so it would not require a lot of extra code to get it working in the `LaratrustUserTrait`.

@santigarcor If you think it's a good idea, I will create a PR 🙂

**Comment by santigarcor** [comment]
I think it's a good idea, just to get the array with the string values.

**Comment by gdebrauwer** [comment]
Ok I will try to create a PR this week 🙂
