### ISSUE TITLE
Forced cache clearance or force user refresh

### ISSUE THREAD

**Issue by mkhyman** [santigarcor/laratrust#379]
Is there a way other than the command line to clear the cache just for laratrust user roles and permissions? Or force a refresh for a particular user?

**Comment by santigarcor** [comment]
Whenever the user is saved or updated the cache is flushed check [here](https://github.com/santigarcor/laratrust/blob/master/src/Traits/LaratrustUserTrait.php#L43)

**Comment by mkhyman** [comment]
Very fast response :)

And that makes perfect sense now. Since what i did was alter my own role by the app, which stopped me being able to do change it back via the app so I altered it manually in the DB which of course doesn't flush the cache. Then changed the config to switch off cache. I did have a look in the code but obviously failed to find the relevant part.

Btw. just started using laratrust but I like it so far thanks for sharing.
