### ISSUE TITLE
User-based Permissions

### ISSUE THREAD

**Issue by ghost** [santigarcor/laratrust#38]
Currently Laratrust has Role-based Permissions, my proposal is to add User-based permissions.

**A brief description taken from [Cartalyst's Sentinel](https://cartalyst.com/manual/sentinel/2.0#permissions):**
_Give the user-based permissions a higher priority and will override role-based permissions. Any permissions granted/rejected on the user will always take precedence over any role-based permissions assigned._

An examples where this could be useful: disallowing a user to post on a forum or participate in a chat room.

Changing the user's role just for that isn't very practical I think.

_I am new to this so I apologize in advance if this doesn't make any sense or I'm posting in the wrong section._

**Comment by KKSzymanowski** [comment]
I thought about this a while ago when my client didn't want any `roles` but wanted to specifically assign very fine-grained permissions directly to users.
I ended up creating two identical sets of permissions and roles and assigning them one to one.
This is a workaround, and also not very good one so I suppose your proposal has merit.

I assume you mean something like this?
![laratrust](https://cloud.githubusercontent.com/assets/13980973/19413472/5115c048-932e-11e6-9356-0eea53a045b8.png)
Or in other words:
![laratrustrelational](https://cloud.githubusercontent.com/assets/13980973/19413473/58bc3c6e-932e-11e6-9d0e-4e71aa006613.png)

I think this change won't introduce any API changes so we will probably be able to maintain backward compatibility.
I imagine we can extend the current migration definition with a new `permission_user` table with  introduction of a separate trait defining the relationship and supplementing the `User::can()` method with additional logic.

What do you exactly mean by _precendence_?
If user has any permissions assigned directly, don't check for permissions inherited from roles?

**Comment by CDOLago** [comment]
> What do you exactly mean by precendence?
If a role assigned to a user determines he should have access to something and a user-based permission determines he **shouldn't** have access to that something, then user-based permission takes precedence, meaning the user **won't** have access to that something. It's basically a way of overriding (and extending) the permissions defined within the roles.

Now that I really think about it I don't think it's possible to implement revoking permissions (like revoking access to a forum) without changing the whole thing. Unless it's some weirdly named permission like revoke_forum and go from there but that looks silly.

I guess your structure works fine if you want to give extra permissions to a user and not revoke them.

How would you go about revoking permissions from a certain user?

**Comment by KKSzymanowski** [comment]
Well, it's tricky, but I suppose we have at least two options:
- Add revocations table and check if the permissions exists in it. No need for `permission_user` table then.
- Add `permission_user` table with additional boolean attribute `revoked` that defaults to `false` and check it's value in the `User::can` method.

I'm personally more in favor of the second options, because it gives us more flexibility.
@santigarcor, what do you think?

**Comment by santigarcor** [comment]
Well I think the second option is the most straightforward way to solve the problem. Because the first one is a little bit complicated to understand at first.

Currently I'm working on adding groups to the middlewares. I could start working on it after finishing that groups thing.

**Comment by prekoc** [comment]
I like this feature and think it will be quite useful. I'll work on implementing this over the weekend and see what i come up with.

**Comment by santigarcor** [comment]
@prekoc That would be great.

**Comment by prekoc** [comment]
@santigarcor I've managed to do some work over the weekend, and i think most of whats needed is done. I just don't like the seeder, had to make a quick fill there to be able to test if it works but it can be a bit better i think, and didn't manage to write tests hopefully i'll get some free time in the next few days to do that. I have't done a pull request yet, you can check the code when you have some free time and see if it's ok or needs changes. https://github.com/prekoc/laratrust

**Comment by santigarcor** [comment]
@prekoc I'm currently finishing my thesis, so when i'm done with that i'll check that out.

Anyway thank you for that code :D

**Comment by santigarcor** [comment]
#45 adds this feature

**Comment by muktin** [comment]
User does not have any of the necessary access rights.
