### ISSUE TITLE
Add additional metadata to user role

### ISSUE THREAD

**Issue by leemcd56** [santigarcor/laratrust#380]
- Laravel Version: 6.2
- Laratrust Version: 5.2

### Description:

I would like to be able to add additional metadata to a role assigned to the user, preferably using the `role_user` pivot table. The reason I need this is that a user may have custom data pertaining to that role that another user with the same role may not have.

Initially I had thought about adding a `metadata` column on the `users` table, but the cost of evaluating the data on the column and making sure it doesn't deform was too much in the long run.

Any ideas on how to go about this? I did try adding the column into the migration but it didn't appear in any queries of user roles.

**Comment by santigarcor** [comment]
@leemcd56 Maybe you didn't add the `withPivot` in the relationships definition.

https://laravel.com/docs/5.8/eloquent-relationships#defining-custom-intermediate-table-models

**Comment by raisonon** [comment]
@leemcd56 Any feedback on how you approached this in the end? Thanks
