### ISSUE TITLE
Compatibility laravel version 6.7 ???

### ISSUE THREAD

**Issue by ferdikam** [santigarcor/laratrust#382]
- Laravel Version: 6.7.0 
- Laratrust Version: #.#.# 

I install package but the errors display to my Terminal.

<img width="1078" alt="Capture d’écran 2019-12-15 à 15 39 55" src="https://user-images.githubusercontent.com/297563/70865113-8f95e980-1f51-11ea-9259-186d343155d4.png">

**Comment by lypsisrudiansyah** [comment]
What Version Of Laratrust, are installed on your project ?

have you try the latest version of laratrust the laratrust 5.2 version ?

**Comment by ferdikam** [comment]
thanks, laratrust 5.2 works.
