### ISSUE TITLE
roles vs permission

### ISSUE THREAD

**Issue by GitzJoey** [santigarcor/laratrust#383]
i just want to have understanding regarding user permission
from what i see laratrust can map the access based on 
1. roles
user has roles has permission
2. permission
user has permission (directly)

is that correct? i mean i want to know whats the rationale behind user have permission without role

thanks

**Comment by santigarcor** [comment]
Yes, you can do that. It was added in case someone wanted to give users directly without the need of creating a new role since there isn't any kind of role hierarchy.
