### ISSUE TITLE
In LaratrustPermission.php line 18:                                                                                                                 Type of Laratrust\Models\LaratrustPermission::$ must be string (as in class Illuminate\Database\Eloquent\     Model)      

### ISSUE THREAD

**Issue by Messhias** [santigarcor/laratrust#384]
- Laravel Version: 5.7.*
- Laratrust Version: 5.0.*

### Steps To Reproduce:

Just run php artisan --seed

P.S: Please suggestions of "create a new project" isn't a solution, this is being happened many times per day, per week, and suddenly stops happening, and suddenly back.

**Comment by santigarcor** [comment]
Could you please show me the contents of your `LaratrustPermission` file, i just checked the one in the repo and everything seems to be fine

**Comment by santigarcor** [comment]
I'm closing this for now, if you experience it again, feel free to reopen this issue or create a new one
