### ISSUE TITLE
Direct changes to the database aren't reflected in my app after clearing the cache

### ISSUE THREAD

**Issue by enaeim** [santigarcor/laratrust#385]
- Laravel Version: 5.8.34
- Laratrust Version: I don't know, maybe 5.2.6

### Description:
You said: "If you made changes to your database directly and the changes aren't reflected in your app, please clear your application cache".
After direct change on database, I clear cache app on local app and it worked correctly but I did it on cPanel in the following way:
I wrote in the routes/web.php file the following code and executed it through the browser (myDomain/cache-clear):

`
Route::get('cache-clear', function () {
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    return back();
});
`

But again the changes did not reflect:

Please help me. Thanks.

Of course, there are 4 empty files in the root of my Laravel project called description, display_name, name and save() that I didn't transfer to the server. Because those were empty.

**Comment by santigarcor** [comment]
What cache driver are you using? Have you tried disabling the cache for Laratrust?

**Comment by santigarcor** [comment]
I'm closing this for now, if you experience it again, feel free to reopen this issue or create a new one
