### ISSUE TITLE
composer.json requirements for laravel 5.3.18

### ISSUE THREAD

**Issue by aem34** [santigarcor/laratrust#39]
Hello,

in the "master" branch there are the following 3 requirements :

"illuminate/console": "~5.1.0",
"illuminate/support": "~5.1.0",
"illuminate/cache": "~5.1.0",

but the versions are 5.3 for those 3 components by now.
Could you please correct it in the composer.json file ?

Thank you !

**Comment by santigarcor** [comment]
@aem34 are you having any problem when installing it with Laravel 5.3?

**Comment by KKSzymanowski** [comment]
As stated [here](https://getcomposer.org/doc/articles/versions.md#tilde)
```
"illuminate/console": "~5.1.0",
```
is equal to
```
"illuminate/console": ">=5.1.0 <5.2.0",
```
therefore installing the `master` branch will cause conflicts.
However the 3.0 branch specifies the requirements as `~5.0` which means `>=5.0 <6.0` and there should be no conflicts with Laravel 5.

**Comment by santigarcor** [comment]
@KKSzymanowski You're right. I'll fix that.

**Comment by santigarcor** [comment]
420e1ca4231a34fe485caa4bbbd25d4f91cc8731 solves it
