### ISSUE TITLE
Improved function whereRoleIs

### ISSUE THREAD

**Issue by AnasOmarObaid** [santigarcor/laratrust#395]
Laravel Version: 7
Laratrust Version: 5.2.8

Description:
When I Use whereRoleIs Function, This Function Not Accept more Than Role So I should use orWhereRoleIs function.
So I Go trait LaratrScopes And Just write one code
![scope](https://user-images.githubusercontent.com/43482636/77277162-01a26b00-6cc5-11ea-83ef-aa658ea52096.PNG)
and the function whereRoleIs becomes accept more than role and also accept one role
just small code ,
and this was so usefull for me.
and also will usefull for programers

**Comment by xenDE** [comment]
Hi,

you can change the `@param` doc for `$role`:
```
trait LaratrustHasScopes
{
    /**
     * This scope allows to retrive the users with a specific role.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  string  $role
     * @param  string  $boolean
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWhereRoleIs($query, $role = '', $team = null, $boolean = 'and')
    {
```

to

`     * @param  string|array  $role
`

this should fix informations in your ide/docs.

best regards,
daniel

**Comment by AnasOmarObaid** [comment]
Hi
yes its works but when i use whereRoleIs the parameter must be array  so i must put array when i use it 
but in my solution if i put array or string there is no error will happen 
best regards 
Anas.

**Comment by xenDE** [comment]
Hi,

i dont understand the problem, sorry.

you can use a string or array, thats correct.
a string is converted to an array in the code. this is how it should be.

```
$aString = "text";
$aStringCaastToArray = (array) $aString;

var_dump($aString);
var_dump($aStringCaastToArray);
/*
string(4) "text"
array(1) {
  [0]=>
  string(4) "text"
}
*/
```
best regards,
daniel

**Comment by santigarcor** [comment]
@AnasOmarObaid you're welcome to create PR with it if you want
