### ISSUE TITLE
Problem in rename permissions name

### ISSUE THREAD

**Issue by mnamazi** [santigarcor/laratrust#396]
- Laravel Version: 7.6.2
- Laratrust Version: 5.2.8

Description :
When i renamed permission "name" from `management.dashboard.index` to `management-dashboard-index`, my web application not be loaded (It does not display an error).
Although I have cleared all the caches with `php artisan cache:clear`

**Comment by santigarcor** [comment]
@mnamazi maybe you have a problem in your code, because the name should only affect the checks if the user has the permission. Maybe somewhere in your code yo have a restriction with the old name.

**Comment by mnamazi** [comment]
> @mnamazi maybe you have a problem in your code, because the name should only affect the checks if the user has the permission. Maybe somewhere in your code yo have a restriction with the old name.

This is not possible because I have checked my code line by line several times
