### ISSUE TITLE
Assign teams in the seeder

### ISSUE THREAD

**Issue by raisonon** [santigarcor/laratrust#398]
- Laravel Version: 7.x
- Laratrust Version: 5.2.8

### Description:

Is it possible to assign teams in the LaratrustSeeder?

Thanks

**Comment by santigarcor** [comment]
No, right now it's not possible to use teams in the LaratrustSeeder

**Comment by santigarcor** [comment]
I'm changing the seeder to avoid seeding users. You should seed that data depending on you business logic.

**Comment by raisonon** [comment]
Ok, thanks 👍
