### ISSUE TITLE
LaratrustSeeder does not respect modified table names

### ISSUE THREAD

**Issue by cdtweb** [santigarcor/laratrust#40]
Followed the instructions here: 
http://laratrust.readthedocs.io/en/3.0/configuration/seeder.html

It looks like the `trucateLaratrustTables()` call is using hard-coded table names. 

```php
    // database/seeds/LaratrustSeeder.php
    /**
     * Truncates all the laratrust tables and the users table
     * @return    void
     */
    public function truncateLaratrustTables()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('permission_role')->truncate();
        DB::table('role_user')->truncate();
        \App\User::truncate();
        \App\Role::truncate();
        \App\Permission::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
```

In my installation I've renamed all of the tables, so the code fails with the following errors:
                                                                                                                                              

>   [Illuminate\Database\QueryException]                                                                                                        
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.permission_role' doesn't exist (SQL: truncate `permission_role`)  
>                                                                                                                                               
> 
>                                                                                                             
>   [PDOException]                                                                                            
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.permission_role' doesn't exist  

                                                                                                           

It looks like making the following change to `truncateLaratrustTables()` resolves the error:

```php
    // database/seeds/LaratrustSeeder.php
    /**
     * Truncates all the laratrust tables and the users table
     * @return    void
     */
    public function truncateLaratrustTables()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table(config('laratrust.permission_role_table'))->truncate();
        DB::table(config('laratrust.role_user_table'))->truncate();
        \App\User::truncate();
        \App\Role::truncate();
        \App\Permission::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
```

**Comment by santigarcor** [comment]
@cdtweb Yeah, you're right. I'll fix it soon

**Comment by santigarcor** [comment]
bbccc46c9ea51d124cd6fbb86d7091b42590dcaf solves it
