### ISSUE TITLE
Add scopes to get users without any role or permission

### ISSUE THREAD

**Issue by wakjoko** [santigarcor/laratrust#400]
Hello @santigarcor ,

I am a fan of your work, really liked it and it would be very nice if we could have some scopes to get list of users that doesn't have any role or any permission.

The reason is from my opinion, each users i will assume them as a guest unless.. they are assigned to certain role or permission.

So it'll be very handy to have the scopes to manage the users without any role or permission.

Currently i have a trait something like below, but maybe you have much better idea how to handle this kind of situation.

Thanks.

- Laravel Version: 5.8.37
- Laratrust Version: 5.2.8

```php
trait LaratrustScopes
{
    /**
     * This scope allows to retrive the users without any role.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  string  $role
     * @param  string  $boolean
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWhereDoesntHaveRole($query)
    {
        return $query->doesntHave('roles');
    }

    /**
     * This scope allows to retrieve the users without any permission.
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  string  $permission
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWhereDoesntHavePermission($query)
    {
        return $query->doesntHave('permissions')->orDoesntHave('roles.permissions');
    }
}
```

**Comment by santigarcor** [comment]
I'll take a look at it. It's actually a good idea to have those methods inside the package.

**Comment by wakjoko** [comment]
Yeah, it could become better if we can directly check on logged in users also.

Have a nice day ahead dude.

**Comment by santigarcor** [comment]
@wakjoko I'm adding them to the next release of Laratrust :smile:

**Comment by wakjoko** [comment]
Great! This could be a little addition but i feel it could be a big niche for Laratrust to play along spatie's long dominance.
Thanks @santigarcor
