### ISSUE TITLE
Custom fields of ownership

### ISSUE THREAD

**Issue by gidaban** [santigarcor/laratrust#401]
- Laravel Version: 7.9.2 
- Laratrust Version: 5.2.9 

### Description:
Is any possible to make a custom checks of ownership?
i want to check ownership not by user id but by profile_id

```
auth()->user->owns($message,'profile_id')
```
In my user table i have 'profile_id' field however i am using another table for store profiles then user_is is not equal with profile_id because i have two types of profiles.

 in message table i have column 'company_profile_id'  then fields in both tables are not same

```
auth()->user()->id; //1 but
auth()->user()->profile_id; //10;
//then in message i have 
{
"id": 1,
"uuid": "8cf5216d-f83a-4b05-a3ee-ba1d8a08833e",
"company_profile_id": 10,
"first_name": "name",
"last_name": "name",
"email": "email@com.com",
"phone_number": null,
"message": "message",
"read_at": "2020-05-04T17:19:34.000000Z",
"reply_at": null,
"created_at": "2020-05-04T18:09:37.000000Z"
}
```

is possible to make method for checking ownership like that ?

**Comment by santigarcor** [comment]
You can do it with the ownable interface, please check here https://laratrust.santigarcor.me/docs/5.2/usage/concepts.html#ownable-interface

**Comment by gidaban** [comment]
Hi,

Yes i saw it, however i have another question, how to use it in my case ?

```
    public function ownerKey($owner)
    {
        return $this->message->company->user->profile_id; ///
//or $this->company->message->user->profile_id
    }
```

**Comment by KKSzymanowski** [comment]
Can multiple users have the same `profile_id`? If so, I don't think it's possible to use the `Ownable` interface to achieve what you need because it assumes an object has one owner.

**Comment by gidaban** [comment]
each user have unique profile_id, it is relationship user and company_profiles table.

**Comment by KKSzymanowski** [comment]
In this case I think the `ownerKey()` method can simply return the `id` of the user who is assigned to the specific profile you're interested in.

This method **has** to return the user's `id` because it is then compared with the primary key of the `User` model.

**Comment by gidaban** [comment]
i have maked class like in example 

```
<?php

namespace App;

class MessageOwnerCheck implements \Laratrust\Contracts\Ownable
{
    public function ownerKey($owner)
    {
        return $this->company->profile->user->profile_id;
    }
}
```
i am getting error `Undefined property: App\MessageOwnerCheck::$company`


`$owner` return user object where is `profile_id`, 

i have make relations
`User.php`
```
   public function profile()
    {
        return $this->morphTo();
    }
```

`CompanyProfile.php`
```
public function user()
    {
        return $this->morphOne('App\Models\User', 'profile');
    }
public function messages()
    {
        return $this->hasMany(CompanyMessage::class, 'company_profile_id', 'id');
    }
```

`CompanyMessage.php`
```
    public function company()
    {
        return $this->belongsTo(CompanyProfile::class);
    }
```

Maybe it will help ?

**Comment by KKSzymanowski** [comment]
What is the purpose of the `MessageOwnerCheck`? It's not a model from what I see. 

If you want to check if a user owns a company message, then the `CompanyMessage` model should implement the `Ownable` interface.

**Comment by gidaban** [comment]
Thanks :)

`CompanyMessage.php`
```
    public function ownerKey($owner)
    {
        return $this->company_profile_id;
    }
```
and also i had use `Trait` in `CompanyProfile.php`

**Comment by KKSzymanowski** [comment]
I don't think this would work. I think you must return the id of the **user** who has that profile.

**Comment by gidaban** [comment]
in company_messages table i dont have user_id field only company_profile_id,
`auth()->user->profile_id` is not equal `auth()->id` because user can have business profile  which belongs to `company_profiles` table or `customer` which belongs to `customer_profiles` table.

Anyway i solved my problem. Thanks again
