### ISSUE TITLE
Panel - prevent specific roles from being deleted

### ISSUE THREAD

**Issue by dmason30** [santigarcor/laratrust#407]
- Laravel Version: 7.x
- Laratrust Version: 6.x

**Suggestion**
Loving the panel in this release! We currently have our own one that we maintain which is largely similar. The problem is we have some roles that we don't want any one to be able to delete or edit. For example, we have a 'Admin' role that automatically gets attached to all of our permissions that we cannot let anyone delete or edit to disable permissions. 

Something like:

```php
// config/laratrust.php

return [
    ...
    'panel' => [
        'restricted_roles' => [
            'admin',
        ]
    ],
];
```

We also have another role where we would not like associated users to be editable. I was thinking maybe the above needs to evolve into its own permission based config:

```php
// config/laratrust.php

return [
    ...
    'panel' => [
        'restricted_roles' => [
            'admin' => [
                 'users' => ['edit' => true],
                 'permissions' => ['edit' => false]
             ],
            'support' => [
                 'users' => ['edit' => true],
                 'permissions' => ['edit' => true]
             ],
            'customer' => [
                 'users' => ['edit' => false],
                 'permissions' => ['edit' => false]
             ], 
        ]
    ],
];
```

**Comment by santigarcor** [comment]
I like the idea. Maybe i would put something more verbose like:

```php
// config/laratrust.php

return [
    ...
    'panel' => [
        'restricted_roles' => [
            'admin' => [
                'assignable' => true,
                'removable' => false,
                'updatable' => false,
                'deletable' => false,
             ],
             ...
        ]
    ],
];
```

But I'm not sure if the addition will benefit a lot of people.

**Comment by Geelik** [comment]
Hello

I think it's a great suggestion. I don't see any real use case for having a role that isn't assignable. If you have role it's purpose is to be used.
I like the modularity added by having `removable`, `updatable` and `deletable`.

If you want i can try to implement this and make a PR.

**Comment by santigarcor** [comment]
@Geelik makes sense, but one thing is if you can create roles on the go, configuring it from the config file would be weird, but I think that wouldn't be applied to all roles, just some of them.

**Comment by dmason30** [comment]
@Geelik All of our roles are assigned to users but our customers when they sign up are automatically assigned the `customer` role. However, I do not want to allow a customer to be assigned any other roles or allow anyone to remove the `customer` role from them.

**Comment by Geelik** [comment]
@dmason30 Oh i see your use case, i didn't thought of that, thanks for the explanantion.
I agree @santigarcor approach is better.

**Comment by santigarcor** [comment]
@dmason30 you're right maybe the booleans aren't necessary. Now the thing is if this feature would add something useful to the panel. Let's say the latter structure i proposed is the final one, how it would work?

@KKSzymanowski what do you think man?

@Geelik Let's figure somethings out first and then we will see how to implement it.

**Comment by KKSzymanowski** [comment]
@santigarcor I haven't ever used this panel, so I'm not the best person to ask 🙂

**Comment by santigarcor** [comment]
@dmason30 if you want you can check this [branch](https://github.com/santigarcor/laratrust/tree/limit-roles-in-panel) I did something there about those roles restrictions. Any comments would be appreciated.

**Comment by dmason30** [comment]
@santigarcor This is a seems to cover most of our use cases. The only thing missing for us is that I would have liked a `not_manageable` or something similar over `not_removeable` as we don't want our `member` role users to be able to be assigned any other roles:

![image](https://user-images.githubusercontent.com/20278756/81843316-5afc7d00-9545-11ea-9306-f0eb79b81706.png)

**Unrelated Feedback:** 
_Roles & Permissions Assignment_
I would say you could have got away with just calling this menu option 'Users' but I understand the need to be somewhat descriptive. Is there a reason why it doesn't select the first model automatically each time you navigate to this page? Rather than showing no results - most users will have just the one model:

![image](https://user-images.githubusercontent.com/20278756/81843807-0dccdb00-9546-11ea-911f-d81dded3d9a2.png)

_Roles View/Edit_
We have some pretty lengthy permission names so the view roles view does get a bit jumbled. Is there a reason why it doesn't use the display name?:

![image](https://user-images.githubusercontent.com/20278756/81842983-da3d8100-9544-11ea-81c9-948c14d6c9a2.png)

Looks ok on an editable role:

![image](https://user-images.githubusercontent.com/20278756/81843035-ede8e780-9544-11ea-9f26-b5acc451524b.png)

**Comment by santigarcor** [comment]
@dmason30 I think that would be out of the scope of the package IMO. 

Thanks for the other feedback, I'll take a look on how to improve the panel and even add the teams support.

I wanted the panel to be as simple as possible but i could grab some ideas from your panel. How did you manage to group the permissions? Did you use some pattern in their name?

**Comment by dmason30** [comment]
All of our permissions are defined as constants in an enumeration style class which also defines the groups. 

I could probably get away with removing our version and making everyone use the awesome panel you have provided I would probably put all our roles in the not editable and would prefer it if you used display names for roles / permissions if they are set.

**Comment by nanaaikinson** [comment]
Can laratrust middleware be used with multiple guards?

**Comment by santigarcor** [comment]
@nanaaikinson that question is not related to this thread. Please go and check the [middleware docs](https://laratrust.santigarcor.me/docs/6.x/usage/middleware.html#concepts).

**Comment by santigarcor** [comment]
@dmason30 I used the `name` just because I usually do that, but It makes sense just to use the `display_name`

**Comment by dmason30** [comment]
@santigarcor I would recommend null coalescing to use the name as backup `$permission->display_name ?? $permission->name` as I am sure a lot don't define the display names. There only purpose is for when you are managing them via an internal tool or via your panel.

**Comment by santigarcor** [comment]
[This release](https://github.com/santigarcor/laratrust/releases/tag/6.1.0) fixes this.
