### ISSUE TITLE
Panel : Create form for permissions

### ISSUE THREAD

**Issue by Geelik** [santigarcor/laratrust#408]
- Laravel Version: 7.10.3
- Laratrust Version: 6.x

The addition of the panel is great !

I asked myself why there is no form manage permissions like roles ? Is there a reason you don't want it or it's just in the todo list ?

**Comment by santigarcor** [comment]
From what I know, permissions are the base of a RBAC system. So you will create a new permission once you already put it in the code. So it doesn't make much sense to create permissions IMHO.

**Comment by Geelik** [comment]
I understand your point and i agree.
