### ISSUE TITLE
Unable to use blade directives

### ISSUE THREAD

**Issue by einkinder** [santigarcor/laratrust#409]
- Laravel Version: 7.0
- Laratrust Version: 6.0

**Describe the bug**
I am unable to use any of the blade directives in my views.

**To Reproduce**

                        @role('superadministrator')
                        <p>This is visible to users with the admin role. Gets translated to
                            \Laratrust::hasRole('superadministrator')</p>
                        @endrole

superadministrator is the role assigned to the superadministrator@app.com which I used to login.

**Comment by santigarcor** [comment]
@einkinder what error are you getting?

**Comment by einkinder** [comment]
syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) 
when using: 

```
                        @permission('edit-user')
                        <p>This is visible to users with the given permissions. Gets translated to
                            \Laratrust::can('edit-user'). The @can directive is already taken by core
                            laravel authorization package, hence the @permission directive instead.</p>
                        @endpermission

```

**Comment by santigarcor** [comment]
@einkinder I checked and the blade directives are working fine. Example above fails because it uses a `@permission` inside the block. Nevertheless I found no issue there.
