### ISSUE TITLE
Call to undefined method Laratrust\Laratrust::role()

### ISSUE THREAD

**Issue by Anpix** [santigarcor/laratrust#41]
In the Docs instruction for Blade Template http://laratrust.readthedocs.io/en/3.0/usage/blade_templates.html

The command \Laratrust::role('admin') don't work, because the function role() doesn't exists.

**Comment by Anpix** [comment]
The right usage is @role()

**Comment by santigarcor** [comment]
@Anpix but you're right, there's an error in the docs, it shoul be `hasRole` instead of `role`
