### ISSUE TITLE
FIx typos

### ISSUE THREAD

**Issue by siarheipashkevich** [santigarcor/laratrust#410]
- Laravel Version: 6.*
- Laratrust Version: 6.*

**Describe the bug**
Please fix the typos in the config file.

**To Reproduce**
https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L271
`accesible` to `accessible`

https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L304
`assign_permisions_to_user` to `assign_permissions_to_user`and check in the code this parameter also.

And maybe will be better to remove empty lines in config file:
https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L157
https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L126
https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L126

**Comment by santigarcor** [comment]
Thank you @siarheipashkevich , could you please create a PR with those fixes?

**Comment by siarheipashkevich** [comment]
@santigarcor yes, I can.
