### ISSUE TITLE
Always returning 403

### ISSUE THREAD

**Issue by nanaaikinson** [santigarcor/laratrust#413]
User has all permissions but laratrust always returns 403.
```
Route::middleware("auth:api")->group(function () {
   Route::get("/user", function(Request $request){
      return $request->user();
   });

   Route::get("/{id}", "Api\Tenant\RoleController@show")->middleware('permission:update-roles');
});

```
When I hit the route for auth user, it returns the user data but the route for role always returns 4033

**Comment by santigarcor** [comment]
@nanaaikinson I think you're not using the proper guard in the middleware. Also check if you are assigning the roles using the methods provided by Laratrust.

Here's an example on how to use custom middlewares from the docs:
```php
middleware' => ['role:owner|writer,require_all|guard:api']
```

So in your case it would be something like:
```php
middleware' => ['permission:update-roles,guard:api']
```

**Comment by nanaaikinson24** [comment]
@santigarcor It worked thank you. What is the difference between `permission:create-posts|guard:api` and `permissions:create-posts,guard:api`

**Comment by santigarcor** [comment]
The `|` is used to define and array. The `,` just separates the parameters passed to the middleware.
