### ISSUE TITLE
assets are unpublishable

### ISSUE THREAD

**Issue by Oreolek** [santigarcor/laratrust#414]
Laravel version: 7.11
Laratrust version: 6.0.2

```
❯ php artisan vendor:publish --tag=laratrust-assets --force
Unable to locate publishable resources.
```

**Comment by santigarcor** [comment]
Did you follow the instructions listed [here](https://laratrust.santigarcor.me/docs/6.x/usage/admin-panel.html#how-to-use-it)?

If so, maybe you should run `php artisan config:clear`

**Comment by Oreolek** [comment]
oh i must've missed the `panel.register` config! thanks!
