### ISSUE TITLE
Administration Panel doesn't work`s?

### ISSUE THREAD

**Issue by Habner-Gabryel** [santigarcor/laratrust#416]
Hi, I recently started using the laratrust 6.0 tool and decided to use the "Admin Panel", but apparently it is not working correctly when publishing using the `php artisan vendor code: publish --tag = laratrust-assets --force`  and changing my  `register`  to  ` true`, it displays the 404 page not found error when trying to enter the Laratrust URL, I tried to change the URL, restarted the test server, cleared the cache, but nothing makes the page work. I don't know if this is just a problem in my code, but I would like to use the panel, I found it extremely useful and would save me a lot of work time.
Is there anything else I can try to resolve my issue?

**Comment by santigarcor** [comment]
Did you follow the instructions on [how to use](https://laratrust.santigarcor.me/docs/6.x/usage/admin-panel.html) the admin panel? First you should enable it, before running the publish assets. If that doesn't work, you could try running `php artisan config:clear` before following the instructions.

**Comment by Habner-Friella** [comment]
yes, i followed the steps on how to use and tried to run `php artisan config: clear`, but it still doesn't work.
As a test server, I am using the wampserver, making my access to the admin panel through `localhost / projectname / public / laratrust`, but when trying to enter, it redirects me to` localhost / laratrust` even though my `.env` the` localhost / projectname / public` URL.
I really can't understand why it happens.

**Comment by santigarcor** [comment]
I'm not sure if it's more a problem with you system configuration. Because I've tried even with a new installation and using `php artisan serve` and it's working.

**Comment by Habner-Gabryel** [comment]
ok, thank's for your support, i will try solve this. 
Sorry for my bad english.

**Comment by santigarcor** [comment]
Don't worry, I'm not native speaker either.

**Comment by 740il** [comment]
I have the same problem i need help

**Comment by shafiqruslan** [comment]
Hi, I'm having the same issue where it returns a 404 error. I already follow the instructions from here https://laratrust.santigarcor.me/docs/6.x/usage/admin-panel.html#how-to-use-it

**Comment by drishyajose** [comment]
This might help someone..
i tried the url  mentioned in the laratrust docs in my local server as 
"http://localhost/projectname/public/laratrust" 
but redirected to
 "http://localhost/laratrust/roles-assignment"  
So  i used this  in my project url as **"**http://localhost/projectname/public/laratrust/roles-assignment**"** .
Now I got the admin panel. Then, from  the menu you can access roles,permissions etc..

**Comment by javedkhan8833** [comment]
awesome,  i also solved my issue by watching your discussion step by step
