### ISSUE TITLE
Does Laratrust play with multi-auth ?

### ISSUE THREAD

**Issue by abuamr-gafurov** [santigarcor/laratrust#417]
- Laravel Version: 7.8.1
- Laratrust Version: 6.0

In my project multi-auth working well.

Does Laratrust play with multi-auth ?

I can't find a solution to this issue in the documentation

**Comment by santigarcor** [comment]
You can use the multiple user models feature and the middlewares multiple guards, check the `config/laratrust.php` file there you can see about the multiple users.

**Comment by abuamr-gafurov** [comment]
Hi, i hope you doing well.

Do you mean "Laratrust User Models (62-77 line in `config/laratrust.php`)" ?

I will be glad if there is any multi-auth example with Laratrust

**Comment by santigarcor** [comment]
I added more docs about the multiple user models in the 6.x docs version you can check it [here](https://laratrust.santigarcor.me/docs/6.x/usage/multiple-users.html)
