### ISSUE TITLE
Sugestion: set full admin permission name in configuration file

### ISSUE THREAD

**Issue by andreladocruz** [santigarcor/laratrust#419]
We keep repeating 

`$user->hasPermission(['admin', 'some.other.permission.name'])`

The idea is to add the permission `'admin'` to some key in the configuration file and just use 

`->hasPermission('entries.contacts.view')`

**Comment by santigarcor** [comment]
What do you have in mind on how that could work?

Also, It will be a little tricky because if you read the code you are not going to understand why it's checking for roles/permissions that aren't explicitly there.

**Comment by andreladocruz** [comment]
laratrust.php

 'full_access_permission' => 'my_full_admin_permission'

hasPermission() method adds this value to the permissions listed. 

Just to avoid having to repeat the permission every time.

this can be an optional setting

**Comment by santigarcor** [comment]
I'm not sure I like this.

Maybe you should re-think why you create an `admin` permission, but instead checking the permission needed to do some action. And if for some reason you need a custom check, 
 that should be a custom permission that should be attached to your admin role.

**Comment by santigarcor** [comment]
Then what you need is to have the admin role created through all your accounts. Something like a shared admin role. because if you are checking for example for the `user-edit` and `admin` permission. It will be easier for you just to simply ask for the `user-edit` permission and attach that permission to the role admin.

**Comment by andreladocruz** [comment]
Yeap... I got your point... thanks for the support
