### ISSUE TITLE
How do I get the roles of a user?

### ISSUE THREAD

**Issue by CreativeKoen** [santigarcor/laratrust#42]
I'm trying to get the role of a user using `$user->roles()` but this is not working.
besides that the docs aren't helping ether.

**Comment by KKSzymanowski** [comment]
Is there any error?
How exactly are you getting these roles?

If you want to just check the existance of a role, say:
```
if($user->hasRole('admin') {
    //
}
```
or with multiple: 
```
if($user->hasRole(['admin', 'owner']) {
    //
}
```
It's described [here](http://laratrust.readthedocs.io/en/3.0/usage/concepts.html#checking-for-roles-permissions) in more detail.

If you want to fetch all the roles, it's the classic Laravel ManyToMany relationship meaning you can say:
```
$roles = $user->roles;
// or
$roles = $user->roles()->get();
```
If you just do:
```
$roles = $user->roles();
```
the `roles` variable will contain an instance of `Illuminate\Database\Eloquent\Relations\BelongsToMany` and you can do further operations on it like `->find($roleId);` or `->orderBy('name')->first();` etc.

Does this clear up anything for you?

**Comment by CreativeKoen** [comment]
I changed `$user->roles()` to `$user->roles` and it worked! Thanks!!

**Comment by KKSzymanowski** [comment]
You're welcome.

**Comment by LeTranAnhVu** [comment]
Hi, Is there anyway to eager loading the role of user. when I use $user->with('roles')->get() . It return all the users with their roles. Since I just want to eager loading the roles in user.
