### ISSUE TITLE
Call to undefined method Laratrust\Laratrust::can() 

### ISSUE THREAD

**Issue by yorkcorp** [santigarcor/laratrust#421]
![App Filters](https://user-images.githubusercontent.com/48572570/83393887-2c8ff600-a3bd-11ea-9313-ec016440d78a.png)
![adminlte](https://user-images.githubusercontent.com/48572570/83393933-4af5f180-a3bd-11ea-9a53-e9c8c3fbedca.png)
![adminlte2](https://user-images.githubusercontent.com/48572570/83393956-5517f000-a3bd-11ea-8396-cfa58702bfee.png)
![error](https://user-images.githubusercontent.com/48572570/83394173-b93ab400-a3bd-11ea-9b4b-c385efa8a0b5.PNG)
in laravel 5.8 and laracast 5.2 its working good ,please can you helpme 
but in Laravel 7.0 and laracast 6.0 not working. this is the link of project
https://www.dropbox.com/s/72qynmfv7jf4xz3/laracast.zip?dl=0

**Comment by santigarcor** [comment]
The method `can` was removed in version 6.x. In the [upgrade guide](https://laratrust.santigarcor.me/docs/6.x/upgrade.html) it says you must remove the usage of the `can` method and replace it by `isAbleTo`.

**Comment by yorkcorp** [comment]
Erdaaa!! yes!!! thanks Parce!!

**Comment by pimduijst** [comment]
We are still struggling with this. In our blade templates we use @permission('foobar') but we still get this same error message in the above screenshot. We are running Laravel 7.x and Laratrust 6.x. Please help!

**Comment by yorkcorpthe** [comment]
In Laravel 11 I have this error 
Call to undefined method Laratrust\Laratrust::isAbleTo()
The same example
![image](https://github.com/user-attachments/assets/469806c7-b424-42de-b373-60e2344b086f)
