### ISSUE TITLE
How to get roles attached to user for given permission?

### ISSUE THREAD

**Issue by karmendra** [santigarcor/laratrust#422]
Hi,

I have a screen that lists a users attached permissions, I want to show is the permission is directly attached to user or is it attached via a role or attached via multiple roles.

Basically this list will have one new column called roles, if it is directly attached this column will be empty else it will show single or comma separated multiple roles.

I am unable to figure how I can use relationships to get this in SINGLE query using eager loading.

Please help with this

Thanks,
K

**Comment by Meeshalk** [comment]
You can use eloquent for this, pull all the permissions and with eager loading you can get roles associated with each permissions.

BTW, these types of questions shouldn't be posted in here, its not even related to Laratrust, its a general laravel question and not even an issue.
