### ISSUE TITLE
Wildcard permission not supported?

### ISSUE THREAD

**Issue by Hatsunyan** [santigarcor/laratrust#427]
i create permision like
```
module.*.action
```
and use check like
```
$user->hasPermission('module.one.action');
$user->hasPermission('module.two.action');
```
but seems its not working like that

**Comment by santigarcor** [comment]
Can you please give me more detail about how it's not working? Because you can create your permissions with your own structure and the check should work fine.

Regarding the wildcard it will work if you change the check to `$user->hasPermission('module.one.*');`

**Comment by siarheipashkevich** [comment]
Hi @santigarcor but can we use * for permission in the database?

I want to assign permission `module.*` to user and after that check it by `$user->hasPermission('module.one.action')` ?

**Comment by santigarcor** [comment]
@siarheipashkevich No, you can't do that. It only works if you assign the permission `module.one.action` and then check for `$user->hasPermission('module.one.*')`

**Comment by siarheipashkevich** [comment]
@santigarcor do you plan to add this ability to the package?

**Comment by santigarcor** [comment]
@siarheipashkevich I don't think so.
