### ISSUE TITLE
Customize Administration Panel

### ISSUE THREAD

**Issue by sprklinginfo** [santigarcor/laratrust#428]
Hi there,

I just installed and enabled the laratrust package in my current Laravel 7 project. I enabled the build-in Administration Panel with the command 'php artisan vendor:publish --tag=laratrust-assets --force'. I can access it. But I changed my User Model to have a 'First' and 'Last' to record user's name information, not a 'name' field. I thought with the above 'vendor:publish' command, all assets will be available in my project 'resources/vendor' folder so I can modify the view to show Auth::user()->first and Auth::user()->last instead. but I don't see them. How do I customize and extend the build-in Admin Panel without changing anything in the 'Vendor' folder? 

Thanks,

**Comment by santigarcor** [comment]
Right now it's not possible to customize it, but I'm thinking in make the views publishable but first I have to make some adjustments in other files.

**Comment by sprklinginfo** [comment]
Thanks for the quick reply. One more question: by default the routes to the admin panel are not secured, how can I secure related routes in my routes/web.php file so only users with superadmin/admin roles can access them?

**Comment by santigarcor** [comment]
There's a section in the config that allows you to add middlewares to those routes, you can check [here](https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L292). Then you only have to add the middlewares to filter those routes for now but in the future i think adding a gate like horizon or telescope should be the solution.

**Comment by sprklinginfo** [comment]
My apologies. This is my first laravel project. If I modify the config/laratrust.php file to have more middlewares, how the file can be reloaded to take effect? I tried with the laratrust:setup command again and didn't seem to work. Do I have to uninstall and reinstall it?

**Comment by santigarcor** [comment]
You don't need to do anything just change/add the middlewares in your `config/laratrust.php` file and that's all. Maybe you can run `php artisan config:clear` in case you've run the config cache command.

**Comment by leighgregg** [comment]
Hello, 
I am interested in the solution for this. Also my first Laravel setup. I have the Admin panel installed and working. However the middleware to prevent access to the Admin Panel is a little confusing to me. I have been looking through Documentaiton about the default Middleware, but as a basic setup for preventing access unless Administrator or Superadministrator I am confused. Can you help me in the right direction for this. Thanks
