### ISSUE TITLE
Couldn't create seeder.

### ISSUE THREAD

**Issue by bobrovskikh** [santigarcor/laratrust#43]
`php artisan laratrust:seeder`

> Couldn't create seeder. 
> Check the write permissions within the database/seeds directory.

`php artisan db:seed --class=LaratrustSeeder`

> Creating Role SUPERADMINISTRATOR
> Creating Permission to create for users
> Creating Permission to read for users
> Creating Permission to update for users
> Creating Permission to delete for users
> Creating Permission to create for acl
> Creating Permission to read for acl
> Creating Permission to update for acl
> Creating Permission to delete for acl
> Creating Permission to read for profile
> Creating Permission to update for profile
> Creating Role ADMINISTRATOR
> Creating Permission to create for users
> Creating Permission to read for users
> Creating Permission to update for users
> Creating Permission to delete for users
> Creating Permission to read for profile
> Creating Permission to update for profile
> Creating Role PARTNER
> Creating Permission to read for profile
> Creating Permission to update for profile
> Creating Permission to read for order_status
> Creating Permission to update for order_status
> Creating Role USER
> Creating Permission to read for profile
> Creating Permission to update for profile

**Comment by santigarcor** [comment]
Well you need permission to write in the `databases/seeds` directory.

**Comment by bobrovskikh** [comment]
how? =)

**Comment by santigarcor** [comment]
If you are in Linux or OSX:

```
sudo chmod -R 777 database/seeds
```
