### ISSUE TITLE
For some reason `$this->can('user.impersonate')` is returning false which true is expected.

### ISSUE THREAD

**Issue by ufiyus** [santigarcor/laratrust#430]
Okay i checked my database and all the data seems correct, no spelling errors so i have no clue. Here are some screenshots of the database. 
![github issue 4](https://user-images.githubusercontent.com/46644293/85104993-a6a2e600-b1d7-11ea-87cd-0530b0257091.PNG)
![github issue 5](https://user-images.githubusercontent.com/46644293/85104995-a73b7c80-b1d7-11ea-95b5-42a9b4a1fb58.PNG)
![github issue 1](https://user-images.githubusercontent.com/46644293/85104998-a73b7c80-b1d7-11ea-82d1-a3938702cc1b.PNG)
![github issue 2](https://user-images.githubusercontent.com/46644293/85105001-a7d41300-b1d7-11ea-8081-03bbc2ca96d8.PNG)
![github issue 3](https://user-images.githubusercontent.com/46644293/85105003-a86ca980-b1d7-11ea-8472-de962b93bf0e.PNG)
So by the looks of it the name of the permission matches the name i passed in the `can` method, it's permission id is 2 which is connected to role id 1, role id 1 is `super.administrator`, role id 1 is connected to user id 1, role id is the main account i am using to test out the admin dashboard i am making. There is no errors, just returning false on something that should be true.
```php
/**
 * Can this user impersonate another user.
 *
 * @return bool Returns true after successful operation and false if not.
 */
public function canImpersonate()
{
    return $this->can('user.impersonate');
}
```
The function above is what i am using, this is in my user model. My laravel version is `7.14.1` and my laratrust version is `6.x`. Any help would be grateful.

**Comment by santigarcor** [comment]
@ufiyus maybe you set those permissions through the DB, have you tries running `php artisan cache:clear`? Or simply disable the cache for laratrust.

**Comment by ufiyus** [comment]
Yea i tried `php artisan cache:clear` I added through my permissions seeder.
```php
<?php

use App\Role;
use App\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void Returns nothing.
     */
    public function run()
    {
        $permissions = [
            // ...
            Permission::create(['name' => 'user.impersonate.protect']),
            Permission::create(['name' => 'user.impersonate']),
            Permission::create(['name' => 'view.users']),
            Permission::create(['name' => 'edit.users']),
            Permission::create(['name' => 'delete.users']),
            Permission::create(['name' => 'ban.users']),
            // ...
        ];
        (Role::where('name', 'super.administrator')->first())->attachPermissions($permissions);
    }
}

```
I was able to solve this issue by using `isAbleTo` method.  i think the can method no longer works. should it?

**Comment by ufiyus** [comment]
After updating to `6.x`, the can method does not work. The work around for this error is using the `isAbleTo` method for anybody having the same issue.
