### ISSUE TITLE
Verification returning 'false' when using teams

### ISSUE THREAD

**Issue by PierreMatos** [santigarcor/laratrust#431]
- Laravel Version: 5.8.37
- Laratrust Version: 5.0.9

**Describe the bug**
I'm having trouble when checking the roles and permissions only when using teams.
 If I run just something like this` $user->hasRole('admin')` or` $user->isAbleTo('create-post')` I get 'true'
but if I add the team parameter like `$user->hasRole('admin', 'project1')` or `$user->can('create-post', 'project1')` I get 'false'

I've attached my user role to the team, using `$user->attachRole('admin', 'project1')` and all id's were correctly inserted  in the role_user table,
![image](https://user-images.githubusercontent.com/60151514/85593263-c9e9ed00-b63e-11ea-8c09-e218fb6d3ced.png)

The only particularity is that my Teams Model is **Project**, and I've changed accordingly in the config/laratrust.php, and my model 'name' is mapped, but I guess those things are correct since i'm able to attach and detach the roles to the teams correctly.

So, my Team is this Project Model:

> 
> namespace App\Models;
> 
> use Illuminate\Support\Facades\DB;
> use Laratrust\Models\LaratrustTeam;
> use Illuminate\Database\Eloquent\Model;
> use Sofa\Eloquence\Eloquence; // base trait
> use Illuminate\Database\Eloquent\SoftDeletes;
> use Sofa\Eloquence\Mappable; // extension trait
> 
> 
> class Project extends LaratrustTeam
> {
>     use SoftDeletes, Eloquence, Mappable;
>     
>     protected $connection = 'mysql';
> 
>     protected $maps = [
>         'name' => 'slug'
>     ];
> 
>     protected $casts = [
>         'configuration' => 'array'
>     ];
> 
>   (...)
> 
>     public function users()
>     {
>         return $this->hasManyThrough('App\Models\User', 'App\Models\RoleUser', 'project_id', 'id', 'id', 'user_id');
>     }
> 
>     public function getNameAttribute()
> {
>     return $this->slug;
> }
> 
> 
> }

My config/laratrust.php

> 
> /**
>  * This file is part of Laratrust,
>  * a role & permission management solution for Laravel.
>  *
>  * @license MIT
>  * @package Laratrust
>  */
> 
> return [
>     /*
>     |--------------------------------------------------------------------------
>     | Use MorphMap in relationships between models
>     |--------------------------------------------------------------------------
>     |
>     | If true, the morphMap feature is going to be used. The array values that
>     | are going to be used are the ones inside the 'user_models' array.
>     |
>     */
>     'use_morph_map' => false,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Use cache in the package
>     |--------------------------------------------------------------------------
>     |
>     | Defines if Laratrust will use Laravel's Cache to cache the roles and permissions.
>     |
>     */
>     'use_cache' => false,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Use teams feature in the package
>     |--------------------------------------------------------------------------
>     |
>     | Defines if Laratrust will use the teams feature.
>     | Please check the docs to see what you need to do in case you have the package already configured.
>     |
>     */
>     'use_teams' => true,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Strict check for roles/permissions inside teams
>     |--------------------------------------------------------------------------
>     |
>     | Determines if a strict check should be done when checking if a role or permission
>     | is attached inside a team.
>     | If it's false, when checking a role/permission without specifying the team,
>     | it will check only if the user has attached that role/permission ignoring the team.
>     |
>     */
>     'teams_strict_check' => true,
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Laratrust User Models
>     |--------------------------------------------------------------------------
>     |
>     | This is the array that contains the information of the user models.
>     | This information is used in the add-trait command, and for the roles and
>     | permissions relationships with the possible user models.
>     |
>     | The key in the array is the name of the relationship inside the roles and permissions.
>     |
>     */
>     'user_models' => [
>         'users' => 'App\Models\User',
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Laratrust Models
>     |--------------------------------------------------------------------------
>     |
>     | These are the models used by Laratrust to define the roles, permissions and teams.
>     | If you want the Laratrust models to be in a different namespace or
>     | to have a different name, you can do it here.
>     |
>     */
>     'models' => [
>         /**
>          * Role model
>          */
>         'role' => 'App\Models\Role',
> 
>         /**
>          * Permission model
>          */
>         'permission' => 'App\Models\Permission',
> 
>         /**
>          * Team model
>          */
>         'team' => 'App\Models\Project',
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Laratrust Tables
>     |--------------------------------------------------------------------------
>     |
>     | These are the tables used by Laratrust to store all the authorization data.
>     |
>     */
>     'tables' => [
>         /**
>          * Roles table.
>          */
>         'roles' => 'roles',
> 
>         /**
>          * Permissions table.
>          */
>         'permissions' => 'permissions',
> 
>         /**
>          * Teams table.
>          */
>         'teams' => 'projects',
> 
>         /**
>          * Role - User intermediate table.
>          */
>         'role_user' => 'role_user',
> 
>         /**
>          * Permission - User intermediate table.
>          */
>         'permission_user' => 'permission_user',
> 
>         /**
>          * Permission - Role intermediate table.
>          */
>         'permission_role' => 'permission_role',
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Laratrust Foreign Keys
>     |--------------------------------------------------------------------------
>     |
>     | These are the foreign keys used by laratrust in the intermediate tables.
>     |
>     */
>     'foreign_keys' => [
>         /**
>          * User foreign key on Laratrust's role_user and permission_user tables.
>          */
>         'user' => 'user_id',
> 
>         /**
>          * Role foreign key on Laratrust's role_user and permission_role tables.
>          */
>         'role' => 'role_id',
> 
>         /**
>          * Role foreign key on Laratrust's permission_user and permission_role tables.
>          */
>         'permission' => 'permission_id',
> 
>         /**
>          * Role foreign key on Laratrust's role_user and permission_user tables.
>          */
>         'team' => 'project_id',
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Laratrust Middleware
>     |--------------------------------------------------------------------------
>     |
>     | This configuration helps to customize the Laratrust middleware behavior.
>     |
>     */
>     'middleware' => [
>         /**
>          * Define if the laratrust middleware are registered automatically in the service provider
>          */
>         'register' => false,
> 
>         /**
>          * Method to be called in the middleware return case.
>          * Available: abort|redirect
>          */
>         'handling' => 'abort',
> 
>         /**
>          * Parameter passed to the middleware_handling method
>          */
>         'params' => '403',
> 
>     ],
> 
>     /*
>     |--------------------------------------------------------------------------
>     | Laratrust Magic 'can' Method
>     |--------------------------------------------------------------------------
>     |
>     | Supported cases for the magic can method (Refer to the docs).
>     | Available: camel_case|snake_case|kebab_case
>     |
>     */
>     'magic_can_method_case' => 'kebab_case',
> ];

> 

**To Reproduce**

if i run this:

          

> $user = User::find($id);
> 
>             $newProject = new Project();
>             $newProject->full_name = 'new project';
>             $newProject->slug = 'newproj';
>             $newProject->save();
> 
>             $admin = new Role();
>             $admin->name         = 'newRole';
>             $admin->display_name = 'User Administrator'; // optional
>             $admin->description  = 'User is allowed to manage and edit other users'; // optional
>             $admin->save();
> 
>             $createPost = new Permission();
>             $createPost->name         = 'create-post';
>             $createPost->display_name = 'Create Posts'; // optional
>             // Allow a user to...
>             $createPost->description  = 'create new blog posts'; // optional
>             $createPost->save();
> 
>             $admin->attachPermission($createPost);
>             $user->attachRole($admin, $newProject);
> 
>             
>             $user->hasRole('create-post', 'newproj');  //false

Returns false

I would be glad if someone could give me a hint on what might be happening and how can I solve this

**Comment by santigarcor** [comment]
Two things:
1. Your table is weird because the `user_type` column must not be an integer, it should be something like App\Models\User or user according to your config.
2. `$user->hasRole('create-post', 'newproj');` will always return false for you, because you are trying to check for a permission using the `hasRole` method.

If you manually modified the assignation table you should run `php artisan cache:clear`

**Comment by PierreMatos** [comment]
sorry my bad, I'm running 

> $user->isAbleTo('create-post','newproj');

 and 

> $user->hasRole('newRole','newproj'); 

both of them returning false.
I did cleared my cache before. And I'm sure it's recognizing the manually modified table because it's attaching and detaching roles and permissions correctly with the modified 'teams'

**Comment by PierreMatos** [comment]
Problem solved, I had this in my user Model

>  public function roles()
>      {
>          return $this->belongsToMany(Role::class);
>      }

**Comment by santigarcor** [comment]
@PierreMatos in most cases you don't need to redefine the relationship, Laratrust already comes with it defined.
