### ISSUE TITLE
Permissions Completely Stopped?

### ISSUE THREAD

**Issue by dmhall0** [santigarcor/laratrust#433]
All permissions throughout the site were working correctly earlier today.
I started coding a completely different section, didn't touch anything related to permissions, and now they are blocking access to every area where I had them set.  Even in my controllers where I have them part of the middleware are blocked.
I have tried changing permissions, roles, even directly gave permission to user, and still nothing.
I don't know where to even start debugging.

Any help would be greatly appreciated.

I am running latest versions of both Laravel and Laratrust, just downloaded last week.

Couple things I have tried...
auth()->user()->allPermissions() - Returns correct permissions
php artisan cache:clear - No change

**Comment by santigarcor** [comment]
@dmhall0 Have you tried disabling the cache?

**Comment by dmhall0** [comment]
@santigarcor 
Thank you for the quick reply.
To do that I 
1 - in config\cache.php Default Cache Store changed from 'file' to 'null'
2 - in .env file changed CACHE_DRIVER from 'file' to 'array'

With the permissions commented out everything worked fine.
When I make them active I get the following error:
Facade\Ignition\Exceptions\ViewException; No query results for model [App\Models\Team]

I checked all my code in that file and everything looks correct.

Any other thoughts?

Thanks again for the help!

**Comment by santigarcor** [comment]
@dmhall0 actually you don't have to disable the cache system-wide, only disable it for laratrust in `config/laratrust.php` there's a cache section in it.

**Comment by dmhall0** [comment]
@santigarcor 
I re-enable the system-wide cache and disabled only for laratrust as you mention.  I then ran <code>php artisan cash:clear</code> which gave me a response of "Application cache cleared!"
I refreshed my page and permissions still blocking.
I have checked my roles, permissions, teams tables and models a hundred times.
Strange...

**Comment by santigarcor** [comment]
Can you please show me the contents of you laratrust config file, and the contents of your role_user table?

**Comment by dmhall0** [comment]
I have attached a pdf of my laratrust config file and an image of my role_user table.
If you want it some other way let me know.
![role_user_table](https://user-images.githubusercontent.com/67370876/86813436-2e994480-c04e-11ea-8d35-39716261d774.png)

[laratrust_config.pdf](https://github.com/santigarcor/laratrust/files/4886050/laratrust_config.pdf)

**Comment by santigarcor** [comment]
@dmhall0 Can you please show me at least some data from that table?

**Comment by dmhall0** [comment]
@santigarcor 
Sorry about that, here you go.
![role_user_data](https://user-images.githubusercontent.com/67370876/86828349-1ed72b80-c061-11ea-8df1-f039799f8590.png)

**Comment by santigarcor** [comment]
I believe you have overwritten the relationship between the user and the roles and you didn't setup the relationship correctly. Because the table has the user_type empty when it should be filled.

Or maybe you set those values manually and forgot to add the user_type.

**Comment by dmhall0** [comment]
I noticed that column was empty so I filled it in, as well as removed the other columns from the table.  I then tested it and still not luck.
![role_user_updated](https://user-images.githubusercontent.com/67370876/86904470-c181bf80-c0de-11ea-8bd2-861ef530b9a8.png)

I am using attachRole when I create a team, which fills in all the columns correctly except for that one.
![store_team](https://user-images.githubusercontent.com/67370876/86904693-11f91d00-c0df-11ea-8b24-0a35d5ba7827.png)

I have tried walking through the code on both attachRole and permissions but I get lost.
Any ideas on next steps to track down what I messed up?

Thanks again @santigarcor  for the help!

**Comment by dmhall0** [comment]
Okay, been busy testing this morning.

Problem...
It was breaking is in my blade file where I had `@permission('user add', $team->id)`

Setup...
User is **only** on 1 team (_name_ = Team 1 with _id_ = 43) and **only** has 1 role (admin).
No permissions are directly assigned to the User, only adopted through the role.
User is also the only one with the role of "admin" and permission of "user add" assigned to that role.
Laratrust cache is disabled.
The team strict_check = false.

Testing...
I tried `hasRole()` and `isAbleTo()` in the following ways and received these results...

`auth()->user()->hasRole('admin')` = True = Good!
`auth()->user()->hasRole('emp')` (role not assigned) = False= Good!
`auth()->user()->hasRole('admin','Team 1')` = **False** = Expected a True?
`auth()->user()->hasRole('admin','43')` = **False** = Expected a True?

`auth()->user()->isAbleTo('user add')` = True = Good!
`auth()->user()->isAbleTo('site full')` (which is not assigned to the admin role) = False= Good!
`auth()->user()->isAbleTo('user add','Team 1')` = **False** = Expected a True?
`auth()->user()->isAbleTo('user add', '43')` = **False** = Expected a True?

Next I assigned the same user also to another team with the role of 'emp'.
I did my testing again and got the following...
`auth()->user()->hasRole('admin')` = True = Good!
`auth()->user()->hasRole('admin','Team 1')` = **False** = Expected a True?
`auth()->user()->hasRole('admin','43')` = **False** = Expected a True?

`auth()->user()->hasRole('emp')` (role assigned on other team) = True = Good!
`auth()->user()->hasRole('emp','Team 2')` = **False** = Expected a True?
`auth()->user()->hasRole('emp','44')` = **False** = Expected a True?

`auth()->user()->isAbleTo('user add')` = True = Good!
`auth()->user()->isAbleTo('site full')` (assigned to emp role on other team) = True = Good!
`auth()->user()->isAbleTo('user add','Team 1')` = **False** = Expected a True?
`auth()->user()->isAbleTo('user add', '43')` = **False** = Expected a True?

I then changed team strict_check = true and redid all the tests, and got the **exact** same results.

I returned back to the very beginning and did `@permission('user add')` (note no team parameter) and it functioned as expected.

So, this leads me to the assumption that something is going on with the team parameter.
Does all of that give any insight to where a problem could be?

**Comment by santigarcor** [comment]
I refered to the relationship, by any chance did you overwrite the `roles()` method in the user model?

**Comment by dmhall0** [comment]
In my User.php model I have
`
public function roles()    {
        return $this->belongsToMany(Role::class)
            ->withTimestamps();
    }
`

**Comment by dmhall0** [comment]
@santigarcor 
Not sure if this error is due to my problem; but I just initiated the admin panel and went to change permissions on one of my roles and received this error...
![laratrust admin panel error](https://user-images.githubusercontent.com/67370876/86934766-1686fb00-c10a-11ea-9acc-a15c25449c09.png)

**Comment by santigarcor** [comment]
@dmhall0 your problem is that you redefined that roles relationship. Check [here](https://github.com/santigarcor/laratrust/blob/master/src/Traits/LaratrustUserTrait.php#L53) how Laratrust defines it by default.

**Comment by dmhall0** [comment]
Sorry, but I'm still learning Laravel, as I am sure you have noticed, so am I supposed to put that in my User model?
![ScreenClip](https://user-images.githubusercontent.com/67370876/86954344-cd43a500-c123-11ea-9d50-584953909e59.png)

**Comment by santigarcor** [comment]
I would recommend you not to overwrite it, but in case you need to add new things there, just use that as a base.
