### ISSUE TITLE
The Mix manifest does not exist.

### ISSUE THREAD

**Issue by dmhall0** [santigarcor/laratrust#434]
I did a fresh install of Laravel and Laratrust.

I enabled the Laratrust Panel and when I went to it I got the following...
![ScreenClip](https://user-images.githubusercontent.com/67370876/87105509-2ea16c00-c229-11ea-8c4e-0e239bd156ed.png)

From what I have found on the web for running `npm install` and `npm run dev` have not worked for me.

**Comment by mchumer** [comment]
Same problem

**Comment by blackforestcode** [comment]
You have to publish the assests used by the panel:
`php artisan vendor:publish --tag=laratrust-assets --force`

Documentation:
[https://laratrust.santigarcor.me/docs/7.x/usage/admin-panel.html](https://laratrust.santigarcor.me/docs/7.x/usage/admin-panel.html)
