### ISSUE TITLE
Non-static method Laratrust\Laratrust::isAbleTo() should not be called statically

### ISSUE THREAD

**Issue by eraporsmk** [santigarcor/laratrust#435]
- Laravel Version: 7.19.1
- Laratrust Version: 6x

Description:
I'm use Laravel AdminLTE form here https://github.com/jeroennoten/Laravel-AdminLTE#6112-custom-menu-filters

**Comment by santigarcor** [comment]
I think the issue is in that project, because it shouldn't be access like that repo is proposin. It should be accessed through the Facade/ by using the alias.

```php
use Laratrust;
// or 
use Laratrust/LaratrustFacade;

Laratrust::isAbleTo('...');
```
