### ISSUE TITLE
orderBy role name in datatables

### ISSUE THREAD

**Issue by eraporsmk** [santigarcor/laratrust#437]
- Laravel Version: 7.19.1
- Laratrust Version: 6.1.1

how to get all users orderBy role name in datatables?
```php
$query = User::query();
return DataTables::eloquent($query)
     ->orderColumn('roles', function ($query, $order) {
        $query->orderBy('?', $order);
     })
//.....
})
```

**Comment by Meeshalk** [comment]
Are you using yajrabox?

**Comment by filippotoso** [comment]
This issue is stale. I'm closing it. If you still need help, open another issue.
