### ISSUE TITLE
Attaching multiple permissions to a user

### ISSUE THREAD

**Issue by Brouhana** [santigarcor/laratrust#438]
I attempted to allow an admin to modify a user and attach permissions for that user. At one point, I successfully allowed the admin to select permissions and attach it to the user. But, it only selected one at a time regardless of how many permissions selected.

Essentially, what I'm trying to replicate is how multiple permissions may be assigned to a user in the User's edit view as in the Laratrust Admin (permissions with select options underneath the role assignment):
![image](https://user-images.githubusercontent.com/8935419/88130425-27228100-cba0-11ea-94ee-b41464355ed8.png)

How would I achieve this? I'd also appreciate a small breakdown as I'm still grasping Laravel.

**Comment by santigarcor** [comment]
@Brouhana so basically if you check multiple permissions at the end only one gets saved?

**Comment by Brouhana** [comment]
> @Brouhana so basically if you check multiple permissions at the end only one gets saved?

Correct

**Comment by santigarcor** [comment]
I tried selecting multiple permissions and saving them and It seems to be working fine. Please check the screenshots:

Before saving:
![image](https://user-images.githubusercontent.com/7565417/91662692-99dd2100-eaa9-11ea-9397-b2175535db1a.png)

After saving:
![image](https://user-images.githubusercontent.com/7565417/91662695-a3668900-eaa9-11ea-8f5e-83d3468c3dcc.png)
