### ISSUE TITLE
I want to show a web page , when i am getting "403" status code ,   

### ISSUE THREAD

**Issue by jeetaugurs** [santigarcor/laratrust#439]
'abort' => [
                'code'=>403,
                'message' => 'User does not have any of the necessary access rights.'
            ],

**Comment by santigarcor** [comment]
@jeetaugurs You can change the middleware handling to redirect to an [specific page](https://laratrust.santigarcor.me/docs/6.x/usage/middleware.html#redirect) or you can [customize your 403 error page](https://laravel.com/docs/7.x/errors#custom-http-error-pages).
