### ISSUE TITLE
How to get a collection of users in this role?

### ISSUE THREAD

**Issue by bobrovskikh** [santigarcor/laratrust#44]
Hello!

How to get a collection of users in this role?

Thank you

**Comment by KKSzymanowski** [comment]
As far as I know this has not been explained in the documentation, but it's fairly simple.

The `User` - `Role` relationship is a *ManyToMany* type, which means the `User` **has many** `Roles` and a `Role` is(or really *can be*) **assigned to many** `Users`. 
In this case, as stated in the official framework documentation, we use a following relationship declaration:
```php
public function posts()
{
    return $this->belongsToMany(Post::class);
}
```

Our case is exactly the same, meaning:
```php
$user = User::first();

$roles = $user->roles; // Get all user roles.
// or
$roles = $user->roles()->get();
```
and
```php
$role = Role::first();

$users = $role->users; // Get all users with this role assigned to them
// or
$users = $role->users()->get();
```

I hope this explains it for you.

By the way, this is an open source project, so you are more than engouraged to take a look at the package files.
The `Role` model uses `Laratrust/Traits/LaratrustRoleTrait`, and in this trait definition you'll find the [relationship declaration](https://github.com/santigarcor/laratrust/blob/3.0/src/Laratrust/Traits/LaratrustRoleTrait.php#L36).
It applies user configuration to be more flexible, but by default it would behave something like following:
```php
public function users()
{
    return $this->belongsToMany(
        App\User::class,
        'role_user',
        'role_id',
        'user_id'
    );
}
```
which is just an explicit way of saying
```php
public function users()
{
    return $this->belongsToMany(App\User::class);
}
```
As you can see there's not much magic going on.

**Comment by bobrovskikh** [comment]
Thank you! Working!

$role = Role::where('name','=','administrator')->first();
$users = $role->users;
