### ISSUE TITLE
Middleware to set desired handler

### ISSUE THREAD

**Issue by dmason30** [santigarcor/laratrust#442]
I have been using this package for serveral years on an application which has both an API and Web routes restricted by permissions/roles.

I use the default `abort` set in the config `laratrust.middleware.handling` for the API and on the first day I created a simple middleware that set this config option to `redirect` on the web routes (see below).

Due to its simplicity and low maintenance I was wondering if you think this is something you would want to add to the package?

**app/Http/Middleware/LaratrustSetMiddlewareToRedirect.php**
```php
class LaratrustSetMiddlewareToRedirect
{
    public function handle($request, Closure $next)
    {
        \Config::set('laratrust.middleware.handling', 'redirect');

        return $next($request);
    }
}
```

**app/Http/Kernal.php**
```php
protected $middlewareGroups = [
        'web' => [
            ...
            LaratrustSetMiddlewareToRedirect::class,
        ],

        'api' => [
            ...
        ],
    ];
```

**Comment by santigarcor** [comment]
@dmason30 I like that approach.

Another nice thing that I'm thinking about is to add invokable middleware handlers(maybe in the future) so people can customize what they really want to do in those cases.

**Comment by santigarcor** [comment]
Closing this for now, if you want to open a PR you are welcome to do it.
