### ISSUE TITLE
User::whereRoleIs()  is not working with the array input(array of roles).

### ISSUE THREAD

**Issue by arkniazi** [santigarcor/laratrust#444]
- Laravel Version: 5.7.*
- Laratrust Version: 5.2.*

I tried to retrieve the Users of multiple roles by passing roles in an array to `whereRoleIs` function but it didn't work. 
If I try like this it works fine.
`User::whereRoleIs('role1')->orWhereRoleIs( 'role2')->get()`

But if I try to use it like this.
` User::whereRoleIs(['role1','role2'])->get()`
then it only returns the users associated with first role.

**Comment by santigarcor** [comment]
I tried to replicate the issue but It worked for me. It basically does a `whereIn` against the role's name column.

**Comment by arkniazi** [comment]
@santigarcor 
I have changed Roles table a bit(name(column) is not unique now. I did this to support separate roles for multiple companies.) can this be the cause of this issue?
