### ISSUE TITLE
Api middleware role check doesn't take into account a multi-db setup

### ISSUE THREAD

**Issue by MrLast98** [santigarcor/laratrust#447]
Hello,
I have recently started a project with Laravel e Laratrust. I have 2 DBs: one only contains the Users table, and is used only at login, the second one is the actual DB where the Laratrust table are populated (the role is not attached to the users table but to another table).
Role attachment works fine, since i can specify which DB to use for permissions and roles, but during the middleware api check i have no way to do that.

From my code:

```
Route::group([
    'prefix' => 'project',
    'middleware' => ['auth', 'role:superAdministrator|administrator|fakeAdministrator|projectManager']

], function ($router){

    Route::post('create', 'ProjectController@create');
    Route::post('delete', 'ProjectController@delete');
    Route::post('update', 'ProjectController@update');
}); 
```

How can i say to this role check to use a different DB? Didn't see anything like this on the Docs or the Config files.

- INFO
Laravel Framework 7.23.0
Laratrust 6.x

**Comment by santigarcor** [comment]
It's not possible, you will need to create new middleware that implements that behavior you need. You could use the base middleware and change the parts that you need. Then turn off the registration and register your new middleware instead.
