### ISSUE TITLE
How to use it with multiple guards?

### ISSUE THREAD

**Issue by juanpscotto** [santigarcor/laratrust#450]
Hi, How can I use it with multiple guards like

`Auth::user('api')`

Thanks

**Comment by santigarcor** [comment]
If you are referring to the middleware you can check [here](https://laratrust.santigarcor.me/docs/6.x/usage/middleware.html#using-different-guards).

But if you refer to the auth user in the rest of the code, you should be doing it like it's specified in the Laravel docs: `Auth::guard(...)->user()`

**Comment by juanpscotto** [comment]
Thanks!
