### ISSUE TITLE
Micro change on config.php

### ISSUE THREAD

**Issue by GeoSot** [santigarcor/laratrust#455]
On Config file, may the following line 

https://github.com/santigarcor/laratrust/blob/7cf9ef84579f8f4e69d18ffe07f64d52bd3905ab/config/laratrust.php#L197

could be changed by this 
```php
\App\Providers\RouteServiceProvider::HOME 
```

**Comment by santigarcor** [comment]
IMHO It's better to leave it like it's right now.
