### ISSUE TITLE
Open laratrust - error "The Mix manifest does not exist. vendor/santigarcor/laratrust/resources/views/panel/layout.blade.php"

### ISSUE THREAD

**Issue by i-coder** [santigarcor/laratrust#459]
npm run prod

Open page laratrust
The Mix manifest does not exist. vendor/santigarcor/laratrust/resources/views/panel/layout.blade.php

**Comment by santigarcor** [comment]
https://laratrust.santigarcor.me/docs/6.x/usage/admin-panel.html#how-to-use-it
