### ISSUE TITLE
Where to create roles and permissions?

### ISSUE THREAD

**Issue by schuesslerf** [santigarcor/laratrust#46]
Hello,

In your guide, you write 

Let’s start by creating the following Roles and Permissions:

```
$owner = new Role();
$owner->name         = 'owner';
$owner->display_name = 'Project Owner'; // optional
$owner->description  = 'User is the owner of a given project'; // optional
$owner->save();

$admin = new Role();
$admin->name         = 'admin';
$admin->display_name = 'User Administrator'; // optional
$admin->description  = 'User is allowed to manage and edit other users'; // optional
$admin->save();
```

Where do I have to do this? I'm a bit confused about it... I made the two models for Role and Permission, but this is not the right place for it, right? Where else? Maybe this is too easy, I don't know, but I don't really get it..

**Comment by KKSzymanowski** [comment]
You have couple of options.

You can do it in a seeder after you migrate the database.

If you just want to test some configuration you can setup a test route and put it there or boot up `php artisan tinker` and run the commands there.

**Comment by schuesslerf** [comment]
Basically I'd like to use it for permanent setup. How does this thing with the seeder work? I found this (http://laratrust.readthedocs.io/en/3.0/configuration/seeder.html), but this would be completely other way to set the roles like in the code I posted above, wouldn't it? Or am I missing something? Notice that I'm quite new to laravel, so maybe there I'm missing something, too.. However, to configure the two above roles (owner and admin), where would I have to put it in or what can I do with the seeder?

**Comment by KKSzymanowski** [comment]
Read the documentation [here](https://laravel.com/docs/5.3/seeding). It explains how seeders work and how to create them.

It should clear up everything for you. If you will have other questions, I will be happy to answer them.

If you're new to Laravel you should also read the docs on migrations or preferably watch Jeffrey's videos on [laracasts.com](Laracasts).

**Comment by schuesslerf** [comment]
Okay, so seeders put the test data in db right? But where can I use the code above? Still a bit confused, because the code above seems to use eloquent and the code example in the Laravel Doc doesn't...

**Comment by schuesslerf** [comment]
What I mean is: With the seeders, I can't use the syntax you provide under concepts right? Instead I have to use this?

`return [
   'role_structure' => [
       'superadministrator' => [
           'users' => 'c,r,u,d',
           'acl' => 'c,r,u,d',
           'profile' => 'r,u'
       ],
       'administrator' => [
           'users' => 'c,r,u,d',
           'profile' => 'r,u'
       ],
       'user' => [
            'profile' => 'r,u'
       ],
   ],
   ...
];`

Is that correct?

**Comment by KKSzymanowski** [comment]
Seeders just run the code you specify in each seeder class, so you can do full Laravel work there.

**Comment by santigarcor** [comment]
@schuesslerf you can customize those values in order to use the roles and permissions you want.

If you only want to put some permissions and roles without any relationship, you will have to use the Laravel seeder.

**Comment by schuesslerf** [comment]
But I can put those customized roles in the seeders as well? Basically I need 3 roles, they for example all can edit their data, the rest is basic roles, so (to be more precise) I want a role for admin, seller, and buyer. Everybody can edit their data, the buyer can search for products, buy something and manage his orders, the seller can set up products to sell, manage his orders he got and so on. Basically I just need to have this functionality, so I somehow have to check, what kind of user it is and depending on it, I load a view or redirect to controller, etc. Important would be to only make the views accessible to the user made for, so a buyer can't access the order overview of a seller. 
So, it would be nice if you could help me, where I (for that situation) can create the roles and permissions (happens once) and where I can check for them then, in order to show user the right view and prevent users from getting into view that they shouldn't see. Thanks in advance

**Comment by KKSzymanowski** [comment]
I think you could figure it out by trial and error but nevertheless I will do my best to explain it to you.

### We need permissons

> Everybody can edit their data

`Permission::create(['name' => 'edit_profile', 'display_name' => 'Edit profile']);`
> buyer can search for products

`Permission::create(['name' => 'search_products', 'display_name' => 'Search for products']);`
> buyer can [...] buy something

`Permission::create(['name' => 'order_product', 'display_name' => 'Order a product']);`
> buyer can [...] manage his orders

`Permission::create(['name' => 'manage_custom_orders', 'display_name' => 'Manage custom orders']);`
> seller can set up products to sell

`Permission::create(['name' => 'manage_products', 'display_name' => 'Manage products']);`
> seller can manage his orders

I assume you mean *all orders*
`Permission::create(['name' => 'manage_all_orders', 'display_name' => 'Manage all orders']);`

And so on...

You can also call these permissions whatever you want eg. `managing_products`, `editing_profiles` or `product_management`, `profile_editing`. It's your call.

### We need roles

```php
Role::create(['name' => 'admin', 'display_name' => 'Administrator']);
Role::create(['name' => 'buyer', 'display_name' => 'Buyer']);
Role::create(['name' => 'seller', 'display_name' => 'Seller']);
```

### We need seeder*(s)*
It will probably easier to put everything in one seeder class so:
`php artisan make:seeder LaratrustSeeder`
or whatever you wanna call it.

Go to `database/seeds/LaratrustSeeder.php` which you just created and
1. Create permissions
2. Create roles
3. Attach permissions to roles

```php
public function run()
{
    $editProfile        = Permission::create(['name' => 'edit_profile', 'display_name' => 'Edit profile']);
    $searchProducts     = Permission::create(['name' => 'search_products', 'display_name' => 'Search for products']);
    $orderProduct       = Permission::create(['name' => 'order_product', 'display_name' => 'Order a product']);
    $manageCustomOrders = Permission::create(['name' => 'manage_custom_orders', 'display_name' => 'Manage custom orders']);
    $manageProducts     = Permission::create(['name' => 'manage_products', 'display_name' => 'Manage products']);
    $manageAllOrders    = Permission::create(['name' => 'manage_all_orders', 'display_name' => 'Manage all orders']);

    $admin  = Role::create(['name' => 'admin', 'display_name' => 'Administrator']);
    $buyer  = Role::create(['name' => 'buyer', 'display_name' => 'Buyer']);
    $seller = Role::create(['name' => 'seller', 'display_name' => 'Seller']);

    $admin->permissions->attach($editProfile);
    $buyer->permissions->attach([$searchProducts, $orderProduct, $manageCustomOrders]);
    $seller->permissions->attach([$manageProducts, $manageAllOrders]);
}
```

**Don't forget to add `$this->call(LaratrustSeeder::class);` in `database/seeds/DatabaseSeeder.php`**

### We need this in database

Here you have two options:
1. `php artisan migrate:refresh --seed` - Rollback and migrate everything and run all seeders.
2. `php artisan db:seed` - Just run all seeders.

All right, we have all of this in database, so we can add some authorization.
You have probably dozen of options here, but my personal favourite are:
1. Wrapping routes in permission-checking middleware.
2. Adding permission checking logic to Request classes(you need to create those).

First option would look like that:
```php
Route::group(['middleware' => 'auth'], function() {

    //
    
    Route::group(['middleware' => 'permission:edit_profile'], function() {
        Route::resource('profile', 'ProfileController', ['only' => ['edit', 'update']]);
    });

    //

});
```

Second:
`php artisan make:request Profile/Update`
In `app/Http/Requests/Profile/Update.php`:
```php
use Illuminate\Contracts\Auth\Guard;
// ...
public function authorize(Guard $auth)
{
    return $auth->user()->can('edit_profile');
}
```
In `app/Http/Controllers/ProfileController.php`
```php
public function update(Profile $profile, Profile\Update $request)
{
    //
}
```

I'm writing these examples from my head without any validation, so forgive any typos or mistakes.

You can read more about authorization in the Laravel documentation or ask on one of the forums(Laracasts, Slack, Gitter, Laravel.io).

Also, watch [this](https://laracasts.com/series/laravel-5-fundamentals) series. It's free.

**Comment by schuesslerf** [comment]
Thank you SO much! Actually, I didn't figure out, to run those calls to create permissions and roles in the run() function and as well, I propably would have forgotten to include the seeder. Also it's good to know, how I can check for the permissions.
So thanks for your effort :)

**Comment by santigarcor** [comment]
@schuesslerf You could have done that with the Laratrust seeder. It seeds the DB with the data you provide in the `laratrust_seeder.php` file.

In that file you only need to change so your file would be something like:

```
return [
   'role_structure' => [
       'admin' => [
           'users' => 'c,r,u,d',
           'roles' => 'c,r,u,d',
           'profile' => 'r,u'
       ],
       'seller' => [
           'products' => 'c,r,u,d',
           'orders' => 'r,u',
           'profile' => 'r,u',
       ],
       'buyer' => [
            'orders' => 'm,e',
            'products' => 'b',
            'profile' => 'r,u'
       ],
   ],
   'permissions_map' => [
        's' => 'search',
        'b' => 'buy',
        'e' => 'edit',
        'm' => 'manage',
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete',
    ]
];
```

And the you follow the instructions in the docs and you will have your permissions, roles and one user for each role :smile:

**Comment by schuesslerf** [comment]
@santigarcor Thanks for that, I'm right that this is nearly the same as the post of @KKSzymanowski but a bit more compact? 
I have one last question: With the solution of @KKSzymanowski , I'm now able to just use 
```
$user = User::where('username', '=', 'michele')->first();#
$user->attachRole($admin);
```

right?

**Comment by santigarcor** [comment]
In the seeder he built? Yes.

**Comment by santigarcor** [comment]
@schuesslerf in every php file. With both methods you will be able to that, because both methods will populate your database with that roles and permissions information.

**Comment by schuesslerf** [comment]
Alright, thanks. I'll close this thread now, if there is something else I'd open up a new thread, but I think I got everything. Thanks for your help, both.

**Comment by santigarcor** [comment]
You're welcome :smile:

**Comment by schuesslerf** [comment]
Well, I got one thing missing... In the seeder, what do I have to import to be able to use "Permission", as well as "Role"? Somehow, no matter what I import, it doesn't work...

**Comment by santigarcor** [comment]
You need to import the role and the permission.

**Comment by schuesslerf** [comment]
Yes, but when I import 

```
use App\Permission;
use App\Role;
```

I get "Method attach does not exist". So are this the right imports? And is there another import I need for that lines to work?

`    $admin->permissions->attach($editProfile);
`

**Comment by KKSzymanowski** [comment]
I'm unable to test it now but you'll probably need to say `$admin->permissions()->attach($editProfile):`

**Comment by schuesslerf** [comment]
Kinda fixed, but I get the next error:

[  [Illuminate\Database\QueryException]
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '{"name":"edit_profile","display_name":"Edi
  t profile","updated_at":"2016-11-01 09:29:36","created_at":"2016-11-01 09:29:36","id":' for column 'permission_id'
  at row 1 (SQL: insert into `permission_role` (`permission_id`, `role_id`) values ({"name":"edit_profile","display_n
  ame":"Edit profile","updated_at":"2016-11-01 09:29:36","created_at":"2016-11-01 09:29:36","id":1}, 1), ({"name":"se
  arch_products","display_name":"Search for products","updated_at":"2016-11-01 09:29:36","created_at":"2016-11-01 09:
  29:36","id":2}, 1), ({"name":"admin_manage_orders","display_name":"Manage all orders as admin","updated_at":"2016-1
  1-01 09:29:36","created_at":"2016-11-01 09:29:36","id":7}, 1), ({"name":"admin_manage_products","display_name":"Man
  age all products as admin","updated_at":"2016-11-01 09:29:36","created_at":"2016-11-01 09:29:36","id":8}, 1))



  [PDOException]
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '{"name":"edit_profile","display_name":"Edi
  t profile","updated_at":"2016-11-01 09:29:36","created_at":"2016-11-01 09:29:36","id":' for column 'permission_id'
  at row 1](url)

**Comment by schuesslerf** [comment]
I guess the id is the problem, so this part: `"id":' for column 'permission_id'`, but whats the problem?

**Comment by santigarcor** [comment]
Did you see the insert your code is trying to do?

```
insert into `permission_role` (`permission_id`, `role_id`) values ({"name":"edit_profile","display_n
  ame":"Edit profile","updated_at":"2016-11-01 09:29:36","created_at":"2016-11-01 09:29:36","id":1}, 1), ...
```

It doesn't make any sense.

**Comment by schuesslerf** [comment]
It's Laratrust that does it basically... Here is all code I use in the seeder:

```
<?php

use Illuminate\Database\Seeder;

use App\Permission;
use App\Role;


class LaratrustSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $editProfile        = Permission::create(['name' => 'edit_profile', 'display_name' => 'Edit profile']);
        $searchProducts     = Permission::create(['name' => 'search_products', 'display_name' => 'Search for products']);
        $orderProduct       = Permission::create(['name' => 'order_product', 'display_name' => 'Order a product']);
        $manageCustomOrders = Permission::create(['name' => 'manage_custom_orders', 'display_name' => 'Manage custom orders']);
        $manageProducts     = Permission::create(['name' => 'manage_products', 'display_name' => 'Manage products']);
        $manageOrders    = Permission::create(['name' => 'manage_orders', 'display_name' => 'Manage orders from customers']);
        $adminManageOrders = Permission::create(['name' => 'admin_manage_orders', 'display_name' => 'Manage all orders as admin']);
        $adminManageProducts = Permission::create(['name' => 'admin_manage_products', 'display_name' => 'Manage all products as admin']);

        $admin  = Role::create(['name' => 'admin', 'display_name' => 'Administrator']);
        $buyer  = Role::create(['name' => 'buyer', 'display_name' => 'Buyer']);
        $seller = Role::create(['name' => 'seller', 'display_name' => 'Seller']);

        $admin->permissions()->attach([$editProfile, $searchProducts, $adminManageOrders, $adminManageProducts]);
        $buyer->permissions()->attach([$editProfile, $searchProducts, $orderProduct, $manageCustomOrders]);
        $seller->permissions()->attach([$editProfile, $manageProducts, $manageOrders]);
    }
}
```

This generates the insert and all other things, where is the mistake then?

**Comment by santigarcor** [comment]
I'm going to test it out.

**Comment by schuesslerf** [comment]
Thanks

**Comment by santigarcor** [comment]
The problem is that when you do `attach` you can't pass an array of models, you can only pass an array of ids.

The only thing i did was add `->id` to every permission in the attach

**Comment by schuesslerf** [comment]
Like that?

      `  $admin->permissions()->attach([$editProfile->id(), $searchProducts->id(), $adminManageOrders->id(), $adminManageProducts->id()]);`

doesn't work as wel....

**Comment by schuesslerf** [comment]
Oh got it, wihout the ((), seems to work now. Thanks.

**Comment by santigarcor** [comment]
Ok, you're welcome

**Comment by underface** [comment]
hi.
any one can explain my how i can use this on the my website?

**Comment by bakumn** [comment]
hello 
i want new permmission updateothers-any or update-others-any. but not created. why help me please

`'permissions_map' => [
        'uo' => 'updateothers', //not create
        'do' => 'deleteothers', //not create
        'dw' => 'download', //created
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete',
    ]`

**Comment by chelohl11** [comment]
Hi, my problem is when I do execute php artisan migrate:fresh --seed, the table Users and role_user are empty. The other tables is ok.

**Comment by KKSzymanowski** [comment]
@chelohl11 Please open another issue if you believe there is a bug in Laratrust and provide some reproducible example.
