### ISSUE TITLE
/database/seeders/LaratrustSeeder.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mcandylab** [santigarcor/laratrust#461]
![image](https://user-images.githubusercontent.com/20170366/94235229-e46c8480-ff13-11ea-957b-45f84f5fab83.png)

I have php -v 7.4, also tried version 7.2, Laravel 7.24. I still get this error. Judging by the `MakeSeederCommand` file, the handler checks for the existence of the file, and if it does not exist, the file is created. What could be the problem?

I have custom path to models folder:
```php
 'user_models' => [
        'users' => \App\Models\User::class,
        'admins' => \App\Models\Admin::class,
    ],

```

**Comment by mcandylab** [comment]
Sorry, its my mistake. My seeders folder name: seeds...

**Comment by mcandylab** [comment]
In Laravel 7 default seeders folder: `seeds`. But Laratrust need `seeders` folder. 

this pool request has changed the name of the folder. 
https://github.com/santigarcor/laratrust/pull/453

it turns out that someone has the name of the folder `seeds`, someone `seeders`

**Maybe check for the existence of two folders?**

**Comment by mcandylab** [comment]
Again my mistake :smile:

If you have this problem, you can use seeders folder name `seeders`, but remove namespace in *Seeder.php files

**Comment by MOstafaMOhamedX** [comment]
do u find solution ?
