### ISSUE TITLE
Using team issues

### ISSUE THREAD

**Issue by liuyong888** [santigarcor/laratrust#468]
Hello bro,
    I am confused about the use of teams. 
    Do I need to add a "team_id" field in the users table because I want to know if a user belongs to which team.
    Please correct me if I misunderstand the teams function!

(https://user-images.githubusercontent.com/45752479/95750401-a91dd400-0ccf-11eb-8fdf-9a0bdcec8268.png)

**Comment by kirkfranklin-alameda** [comment]
[Roles Assignment & Removal](https://laratrust.santigarcor.me/docs/6.x/usage/teams.html#roles-assignment-removal) tells you how to associate a user with a role on a team. I believe this is stored in the role_user pivot table.

`$team = Team::where('name', 'my-awesome-team')->first();
$admin = Role::where('name', 'admin')->first();

$user->attachRole($admin, $team);`
