### ISSUE TITLE
Upgrade to 6.0 (Laravel upgrade from 7 to 8)

### ISSUE THREAD

**Issue by Aitzgorri** [santigarcor/laratrust#471]
Hello,
I upgraded my app from Laravel 7 to 8 and tried to upgrade Laratrust to 6.

When I run composer update I get following error:

_Problem 1
    - Root composer.json requires santigarcor/laratrust 6.0 -> satisfiable by santigarcor/laratrust[6.0.0].
    - santigarcor/laratrust 6.0.0 requires laravel/framework ~6.0|~7.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev, v7.0.0,
..., 7.x-dev] but it conflicts with your root composer.json require (^8.0)._

Based on the Laratrust versioning information, the version 6 should be aligned with Laravel 8.

Am I doing something wrong or is this a bug?

Thank you

**Comment by KKSzymanowski** [comment]
You should upgrade to Laratrust >= 6.2.0 because since this version Laravel 8 is supported. Laratrust 6.0.* and 6.1.* doesn't support Laravel 8.

**Comment by Aitzgorri** [comment]
Thank you!

> 
> 
> You should upgrade to Laratrust >= 6.2.0 because since this version Laravel 8 is supported. Laratrust 6.0.* and 6.1.* doesn't support Laravel 8.
