### ISSUE TITLE
Flash messages question

### ISSUE THREAD

**Issue by nabeelio** [santigarcor/laratrust#474]
Hi,

I'm using the Laracast flash messages, where the views look like this: https://github.com/laracasts/flash/blob/master/src/views/message.blade.php

I get errors using the Laratrust flash messages though, it seems like `$message` is just a string. Which flash() library is this compatible with? I'm a little confused by the different implementations between Livewire and Laracasts etc, how did you envision that was being used in a template?

Thanks!

**Comment by santigarcor** [comment]
@nabeelio Laratrust doesn't provide a flash message functionality. If you are [refering](https://github.com/santigarcor/laratrust/blob/master/config/laratrust.php#L187) to this, it's just the parameter that will be passed to the `abort` function in the middleware.

**Comment by nabeelio** [comment]
Ah got it, thanks, so I gotta track that down. Appreciate the reply!
