### ISSUE TITLE
Integrate Laratrust - Error with Laravel 8.12

### ISSUE THREAD

**Issue by Urbannet** [santigarcor/laratrust#481]
Hello
I try with Laravel 8.12 but i have this error
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - santigarcor/laratrust[5.2.8, ..., 5.2.x-dev] require laravel/framework ~5.6.0|~5.7.0|~5.8.0|~6.0|~7.0 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8.12).
    - santigarcor/laratrust[5.2.0, ..., 5.2.2] require laravel/framework ~5.6.0|~5.7.0|~5.8.0 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8.12).
    - santigarcor/laratrust[5.2.3, ..., 5.2.7] require laravel/framework ~5.6.0|~5.7.0|~5.8.0|~6.0 -> found laravel/framework[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8.12).
    - Root composer.json requires santigarcor/laratrust 5.2.* -> satisfiable by santigarcor/laratrust[5.2.0, ..., 5.2.x-dev].
Your help please.

**Comment by santigarcor** [comment]
What version of Laratrust are you trying to use? Because I just installed Laratrust 6.x on Larave 8.20

**Comment by Urbannet** [comment]
I used 5.2  . It s ok with 6.3
Thank you

**Comment by santigarcor** [comment]
It won't work with that version. Laratrust 5.2 only works with Larave 5.6.x - 5.8.x. Check [here](https://github.com/santigarcor/laratrust#version-compatibility) for the compatibility list.
