### ISSUE TITLE
Laratrust data table not seeds in Laravel 8

### ISSUE THREAD

**Issue by devhoussam** [santigarcor/laratrust#482]
I am using **Laravel 8** and **Laratrust 6.x** for the authentication part. but when I run **php artisan db:seed** command some of following tables `users, role_user, permission_user`  are not **seeds** with **data**. how could I fix this problem? My `DatabaseSeeder.php` file is as following 👍 

```
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();
       $this->call(LaratrustSeeder::class);
    }
}
```

**Comment by Meeshalk** [comment]
Is there anything in the logs, any errors?

**Comment by filippotoso** [comment]
This issue has not seen activity in the last year. I'm going to close it. If you still need help, open another issue.
