### ISSUE TITLE
get permission by role

### ISSUE THREAD

**Issue by massimodevitis** [santigarcor/laratrust#483]
hi,
i use the 6.x version and for get permission user i use: Auth::user()->isAbleTo('edit-blog');
For get permission by role which method i must to use?

in old laratrust was: Laratrust::hasRoleAndOwns('admin', 'edit-blog');

br
Max

**Comment by liuyong888** [comment]
Look this https://laratrust.santigarcor.me/docs/6.x/usage/roles-and-permissions.html#user-ability(url)

**Comment by massimodevitis** [comment]
good :)
