### ISSUE TITLE
SQLSTATE[HY000]: General error: 1005

### ISSUE THREAD

**Issue by callmesupercookie** [santigarcor/laratrust#484]
SQLSTATE[HY000]: General error: 1005 Can't create table `medi`.`team_user` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `team_user` add constraint `team_user_team_id_foreign` foreign key (`team_id`
) references `teams` (`id`))

- Laravel Version: 7
- Laratrust Version: 6.3

**Describe the bug**
While migrating the standart migration generated from laratrust it throws an error. 

**To Reproduce**
Migrate the generated migration from laratrust

**Comment by KKSzymanowski** [comment]
Check if the columns on both sides of the foreign key have the same type. Probably one is an unsigned integer and other is a big unsigned integer.

**Comment by callmesupercookie** [comment]
Thanks that makes sense!
