### ISSUE TITLE
isAbleTo return always true

### ISSUE THREAD

**Issue by massimodevitis** [santigarcor/laratrust#487]
- Laravel Version: 8.8.0
- Laratrust Version: 6.3

**Describe the bug**
I have not assigned any permissions to users, but only to roles.
but when I try to do:

Auth::user()->isAbleTo('create-post') or Auth::user()->hasPermission('create-post');
the result is always true;

any help?

br Max

**To Reproduce**

**Comment by KKSzymanowski** [comment]
Have you assigned roles to users?

**Comment by massimodevitis** [comment]
yes,
i have assigned roles to users

**Comment by KKSzymanowski** [comment]
If you have assigned a permission to some role and then the role to some user, the user has this permission through the role and `hasPermission()` will return true.

**Comment by massimodevitis** [comment]
ok,
thanks for the clarification

br
Max
