### ISSUE TITLE
Custom team column

### ISSUE THREAD

**Issue by micobarac** [santigarcor/laratrust#490]
I have a use case where I need to assign the `office/location` to the `team`. That means that I need to have an `officeId` column/foreign key in the `team` table and model. What is the proper way to add an `additional column/foreign key` to the `team` table/model?

**Comment by GregPeden** [comment]
I have modified the Team model to include a one-to-one polymorphic relationship called "context" then I bind the teams to their pertinent context. Every team has a host model responsible for it via the "context" relationship (and the inverse "team" from the host model).
