### ISSUE TITLE
is this library forked form Zizaco/entrust?

### ISSUE THREAD

**Issue by ahmadazimi** [santigarcor/laratrust#50]
Hi there, 

I have some massive projects which using https://github.com/Zizaco/entrust.
I wanna switch to **laratrust** now.
Can I migrate to laratrust from zizaco/entrust easily?

**Comment by KKSzymanowski** [comment]
It's not forked *per se*, but from my experience migrating from one to another shouldn't be a problem.

**Comment by erikwestlund** [comment]
Kuba,

It is forked.  It's as close to a drop-in replacement of Entrust as you can
get, and it's improving. In my experience I just had to remove Entrust from
composer.json, add laratrust, update my service providers, and change the
trait in the App\User model.  The rest of the API is compatible.

I'm pleased.


From the laratrust readme:

Note

This is a fork of Zizaco's original code <https://github.com/Zizaco/entrust>;
thanks go to him for getting this thing started! Please note that this fork
is not used on Zizaco's page at this time, nor is it maintained or
contributed to by him.

**Comment by KKSzymanowski** [comment]
> It is forked

I suppose you could say, it's forked. What I meant was, it isn't the classic git fork but rather a project which inherited the codebase of Entrust.
