### ISSUE TITLE
Laratrust class

### ISSUE THREAD

**Issue by shafiqruslan** [santigarcor/laratrust#501]
Hi, I want to use the shortcuts `Laratrust::hasRole('role-name');` but I don't know what should I import for the namespace?

**Comment by KKSzymanowski** [comment]
This is the class you're looking for:
https://github.com/santigarcor/laratrust/blob/master/src/Laratrust.php

so
```php
use Laratrust\Laratrust;
```

I'd like to recommend using an editor which suggests imports. If you don't wanna pay for PhpStorm you can achieve similar results in Sublime Text or Visual Studio Code using plugins.

**Comment by KKSzymanowski** [comment]
If you have completed this installation step:
> In the same config/app.php add the following to the aliases array:
> 
> `'Laratrust'   => Laratrust\LaratrustFacade::class,`

then you can do:
```php
use Laratrust;

// ...

Laratrust::hasRole('role-name');
```

If you haven't added the alias you would have to do:
```php
use Laratrust\LaratrustFacade;

// ...

LaratrustFacade::hasRole('role-name');
```

**Comment by shafiqruslan** [comment]
Hi just curious, I didn't see any installation step that said this:
```
In the same config/app.php add the following to the aliases array:

'Laratrust' => Laratrust\LaratrustFacade::class,
```

where you find it?

**Comment by KKSzymanowski** [comment]
I was looking at the [old docs for version 5.*](https://laratrust.readthedocs.io/en/5.0/installation.html). 

@santigarcor There is no mention of this alias in the new docs for 6.* Is this intentional?

**Comment by santigarcor** [comment]
@KKSzymanowski and @shafiqruslan I removed that from the docs because they are registered by default when using the package autodiscovery(not sure if that's the name).
