### ISSUE TITLE
laratrust Auth(hasRole)

### ISSUE THREAD

**Issue by moepic19** [santigarcor/laratrust#502]
![laratrust](https://user-images.githubusercontent.com/54062733/115950149-32655d00-a4e2-11eb-8910-1156fd3771b5.png)

Undefined method 'hasRole'.

can you help me withh that

**Comment by santigarcor** [comment]
If it's the linter, don't worry about it. But if you are getting a runtime error, maybe your user class is not using the `LaratrustUserTrait`

**Comment by moepic19** [comment]
thanks for the help
