### ISSUE TITLE
Laravel 8 multi auth - multiple user models

### ISSUE THREAD

**Issue by nicolastorgato** [santigarcor/laratrust#508]
Hi, 

let's say that I have 2 roles: User and Admin. The problem is that the User gotta have a lot more information/table fields, that the Admin doesn't have.
What if my USER has more or different information than the ADMIN? Normally there is only one table, both for user and admin.   
Is there a way to have a table for the simple users and another one for the admins, and still using laratrust?

Thanks!

**Comment by KKSzymanowski** [comment]
Generally there are several approaches to solving this problem:
1. Create two completely separate tables in the DB for users and for admins. In this case you can also create a database view for fetching all users and admins in one query.
2. Create one table for common fields and two more tables for type-specific fields (`users`, `user_details`, `admin_details`, for example).
3. Have one table for all users and admins. User-specific fields will be NULL in case of admins and admin-specific fields will be NULL for regular users. You'd have to differentiate users somehow - you can use a role for this or add a `type` field which would accept `user` or `admin` for example.

I personally like the last approach the most but if you'd like to have separate tables take a look at [Multiple User Models](https://laratrust.santigarcor.me/docs/6.x/usage/multiple-users.html) in the Laratrust docs.

**Comment by nicolastorgato** [comment]
First off, thank you for your answer! 

Considering the third possibility, what if multiple user-specific fields must be required? I mean, they cannot be NULL

Considering the first possibility, in order to be able to work with 2 tables, do I just have to specify the other admin model, like this:
```
    'user_models' => [
        'users' => \App\Models\User::class,
        'admins' => \App\Models\Admin::class,
    ],
```
or is there something else I have to do? How am I supposed to distinguish the two tables in the code?

**Comment by KKSzymanowski** [comment]
> Considering the third possibility, what if multiple user-specific fields must be required? I mean, they cannot be NULL

If you're using MySQL 8 you can implement `CHECK` constraints. Take a look here: https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=24850a13df8a02f87ae43fda0e4152d3
If you use some other database or earlier MySQL version you'd have to do this validation only in the application layer (eg in request validation).

> Considering the first possibility, in order to be able to work with 2 tables, do I just have to specify the other admin model, like this:
> ```
> 'user_models' => [
>     'users' => \App\Models\User::class,
>     'admins' => \App\Models\Admin::class,
> ],
> or is there something else I have to do? How am I supposed to distinguish the two tables in the code?

Your config looks ok but I haven't ever used this multi-model feature in Laratrust so I cannot give you any further guidance, sorry.
