### ISSUE TITLE
NotFoundHttpException even when access should be denied

### ISSUE THREAD

**Issue by lkreher** [santigarcor/laratrust#51]
I have a resource route, that represent a model, say customers, and access to all of the routes should be restricted to users that have a certain role. The route has the URI "customers/{customer}". As expected, access to existing customers is blocked by the role middleware. 

But when entering an invalid route parameter the application returns a NotFoundHttpException, indicating that the parameter is resolved before the middleware even checks if the user is allowed to access that information. This way even an unauthorized person can figure out which route parameters are valid, and can determine how many customers are registered. 

Also this prevents the standard 403 response from being sent out, since the NotFoundHttpException takes priority.

**Comment by santigarcor** [comment]
But there's no way to change that, that's the way Laravel works.

**Comment by KKSzymanowski** [comment]
Yes, the route parameters are resolved in the Router, before any middleware.

If you want to be sure that the user receives 403 response, you need to change the controller.
I suppose this is the current signature:
```
public function show(Customer $customer)
```
I would replace that with:
```
public function show($customerId)
{
    $customer = Customer::findOrFail($customerId);
    
    // 
}
This way you can be certain that the customer is retrieved only after passing all middleware.
If some middleware throws an exception, the controller method body will not be executed.

**Comment by lkreher** [comment]
@santigarcor @KKSzymanowski I see the problem and understand it, but:

The default auth middleware does it perfectly fine, whenever the page is viewed without being logged in it will redirect to the login, no matter whether the requested content exists or not. I'm using both middlewares in a Route::group, they are passed the exact same way, no reason why auth should be able to do it and laratrust can't. 

I'll have a look into the auth middleware to see how it is done later, maybe I can figure out what they're doing differently.

**Comment by KKSzymanowski** [comment]
> I'll have a look into the auth middleware to see how it is done later, maybe I can figure out what they're doing differently.

You can also trigger an exception at the beginning of a controller method to see the call stack and figure out the order of middleware. Maybe this is the reason of this behaviour.
You can do this with just saying `echo($someNonexistentVariable);`
Be sure though that the request passes all middleware, so you need to be authenticated and authorized.

**Comment by lkreher** [comment]
> You can also trigger an exception at the beginning of a controller method to see the call stack and figure out the order of middleware. Maybe this is the reason of this behaviour.
You can do this with just saying echo($someNonexistentVariable);
Be sure though that the request passes all middleware, so you need to be authenticated and authorized.

I know the auth middleware is called before the role middleware, because when I'm not logged in I get redirected to the login page, as performed by the auth middleware. Now I'm asking why the auth middleware is able to perform the redirect, while the role middleware fails to output the 403 error because the 404 takes priority.

The issue is indeed mitigated if I don't inject the Model, but still the question stands why auth middleware doesn't throw 404 exception.

**Comment by KKSzymanowski** [comment]
I meant, you should check if the SubsituteBindings middleware is executed before or after the Role middleware.
If *before*, you have your explanation and you should check if it's possible to execute it *after*.
Nevertheless, as Santiago said, it's more of a Laravel issue, so if you think this is a bug, you should post it to [Laravel/Framework#issues](https://github.com/laravel/framework/issues)
