### ISSUE TITLE
Changes made in database are not displayed on web

### ISSUE THREAD

**Issue by akashvaidya23** [santigarcor/laratrust#510]
Rather than deleting cache and cookies, the changes directly made in database tables are not displayed on web after executing the codes. Kindly help..

**Comment by filippotoso** [comment]
If you are talking about changes applied directly to roles, permission, teams, (etc.) tables they are cached for performance sake.

If you apply the changes using the Models (and their Laratrust traits), you should not encounter caching problems of sort.
