### ISSUE TITLE
[BUG] Logged user has admin role but the middleware role:admin dont work

### ISSUE THREAD

**Issue by Franziskeer** [santigarcor/laratrust#513]
- Laravel Version: 8.45.1
- Laratrust Version: 6.3.2

**Method hasRole (and middleware role) always return false**
I want some roles to get into a page with the role:admin middleware, but when i use it it fails. I tried to make the most basic example for checking the user role and the method hasRole returns false.

![Captura de pantalla 2021-06-18 a las 11 07 37](https://user-images.githubusercontent.com/32106656/122537006-6b730700-d025-11eb-9d7c-13a449eec24d.png)

![image](https://user-images.githubusercontent.com/32106656/122536944-5ac29100-d025-11eb-8f66-2b1a8c3dfe95.png)

As you can see, the user has the admin role but the method hasRole return false. In the image you can see that i use the Laratrust alias, but if i use the $user variable it return false too.

**To Reproduce**
I just seed my database with roles like so:
![Captura de pantalla 2021-06-18 a las 11 13 26](https://user-images.githubusercontent.com/32106656/122537820-3fa45100-d026-11eb-8be7-07fbca3135b8.png)

And my users:
![Captura de pantalla 2021-06-18 a las 11 14 06](https://user-images.githubusercontent.com/32106656/122537900-5480e480-d026-11eb-8e76-4eaf0dc8b512.png)

Then i try to use the middleware on the dashboard route but it redirects me to default page (i change the middleware.handling from abort to redirect for this):
![Captura de pantalla 2021-06-18 a las 11 16 03](https://user-images.githubusercontent.com/32106656/122538219-9ca00700-d026-11eb-987c-b791dc9db330.png)

**Edit:**
I'm not sure but with another roles package (spatie/permissions) i had the same trouble, the hasRole method was not working. Maybe it has relation with the Laravel 8 models path refactor (In laravel 7 was App\User but in laravel 8 is App\Models\User).

**Comment by Sogl** [comment]
Have you found a solution?

**Comment by Franziskeer** [comment]
Not yet, but i found a trick to make my requirement work.
There is another middleware called ability.

![image](https://user-images.githubusercontent.com/32106656/125684855-5352d0fa-3241-498b-935e-ba21c6500120.png)

The trick is to not pass a parameter for the permission like so:
![image](https://user-images.githubusercontent.com/32106656/125685087-a51c4670-5274-45b2-81ae-ad1c0d3654fe.png)
This way it checks all the parameters as an or logical operation. You can still pass the required_all adding another comma and the third parameter to make it an and logical operation.

I don't try to use it as a method like in the comment of the first image, but for the moment this work for my route. If this is a bug i hope they fix it soon. Tomorrow i will try it again because of the ghost bug on https://github.com/santigarcor/laratrust/issues/519#issuecomment-879917840.

**Comment by Sogl** [comment]
For my problem I found a solution: https://github.com/santigarcor/laratrust/issues/521#issuecomment-880253773

**Comment by Franziskeer** [comment]
As https://github.com/santigarcor/laratrust/issues/519#issuecomment-879917840 mentioned, now role middleware and hasRole method work as intended. I don't know why this happens nor what was the fix, the only thing i recommend you is to execute cache:clear optimize:clear and config:clear artisan commands or just keep working on your project until it fix it.
