### ISSUE TITLE
Documentation site is not working ! It's Offline ! Please check !

### ISSUE THREAD

**Issue by Ticket-Master** [santigarcor/laratrust#515]
Documentation site is not working ! It's Offline ! Please check ! 

Error shows like these in chrome when i try to open documentation site Link : https://laratrust.santigarcor.me/docs/6.x/

This site can’t be reachedCheck if there is a typo in laratrust.santigarcor.me.
If spelling is correct, try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by santigarcor** [comment]
I looks like it's working now
