### ISSUE TITLE
How to grant 'superadministrator' role all permissions without assign any permissions to it

### ISSUE THREAD

**Issue by o4itea** [santigarcor/laratrust#518]
How make `superadministrator` role get respond `true` to all permissions, without needing to assign all those permissions to a role.
`@ability` is a good directive but I don't want to use it everywhere with `superadministrator`

I found a way works with `@can` directive witch is to add the follow check in AuthServiceProvider 
`Gate::before( fn($user, $ability) => $user->hasRole('superadministrator') ? true : null );`

But it didn't works with laratrust directives and methods.

So, Is there way grant 'superadministrator' role all permissions without assign any permissions to it.

**Comment by santigarcor** [comment]
There's no way with the current code to achieve that. I would really recommend you to add all the permissions to the superadmin so you rely only on permissions, not on roles
