### ISSUE TITLE
@role & hasRole returning wrong boolean value

### ISSUE THREAD

**Issue by SupianIDz** [santigarcor/laratrust#519]
- Laravel Version: 8.49.2
- Laratrust Version: 6.3

**Describe the bug**
As seen in the attachment, user id "13" with role "sysadmin" but returns false.

**To Reproduce**

![anjing](https://user-images.githubusercontent.com/37969970/125319980-d89c6280-e36d-11eb-8613-71ec5ab12581.png)

**Comment by SupianIDz** [comment]
JingKonTod

**Comment by Sogl** [comment]
Have you found a solution?

**Comment by SupianIDz** [comment]
> Have you found a solution?

After the open issue a few days ago, I didn't touch the project again until you asked this then I rechecked as in the attached image.

This is very strange, sometimes it returns true, but sometimes it returns false.

Ghost Bug

![w](https://user-images.githubusercontent.com/37969970/125635033-f075111c-787c-4f6c-b7de-79fdb1e03a38.png)

**Comment by Sogl** [comment]
For my problem I found a solution: https://github.com/santigarcor/laratrust/issues/521#issuecomment-880253773

**Comment by SupianIDz** [comment]
> For my problem I found a solution: [#521 (comment)](https://github.com/santigarcor/laratrust/issues/521#issuecomment-880253773)

However, my model in this case is in accordance with the configuration.

![a](https://user-images.githubusercontent.com/37969970/125765263-9460936c-d0ae-4e24-83e0-7fb8eb9b4c81.png)
![b](https://user-images.githubusercontent.com/37969970/125765483-68b6318d-debe-4733-afbc-72403ebc352d.png)

**Comment by haleyngonadi** [comment]
I'm also having the same issue. Did you find a working solution?

**Comment by SupianIDz** [comment]
> I'm also having the same issue. Did you find a working solution?

Still not, sometimes this bug appears, but sometimes it works normally.

cc : @santigarcor

**Comment by drdan18** [comment]
Same issue here.  That's too bad.

**Comment by santigarcor** [comment]
Do we know if maybe is an issue with the cache?

**Comment by santigarcor** [comment]
@SupianIDz have you tried disabling the cache?

**Comment by SupianIDz** [comment]
@santigarcor  I'm sure it's because of the cache, I'll open the PR to turn off the cache in non-production mode, to avoid headaches during development.
