### ISSUE TITLE
permissions with livewire 2

### ISSUE THREAD

**Issue by yaseralshikh** [santigarcor/laratrust#525]
hello friends ..

Thank you for this wonderful library, I use it in all my projects, but with laravel8 with livewire2 ; it is good with Rules :

```
<div class="mt-4">
    <x-label for="role_id" value="{{ __('site.role') }}" />
    <select name="role_id" id="role_id" wire:model="role_id" class="block w-full mt-1 border-gray-300 rounded-md shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50">
        <option hidden>@lang('site.role_type')</option>
        @foreach ($roles as $role)
            <option value="{{ $role->id }}">{{ $role->name }}</option>
        @endforeach
    </select>
    @error('role_id')<span class="text-sm font-extrabold text-red-600">{{ $message }}</span>@enderror
</div>
```

but I don't know how to use it with permissions .

```
@foreach ($permissions as $permission)
    <x-jet-checkbox type="checkbox" name="permissions[]" wire:model="permissions" value="{{ $permission->id }}"  class="w-5 h-5 mr-3 text-gray-600 form-checkbox"/>
    <label class="inline-flex items-center mt-3">{{ $permission->name }}</label>
@endforeach
```

I got this error :

`Attempt to read property "id" on array (View: C:\xampp\htdocs\courses\laravel\laravel8_laratrust2\resources\views\livewire\backend\user.blade.php)`

**Comment by webtux** [comment]
<select name="role_id" id="role_id" wire:model="PERMISSIONS">

**Comment by santigarcor** [comment]
I haven't used livewire but seems like you are using the wrong model `wire:model="permissions"` there permissions is an array. or it looks like your $permission variable is an array instead of an object.
