### ISSUE TITLE
¿Laravel 9 support?

### ISSUE THREAD

**Issue by juanadamuzsimj** [santigarcor/laratrust#544]
- Laravel Version: 9
- Laratrust Version: 6.4.0

Not possible to  composer require / update due to laravel 9 not listed in supported versions

**Comment by omalizadeh** [comment]
#542

**Comment by santigarcor** [comment]
@juanadamuzsimj I'll try to find a space later today to merge it and leave it at least working on dev before doing an actual release

**Comment by Eduardowm** [comment]
Any update?

**Comment by santigarcor** [comment]
@Eduardowm , @omalizadeh and @juanadamuzsimj could you please test it from dev?

**Comment by omalizadeh** [comment]
I tested master branch on one of my projects, everything seems normal and working (i don't use team feature btw). thanks.

@santigarcor

**Comment by businessdotkom2020** [comment]
Any update?

**Comment by santigarcor** [comment]
@businessdotkom2020 you can test it with devmaster, i haven't had the time for adding some things before creating the release

**Comment by juanadamuzsimj** [comment]
> @Eduardowm , @omalizadeh and @juanadamuzsimj could you please test it from master?

Everything is working ok!

**Comment by juanadamuzsimj** [comment]
> 
You can merge 👍

**Comment by santigarcor** [comment]
I'm going to reopen this one until I create the release

**Comment by msulaimanmisri** [comment]
Tested and everything is fine using the master branch on my Laravel 9 application. Thanks, @santigarcor!
