### ISSUE TITLE
Short syntax route filter does not working in Laravel 5.3

### ISSUE THREAD

**Issue by aminkhannsu** [santigarcor/laratrust#55]
If i use following short syntax
`Laratrust::routeNeedsRole('/loginsuccess', 'customer', Redirect::to('/customer'));
Laratrust::routeNeedsRole('/loginsuccess', 'admin', Redirect::to('/admin'))`

laravel shows me error

`BadMethodCallException in Macroable.php line 74:
Method filter does not exist.`

any suggestion?

**Comment by santigarcor** [comment]
I have to check that filter method, but in the mean time why don't you use middleware?

**Comment by santigarcor** [comment]
@aminkhannsu I think the filters were removed with the introduction of middleware

**Comment by santigarcor** [comment]
Those methods only work in `<5.1` versions
