### ISSUE TITLE
Sub Domain Route

### ISSUE THREAD

**Issue by ahr1384** [santigarcor/laratrust#556]
Hello
The package is very good
There is only one problem
I want to move admin panel routes to my subdomain in Laravel but I can not
It would be much better if it was like the auth section (Auth :: routes) adding routes

**Comment by ahr1384** [comment]
And Can Add tags and categorize permissions

**Comment by ahr1384** [comment]
@santigarcor

**Comment by filippotoso** [comment]
The ability to put Laratrust panel in a subdomain will be added within the end of the week (I need to write some tests before).

About the ability to add tags and categorize permissions, you can do it easily with additional models as a permission is a standard Model.
