### ISSUE TITLE
Enhorabuena Santi, has mejorado Entrust de manera significativa

### ISSUE THREAD

**Issue by jgrandar** [santigarcor/laratrust#56]
Esta rama proporciona pequeñas mejoras pero en mucha cantidad, y lo mejor sin duda es la documentación, ojalá todos los proyectos estuviesen documentados así. Solo falta que salga adelante lo de los grupos, que es lo único que me has dejado hacer a mi en mi proyecto :laughing:

**Comment by santigarcor** [comment]
Gracias @jgrandar, en el momento puedes usar un RC de la versión de los grupos. No la he liberado, porque estoy revisando un PR con el tema de control de acceso basado directamente en permisos.

Acá (http://laratrust.readthedocs.io/en/master/index.html) puedes ver las instrucciones para usar dicha versión.
