### ISSUE TITLE
Seeder Roles & Permissions Descriptions

### ISSUE THREAD

**Issue by dmhall0** [santigarcor/laratrust#567]
First, amazing product.  Absolutely love it!
Second, let me apologize if this is not the right place for this type of request...

I am using latest version of both Laravel and Laratrust.

I want to customize the descriptions for both the roles and permissions; but I see in the LaratrustSeeder file these db table fields are just populated with the display_name of each.  How can I change this in the LaratrustSeeder file and/or config/laratrust_seeder file?

Thanks for your help!

**Comment by filippotoso** [comment]
Just publish the assets:

https://laratrust.santigarcor.me/docs/7.x/installation.html

Then make the seeder:

https://laratrust.santigarcor.me/docs/7.x/usage/seeder.html#seeder-configuration-file

And then customize the seeder as you need.
