### ISSUE TITLE
Wrong phpdoc param type for function hasPermission()

### ISSUE THREAD

**Issue by lucasjose501** [santigarcor/laratrust#568]
I'm using Larastan (PHP Stan) to scan the code for bugs and typos. The function `hasPermission($permission, $team = null, $requireAll = false)` accepts int in the $team variable handled by the helper 'getIdFor' but the phpdoc does not mention it and reports as error on phpstan.

Error: `Parameter #2 $team of method App\Models\User::hasPermission() expects bool|string|null, int given.`

The code is working, it's just a false positive report.

https://github.com/santigarcor/laratrust/blob/8a18c70bb1ced09baed361b68c432b0bedb74f16/src/Traits/LaratrustUserTrait.php#L227

**Comment by filippotoso** [comment]
Will be fixed in the next release.
