### ISSUE TITLE
User model relations in cache

### ISSUE THREAD

**Issue by stevevg** [santigarcor/laratrust#57]
Hello,
I set up caching with redis, and I was looking at what happens during my application life-cycle using `redis-cli monitor`.
When I login into my application, this command is run
`"SETEX" "laravel:laratrust_roles_for_user_78" "3600" "O:39 [...]`
which saves into cache a huge amont of data (i.e. my user with all its relations, that is really a lot of stuff).

Is there a way to stop laratrust doing so? I mean, I suppose that we are only interested in user's role, not all the relations that the user brings with himself...

If this can help, the same issue happened with entrust (I just switched to laratrust yesterday).

**Comment by santigarcor** [comment]
It's weird because the line that brings the user's role caches the roles relationship:

```php
$cacheKey = 'laratrust_roles_for_user_' . $this->getKey();

return Cache::remember($cacheKey, Config::get('cache.ttl', 60), function () {
    return $this->roles()->get();
});
```

**Comment by stevevg** [comment]
In fact, that seemed weird to me too, I saw that code...
