### ISSUE TITLE
Hardcoding roles and permissions

### ISSUE THREAD

**Issue by binaryfire** [santigarcor/laratrust#573]
Hi all

I'm dealing with a multi-db multi-tenant app. Roles and permissions are the same for all tenants. Each tenant's admin will only be able to assign one or more preset roles to users.

It's not really practical to manage things via the database- re-seeding to 1000s of dbs each time I make a change will be a headache.

Is there any way to hardcode roles and permissions and still use all the other features of the package?

Thanks!

**Comment by santigarcor** [comment]
Maybe if you use [Caleb's package](https://github.com/calebporzio/sushi) that adds the inline DB drive, and override the permission model, but i'm not 100% sure it will work out of the box.
