### ISSUE TITLE
Too many same queries execute

### ISSUE THREAD

**Issue by msulaimanmisri** [santigarcor/laratrust#574]
- Laravel Version: 9.36
- Laratrust Version: 7.1

**Describe the bug**
For every page I've visited, the Laratrust query executes and duplicates the data. I'm trying to fix it by myself but failed. The same msg is: 

````select `roles`.*, `role_user`.`user_id` as `pivot_user_id`, `role_user`.`role_id` as `pivot_role_id`, `role_user`.`user_type` as `pivot_user_type` from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = 6 and `role_user`.`user_type` = 'App\Models\User'````

**To Reproduce**
I've checked in my other Laravel application using Laravel 8 and Laratrust version ^6, and this problem does not appear.

Can you confirm on your side that it only happens on Laravel 9 and Laratrust version 7.1 @santigarcor ?

Here the image:

![image](https://user-images.githubusercontent.com/47172118/196484047-f9a13200-8906-4c12-96e5-186c6bf5c126.png)

**Comment by KKSzymanowski** [comment]
One quick fix would be to enable the laratrust cache from the .env file:
```bash
LARATRUST_ENABLE_CACHE=true
```

I believe this would cache this user's roles and you should see only one query.

**Comment by msulaimanmisri** [comment]
Very true and thanks a lot @KKSzymanowski for helping this out! I never think it's the cache in the first place.

**Comment by KKSzymanowski** [comment]
I wouldn't personally enable the cache for local development because it will cause you some issues if you for example directly assign the roles or permissions in the database. Just make sure to enable the cache in production, it can have significant impact on performance

**Comment by msulaimanmisri** [comment]
Very true @KKSzymanowski . I also not intend to active it when production. Just trying to figure out why is that happen. 

Thanks for the suggestion though.
