### ISSUE TITLE
Laratrust Admin Panel restrict routes access

### ISSUE THREAD

**Issue by davemin** [santigarcor/laratrust#576]
Hi , i need to restrict access to admin panel routes only at admin role, but the routes publishing is missing.

How can do that?

thx

**Comment by filippotoso** [comment]
You can disable the routes registration using the the `laratrust.panel.register` configuration option.

Then, in your own web routes file, register the routes with the the needed restrictions.

**Comment by jrwingate** [comment]
Can you give an example?  What controller do we point the route to in the web routes file?

**Comment by filippotoso** [comment]
Just read the source code:

https://github.com/santigarcor/laratrust/blob/master/routes/web.php

**Comment by santigarcor** [comment]
In the docs you can adds the middlewares you wan to check, you can use the role middleware to restrict the acccess
