### ISSUE TITLE
Routs Never Working Under Middlewares 

### ISSUE THREAD

**Issue by Ali-Raza-Tawary** [santigarcor/laratrust#577]
When i Try to Implements Middleware of admin Panel package for setting permissions Routs even they are not defined anywhere so i defined new routs and applied middlewares and it never works gives errors and with out middlewares and restriction admin panel works fine os what the benifit of this package even i can,t retirict users on routs of admin panel .. aaaa its sucks whole day i spend to fined where are default routs and there middlewares deffined but not fined any thing ..

**Comment by filippotoso** [comment]
The panel routes are defined in the package sources:

https://github.com/santigarcor/laratrust/blob/master/routes/web.php

And they are registred in the service provider:

https://github.com/santigarcor/laratrust/blob/master/src/LaratrustServiceProvider.php#L99
