### ISSUE TITLE
CSS compability

### ISSUE THREAD

**Issue by ArturoAtencio** [santigarcor/laratrust#578]
Hi, just installed the package, works just fine, until I get to the admin panel. Its css seems not compatible with my project.

Im runnign a very old boostrap version. Is there a way for me to set the css file to an old bootstrapt v? 

Thank you

**Comment by filippotoso** [comment]
The admin panel uses tailwind.

You can try to make them work together but [it's not reccomended](https://www.geeksforgeeks.org/how-to-use-both-tailwind-css-and-bootstrap-4-at-the-same-time/).
