### ISSUE TITLE
I can't install  santigarcor/laratrust for Laravel 10

### ISSUE THREAD

**Issue by ayadi1** [santigarcor/laratrust#583]
- Laravel Version: 10
- Laratrust Version: latest

**Describe the bug**
I can't install  santigarcor/laratrust for Laravel 10

** error message **
 Problem 1
    - Root composer.json requires laravel/framework ^9.0, found laravel/framework[v9.0.0, ..., v9.52.0] but the package is fixed to v10.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
  Problem 2
    - Root composer.json requires santigarcor/laratrust ^7.1 -> satisfiable by santigarcor/laratrust[7.1.0].
    - santigarcor/laratrust 7.1.0 requires laravel/framework ~6.0|~7.0|~8.0|^9.0 -> found laravel/framework[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but the package is fixed to v10.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require santigarcor/laratrust:*" to figure out if any version is installable, or "composer require santigarcor/laratrust:^2.1" if you know which you need.

**Comment by lucasjose501** [comment]
I think it will be easier to fork and upgrade the package to laravel 10, because I think this package is abandoned.

**Comment by KKSzymanowski** [comment]
I published a new 7.2.0 version with Laravel 10 compatibility. Can you check if everything works well for you?

**Comment by ayadi1** [comment]
the package was installed successfully with new version thanks
