### ISSUE TITLE
[DISCUSSION] This project's future

### ISSUE THREAD

**Issue by websitevirtuoso** [santigarcor/laratrust#584]
**Why this issue is here**
We are talking about this project not being maintained anymore. Right now we have 15 PR, in which fixes some small bugs and adds some feature.

**Why it should be forked by the community**
@santigarcor made a great job and I'm grateful for him creating this repo and making it better since the start. This project belongs to him and there is no one who deserves more credits than him. The community should fork it and keep it active;

Accessing Fawmi's [profile](https://github.com/fawmi) you will find that he is inactive since March/2022. The coincidence is that it was when he updated this repo for the last time;

**This repo is important and has a great potential;**

**Who should fork it**
IMO, anyone who have the motivation, the responsability and wants to make it better. If you want to do it, please remember that this project belongs to [santigarcor](https://github.com/santigarcor) and the community.

**Why I didn't forked it**
TBH I would do it right now, but I believe all the community has a voice, so I want your opinion. Also, I would need help to keep the project maintained.

**Comment by lucasjose501** [comment]
I could help with some fixes. I'm using this project and know some things that could be improved, but I don't want to take the responsibility to "own" and maintain it.

You have my support @websitevirtuoso

**Comment by filippotoso** [comment]
I contacted @santigarcor to know if he would like to add me as a maintainer. Around a year ago I asked Marcel Pociot and became a maintainer of his Botman packages. I use them in multiple projects and needed to fix some issues and keep them up to date with the latest versions of Laravel. 

The same situation applies to Laratrust.

I hope he'll answer, and we can all work toward improving Laratrust. Otherwise, we'll discuss how to proceed with the fork and handle the future developments.

**Comment by santigarcor** [comment]
Hey guys, sorry I haven't checked on the repo lately. I really want to help the community and not to abandon the project. I haven't had the time to actively work on it, so I'm going to check @filippotoso request.

**Comment by santigarcor** [comment]
@websitevirtuoso before anyone embarks in the forking path, i would like to check what @filippotoso proposed

**Comment by santigarcor** [comment]
I just added filippo as a collaborator, let's see how things work out lile this.

Closing this for now

**Comment by websitevirtuoso** [comment]
great.
@filippotoso let us know and we all can work on this together.
I can take few PR to check, I also think that @lucasjose501 we help us as well

**Comment by filippotoso** [comment]
Thanks for the support @websitevirtuoso and @lucasjose501!

I did some cleaning up. Another couple of days and we can start talking about improvements and evolutions.
When you are ready, write down your ideas and open an issue so we can start working on them.

**Comment by santigarcor** [comment]
@websitevirtuoso I opened a huge PR in case you want to help reviewing with it.

**Comment by websitevirtuoso** [comment]
I didn't test it but checked the PR. Looks great. I have only 1 question. Why do we need to break compatibility with the current API?

**Comment by santigarcor** [comment]
@websitevirtuoso I find it too technical not like the Laravel methods that are like talking with a non-technical person.

Obviously I'm open to leave them and mark them as deprecated.

**Comment by websitevirtuoso** [comment]
No I think we don't need to mark them as deprecated. If you think that breaking changes required then let's wait others opinions. Thanks for great PR
