### ISSUE TITLE
Completely remove the owns feature 

### ISSUE THREAD

**Issue by santigarcor** [santigarcor/laratrust#595]
Thw ownership feature should be removed from the package since i extracted it to its own package and it doesn't have to do anything with roles and permissions.

**Comment by filippotoso** [comment]
We can add it to the breaking changes list of 8.x

**Comment by Tofandel** [comment]
Except the `santigacor/laravel-ownable` package has not been updated in 3 years and is not compatible with laravel 9 and 10

**Comment by santigarcor** [comment]
@Tofandel You're more than welcome to help with updating it to make it compatible with Laravel 9 and 10

**Comment by GregPeden** [comment]
> @Tofandel You're more than welcome to help with updating it to make it compatible with Laravel 9 and 10

@santigarcor 
https://github.com/santigarcor/laravel-ownable/pull/2
