### ISSUE TITLE
Postgres Error

### ISSUE THREAD

**Issue by Romchik** [santigarcor/laratrust#60]
I think, Laracast should be compartible with Postgres, because Laravel is compartible.

But I have this error:
```
[Illuminate\Database\QueryException]
SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "foreign_key_checks" (SQL: SET FOREIGN_KEY_CHECKS = 0)

[PDOException]
SQLSTATE[42704]: Undefined object: 7 ERROR:  unrecognized configuration parameter "foreign_key_checks"
```

Reason:
src/views/generators/seeder.blade.php

```php
    /**
     * Truncates all the laratrust tables and the users table
     * @return  void
     */
    public function truncateLaratrustTables()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('{{ config('laratrust.permission_role_table') }}')->truncate();
        DB::table('{{ config('laratrust.role_user_table') }}')->truncate();
        \{{ $user }}::truncate();
        \{{ $role }}::truncate();
        \{{ $permission }}::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
```

**Comment by KKSzymanowski** [comment]
Here's a comment by joelennon on [this](https://gist.github.com/isimmons/8202227) gist.
> to get this to work in Postgres you'll need to do something like the following:
> ```
> DB::statement("TRUNCATE TABLE posts");
> DB::statement("TRUNCATE TABLE users CASCADE");
> ```
> Make sure you truncate the table with the foreign key first, and then use TRUNCATE TABLE ... CASCADE on the table it references.

Maybe we should do something similar.

**Comment by santigarcor** [comment]
@KKSzymanowski is right, but i should fix that and use the code according to the database configuration
