### ISSUE TITLE
How do i fix this ? i am using laravel 8 with santigarcor/laratrust": "^6.0

### ISSUE THREAD

**Issue by wankimmy** [santigarcor/laratrust#613]
![image](https://user-images.githubusercontent.com/34327646/224155531-60f33b50-203e-4afb-880d-9fa97d3e7f87.png)

![image](https://user-images.githubusercontent.com/34327646/224155586-9f30c3ea-b21c-44c6-9fb6-4a3feb599a6e.png)

**Comment by wankimmy** [comment]
@santigarcor please need your help, i was upgrading for laravel 6 to 8

**Comment by filippotoso** [comment]
Please read the upgrade guide:

https://laratrust.santigarcor.me/docs/6.x/upgrade.html

> If you use the can method you MUST change it to isAbleTo. We removed the can method in order to support Laravel policies and gates out of the box.

In your case, create a method named `laratrustCan()` and call the `isAbleTo()` method from that.

**Comment by wankimmy** [comment]
> Please read the upgrade guide:
> 
> https://laratrust.santigarcor.me/docs/6.x/upgrade.html
> 
> > If you use the can method you MUST change it to isAbleTo. We removed the can method in order to support Laravel policies and gates out of the box.
> 
> In your case, create a method named `laratrustCan()` and call the `isAbleTo()` method from that.

can u provide a source code for this ? reate a method named laratrustCan() and call the isAbleTo()

**Comment by wankimmy** [comment]
> Please read the upgrade guide:
> 
> https://laratrust.santigarcor.me/docs/6.x/upgrade.html
> 
> > If you use the can method you MUST change it to isAbleTo. We removed the can method in order to support Laravel policies and gates out of the box.
> 
> In your case, create a method named `laratrustCan()` and call the `isAbleTo()` method from that.

can u provide a source code for this ? reate a method named laratrustCan() and call the isAbleTo()

**Comment by santigarcor** [comment]
You just have to replace all the laratrustCan method calls to isAbleTo as the upgrade guide says.

**Comment by wankimmy** [comment]
ok the error is resolved, but my $user->hasRole(['superadmin', 'hq_operation_manager']) not able to work

![image](https://user-images.githubusercontent.com/34327646/224168529-68e45f36-f44f-4893-911f-be2f0d1df97e.png)


![image](https://user-images.githubusercontent.com/34327646/224168437-82aa8c86-c968-4226-a257-74a1688b7b4b.png)

![image](https://user-images.githubusercontent.com/34327646/224168476-c3424337-7d1c-4eeb-ac08-007f6371ff75.png)

**Comment by wankimmy** [comment]
ok the error is resolved, but my $user->hasRole(['superadmin', 'hq_operation_manager']) not able to work

![image](https://user-images.githubusercontent.com/34327646/224168529-68e45f36-f44f-4893-911f-be2f0d1df97e.png)


![image](https://user-images.githubusercontent.com/34327646/224168437-82aa8c86-c968-4226-a257-74a1688b7b4b.png)

![image](https://user-images.githubusercontent.com/34327646/224168476-c3424337-7d1c-4eeb-ac08-007f6371ff75.png)

**Comment by wankimmy** [comment]
![image](https://user-images.githubusercontent.com/34327646/224169383-133df6f2-07d2-4909-a086-23d6aac0aefb.png)
