### ISSUE TITLE
 How can I disable the pagination feature?

### ISSUE THREAD

**Issue by bhdrnzl** [santigarcor/laratrust#617]
How can I disable the pagination feature?

How can I disable the pagination feature? I tried inheriting the controller file "Santigarcor\Laratrust\Src\Http\Controllers\PermissionsController":

Route:
```
use App\Http\Controllers\Laratrust\PermissionsController;

Route::get('/admin/kullanici-yonetimi/roller-ve-izinler/permissions', [PermissionsController::class, 'index'])->name('custom.permissions.index');
```
```
<?php

namespace App\Http\Controllers\Laratrust;

use Santigarcor\Laratrust\Src\Http\Controllers\PermissionsController as LaratrustPermissionsController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class PermissionsController extends LaratrustPermissionsController
{
    protected $permissionModel;

    public function __construct()
    {
        $this->permissionModel = Config::get('laratrust.models.permission');
    }

    public function index(Request $request)
    {
        $permissions = $this->permissionModel->get();
        
        return View::make('laratrust::panel.permissions.index', [
            'permissions' => $permissions,
        ]);
    }
}
```

`Class "Santigarcor\Laratrust\Src\Http\Controllers\PermissionsController" not found`

how do i do this?

**Comment by filippotoso** [comment]
The esiest solution is to override the 


The full classname is `Laratrust\Http\Controllers\PermissionsController`

https://github.com/santigarcor/laratrust/blob/7.x/src/Http/Controllers/PermissionsController.php

Then I suggest you disable the panel registration (laratrust.panel.register config) and reregister manually your own routes:

https://github.com/santigarcor/laratrust/blob/81206ca3aab9bcbd4bed9b2c0b93158c8c1fb568/src/LaratrustServiceProvider.php#L99
https://github.com/santigarcor/laratrust/blob/81206ca3aab9bcbd4bed9b2c0b93158c8c1fb568/routes/web.php
