### ISSUE TITLE
@permission('permission'): Call to undefined method Laratrust\Laratrust::isAbleTo()

### ISSUE THREAD

**Issue by rollercontainer** [santigarcor/laratrust#619]
Laravel 10, upgraded from Laratrust 7.2 to 8.0.

Blade Syntax @permission('permission') throws error:
Call to undefined method Laratrust\Laratrust::isAbleTo()

Syntax and function call are described in the docs:
https://laratrust.santigarcor.me/docs/8.x/usage/blade-templates.html

**Comment by santigarcor** [comment]
Fixed by #618

**Comment by santigarcor** [comment]
@rollercontainer please run `composer update` the fix should be up right now

**Comment by rollercontainer** [comment]
Thanks a lot! Will try tomorrow morning.
