### ISSUE TITLE
Small, possible improvment

### ISSUE THREAD

**Issue by rollercontainer** [santigarcor/laratrust#620]
in your new config, there is a query if the app is in production:

https://github.com/santigarcor/laratrust/blob/8.x/config/laratrust.php#L75

you may use: app()->isProduction()

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Application.php#L671

**Comment by santigarcor** [comment]
Since it's a configuration file we should only use the `env()` function. The framework isn't probably loaded yet.
