### ISSUE TITLE
Call to undefined method App\Models\User::addRole()

### ISSUE THREAD

**Issue by kayz9119** [santigarcor/laratrust#621]
I'm getting this error and I can't find the solution, is there anyone can help me?

**Comment by santigarcor** [comment]
How did you configure the user?

**Comment by PardisZaryab** [comment]
Hello,
I'm getting the same error after creating user.
here is the error code | Call to undefined method App\Models\User::attachRole()
I went through the documentation but I did not understand the Step4.
I used to work with Laratrust before it was working but it doesn't work recently.
Thank you and appreciate your help
