### ISSUE TITLE
https://laratrust.santigarcor.me/ site down.

### ISSUE THREAD

**Issue by corbin1988** [santigarcor/laratrust#622]
Hey there, I was just trying to work with your package, but noticed that the site is down. Thanks

**Comment by santigarcor** [comment]
I moved the domain to another registrar, that's why it's down. Let me try to fix it

**Comment by santigarcor** [comment]
@corbin1988 could you please try again?

**Comment by santigarcor** [comment]
@filippotoso could you please try accessing the docs site?

**Comment by filippotoso** [comment]
I can access it.

**Comment by corbin1988** [comment]
It works for me now. Thank you!
