### ISSUE TITLE
New Admin Panel

### ISSUE THREAD

**Issue by santigarcor** [santigarcor/laratrust#623]
If we manage to get to my [monthly goal](https://github.com/sponsors/santigarcor), during that month/time I will work on rebuilding the admin panel with Vue supporting the teams feature and even maybe add a JS package to use with this package.

**Comment by mezoo-adel** [comment]
hi, how are you?
I want to ask for a something, i'm not sure if it's an issue, about panel's middleware. 
the panel's middleware by default is 'web' and it's accessible by anyone. Also, we can't use auth because "auth redirects to /home" and I can't use ['role:admin'] because it aborts that "User does not have any of the necessary access rights." 
and when I used a custom middleware I found that $request->all() is null.
May I be missing something about assigning laratrust middlewares or what should I search for??
thanks in advance.

`'panel' => [
        /*
        |--------------------------------------------------------------------------
        | Laratrust Panel Register
        |--------------------------------------------------------------------------
        |
        | This manages if routes used for the admin panel should be registered.
        | Turn this value to false if you don't want to use Laratrust admin panel
        |
        */
        'register' => true,

        /*
        |--------------------------------------------------------------------------
        | Laratrust Panel Domain
        |--------------------------------------------------------------------------
        |
        | This is the Domain Laratrust panel for roles and permissions
        | will be accessible from.
        |
        */
        'domain' => env('LARATRUST_PANEL_DOMAIN'),

        /*
        |--------------------------------------------------------------------------
        | Laratrust Panel Path
        |--------------------------------------------------------------------------
        |
        | This is the URI path where Laratrust panel for roles and permissions
        | will be accessible from.
        |
        */
        'path' => env('LARATRUST_PANEL_PATH', 'dashboard'),

        /*
        |--------------------------------------------------------------------------
        | Laratrust Panel Path
        |--------------------------------------------------------------------------
        |
        | The route where the go back link should point
        |
        */
        'go_back_route' => '/home',

        /*
        |--------------------------------------------------------------------------
        | Laratrust Panel Route Middleware
        |--------------------------------------------------------------------------
        |
        | These middleware will get added onto each Laratrust panel route.
        |
        */
        'middleware' => ['web'],

        /*
        |--------------------------------------------------------------------------
        | Enable permissions assignment
        |--------------------------------------------------------------------------
        |
        | Enable/Disable the permissions assignment to the users.
        |
        */
        'assign_permissions_to_user' => true,

        /*
        |--------------------------------------------------------------------------
        | Enable permissions creation
        |--------------------------------------------------------------------------
        |
        | Enable/Disable the possibility to create permissions from the panel.
        |
        */
        'create_permissions' => true,

        /*
        |--------------------------------------------------------------------------
        | Add restriction to roles in the panel
        |--------------------------------------------------------------------------
        |
        | Configure which roles can not be editable, deletable and removable.
        | To add a role to the restriction, use name of the role here.
        |
        */
        'roles_restrictions' => [
            // The user won't be able to remove roles already assigned to users.
            'not_removable' => [],

            // The user won't be able to edit the role and the permissions assigned.
            'not_editable' => [],

            // The user won't be able to delete the role.
            'not_deletable' => [],
        ],
    ],`

**Comment by Sogl** [comment]
Sounds interesting. Is there any progress?

**Comment by santigarcor** [comment]
@Sogl not yet, as I said there it depends on the monthly goal
