### ISSUE TITLE
hasRole does not exist Error

### ISSUE THREAD

**Issue by PardisZaryab** [santigarcor/laratrust#625]
Hello I still have problem with new Laratrust version, It give me (hasRole does not exist) error.
It create the user but when I write a condition like I used to do before to redirect each user to specific page it give me above mentioned error.
Please help me with this.
Thank you

**Comment by filippotoso** [comment]
Follow the documentation:

https://laratrust.santigarcor.me/docs/8.x/installation.html

4. Add the Laratrust\Contracts\LaratrustUser interface and Laratrust\Traits\HasRolesAndPermissions trait in your user classes.

```php
use Laratrust\Contracts\LaratrustUser;
use Laratrust\Traits\HasRolesAndPermissions;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements LaratrustUser
{
    use HasRolesAndPermissions;

    // ...
}
```

**Comment by PardisZaryab** [comment]
I have done that and here is my user model and Dashboard file repository address.
https://github.com/PardisZaryab/zar

**Comment by filippotoso** [comment]
I just created a new Laravel installation, installed Laratrust per documentation and `Auth::user()->hasRole()` works perfectly.

What happens if you execute the following code at the beginning of the DashboardController::index() method?

```php
dd(Auth::user());
```

**Comment by PardisZaryab** [comment]
This is the result.

App\Models\User {#666 ▼ // app\Http\Controllers\DashboardController.php:14
  #connection: "mysql"
  #table: "users"
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  +preventsLazyLoading: false
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #escapeWhenCastingToString: false
  #attributes: array:8 [▶]
  #original: array:8 [▶]
  #changes: []
  #casts: array:1 [▶]
  #classCastCache: []
  #attributeCastCache: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  +usesUniqueIds: false
  #hidden: array:2 [▶]
  #visible: []
  #fillable: array:3 [▶]
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  #accessToken: null
}

**Comment by filippotoso** [comment]
What about:

```php
dump(class_uses(Auth::user()));
dd(method_exists(Auth::user(), 'hasRole'));
```

**Comment by PardisZaryab** [comment]
I added 
dd(Auth::user());
at the end of my dashboard code and it worked.
Thank you so much for help
