### ISSUE TITLE
I can't install laratrust in laravel 5.3

### ISSUE THREAD

**Issue by asadi20** [santigarcor/laratrust#63]
hi
I can't install your laratrust in my fully working laravel 5.3
I follow your documentation for installation step by step
after commit basic configuration when I'm going to run this command:
php artisan vendor:publish
I've got this message:
[Symfony\Component\Debug\Exception\FatalThrowableError]
 Class 'Laratrust\LaratrustServiceProvider' not found

**Comment by haydndup** [comment]
Did you run:
`composer dump-autoload`

**Comment by asadi20** [comment]
yes and still nothing

**Comment by asadi20** [comment]
finally i can solve it:
1- remove every thing that i created in the installation process like: class providers,composer.json
2- enter `composer dump-autoload` tnx to haydndup ;)
3- follow the installation manual

**Comment by haydndup** [comment]
Glad it's fixed!
