### ISSUE TITLE
Question: How to over ride Create/Edit User Request class

### ISSUE THREAD

**Issue by seth-setiadha** [santigarcor/laratrust#632]
Hi @santigarcor ,

I have a form where I need to validate the email domain based on the email domain list that we have on our application setting.
In order todo that I need to modified app/Http/Requests/CreatesUsersRequest.php and EditsUsersRequest.php

is there a way to over ride this class?

**Comment by santigarcor** [comment]
Is this question related to Laratrust?  I'm failing to see how it relates to Laratrust

**Comment by seth-setiadha** [comment]
Sorry to confuse you, I should've posted this on another github which also opened on the other tab
