### ISSUE TITLE
Objects Ownership

### ISSUE THREAD

**Issue by rostami4567** [santigarcor/laratrust#633]
hello 
I use laratrust 7 and upgrade it to 8 version 
after that I am get this error:  Interface "Laratrust\Contracts\Ownable" not found 
how to fix it?
and I am not found Object ownership  in documentation but there is not in upgrade guide anything about obsolete this method

**Comment by filippotoso** [comment]
Install this package:
https://github.com/santigarcor/laravel-ownable
