### ISSUE TITLE
Upgrade from 7.x to 8.x documentation missing relationship queries

### ISSUE THREAD

**Issue by incoming-th** [santigarcor/laratrust#636]
- Laravel Version: 10
- Laratrust Version: 8

**Describe the bug**
In the upgrade documentation, a mention of the change on the PDO queries seems missing.

**To Reproduce**
Browse to https://laratrust.santigarcor.me/docs/8.x/upgrade.html

The previous querying relation must also be updated:

whereRoleIs => whereHasRole
orWhereRoleIs => orWhereHasRole
wherePermissionIs => whereHasPermission
orWherePermissionIs => orWhereHasPermission

I am unsure for those if typo in doc or not (https://laratrust.santigarcor.me/docs/8.x/usage/querying-relationships.html#roles-permissions-absence):
whereDoesntHaveRole => whereDoesntHaveRoles (added a "s")
whereDoesntHavePermission => whereDoesntHavePermission (should be whereDoesntHavePermissions ?)

**Comment by santigarcor** [comment]
Could you please add those to the upgrade docs? It's not a typo, the scopes changed

**Comment by Masumrahmanhasan** [comment]
added this docs on #646
