### ISSUE TITLE
Blade templates and user_role, potential issue?

### ISSUE THREAD

**Issue by Jam0r85** [santigarcor/laratrust#64]
Using blade helpers, unless I am miss understanding how this works, there seems to be an issue with using @permission('insert-permission-here') when a user is only assigned to a role and the role is assigned permissions?

Does the role filter down permissions linked via the permission_role table without involving groups?

If I assign the permission direct to the user (using permission_user) then using @permission allows access.
If I assign the user to a role (using role_user) and permission_user is empty, @permission denys access.

Is this correct or is this a bug?

**Comment by santigarcor** [comment]
I think you are talking about 4.0.0rc. if you attach a role and the role has the permission, when you check that permission it goes all the way to the permissions table through the permission_role table. If you add the group to that method, it checks the role inside that group using the same table, role_permission.

If you attach the permission directly to the user, it uses the permission_user table. If I'm not wrong, it first checks the permission_user table and then it checks the ones within the groups.

It's not a bug, it doesn't support the groups functionality in that direct association yet.
