### ISSUE TITLE
Errror: Index name is too long.

### ISSUE THREAD

**Issue by mhmiton** [santigarcor/laratrust#647]
**Getting index error on migration -**

`SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'acl_permission_user_user_id_permission_id_user_type_team_id_unique' is too long (Connection: mysql, SQL: alter table `acl_permission_user` add unique `acl_permission_user_user_id_permission_id_user_type_team_id_unique`(`user_id`, `permission_id`, `user_type`, `team_id`))`

- Laravel Version: 10.10
- Laratrust Version: 8.2

**Comment by websitevirtuoso** [comment]
set your own index for table. This lib is not responsible for errors in mysql. or create issue in myslq repo
