### ISSUE TITLE
Dynamic Routing

### ISSUE THREAD

**Issue by sricodelli** [santigarcor/laratrust#648]
I have used this package with the admin panel it created. Everything works fine as expected.
I do not see documentaion for the routes. Since im creating roles and permissions from the admin panel i want the routes/web.php to be dynamic. I dont want to add  Route::group(['middleware' => ['role:admin']], function () { for each role create. Is there a way to make it dynamic which works for roles that we create in future

**Comment by filippotoso** [comment]
You can create your own middleware to handle the role validation based on the information in the database,

**Comment by filippotoso** [comment]
I don't know what `hasRoleAndPermissionForRoute()` does so I can't answer your question.

You said "im creating roles and permissions from the admin panel i want the routes/web.php to be dynamic". I suppose that it means you are dynamically assigning roles and permissions to specific routes. Depending on how you do that, your middleware should handle the authorization process.

**Comment by memiljamel** [comment]
any idea?
