### ISSUE TITLE
INFO  No publishable resources for tag ["laratrust"].

### ISSUE THREAD

**Issue by kakashikuna** [santigarcor/laratrust#653]
Hello, 

i can´t install lalatrust.

- Laravel Version: 10.38.1

**Describe the bug**
INFO  No publishable resources for tag ["laratrust"].

**To Reproduce**
php artisan vendor:publish --tag="laratrust"

**Comment by filippotoso** [comment]
Tested with Larave (v10.39.0) and Laratrust (v8.2.1) and it works correctly.

**Comment by kakashikuna** [comment]
Plesk with the Laravel extension causes the problem on another server without Plesk it runs without problems
