### ISSUE TITLE
Unable to install on Laravel 5.3

### ISSUE THREAD

**Issue by alex-LE** [santigarcor/laratrust#66]
I get the following composer error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install santigarcor/laratrust 3.0.10
    - Conclusion: don't install santigarcor/laratrust 3.0.9
    - Conclusion: don't install santigarcor/laratrust 3.0.8
    - Conclusion: don't install santigarcor/laratrust 3.0.7
    - Conclusion: don't install santigarcor/laratrust 3.0.6
    - Conclusion: don't install santigarcor/laratrust 3.0.5
    - Conclusion: don't install santigarcor/laratrust 3.0.4
    - Conclusion: don't install santigarcor/laratrust 3.0.3
    - Conclusion: don't install santigarcor/laratrust 3.0.2
    - Conclusion: don't install santigarcor/laratrust 3.0.1
    - Conclusion: remove nikic/php-parser v3.0.2
    - Installation request for santigarcor/laratrust 3.0.* -> satisfiable by santigarcor/laratrust[3.0.0, 3.0.1, 3.0.10, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9].
    - Conclusion: don't install nikic/php-parser v3.0.2
    - santigarcor/laratrust 3.0.0 requires kkszymanowski/traitor ^0.2.0 -> satisfiable by kkszymanowski/traitor[0.2.0, 0.2.1, 0.2.2].
    - kkszymanowski/traitor 0.2.0 requires nikic/php-parser ^1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - kkszymanowski/traitor 0.2.1 requires nikic/php-parser ^1.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1].
    - kkszymanowski/traitor 0.2.2 requires nikic/php-parser ^1.0|^2.0 -> satisfiable by nikic/php-parser[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.1, v2.1.0, v2.1.1].
    - Can only install one of: nikic/php-parser[v1.0.0, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.0.1, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.0.2, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.1.0, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.2.0, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.2.1, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.2.2, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.3.0, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.4.0, v3.0.2].
    - Can only install one of: nikic/php-parser[v1.4.1, v3.0.2].
    - Can only install one of: nikic/php-parser[v2.0.0, v3.0.2].
    - Can only install one of: nikic/php-parser[v2.0.1, v3.0.2].
    - Can only install one of: nikic/php-parser[v2.1.0, v3.0.2].
    - Can only install one of: nikic/php-parser[v2.1.1, v3.0.2].
    - Installation request for nikic/php-parser (locked at v3.0.2) -> satisfiable by nikic/php-parser[v3.0.2].

Installation failed, reverting ./composer.json to its original content.

It seems that php-parse is already installed in version 3.0.2 as a requirement of "classpreloader/classpreloader" which is a requirement of laravel itself.

What can i do?

**Comment by KKSzymanowski** [comment]
I have to update the Traitor package to require `nikic/php-parser` 1.\*, 2.\* and 3.\*

**Comment by KKSzymanowski** [comment]
I updated the Traitor to 0.2.3. Check now if you can install Laratrust.

**Comment by alex-LE** [comment]
works, great! thanks!
