### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by Mtillmann** [santigarcor/laratrust#675]
I'm in the process of upgrading a Laravel App and came across this:

https://github.com/santigarcor/laratrust/blob/aa43d35e4285af30a52eff6dbbe9a2e81adeaa6a/docs/docs/8.x/the-basics/models/user.md?plain=1#L9

The docs state that `User` should extend an unspecified `Model` class, while the default laravel User-Model extends `Illuminate\Foundation\Auth\User` 

```php
use Illuminate\Foundation\Auth\User as Authenticatable;
// ...

class User extends Authenticatable
{
```

In my case, I kept the `Authenticatable` base class, and it worked.

**Comment by santigarcor** [comment]
I think you're right, that part should be fixed, could you please send a PR fixing that part?
