### ISSUE TITLE
Here are some documentation comments on my recent install of Laratrust into a Laravel 5.2 project

### ISSUE THREAD

**Issue by edgreenberg** [santigarcor/laratrust#68]
-- Installation

Add a comma after 
Laratrust\LaratrustServiceProvider::class
to match:
'Laratrust'   => Laratrust\LaratrustFacade::class,

-- After Installation - configuration files

-- The following statement is not understandable.  If I didn't have the original entrust documentation, I'd be totally lost:

**Set the property values in the config/auth.php. These values will be used by laratrust to refer to the correct user model.**

-- Somehow I wound up with two <timestamp>_laratrust_setup_tables.php

-- Documentation says: 
** After the migration, four new tables will be present:**
In actuallity I got SIX new tables.  In addition to the four mentioned I got groups and permission_user 

-- Documentation says: 
** Create a Role model inside app/models/Role.php using the following example: **
Is it not so that 1) Models go under app/ not app/model  and 2) models should have initial caps filenames.  If you really want them under app/models, the doc should instruct to create the models directory.   Besides, once you do "composer dump-autoload" does it matter where they go? 

-- Documentation says: 
** Next, use the LaratrustUserTrait trait in your existing User model. For example:** 

This seems to have been done automatically for me by an earlier step.

**Comment by santigarcor** [comment]
So these annotations are for the master branch not the 3.0 one?

**Comment by edgreenberg** [comment]
I'm sorry I wasn't clear.   When I wrote this, I didn't realize how different the two branches were.
 
So yes, this is for the Dev branch.
 
Would you like me to pull the documentation and update it based on doing a fresh install? It would be my pleasure to contribute that work to the project.
 
Let me know,
 
Ed Greenberg
 
 
 
-----Original Message-----

**Comment by santigarcor** [comment]
It would be great man, I would appreciate that :)
