### ISSUE TITLE
Trait "Laratrust\Traits\LaratrustUserTrait" not found

### ISSUE THREAD

**Issue by kamilath-coder** [santigarcor/laratrust#680]
- Laravel Version: latest version 11
- Laratrust Version: "^8.3"

**Describe the bug**

**To Reproduce**

**Comment by goodmuyis** [comment]
You might want to downgrade to `"santigarcor/laratrust": "^7.2"`
I could not get v8x to work as well

**Comment by santigarcor** [comment]
If you were upgrading please read the [upgrade guide](https://laratrust.santigarcor.me/docs/8.x/upgrade.html). The name of the trait was changed for 8.x to [HasRolesAndPermissions](https://github.com/santigarcor/laratrust/blob/master/src/Traits/HasRolesAndPermissions.php).
