### ISSUE TITLE
Question about LaratrustUserTrait::can

### ISSUE THREAD

**Issue by KKSzymanowski** [santigarcor/laratrust#7]
UPDATE: Probably the same question for `hasRole()`

I was wondering, shouldn't `$user->can([])` return `true` when user has no permissions?

Example:
We have some collection of Things. Every one of the Things requires one from a set of permissions to access. Some of them don't require any permissions to access.
When a User doesn't have any permissions, he should still access the Thing that requires no permissions.

With current algorithm, in previously mentioned case User is forbidden to do that, because we return `$requireAll` which is `false`.

**Comment by KKSzymanowski** [comment]
If my train of thought is correct, to fix it all that needs to be done is
```
if (is_array($permission)) {

    // --- BEGIN CHANGES ---
    if(empty($permissions)) {
        return true;
    }
    // --- END CHANGES

    foreach ($permission as $permName) {
        $hasPerm = $this->can($permName);

        if ($hasPerm && !$requireAll) {
            return true;
        } elseif (!$hasPerm && $requireAll) {
            return false;
        }
    }

    // If we've made it this far and $requireAll is FALSE, then NONE of the perms were found
    // If we've made it this far and $requireAll is TRUE, then ALL of the perms were found.
    // Return the value of $requireAll;
    return $requireAll;
}
```

**Comment by santigarcor** [comment]
But why would you do something like this `$user->can([])` ?

**Comment by KKSzymanowski** [comment]
I don't have a good example, but let's give it a try:
Suppose we have rooms multiple doors. A person has access to a room when he has a key to at least one of the doors. Some rooms can have doors that can't be locked so everyone can access this room.
To find out if a person can access specific room, we would call:
```
$person->hasKey($room->requiredKeys);
```
If a room has no lockable doors, the `$room->requiredKeys` would return `[]` so we would in fact call `$person->hasKey([]);`.

Back to the reality: We can have a system which works as described above and a set of required permissions(or roles) can be empty so we would do `user->can([])`(or `user->hasRole([])`) in some of the cases.

I hope I'm talking sense.

**Comment by santigarcor** [comment]
@KKSzymanowski I got your point. I'll change that

**Comment by santigarcor** [comment]
a3fadd34ce23f7663471aac60432a92a8d8c386f solves this
