### ISSUE TITLE
LaratrustRoleTrait attachPermissions Behaviour

### ISSUE THREAD

**Issue by JamesTimms** [santigarcor/laratrust#70]
Hi there,

Using Laravel 5.3 and Laratrust 3.0. 
Assuming my Admin role has permissions create-users and read-users, when I try to sync multiple roles as shown below it errors out;
```
$role = \App\Role::first(); //Admin role
$role=>attachPermissions([1, 2, 3]);// create-users, read-users, update-users.
```
> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1' for key 'PRIMARY' (SQL: insert into `permission_role` (`permission_id`, `role_id`) values (1, 1))

This is because attachPermissions calls attachPermission for each item in the array which will call `$this->permissions()->attach($permission);`. 

Documentation states;
> $owner->attachPermissions([$createPost, $editUser]);
// equivalent to $owner->permissions()->sync([$createPost->id, $editUser->id]);

Which is not the case, however the function savePermissions does follow the stated behaviour which I only found after digging around the code. 

Had a quick look and doesn't seem to appear in 3.0 or master docs. Maybe the docs should be updated to reflect this?

**Comment by santigarcor** [comment]
Hmm, you're totally right, the docs have to be changed because it does not work like a `sync`
