### ISSUE TITLE
userability always return true

### ISSUE THREAD

**Issue by asadi20** [santigarcor/laratrust#72]
in blade when i use:
$user->abilty('rolename','permissionname')
always return true for any role and permission
$user->can work fine
Can i use above statement in blade?

**Comment by santigarcor** [comment]
Which version are you using?

Does the user has one of those two?

**Comment by asadi20** [comment]
version 3.0
in role_user table
user_id      role_id
1                      2

in permission_role
role_id       permission_id
2                          1
 when i use $user->abilty('rolename for id 2','permission name for id 2') must return false but return trure

**Comment by santigarcor** [comment]
I'll test that to see if i can reproduce it

**Comment by santigarcor** [comment]
But you know there's nothing wrong with that, the ability check if the user has the role or the permission, and in your case the user doesn't have the permission (permission with id 2), but has the role (role with id 2)

**Comment by santigarcor** [comment]
If you want the ability to check if the user has both of them you have to add a third parameter that is the options array. 

I'll leave the link to the user ability part in the docs
http://laratrust.readthedocs.io/en/3.0/usage/concepts.html#user-ability
