### ISSUE TITLE
Issue with middleware on Route

### ISSUE THREAD

**Issue by dflow** [santigarcor/laratrust#73]
`Route::get('test', function(){
return 'foo';
})->middleware('role:admin');`

I get 
 HttpException in Application.php line 917:

**Comment by Jam0r85** [comment]
I had a similar issue.

Open 'config/laratrust.php' and set as follows:

`    /*
    |--------------------------------------------------------------------------
    | Method to be called in the middleware return case
    | Available: abort|redirect
    |--------------------------------------------------------------------------
    */
    'middleware_handling' => 'redirect',

    /*
    |--------------------------------------------------------------------------
    | Parameter passed to the middleware_handling method
    |--------------------------------------------------------------------------
    */
    'middleware_params' => '/login',`

**Comment by santigarcor** [comment]
Thank you i just changed the docs in order to have the `/`

**Comment by octoquad** [comment]
I just hit this as well. If you add a view to handle the necessary HTTP status code, in this case 403 Forbidden, it will not throw this exception. See https://laravel.com/docs/5.3/errors#http-exceptions for more information.
