### ISSUE TITLE
Can I check permission for Role? 

### ISSUE THREAD

**Issue by rutvij2292** [santigarcor/laratrust#77]
Can I check Permission for the Role? Like 

```
$role->hasPermission(['edit-user'])
```

should return true or false? Or anyone can suggest how to check role has permission? 

I need display all the permission and all roles. If a role has permission then a checkbox is checked. Same as Magento Role and Permission page. Can anyone please help me? 

Thanks.

**Comment by rutvij2292** [comment]
Sorry, I solved problem by my own. Thanks for an amazing plugin. Thanks a lot @santigarcor 

Love it. 


If anyone wants edit page same like Magento. Here's the solution.


```

@foreach($permissions as $permission)
    @foreach($roles as $role)
        @if($role->hasPermission($permission->name))
            {{-- DO WHATEVER YOU WANT --}}
        @else
            {{-- DO WHATEVER YOU WANT --}}
        @endif
    @endforeach
@endforeach
```

**Comment by santigarcor** [comment]
But why don't you use the can method? That code is almost doing the same as the can method.

**Comment by rutvij2292** [comment]
@santigarcor  Is there any difference between can and hasPermission method? I would like to know. 

Thanks for pointing out.

**Comment by santigarcor** [comment]
As the doc says, the can method checks if the user can do something by checking all the permissions through the roles that the user has attached.

The hasPermission just checks if a role has a permission.

**Comment by rutvij2292** [comment]
Okay, but here I am displaying all the roles and permission associated with each role. Similar to Magento's Role and Permission edit page.

Something like this:

![image](https://cloud.githubusercontent.com/assets/16564857/22228282/01e2089c-e185-11e6-81ca-932aeda58560.png)

**Comment by santigarcor** [comment]
Ahhh OK, nevermind I didn't say anything. Your code is right.
