### ISSUE TITLE
Make value of $foreignKeyName inside owns() method customizable

### ISSUE THREAD

**Issue by tomhatzer** [santigarcor/laratrust#79]
Hi!

Thank you very much for your Laratrust extension :)

Would it be possible to make the $foreignKeyName variable inside the owns() method (within LaratrustUserTrait.php) customizable?

My table columns and model variables are not camelcase, instead I'm using underscores eg. user_id.

The quick and dirty solution I'm using currently is, overwriting the owns method inside my User model and defining my own foreign key.

Thank you very much!

Best wishes
Tom

**Comment by santigarcor** [comment]
Well the current method does this:

```php
$foreignKeyName = snake_case(get_class($this). 'Id');
```

So the `$foreignKeyName` would result as `user_id` (In case that your user model is the one that uses the `LaratrustUserTrait` ).

But in any case, i'll add the option in the method to customize de `$foreignKeyName`.

**Comment by tomhatzer** [comment]
Oh, I'm sorry. Didn't think of that. I think I should have asked the documentation first :D Didn't know what the snake_case helper did. Now I know. Thanks!

**Comment by santigarcor** [comment]
No problem, but anyways i'll add that option to the method in case someone does not use snake_case for their foreign keys

**Comment by tomhatzer** [comment]
Thank you very much!
