### ISSUE TITLE
Does any one knows if this project is working with laravel 5.4??

### ISSUE THREAD

**Issue by reiter777** [santigarcor/laratrust#80]
i tested everything fine except for the permissions nothing is working in this case @permission @endpermission 
if($user->can('create-user') stuff like that

**Comment by santigarcor** [comment]
Could you be more specific, which laratrust version and what are you trying to do?

What are you getting?

**Comment by santigarcor** [comment]
@reiter777 I just tested a new project of laravel 5.4 with laratrust 3.0 and everything worked fine, even the `@permission()` and the `can()` method.

**Comment by reiter777** [comment]
sorry for the time! but yes let me show you. As you can see the current user karloz has de permission of editar-roles, but when a code the method permission('editar-roles'), i can not access the controler and i can not see the button editar at the template view also, 
![editar roles](https://cloud.githubusercontent.com/assets/6207721/22697245/880f86dc-ed16-11e6-98ba-f039095da11c.png)

**Comment by santigarcor** [comment]
Well you are showing me the permissions table, permission_role table, but not the role_user and the role table so i don't know if that user has the permission.

The test i did was: create a new project, installed laratrust 3.0, seed the database with the seeder and jus check if an user can do something and everything worked fine.

**Comment by reiter777** [comment]
o right here is the users and roles table. I did what you say i created a new project i include the 3.0 version but its the same, i also included the seed.
![roles](https://cloud.githubusercontent.com/assets/6207721/22700096/0cf3efc0-ed1f-11e6-9527-c5e55ed833be.png)

**Comment by santigarcor** [comment]
I'll check again trying to use the same data you have there.

**Comment by santigarcor** [comment]
The tables in order are: users, roles, role_user, permissions, permission_role:
![test](https://cloud.githubusercontent.com/assets/7565417/22704113/874b8b74-ed34-11e6-94aa-57151ea02bce.jpg)

and if i do this:
```php
        @permission('read-profile')
            {{ dump(auth()->user()->can('read-profile')) }}
        @endpermission
```

i get `true`

and if do this:
```php
        @permission('read-profile')
            {{ dump(auth()->user()->can('read-profile')) }}
        @endpermission
```

i don't get nothing because the user doesn't have the permission.

With that in mind i think your problem is the cache, because maybe you are not using the laratrust roles assignation methods, but the normal laravel many to many attach or sync method.

**Comment by reiter777** [comment]
as you say, teah im using te attach method is tha bad?im not using the LaratrustRoleTrait :/ because i get errors when im trying to use same when i want to use de relationships in the views, like this, $usuarios = $this->users->with('roles.permissions')->paginate(10); i get this error 
![error](https://cloud.githubusercontent.com/assets/6207721/22704725/4f2144b0-ed2e-11e6-9988-b76b50716f67.png). Maybe you have right for the other error and its only the cache

**Comment by santigarcor** [comment]
Did you follow the installation instructions? does you User model uses the LaratrustUserTrait? And your Role model extends from LaratrustRole? And you Permission model extends from LaratrustPermission?

**Comment by reiter777** [comment]
yeah of course, i follow the installation instructions step by step.
![mas datos](https://cloud.githubusercontent.com/assets/6207721/22705139/05570d0e-ed30-11e6-91de-4273a874834e.png)

**Comment by KKSzymanowski** [comment]
@reiter777 
Your exception says:
> Call to undefined relationship [roles] on model [**Illuminate\Foundation\Auth\User**]

You probably imported the wrong User class.

**Comment by santigarcor** [comment]
@KKSzymanowski  i haven't noticed that out.

**Comment by reiter777** [comment]
@KKSzymanowski yeah man thanks a lot! and really sorry for the troubles also to you @santigarcor. ! and congrats to the package is really nice!

**Comment by KKSzymanowski** [comment]
@reiter777 No problem. 

Three friendly advices for you: 
- Try to learn English a little bit more. It's a somewhat difficult to read your messages and I can promise you, it will greatly benefit you in the future.
- Try to use only English in your code. You might some day end up in an international team and this way you wouldn't have to change anything in your workflow.
- Read the exception messages. 😄
