### ISSUE TITLE
hasRole() returns false.

### ISSUE THREAD

**Issue by farazappy** [santigarcor/laratrust#85]
Hey everyone!

I recently installed Laratrust on my system for roles and permission management.

I seeded the tables with my required roles and permissions, Inserted 1 record under `role_user` table manually where user is me and role is administrator.

When I get the user using 
`$user = User::with('roles')->find(1);` I get the user, with the roles.

But if I do something like,

`$user = User::find(1);`
`$role = Role::find(1);`
`$user->hasRole($role);` -> Returns false, where as the user already has the role.

What is going wrong here?

Also in the SignUp controller, I have 
`$user = new User($request->all());`
`$user->attachRole($roleId);`

This returns an error saying Only one argument was passed, the role id, user id is missing.

Any help would be appreciated.

**Comment by santigarcor** [comment]
First of all when you check if a user has a role you can't pass the `$role` object you have to pass the role name so in that case it would be:

```
$user->hasRole($role->name);
```

And in your second case you have not saved your user, so there's no user id existing to attach the role.
You should do:

```
$user =  User::create($request->al()); // This saves the user, but when you do new User it only instantiates it
$user->attachRole($roleId);
```
