### ISSUE TITLE
Namespace idea

### ISSUE THREAD

**Issue by KKSzymanowski** [santigarcor/laratrust#9]
How about using `Laratrust` as the vendor namespace instead of `Santigarcor\Laratrust`.
For example `Santigarcor\Laratrust\LaratrustRole` would become simply `Laratrust\LaratrustRole`.

It's easier to remember and `LaratrustFacade` due to an alias is used without `Santigarcor` prefix so it would provide consistency.

What do you think?

**Comment by laravelish** [comment]
im with you bro

**Comment by santigarcor** [comment]
Well i don't have any problem with that, but would be any problem with packagist?

**Comment by KKSzymanowski** [comment]
@santigarcor How do you mean? For all I know packagist isn't concerned at all with namespacing.

It works eg. in https://github.com/briannesbitt/Carbon or https://github.com/kkszymanowski/traitor.

**Comment by santigarcor** [comment]
Hmmm ok that's fine

**Comment by KKSzymanowski** [comment]
I'm in the process of refactoring Role and Permission generator commands and writing tests for it. Once I'm done, I will PR this namespace change.

**Comment by Mathius17** [comment]
Love the idea
