### ISSUE TITLE
Laratrust conflicts with Authorizable trait

### ISSUE THREAD

**Issue by ahjorth** [santigarcor/laratrust#90]
I understand that LaratrustUserTrait is intended to replace the Authorizable trait, but there are situations where you would want to use the Authorizable trait instead.

I use Laratrust for site wide permissions, but for my forum I needed my own that could assign and read permissions from specific boards. So I would like to be able to call `$user->can('view', $board);` but this isn't possible.

And afaik, it's not as simple as just doing `LaratrustUserTrait::can as hasPermission;` since all directives etc. are so tied into the `can()` method.

So I was wondering if there's a way to resolve these conflicts once and for all. Using `can` seems unecessary.

Since Laratrust is a Laravel package, it would be nice to try and avoid things like `can`, `cannot` and `cant` for the sake of avoiding conflicts like this.

So my suggestion would be to rename these methods to something more unique from Laravel, like `hasPermission` or similar. I know semantically it might look worse, but for the sake of keeping the features of laravel intact even while using this package I think it might be worth it

**Comment by santigarcor** [comment]
But you can use the new ownable interface and the new methods i added yesterday so there's no need to use that method. 

I haven't tagged that or documented it yet, but i will soon.

**Comment by ahjorth** [comment]
There is if I specifically need to access the `Authorizable::can` from a user object. I can look into maybe resolving the conflict by doing `Authorizable::can as hasPermission` but my point is still that Laratrust and Laravel Authorization are by their very nature conflicting when the two uses the same names.

When 5.1.11 first came out, most Laravel based role/permission systems (including this one) had to change. The @can directive was renamed. Why was not the other references to `can` also renamed to avoid any conflict?

**Comment by santigarcor** [comment]
That would be a big and breaking change, until now you are the only one (known) that has had a problem with the can method and the Authorizable trait.

And even if the change is made, i would need help with a migration helper, because i wouldn't like the user to have to go through each file and find the can method and change it by the new method name, that'd be tedious.

**Comment by ahjorth** [comment]
I understand. I'm not saying it's a requirement as of now, but maybe in a next major update it could be considered if more people agreed.

For now, I have solved the conflict by adding this to my `User.php` model

```
use LaratrustUserTrait;
use Authorizable {
    LaratrustUserTrait::can insteadof Authorizable;
    Authorizable::can as laravelCan;
}
```

**Comment by santigarcor** [comment]
I'm working on the multiauth feature, so i'll make the can method changes there, but i'll put two options for the method: 

`hasPermission` and `isAbleTo`

In addition to that i'll add the `is` method (will be another way to call the hasRole method).

**Comment by ahjorth** [comment]
Sounds great.

Sorry if it's a bother. I just tend to think it's easier to try and avoid conflicts even if the use scenario might be a little obscure. I remember when everyone had to scramble to change their @can directives in 5.1.11 :smile:

**Comment by santigarcor** [comment]
L won't delete the can method, i'll change the references inside Laratrust to a hasPermission method but i'll leave the can method for compatibility, so there's no problem if someone just wants to use the Authorizable trait, because they'll have the hasPermission or isAbleTo method.

**Comment by ahjorth** [comment]
Great, good job :)
