### ISSUE TITLE
users Relationship error on Permission Model

### ISSUE THREAD

**Issue by ebbbang** [santigarcor/laratrust#91]
In Laratrust Permission Trait's `users` relationship method, `Config::get('laratrust.role')` is called.
But the default config file doesn't have this config property.

To recreate this issue:
1. Create Permission
2. Call users relationship on permission

Error : Class name must be a valid object or a string

**Comment by ebbbang** [comment]
When will this reflect in 3.1 ?

**Comment by santigarcor** [comment]
Today
