### ISSUE TITLE
Problem with attaching roles to an user

### ISSUE THREAD

**Issue by alperyazgan** [santigarcor/laratrust#99]
With version 3.2 I got the following error while trying to attach any role to an user:

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "user_t  
  ype" violates not-null constraint                                            
  DETAIL:  Failing row contains (1, 1, null). (SQL: insert into "role_user" (  
  "role_id", "user_id") values (1, 1))

Problem is repeatable and simple to produce:
1. Create a role and permissions

$sysadmin = Role::create([...]);
Permission::create([...]); /* some of */

2. Attach permissions to role

$sysadmin->attachPermissions(Permission::all()->toArray());

3. Attach the role to the user
User::where('name', 'SYSTEM ADMINISTRATOR')->first()->attachRole($sysadmin);

and error ??

PS. I know what the problem is, right now I do not want to intervene with your code :-)

**Comment by santigarcor** [comment]
So what's the problem? If you know what's the problem, tell me so I can address it, or if it's something you did wrong.

**Comment by alperyazgan** [comment]
My suggestion is just a patch;
In File /src/views/generators/migration.blade.php line 62
   > $table->string('user_type');
could be set to 
  > $table->string('user_type')->nullable();
for a quick fix, because I see no way to set that field to any value ( maybe, you mean to set hat field a default value of 'users' ? )

**Comment by santigarcor** [comment]
That's no the solution, you are doing something wrong because it's no setting right that column and it's set by the relationship between the user and the role, what do you have in the relationship? Did you overwrite it? Because it's like the polymorphic many to many is not working there.

**Comment by alperyazgan** [comment]
OK then, what is wrong could you please underline it ?

- Installation is ok with respect to the documents ( no seeder is used - laratrust_seeder.php )
Models (Role, Permission, User) are the same - auto configured

- Config (laratrust.php) is ok with the following settings changed :

> ...
>   'user_models' => [
>     'users' => 'App\Models\User',
>   ],
> ...
>   'role' => 'App\Models\Role',
> ...
>   'permission' => 'App\Models\Permission',
> ...

- And the rest is in a seeder file doing the job to create Role, Permission and User as I said earlier in the post.

What am I missing ?

 PS. No relationship overwrites, no additional codes to the models, whatsoever  
After first failure I created an empty project, the same thing happened, that field was not set to any value. So the fresh Installation of Laratrust 3.2 on Laravel 5.4 causes the same problem.

**Comment by santigarcor** [comment]
@alperyazgan I just did all the things you said, fresh 5.4 install and Laratrust 3.2, then added your configuration, then automatic laratrust setup, filled the database seeder with your code, and it worked.

This is the configuration i used:

```
'user_models' => [
    'users' => 'App\Models\User',
],
'role' => 'App\Models\Role',
'permission' => 'App\Models\Permission',
```

This is the seeder code i used:

```
User::create(['name' => 'SYSTEM ADMINISTRATOR', 'email' => 'test@test.com', 'password' => '123']);
        
$sysadmin = Role::create(['name' => 'sysadmin']);
Permission::create(['name' => 'something']);
$sysadmin->attachPermissions(Permission::all()->toArray());

User::where('name', 'SYSTEM ADMINISTRATOR')->first()->attachRole($sysadmin);
```

**Comment by alperyazgan** [comment]
Found the problem on my side, a misplaced model Role in App\Role.php causes the problem (it has own relations to user), why there are two models I do not know, I have to check, but  laratrust installation is ok, no prob right now.
